openapi: 3.0.0
info:
  version: "1.0.0"
  x-release: v4
  title: APIs.io Engineering Platform Amazon API Gateway 2014 11 13 Access Service Tokens API
  description: <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: apigateway
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/apigateway-2015-07-09.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: https://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: http://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
- url: https://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: Access Service Tokens
paths:
  /accounts/{account_id}/access/service_tokens:
    get:
      description: Lists all service tokens.
      operationId: access-service-tokens-list-service-tokens
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/access_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_api-response-common-failure'
          description: List service tokens response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_components-schemas-response_collection'
          description: List service tokens response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform List service tokens
      tags:
      - Access Service Tokens
      x-api-token-group:
      - 'Access: Service Tokens Write'
      - 'Access: Service Tokens Read'
    post:
      description: Generates a new service token. **Note:** This is the only time you can get the Client Secret. If you lose the Client Secret, you will have to rotate the Client Secret or create a new service token.
      operationId: access-service-tokens-create-a-service-token
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/access_identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                duration:
                  $ref: '#/components/schemas/access_duration'
                name:
                  $ref: '#/components/schemas/access_schemas-name'
              required:
              - name
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_api-response-common-failure'
          description: Create a service token response failure
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_create_response'
          description: Create a service token response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Create a service token
      tags:
      - Access Service Tokens
      x-api-token-group:
      - 'Access: Service Tokens Write'
  /accounts/{account_id}/access/service_tokens/{service_token_id}:
    delete:
      description: Deletes a service token.
      operationId: access-service-tokens-delete-a-service-token
      parameters:
      - in: path
        name: service_token_id
        required: true
        schema:
          $ref: '#/components/schemas/access_uuid'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/access_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_api-response-common-failure'
          description: Delete a service token response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_schemas-single_response'
          description: Delete a service token response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Delete a service token
      tags:
      - Access Service Tokens
      x-api-token-group:
      - 'Access: Service Tokens Write'
    get:
      description: Fetches a single service token.
      operationId: access-service-tokens-get-a-service-token
      parameters:
      - in: path
        name: service_token_id
        required: true
        schema:
          $ref: '#/components/schemas/access_uuid'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/access_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_api-response-common-failure'
          description: Get a service token response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_schemas-single_response'
          description: Get a service token response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Get a service token
      tags:
      - Access Service Tokens
      x-api-token-group:
      - 'Access: Service Tokens Write'
      - 'Access: Service Tokens Read'
    put:
      description: Updates a configured service token.
      operationId: access-service-tokens-update-a-service-token
      parameters:
      - in: path
        name: service_token_id
        required: true
        schema:
          $ref: '#/components/schemas/access_uuid'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/access_identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                duration:
                  $ref: '#/components/schemas/access_duration'
                name:
                  $ref: '#/components/schemas/access_schemas-name'
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_api-response-common-failure'
          description: Update a service token response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_schemas-single_response'
          description: Update a service token response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Update a service token
      tags:
      - Access Service Tokens
      x-api-token-group:
      - 'Access: Service Tokens Write'
  /accounts/{account_id}/access/service_tokens/{service_token_id}/refresh:
    post:
      description: Refreshes the expiration of a service token.
      operationId: access-service-tokens-refresh-a-service-token
      parameters:
      - in: path
        name: service_token_id
        required: true
        schema:
          $ref: '#/components/schemas/access_uuid'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/access_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_api-response-common-failure'
          description: Refresh a service token response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_schemas-single_response'
          description: Refresh a service token response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Refresh a service token
      tags:
      - Access Service Tokens
      x-api-token-group:
      - 'Access: Service Tokens Write'
  /accounts/{account_id}/access/service_tokens/{service_token_id}/rotate:
    post:
      description: Generates a new Client Secret for a service token and revokes the old one.
      operationId: access-service-tokens-rotate-a-service-token
      parameters:
      - in: path
        name: service_token_id
        required: true
        schema:
          $ref: '#/components/schemas/access_uuid'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/access_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_api-response-common-failure'
          description: Rotate a service token response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_create_response'
          description: Rotate a service token response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Rotate a service token
      tags:
      - Access Service Tokens
components:
  schemas:
    access_create_response:
      allOf:
      - $ref: '#/components/schemas/access_api-response-single'
      - properties:
          result:
            properties:
              client_id:
                $ref: '#/components/schemas/access_client_id'
              client_secret:
                $ref: '#/components/schemas/access_client_secret'
              created_at:
                $ref: '#/components/schemas/access_timestamp'
              duration:
                $ref: '#/components/schemas/access_duration'
              id:
                description: The ID of the service token.
                type: string
              name:
                $ref: '#/components/schemas/access_schemas-name'
              updated_at:
                $ref: '#/components/schemas/access_timestamp'
    access_client_id:
      description: The Client ID for the service token. Access will check for this value in the `CF-Access-Client-ID` request header.
      example: 88bf3b6d86161464f6509f7219099e57.access.example.com
      type: string
    access_schemas-name:
      description: The name of the service token.
      example: CI/CD token
      type: string
    access_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/access_messages'
        messages:
          $ref: '#/components/schemas/access_messages'
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      type: object
    access_components-schemas-response_collection:
      allOf:
      - $ref: '#/components/schemas/access_api-response-collection'
      - properties:
          result:
            items:
              $ref: '#/components/schemas/access_service-tokens'
            type: array
    access_result_info:
      properties:
        count:
          description: Total number of results for the requested service
          example: 1
          type: number
        page:
          description: Current page within paginated list of results
          example: 1
          type: number
        per_page:
          description: Number of results per page of results
          example: 20
          type: number
        total_count:
          description: Total results available without any search parameters
          example: 2000
          type: number
      type: object
    access_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/access_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/access_messages'
          example: []
        result:
          enum:
          - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    access_identifier:
      description: Identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      type: string
    access_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    access_api-response-collection:
      allOf:
      - $ref: '#/components/schemas/access_api-response-common'
      - properties:
          result_info:
            $ref: '#/components/schemas/access_result_info'
      type: object
    access_service-tokens:
      properties:
        client_id:
          $ref: '#/components/schemas/access_client_id'
        created_at:
          $ref: '#/components/schemas/access_timestamp'
        duration:
          $ref: '#/components/schemas/access_duration'
        expires_at:
          $ref: '#/components/schemas/access_timestamp'
        id:
          allOf:
          - description: The ID of the service token.
          - $ref: '#/components/schemas/access_uuid'
        name:
          $ref: '#/components/schemas/access_schemas-name'
        updated_at:
          $ref: '#/components/schemas/access_timestamp'
      type: object
    access_uuid:
      description: UUID
      example: f174e90a-fafe-4643-bbbc-4a0ed4fc8415
      maxLength: 36
      type: string
    access_client_secret:
      description: The Client Secret for the service token. Access will check for this value in the `CF-Access-Client-Secret` request header.
      example: bdd31cbc4dec990953e39163fbbb194c93313ca9f0a6e420346af9d326b1d2a5
      type: string
    access_duration:
      default: 8760h
      description: 'The duration for how long the service token will be valid. Must be in the format `300ms` or `2h45m`. Valid time units are: ns, us (or µs), ms, s, m, h. The default is 1 year in hours (8760h).'
      example: 60m
      type: string
    access_timestamp:
      example: '2014-01-01T05:20:00.12345Z'
      format: date-time
      type: string
    access_api-response-single:
      allOf:
      - $ref: '#/components/schemas/access_api-response-common'
      type: object
    access_schemas-single_response:
      allOf:
      - $ref: '#/components/schemas/access_api-response-single'
      - properties:
          result:
            $ref: '#/components/schemas/access_service-tokens'
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/apigateway/
x-hasEquivalentPaths: true
