openapi: 3.2.0
info:
  description: 'To get started using Cloudflare''s products and services via the API, refer to [how to interact with Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/), which covers using tools like [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform) and the [official SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows who is making requests and what permissions you have. Create an API token to grant access to the API to perform actions.


    To create an API token, from the Cloudflare dashboard, go to My Profile > API Tokens and select Create Token. For more information on how to create and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).'
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: APIs.io Engineering Platform Cloudflare Worker Account Settings API
  version: 4.0.0
tags:
- name: Worker Account Settings
paths:
  /accounts/{account_id}/workers/account-settings:
    get:
      description: Fetches Worker account settings for an account.
      operationId: worker-account-settings-fetch-worker-account-settings
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/workers_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/workers_account-settings-response'
                - $ref: '#/components/schemas/workers_api-response-common-failure'
          description: Fetch Worker Account Settings response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/workers_account-settings-response'
          description: Fetch Worker Account Settings response
      security:
      - api_token: []
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Fetch Worker Account Settings
      tags:
      - Worker Account Settings
      x-api-token-group:
      - Cloudflare Zero Trust PII Read
      - DDoS Botnet Feed Write
      - DDoS Botnet Feed Read
      - Workers R2 Storage Write
      - Workers R2 Storage Read
      - DDoS Protection Write
      - DDoS Protection Read
      - Workers Tail Read
      - Workers KV Storage Write
      - Workers KV Storage Read
      - Workers Scripts Write
      - Workers Scripts Read
      - 'Load Balancing: Monitors and Pools Write'
      - 'Load Balancing: Monitors and Pools Read'
      - Account Firewall Access Rules Write
      - Account Firewall Access Rules Read
      - DNS Firewall Write
      - DNS Firewall Read
      - Billing Write
      - Billing Read
      - Account Settings Write
      - Account Settings Read
      x-cfPermissionsRequired:
        enum:
        - com.cloudflare.api.account.read
    put:
      description: Creates Worker account settings for an account.
      operationId: worker-account-settings-create-worker-account-settings
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/workers_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/workers_account-settings'
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/workers_account-settings-response'
                - $ref: '#/components/schemas/workers_api-response-common-failure'
          description: Create Worker Account Settings response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/workers_account-settings-response'
          description: Create Worker Account Settings response
      security:
      - api_token: []
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Create Worker Account Settings
      tags:
      - Worker Account Settings
      x-api-token-group:
      - Account Settings Write
      x-cfPermissionsRequired:
        enum:
        - com.cloudflare.api.account.update
components:
  schemas:
    workers_account-settings-response:
      allOf:
      - $ref: '#/components/schemas/workers_api-response-common'
      - properties:
          result:
            $ref: '#/components/schemas/workers_account-settings'
    workers_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/workers_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/workers_messages'
          example: []
        result:
          enum:
          - null
          type:
          - object
          - 'null'
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    workers_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/workers_messages'
        messages:
          $ref: '#/components/schemas/workers_messages'
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      type: object
    workers_account-settings:
      properties:
        default_usage_model:
          type: string
        green_compute:
          type: boolean
      type: object
    workers_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    workers_identifier:
      description: Identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      type: string
  securitySchemes:
    api_email:
      in: header
      name: X-Auth-Email
      type: apiKey
    api_key:
      in: header
      name: X-Auth-Key
      type: apiKey
    api_token:
      scheme: bearer
      type: http
    user_service_key:
      in: header
      name: X-Auth-User-Service-Key
      type: apiKey
