openapi: 3.0.0
info:
  version: "1.0.0"
  x-release: v4
  title: APIs.io Engineering Platform Amazon API Gateway 2014 11 13 Zero Trust Risk Scoring Integrations API
  description: <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: apigateway
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/apigateway-2015-07-09.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: https://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: http://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
- url: https://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: Zero Trust Risk Scoring Integrations
paths:
  /accounts/{account_id}/zt_risk_scoring/integrations:
    get:
      operationId: dlp-zt-risk-score-integration-list
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          type: string
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dlp_api-response-common-failure'
          description: List failure response
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/dlp_api-response-single'
                - properties:
                    result:
                      $ref: '#/components/schemas/dlp_RiskScoreIntegrationArray'
                  type: object
          description: List response
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform List all risk score integrations for the account.
      tags:
      - Zero Trust Risk Scoring Integrations
      x-api-token-group:
      - Teams Read
      - Teams Write
    post:
      operationId: dlp-zt-risk-score-integration-create
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/dlp_CreateIntegrationBody'
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dlp_api-response-common-failure'
          description: Create failure response
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/dlp_api-response-single'
                - properties:
                    result:
                      $ref: '#/components/schemas/dlp_RiskScoreIntegration'
                  type: object
          description: Create response
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Create new risk score integration.
      tags:
      - Zero Trust Risk Scoring Integrations
      x-api-token-group:
      - Teams Write
  /accounts/{account_id}/zt_risk_scoring/integrations/{integration_id}:
    delete:
      operationId: dlp-zt-risk-score-integration-delete
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          type: string
      - in: path
        name: integration_id
        required: true
        schema:
          format: uuid
          type: string
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dlp_api-response-common-failure'
          description: Delete failure response
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/dlp_api-response-single'
                - properties:
                    result:
                      $ref: '#/components/schemas/dlp_Empty'
                  type: object
          description: Delete response
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Delete a risk score integration.
      tags:
      - Zero Trust Risk Scoring Integrations
    get:
      operationId: dlp-zt-risk-score-integration-get
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          type: string
      - in: path
        name: integration_id
        required: true
        schema:
          format: uuid
          type: string
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dlp_api-response-common-failure'
          description: Get failure response
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/dlp_api-response-single'
                - properties:
                    result:
                      $ref: '#/components/schemas/dlp_RiskScoreIntegration'
                  type: object
          description: Get response
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Get risk score integration by id.
      tags:
      - Zero Trust Risk Scoring Integrations
    put:
      description: Overwrite the reference_id, tenant_url, and active values with the ones provided
      operationId: dlp-zt-risk-score-integration-update
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          type: string
      - in: path
        name: integration_id
        required: true
        schema:
          format: uuid
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/dlp_UpdateIntegrationBody'
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dlp_api-response-common-failure'
          description: Update failure response
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/dlp_api-response-single'
                - properties:
                    result:
                      $ref: '#/components/schemas/dlp_RiskScoreIntegration'
                  type: object
          description: Update response
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Update a risk score integration.
      tags:
      - Zero Trust Risk Scoring Integrations
  /accounts/{account_id}/zt_risk_scoring/integrations/reference_id/{reference_id}:
    get:
      operationId: dlp-zt-risk-score-integration-get-by-reference-id
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          type: string
      - in: path
        name: reference_id
        required: true
        schema:
          type: string
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dlp_api-response-common-failure'
          description: Get failure response
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/dlp_api-response-single'
                - properties:
                    result:
                      $ref: '#/components/schemas/dlp_RiskScoreIntegration'
                  type: object
          description: Get response
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Get risk score integration by reference id.
      tags:
      - Zero Trust Risk Scoring Integrations
components:
  schemas:
    dlp_CreateIntegrationBody:
      properties:
        integration_type:
          $ref: '#/components/schemas/dlp_RiskScoreIntegrationType'
        reference_id:
          description: 'A reference id that can be supplied by the client. Currently this should be set to the Access-Okta IDP ID (a UUIDv4).

            https://developers.cloudflare.com/api/operations/access-identity-providers-get-an-access-identity-provider'
          nullable: true
          type: string
        tenant_url:
          description: The base url of the tenant, e.g. "https://tenant.okta.com"
          format: uri
          type: string
      required:
      - integration_type
      - tenant_url
      type: object
    dlp_RiskScoreIntegrationType:
      enum:
      - Okta
      type: string
    dlp_api-response-single:
      allOf:
      - $ref: '#/components/schemas/dlp_api-response-common'
      type: object
    dlp_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/dlp_messages'
        messages:
          $ref: '#/components/schemas/dlp_messages'
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      type: object
    dlp_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/dlp_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/dlp_messages'
          example: []
        result:
          enum:
          - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    dlp_UpdateIntegrationBody:
      properties:
        active:
          description: Whether this integration is enabled. If disabled, no risk changes will be exported to the third-party.
          type: boolean
        reference_id:
          description: 'A reference id that can be supplied by the client. Currently this should be set to the Access-Okta IDP ID (a UUIDv4).

            https://developers.cloudflare.com/api/operations/access-identity-providers-get-an-access-identity-provider'
          nullable: true
          type: string
        tenant_url:
          description: The base url of the tenant, e.g. "https://tenant.okta.com"
          format: uri
          type: string
      required:
      - tenant_url
      - active
      type: object
    dlp_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    dlp_RiskScoreIntegration:
      properties:
        account_tag:
          description: The Cloudflare account tag.
          type: string
        active:
          description: Whether this integration is enabled and should export changes in risk score.
          type: boolean
        created_at:
          description: When the integration was created in RFC3339 format.
          format: date-time
          type: string
        id:
          description: The id of the integration, a UUIDv4.
          format: uuid
          type: string
        integration_type:
          $ref: '#/components/schemas/dlp_RiskScoreIntegrationType'
        reference_id:
          description: 'A reference ID defined by the client.

            Should be set to the Access-Okta IDP integration ID.

            Useful when the risk-score integration needs to be associated with a secondary asset and recalled using that ID.'
          type: string
        tenant_url:
          description: The base URL for the tenant. E.g. "https://tenant.okta.com"
          type: string
        well_known_url:
          description: The URL for the Shared Signals Framework configuration, e.g. "/.well-known/sse-configuration/{integration_uuid}/". https://openid.net/specs/openid-sse-framework-1_0.html#rfc.section.6.2.1
          type: string
      required:
      - id
      - account_tag
      - integration_type
      - reference_id
      - tenant_url
      - well_known_url
      - active
      - created_at
      type: object
    dlp_RiskScoreIntegrationArray:
      items:
        $ref: '#/components/schemas/dlp_RiskScoreIntegration'
      type: array
    dlp_Empty:
      nullable: true
      type: object
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/apigateway/
x-hasEquivalentPaths: true
