openapi: 3.0.0
info:
  version: "1.0.0"
  x-release: v4
  title: APIs.io Engineering Platform Amazon API Gateway 2014 11 13 Device DEX Tests API
  description: <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: apigateway
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/apigateway-2015-07-09.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: https://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: http://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
- url: https://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: Device DEX Tests
paths:
  /accounts/{account_id}/devices/dex_tests:
    get:
      description: Fetch all DEX tests.
      operationId: device-dex-test-details
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/teams-devices_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/teams-devices_dex-single_response'
                - $ref: '#/components/schemas/teams-devices_api-response-common-failure'
          description: Device DEX test response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/teams-devices_dex-response_collection'
          description: Device DEX test details response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform List Device DEX tests
      tags:
      - Device DEX Tests
      x-api-token-group:
      - Cloudflare DEX Write
      - Cloudflare DEX Read
      - Teams Report
      - Teams Read
    post:
      description: Create a DEX test.
      operationId: device-dex-test-create-device-dex-test
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/teams-devices_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/teams-devices_device-dex-test-schemas-http'
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/teams-devices_dex-single_response'
                - $ref: '#/components/schemas/teams-devices_api-response-common-failure'
          description: Update Dex test response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/teams-devices_dex-single_response'
          description: Update Dex test response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Create Device DEX test
      tags:
      - Device DEX Tests
      x-api-token-group:
      - Cloudflare DEX Write
  /accounts/{account_id}/devices/dex_tests/{dex_test_id}:
    delete:
      description: Delete a Device DEX test. Returns the remaining device dex tests for the account.
      operationId: device-dex-test-delete-device-dex-test
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/teams-devices_identifier'
      - in: path
        name: dex_test_id
        required: true
        schema:
          $ref: '#/components/schemas/teams-devices_uuid'
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/teams-devices_dex-response_collection'
                - $ref: '#/components/schemas/teams-devices_api-response-common-failure'
          description: Delete DEX test response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/teams-devices_dex-response_collection'
          description: Delete Device DEX test response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Delete Device DEX test
      tags:
      - Device DEX Tests
      x-api-token-group:
      - Cloudflare DEX Write
    get:
      description: Fetch a single DEX test.
      operationId: device-dex-test-get-device-dex-test
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/teams-devices_identifier'
      - in: path
        name: dex_test_id
        required: true
        schema:
          $ref: '#/components/schemas/teams-devices_uuid'
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/teams-devices_dex-single_response'
                - $ref: '#/components/schemas/teams-devices_api-response-common-failure'
          description: Device DEX test response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/teams-devices_dex-single_response'
          description: Device DEX test details response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Get Device DEX test
      tags:
      - Device DEX Tests
      x-api-token-group:
      - Cloudflare DEX Write
      - Cloudflare DEX Read
      - Teams Report
      - Teams Read
    put:
      description: Update a DEX test.
      operationId: device-dex-test-update-device-dex-test
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/teams-devices_identifier'
      - in: path
        name: dex_test_id
        required: true
        schema:
          $ref: '#/components/schemas/teams-devices_uuid'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/teams-devices_device-dex-test-schemas-http'
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/teams-devices_dex-single_response'
                - $ref: '#/components/schemas/teams-devices_api-response-common-failure'
          description: Update Dex test response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/teams-devices_dex-single_response'
          description: Update Dex test response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Update Device DEX test
      tags:
      - Device DEX Tests
      x-api-token-group:
      - Cloudflare DEX Write
components:
  schemas:
    teams-devices_dex_target_policy:
      properties:
        default:
          description: Whether the profile is the account default
          type: boolean
        id:
          description: The id of the device settings profile
          type: string
        name:
          description: The name of the device settings profile
          type: string
      type: object
    teams-devices_device-dex-test-schemas-interval:
      description: How often the test will run.
      example: 30m
      type: string
    teams-devices_device-dex-test-schemas-description:
      description: Additional details about the test.
      example: Checks the dash endpoint every 30 minutes
      type: string
    teams-devices_dex-single_response:
      allOf:
      - $ref: '#/components/schemas/teams-devices_api-response-single'
      - properties:
          result:
            $ref: '#/components/schemas/teams-devices_device-dex-test-schemas-http'
    teams-devices_device-dex-test-target-policies:
      description: Device settings profiles targeted by this test
      items:
        $ref: '#/components/schemas/teams-devices_dex_target_policy'
      type: array
    teams-devices_api-response-single:
      allOf:
      - $ref: '#/components/schemas/teams-devices_api-response-common'
      - properties:
          result:
            anyOf:
            - type: object
            - type: string
            nullable: true
            type: object
      type: object
    teams-devices_device-dex-test-schemas-enabled:
      description: Determines whether or not the test is active.
      example: true
      type: boolean
    teams-devices_device-dex-test-schemas-data:
      description: The configuration object which contains the details for the WARP client to conduct the test.
      example:
        host: https://dash.cloudflare.com
        kind: http
        method: GET
      properties:
        host:
          description: The desired endpoint to test.
          example: https://dash.cloudflare.com
          type: string
        kind:
          description: The type of test.
          example: http
          type: string
        method:
          description: The HTTP request method type.
          example: GET
          type: string
      type: object
    teams-devices_identifier:
      example: 699d98642c564d2e855e9661899b7252
    teams-devices_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/teams-devices_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/teams-devices_messages'
          example: []
        result:
          enum:
          - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    teams-devices_uuid:
      description: API UUID.
      example: f174e90a-fafe-4643-bbbc-4a0ed4fc8415
      maxLength: 36
      type: string
    teams-devices_device-dex-test-schemas-http:
      properties:
        data:
          $ref: '#/components/schemas/teams-devices_device-dex-test-schemas-data'
        description:
          $ref: '#/components/schemas/teams-devices_device-dex-test-schemas-description'
        enabled:
          $ref: '#/components/schemas/teams-devices_device-dex-test-schemas-enabled'
        interval:
          $ref: '#/components/schemas/teams-devices_device-dex-test-schemas-interval'
        name:
          $ref: '#/components/schemas/teams-devices_device-dex-test-schemas-name'
        target_policies:
          $ref: '#/components/schemas/teams-devices_device-dex-test-target-policies'
        targeted:
          type: boolean
      required:
      - name
      - interval
      - enabled
      - data
      type: object
    teams-devices_device-dex-test-schemas-name:
      description: The name of the DEX test. Must be unique.
      example: HTTP dash health check
      type: string
    teams-devices_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/teams-devices_messages'
        messages:
          $ref: '#/components/schemas/teams-devices_messages'
        result:
          anyOf:
          - type: object
          - items: {}
            type: array
          - type: string
        success:
          description: Whether the API call was successful.
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    teams-devices_api-response-collection-common:
      allOf:
      - $ref: '#/components/schemas/teams-devices_api-response-common'
      - properties:
          result:
            items: {}
            nullable: true
            type: array
      type: object
    teams-devices_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    teams-devices_dex-response_collection:
      allOf:
      - $ref: '#/components/schemas/teams-devices_api-response-collection-common'
      - properties:
          result:
            items:
              $ref: '#/components/schemas/teams-devices_device-dex-test-schemas-http'
            type: array
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/apigateway/
x-hasEquivalentPaths: true
