openapi: 3.2.0
info:
  description: 'To get started using Cloudflare''s products and services via the API, refer to [how to interact with Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/), which covers using tools like [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform) and the [official SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows who is making requests and what permissions you have. Create an API token to grant access to the API to perform actions.


    To create an API token, from the Cloudflare dashboard, go to My Profile > API Tokens and select Create Token. For more information on how to create and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).'
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: APIs.io Engineering Platform Cloudflare Security Center Insights API
  version: 4.0.0
tags:
- name: Security Center Insights
paths:
  /accounts/{account_id}/intel/attack-surface-report/{issue_id}/dismiss:
    put:
      operationId: archive-security-center-insight
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/security-center_identifier'
      - in: path
        name: issue_id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                dismiss:
                  default: true
                  type: boolean
              type: object
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/security-center_api-response-common-failure'
          description: Client Error
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/security-center_api-response-single'
          description: OK
      security:
      - api_email: []
        api_key: []
      - api_token: []
      summary: APIs.io Engineering Platform Archive Security Center Insight
      tags:
      - Security Center Insights
  /accounts/{account_id}/intel/attack-surface-report/issue-types:
    get:
      operationId: get-security-center-issue-types
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/security-center_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/security-center_api-response-common-failure'
          description: Client Error
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/security-center_api-response-common'
                - properties:
                    result:
                      anyOf:
                      - items:
                          type: string
                        type: array
          description: OK
      security:
      - api_email: []
        api_key: []
      - api_token: []
      summary: APIs.io Engineering Platform Get Security Center Issues Types
      tags:
      - Security Center Insights
  /accounts/{account_id}/intel/attack-surface-report/issues:
    get:
      operationId: get-security-center-issues
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/security-center_identifier'
      - in: query
        name: dismissed
        schema:
          $ref: '#/components/schemas/security-center_dismissed'
      - in: query
        name: issue_class
        schema:
          $ref: '#/components/schemas/security-center_issueClasses'
      - in: query
        name: issue_type
        schema:
          $ref: '#/components/schemas/security-center_issueTypes'
      - in: query
        name: product
        schema:
          $ref: '#/components/schemas/security-center_products'
      - in: query
        name: severity
        schema:
          $ref: '#/components/schemas/security-center_severityQueryParam'
      - in: query
        name: subject
        schema:
          $ref: '#/components/schemas/security-center_subjects'
      - in: query
        name: issue_class~neq
        schema:
          $ref: '#/components/schemas/security-center_issueClasses'
      - in: query
        name: issue_type~neq
        schema:
          $ref: '#/components/schemas/security-center_issueTypes'
      - in: query
        name: product~neq
        schema:
          $ref: '#/components/schemas/security-center_products'
      - in: query
        name: severity~neq
        schema:
          $ref: '#/components/schemas/security-center_severityQueryParam'
      - in: query
        name: subject~neq
        schema:
          $ref: '#/components/schemas/security-center_subjects'
      - in: query
        name: page
        schema:
          allOf:
          - $ref: '#/components/schemas/security-center_page'
          default: 1
      - in: query
        name: per_page
        schema:
          allOf:
          - $ref: '#/components/schemas/security-center_perPage'
          default: 25
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/security-center_api-response-common-failure'
          description: Client Error
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/security-center_api-response-common'
                - properties:
                    result:
                      anyOf:
                      - properties:
                          count:
                            $ref: '#/components/schemas/security-center_count'
                          issues:
                            items:
                              $ref: '#/components/schemas/security-center_issue'
                            type: array
                          page:
                            $ref: '#/components/schemas/security-center_page'
                          per_page:
                            $ref: '#/components/schemas/security-center_perPage'
                        type: object
          description: OK
      security:
      - api_email: []
        api_key: []
      - api_token: []
      summary: APIs.io Engineering Platform Get Security Center Issues
      tags:
      - Security Center Insights
  /accounts/{account_id}/intel/attack-surface-report/issues/class:
    get:
      operationId: get-security-center-issue-counts-by-class
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/security-center_identifier'
      - in: query
        name: dismissed
        schema:
          $ref: '#/components/schemas/security-center_dismissed'
      - in: query
        name: issue_class
        schema:
          $ref: '#/components/schemas/security-center_issueClasses'
      - in: query
        name: issue_type
        schema:
          $ref: '#/components/schemas/security-center_issueTypes'
      - in: query
        name: product
        schema:
          $ref: '#/components/schemas/security-center_products'
      - in: query
        name: severity
        schema:
          $ref: '#/components/schemas/security-center_severityQueryParam'
      - in: query
        name: subject
        schema:
          $ref: '#/components/schemas/security-center_subjects'
      - in: query
        name: issue_class~neq
        schema:
          $ref: '#/components/schemas/security-center_issueClasses'
      - in: query
        name: issue_type~neq
        schema:
          $ref: '#/components/schemas/security-center_issueTypes'
      - in: query
        name: product~neq
        schema:
          $ref: '#/components/schemas/security-center_products'
      - in: query
        name: severity~neq
        schema:
          $ref: '#/components/schemas/security-center_severityQueryParam'
      - in: query
        name: subject~neq
        schema:
          $ref: '#/components/schemas/security-center_subjects'
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/security-center_api-response-common-failure'
          description: Client Error
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/security-center_valueCountsResponse'
          description: OK
      security:
      - api_email: []
        api_key: []
      - api_token: []
      summary: APIs.io Engineering Platform Get Security Center Issue Counts by Class
      tags:
      - Security Center Insights
  /accounts/{account_id}/intel/attack-surface-report/issues/severity:
    get:
      operationId: get-security-center-issue-counts-by-severity
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/security-center_identifier'
      - in: query
        name: dismissed
        schema:
          $ref: '#/components/schemas/security-center_dismissed'
      - in: query
        name: issue_class
        schema:
          $ref: '#/components/schemas/security-center_issueClasses'
      - in: query
        name: issue_type
        schema:
          $ref: '#/components/schemas/security-center_issueTypes'
      - in: query
        name: product
        schema:
          $ref: '#/components/schemas/security-center_products'
      - in: query
        name: severity
        schema:
          $ref: '#/components/schemas/security-center_severityQueryParam'
      - in: query
        name: subject
        schema:
          $ref: '#/components/schemas/security-center_subjects'
      - in: query
        name: issue_class~neq
        schema:
          $ref: '#/components/schemas/security-center_issueClasses'
      - in: query
        name: issue_type~neq
        schema:
          $ref: '#/components/schemas/security-center_issueTypes'
      - in: query
        name: product~neq
        schema:
          $ref: '#/components/schemas/security-center_products'
      - in: query
        name: severity~neq
        schema:
          $ref: '#/components/schemas/security-center_severityQueryParam'
      - in: query
        name: subject~neq
        schema:
          $ref: '#/components/schemas/security-center_subjects'
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/security-center_api-response-common-failure'
          description: Client Error
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/security-center_valueCountsResponse'
          description: OK
      security:
      - api_email: []
        api_key: []
      - api_token: []
      summary: APIs.io Engineering Platform Get Security Center Issue Counts by Severity
      tags:
      - Security Center Insights
  /accounts/{account_id}/intel/attack-surface-report/issues/type:
    get:
      operationId: get-security-center-issue-counts-by-type
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/security-center_identifier'
      - in: query
        name: dismissed
        schema:
          $ref: '#/components/schemas/security-center_dismissed'
      - in: query
        name: issue_class
        schema:
          $ref: '#/components/schemas/security-center_issueClasses'
      - in: query
        name: issue_type
        schema:
          $ref: '#/components/schemas/security-center_issueTypes'
      - in: query
        name: product
        schema:
          $ref: '#/components/schemas/security-center_products'
      - in: query
        name: severity
        schema:
          $ref: '#/components/schemas/security-center_severityQueryParam'
      - in: query
        name: subject
        schema:
          $ref: '#/components/schemas/security-center_subjects'
      - in: query
        name: issue_class~neq
        schema:
          $ref: '#/components/schemas/security-center_issueClasses'
      - in: query
        name: issue_type~neq
        schema:
          $ref: '#/components/schemas/security-center_issueTypes'
      - in: query
        name: product~neq
        schema:
          $ref: '#/components/schemas/security-center_products'
      - in: query
        name: severity~neq
        schema:
          $ref: '#/components/schemas/security-center_severityQueryParam'
      - in: query
        name: subject~neq
        schema:
          $ref: '#/components/schemas/security-center_subjects'
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/security-center_api-response-common-failure'
          description: Client Error
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/security-center_valueCountsResponse'
          description: OK
      security:
      - api_email: []
        api_key: []
      - api_token: []
      summary: APIs.io Engineering Platform Get Security Center Issue Counts by Type
      tags:
      - Security Center Insights
components:
  schemas:
    security-center_count:
      description: Total number of results
      example: 1
      type: integer
    security-center_issueTypes:
      example:
      - compliance_violation
      - email_security
      items:
        $ref: '#/components/schemas/security-center_issueType'
      type: array
    security-center_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    security-center_valueCountsResponse:
      allOf:
      - $ref: '#/components/schemas/security-center_api-response-common'
      - properties:
          result:
            anyOf:
            - items:
                properties:
                  count:
                    example: 1
                    type: integer
                  value:
                    type: string
                type: object
              type: array
    security-center_products:
      example:
      - access
      - dns
      items:
        type: string
      type: array
    security-center_subjects:
      items:
        $ref: '#/components/schemas/security-center_subject'
      type: array
    security-center_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/security-center_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/security-center_messages'
          example: []
        result:
          enum:
          - null
          type:
          - object
          - 'null'
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    security-center_dismissed:
      example: false
      type: boolean
    security-center_issueType:
      enum:
      - compliance_violation
      - email_security
      - exposed_infrastructure
      - insecure_configuration
      - weak_authentication
      type: string
    security-center_perPage:
      description: Number of results per page of results
      example: 25
      maximum: 1000
      minimum: 1
      type: integer
    security-center_issueClasses:
      example:
      - a_record_dangling
      - always_use_https_not_enabled
      items:
        $ref: '#/components/schemas/security-center_issueClass'
      type: array
    security-center_issueClass:
      example: always_use_https_not_enabled
      type: string
    security-center_subject:
      example: example.com
      type: string
    security-center_severityQueryParam:
      example:
      - low
      - moderate
      items:
        enum:
        - low
        - moderate
        - critical
        type: string
      type: array
    security-center_identifier:
      description: Identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      type: string
    security-center_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/security-center_messages'
        messages:
          $ref: '#/components/schemas/security-center_messages'
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      type: object
    security-center_issue:
      properties:
        dismissed:
          example: false
          type: boolean
        id:
          type: string
        issue_class:
          $ref: '#/components/schemas/security-center_issueClass'
        issue_type:
          $ref: '#/components/schemas/security-center_issueType'
        payload:
          type: object
        resolve_link:
          type: string
        resolve_text:
          type: string
        severity:
          enum:
          - Low
          - Moderate
          - Critical
          type: string
        since:
          format: date-time
          type: string
        subject:
          $ref: '#/components/schemas/security-center_subject'
        timestamp:
          format: date-time
          type: string
      type: object
    security-center_page:
      description: Current page within paginated list of results
      example: 1
      type: integer
    security-center_api-response-single:
      allOf:
      - $ref: '#/components/schemas/security-center_api-response-common'
      type: object
  securitySchemes:
    api_email:
      in: header
      name: X-Auth-Email
      type: apiKey
    api_key:
      in: header
      name: X-Auth-Key
      type: apiKey
    api_token:
      scheme: bearer
      type: http
    user_service_key:
      in: header
      name: X-Auth-User-Service-Key
      type: apiKey
