openapi: 3.2.0
info:
  description: 'To get started using Cloudflare''s products and services via the API, refer to [how to interact with Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/), which covers using tools like [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform) and the [official SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows who is making requests and what permissions you have. Create an API token to grant access to the API to perform actions.


    To create an API token, from the Cloudflare dashboard, go to My Profile > API Tokens and select Create Token. For more information on how to create and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).'
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: APIs.io Engineering Platform Cloudflare Zero Trust Audit SSH Settings API
  version: 4.0.0
tags:
- name: Zero Trust Audit SSH Settings
paths:
  /accounts/{account_id}/gateway/audit_ssh_settings:
    get:
      description: Get all Zero Trust Audit SSH settings for an account.
      operationId: zero-trust-get-audit-ssh-settings
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/zero-trust-gateway_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/zero-trust-gateway_audit_ssh_settings_components-schemas-single_response'
                - $ref: '#/components/schemas/zero-trust-gateway_api-response-common-failure'
          description: Get Zero Trust Audit SSH Settings response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/zero-trust-gateway_audit_ssh_settings_components-schemas-single_response'
          description: Get Zero Trust Audit SSH settings response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Get Zero Trust Audit SSH settings
      tags:
      - Zero Trust Audit SSH Settings
    put:
      description: Updates Zero Trust Audit SSH settings.
      operationId: zero-trust-update-audit-ssh-settings
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/zero-trust-gateway_identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                public_key:
                  $ref: '#/components/schemas/zero-trust-gateway_public_key'
                seed_id:
                  $ref: '#/components/schemas/zero-trust-gateway_audit_ssh_settings_components-schemas-uuid'
              required:
              - public_key
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/zero-trust-gateway_audit_ssh_settings_components-schemas-single_response'
                - $ref: '#/components/schemas/zero-trust-gateway_api-response-common-failure'
          description: Update Zero Trust Audit SSH Setting response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/zero-trust-gateway_audit_ssh_settings_components-schemas-single_response'
          description: Update Zero Trust Audit SSH Setting response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Update Zero Trust Audit SSH settings
      tags:
      - Zero Trust Audit SSH Settings
components:
  schemas:
    zero-trust-gateway_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/zero-trust-gateway_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/zero-trust-gateway_messages'
          example: []
        result:
          enum:
          - null
          type:
          - object
          - 'null'
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    zero-trust-gateway_api-response-single:
      allOf:
      - $ref: '#/components/schemas/zero-trust-gateway_api-response-common'
      type: object
    zero-trust-gateway_audit_ssh_settings_components-schemas-single_response:
      allOf:
      - $ref: '#/components/schemas/zero-trust-gateway_api-response-single'
      - properties:
          result:
            $ref: '#/components/schemas/zero-trust-gateway_settings'
    zero-trust-gateway_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/zero-trust-gateway_messages'
        messages:
          $ref: '#/components/schemas/zero-trust-gateway_messages'
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      type: object
    zero-trust-gateway_settings:
      properties:
        created_at:
          $ref: '#/components/schemas/zero-trust-gateway_timestamp'
        public_key:
          $ref: '#/components/schemas/zero-trust-gateway_public_key'
        seed_id:
          $ref: '#/components/schemas/zero-trust-gateway_audit_ssh_settings_components-schemas-uuid'
        updated_at:
          $ref: '#/components/schemas/zero-trust-gateway_timestamp'
      type: object
    zero-trust-gateway_audit_ssh_settings_components-schemas-uuid:
      description: Seed ID
      example: f174e90a-fafe-4643-bbbc-4a0ed4fc8415
      maxLength: 36
      type: string
    zero-trust-gateway_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    zero-trust-gateway_timestamp:
      example: '2014-01-01T05:20:00.12345Z'
      format: date-time
      type: string
    zero-trust-gateway_public_key:
      description: SSH encryption public key
      example: 1pyl6I1tL7xfJuFYVzXlUW8uXXlpxegHXBzGCBKaSFA=
      type: string
    zero-trust-gateway_identifier:
      example: 699d98642c564d2e855e9661899b7252
      type: string
  securitySchemes:
    api_email:
      in: header
      name: X-Auth-Email
      type: apiKey
    api_key:
      in: header
      name: X-Auth-Key
      type: apiKey
    api_token:
      scheme: bearer
      type: http
    user_service_key:
      in: header
      name: X-Auth-User-Service-Key
      type: apiKey
