openapi: 3.0.0
info:
  version: 2015-07-09
  x-release: v4
  title: APIs.io Engineering Platform Amazon API Gateway 2014 11 13 Account Resource Groups API
  description: <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: apigateway
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/apigateway-2015-07-09.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: https://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: http://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
- url: https://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: Account Resource Groups
paths:
  /accounts/{account_id}/iam/resource_groups:
    get:
      description: List all the resource groups for an account.
      operationId: account-resource-group-list
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/iam_account_identifier'
      - in: query
        name: id
        schema:
          description: ID of the resource group to be fetched.
          example: 6d7f2f5f5b1d4a0e9081fdc98d432fd1
          maxLength: 32
          minLength: 32
          type: string
      - in: query
        name: name
        schema:
          description: Name of the resource group to be fetched.
          example: NameOfTheResourceGroup
          type: string
      - in: query
        name: page
        schema:
          default: 1
          description: Page number of paginated results.
          minimum: 1
          type: number
      - in: query
        name: per_page
        schema:
          default: 20
          description: Maximum number of results per page.
          maximum: 50
          minimum: 5
          type: number
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/iam_api-response-common-failure'
          description: List Resource Groups response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/iam_collection_resource_groups_response'
          description: List Resource Groups response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform List Resource Groups
      tags:
      - Account Resource Groups
      x-cfPermissionsRequired:
        enum:
        - com.cloudflare.api.iam.resource-group.list
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
    post:
      description: Create a new Resource Group under the specified account.
      operationId: account-resource-group-create
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/iam_account_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/iam_create_resource_group'
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/iam_api-response-common-failure'
          description: Add Member response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/iam_created_resource_group_response'
          description: Add Resource Group response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Create Resource Group
      tags:
      - Account Resource Groups
      x-cfPermissionsRequired:
        enum:
        - com.cloudflare.api.iam.resource-group.create
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
  /accounts/{account_id}/iam/resource_groups/{resource_group_id}:
    delete:
      description: Remove a resource group from an account.
      operationId: account-resource-group-delete
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/iam_account_identifier'
      - in: path
        name: resource_group_id
        required: true
        schema:
          $ref: '#/components/schemas/iam_resource_group_components-schemas-identifier'
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/iam_api-response-common-failure'
          description: Remove Member response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/iam_api-response-single-id'
          description: Remove Resource Group response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Remove Resource Group
      tags:
      - Account Resource Groups
      x-cfPermissionsRequired:
        enum:
        - com.cloudflare.api.iam.resource-group.delete
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
    get:
      description: Get information about a specific resource group in an account.
      operationId: account-resource-group-details
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/iam_account_identifier'
      - in: path
        name: resource_group_id
        required: true
        schema:
          $ref: '#/components/schemas/iam_resource_group_components-schemas-identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/iam_api-response-common-failure'
          description: Resource Group Details response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/iam_resource_group'
          description: Resource Group Details response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Resource Group Details
      tags:
      - Account Resource Groups
      x-cfPermissionsRequired:
        enum:
        - com.cloudflare.api.iam.resource-group.read
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
    put:
      description: Modify an existing resource group.
      operationId: account-resource-group-update
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/iam_account_identifier'
      - in: path
        name: resource_group_id
        required: true
        schema:
          $ref: '#/components/schemas/iam_resource_group_components-schemas-identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/iam_create_resource_group'
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/iam_api-response-common-failure'
          description: Update Resource Group response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/iam_resource_group'
          description: Update Resource Group response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Update Resource Group
      tags:
      - Account Resource Groups
      x-cfPermissionsRequired:
        enum:
        - com.cloudflare.api.iam.resource-group.update
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
components:
  schemas:
    iam_scope:
      description: A scope is a combination of scope objects which provides additional context.
      properties:
        key:
          $ref: '#/components/schemas/iam_scope_key'
        objects:
          description: A list of scope objects for additional context.
          items:
            $ref: '#/components/schemas/iam_scope_object'
          type: array
      required:
      - key
      - objects
      type: object
    iam_resource_group_components-schemas-identifier:
      description: Resource Group identifier tag.
      example: 6d7f2f5f5b1d4a0e9081fdc98d432fd1
      maxLength: 32
      readOnly: true
      type: string
    iam_create_resource_group_scope_scope_object:
      description: A scope object represents any resource that can have actions applied against invite.
      properties:
        key:
          $ref: '#/components/schemas/iam_create_resource_group_scope_scope_object_key'
      required:
      - key
      type: object
    iam_scope_key:
      description: This is a combination of pre-defined resource name and identifier (like Account ID etc.)
      example: com.cloudflare.api.account.eb78d65290b24279ba6f44721b3ea3c4
      readOnly: true
    iam_account_identifier:
      description: Account identifier tag.
      example: eb78d65290b24279ba6f44721b3ea3c4
      maxLength: 32
      readOnly: true
      type: string
    iam_result_info:
      properties:
        count:
          description: Total number of results for the requested service
          example: 1
          type: number
        page:
          description: Current page within paginated list of results
          example: 1
          type: number
        per_page:
          description: Number of results per page of results
          example: 20
          type: number
        total_count:
          description: Total results available without any search parameters
          example: 2000
          type: number
      type: object
    iam_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/iam_messages'
        messages:
          $ref: '#/components/schemas/iam_messages'
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      type: object
    iam_create-scope:
      description: A scope is a combination of scope objects which provides additional context.
      properties:
        key:
          $ref: '#/components/schemas/iam_create_resource_group_scope_scope_key'
        objects:
          description: A list of scope objects for additional context. The number of Scope objects should not be zero.
          items:
            $ref: '#/components/schemas/iam_create_resource_group_scope_scope_object'
          type: array
      required:
      - key
      - objects
      type: object
    iam_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/iam_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/iam_messages'
          example: []
        result:
          enum:
          - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    iam_scope_object_key:
      description: This is a combination of pre-defined resource name and identifier (like Zone ID etc.)
      example: com.cloudflare.api.account.zone.23f8d65290b24279ba6f44721b3eaad5
      readOnly: true
    iam_created_resource_group_response:
      description: A group of scoped resources.
      properties:
        id:
          description: Identifier of the group.
          example: 6d7f2f5f5b1d4a0e9081fdc98d432fd1
          readOnly: true
          type: string
        meta:
          description: Attributes associated to the resource group.
          example:
            editable: 'false'
          type: object
        scope:
          $ref: '#/components/schemas/iam_create-scope'
      type: object
    iam_common_components-schemas-identifier:
      description: Identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      readOnly: true
      type: string
    iam_api-response-collection:
      allOf:
      - $ref: '#/components/schemas/iam_api-response-common'
      - properties:
          result:
            items: {}
            nullable: true
            type: array
          result_info:
            $ref: '#/components/schemas/iam_result_info'
      type: object
    iam_create_resource_group:
      properties:
        meta:
          description: Attributes associated to the resource group.
          example:
            editable: 'false'
          type: object
        name:
          description: Name of the resource group.
          example: NameOfTheResourceGroup
          readOnly: true
          type: string
        scope:
          $ref: '#/components/schemas/iam_create-scope'
      required:
      - scope
      type: object
    iam_create_resource_group_scope_scope_key:
      description: This is a combination of pre-defined resource name and identifier (like Account ID etc.)
      example: com.cloudflare.api.account.eb78d65290b24279ba6f44721b3ea3c4
    iam_create_resource_group_scope_scope_object_key:
      description: This is a combination of pre-defined resource name and identifier (like Zone ID etc.)
      example: com.cloudflare.api.account.zone.23f8d65290b24279ba6f44721b3eaad5
    iam_collection_resource_groups_response:
      allOf:
      - $ref: '#/components/schemas/iam_api-response-collection'
      - properties:
          result:
            $ref: '#/components/schemas/iam_resource_groups'
        type: object
      title: List of Resource groups
    iam_resource_group:
      description: A group of scoped resources.
      properties:
        id:
          description: Identifier of the group.
          example: 6d7f2f5f5b1d4a0e9081fdc98d432fd1
          readOnly: true
          type: string
        meta:
          description: Attributes associated to the resource group.
          example:
            editable: 'false'
          properties:
            key:
              type: string
            value:
              type: string
          type: object
        name:
          description: Name of the resource group.
          example: com.cloudflare.api.account.eb78d65290b24279ba6f44721b3ea3c4
          readOnly: true
          type: string
        scope:
          description: The scope associated to the resource group
          items:
            $ref: '#/components/schemas/iam_scope'
          type: array
      required:
      - id
      - scope
      type: object
    iam_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    iam_scope_object:
      description: A scope object represents any resource that can have actions applied against invite.
      properties:
        key:
          $ref: '#/components/schemas/iam_scope_object_key'
      required:
      - key
      type: object
    iam_resource_groups:
      description: A list of resource groups that the policy applies to.
      items:
        $ref: '#/components/schemas/iam_resource_group'
      type: array
    iam_api-response-single-id:
      allOf:
      - $ref: '#/components/schemas/iam_api-response-common'
      - properties:
          result:
            nullable: true
            properties:
              id:
                $ref: '#/components/schemas/iam_common_components-schemas-identifier'
            required:
            - id
            type: object
      type: object
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/apigateway/
x-hasEquivalentPaths: true
