openapi: 3.0.0
info:
  version: 2015-07-09
  x-release: v4
  title: APIs.io Engineering Platform Amazon API Gateway 2014 11 13 Registrar Domains API
  description: <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: apigateway
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/apigateway-2015-07-09.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: https://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: http://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
- url: https://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: Registrar Domains
paths:
  /accounts/{account_id}/registrar/domains:
    get:
      description: List domains handled by Registrar.
      operationId: registrar-domains-list-domains
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/registrar-api_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/registrar-api_domain_response_collection'
                - $ref: '#/components/schemas/registrar-api_api-response-common-failure'
          description: List domains response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/registrar-api_domain_response_collection'
          description: List domains response
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform List domains
      tags:
      - Registrar Domains
  /accounts/{account_id}/registrar/domains/{domain_name}:
    get:
      description: Show individual domain.
      operationId: registrar-domains-get-domain
      parameters:
      - in: path
        name: domain_name
        required: true
        schema:
          $ref: '#/components/schemas/registrar-api_domain_name'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/registrar-api_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/registrar-api_domain_response_single'
                - $ref: '#/components/schemas/registrar-api_api-response-common-failure'
          description: Get domain response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/registrar-api_domain_response_single'
          description: Get domain response
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Get domain
      tags:
      - Registrar Domains
    put:
      description: Update individual domain.
      operationId: registrar-domains-update-domain
      parameters:
      - in: path
        name: domain_name
        required: true
        schema:
          $ref: '#/components/schemas/registrar-api_domain_name'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/registrar-api_identifier'
      requestBody:
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/registrar-api_domain_update_properties'
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/registrar-api_domain_response_single'
                - $ref: '#/components/schemas/registrar-api_api-response-common-failure'
          description: Update domain response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/registrar-api_domain_response_single'
          description: Update domain response
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Update domain
      tags:
      - Registrar Domains
components:
  schemas:
    registrar-api_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/registrar-api_messages'
        messages:
          $ref: '#/components/schemas/registrar-api_messages'
        result:
          anyOf:
          - type: object
          - items:
              type: object
            type: array
          - type: string
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    registrar-api_contacts:
      allOf:
      - $ref: '#/components/schemas/registrar-api_contact_properties'
      type: object
    registrar-api_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/registrar-api_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/registrar-api_messages'
          example: []
        result:
          enum:
          - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    registrar-api_zipcode:
      description: The zipcode or postal code where the user lives.
      example: '12345'
      maxLength: 20
      nullable: true
      type: string
    registrar-api_domain_identifier:
      description: Domain identifier.
      example: ea95132c15732412d22c1476fa83f27a
      maxLength: 32
      readOnly: true
      type: string
    registrar-api_organization:
      description: Name of organization.
      example: Cloudflare, Inc.
      type: string
    registrar-api_created_at:
      description: Shows time of creation.
      example: '2018-08-28T17:26:26Z'
      format: date-time
      type: string
    registrar-api_first_name:
      description: User's first name
      example: John
      maxLength: 60
      nullable: true
      type: string
    registrar-api_email:
      description: The contact email address of the user.
      example: user@example.com
      maxLength: 90
      type: string
    registrar-api_locked:
      description: Shows whether a registrar lock is in place for a domain.
      example: false
      type: boolean
    registrar-api_domain_response_single:
      allOf:
      - $ref: '#/components/schemas/registrar-api_api-response-single'
      - properties:
          result:
            type: object
    registrar-api_can_register:
      description: Indicates if the domain can be registered as a new domain.
      example: false
      type: boolean
    registrar-api_api-response-single:
      allOf:
      - $ref: '#/components/schemas/registrar-api_api-response-common'
      - properties:
          result:
            nullable: true
            type: object
      type: object
    registrar-api_domains:
      allOf:
      - $ref: '#/components/schemas/registrar-api_domain_properties'
      type: object
    registrar-api_supported_tld:
      description: Whether a particular TLD is currently supported by Cloudflare Registrar. Refer to [TLD Policies](https://www.cloudflare.com/tld-policies/) for a list of supported TLDs.
      example: true
      type: boolean
    registrar-api_city:
      description: City.
      example: Austin
      type: string
    registrar-api_current_registrar:
      description: Shows name of current registrar.
      example: Cloudflare
      type: string
    registrar-api_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    registrar-api_state:
      description: State.
      example: TX
      type: string
    registrar-api_updated_at:
      description: Last updated.
      example: '2018-08-28T17:26:26Z'
      format: date-time
      type: string
    registrar-api_country:
      description: The country in which the user lives.
      example: US
      maxLength: 30
      nullable: true
      type: string
    registrar-api_privacy:
      description: Privacy option controls redacting WHOIS information.
      example: true
      type: boolean
    registrar-api_address2:
      description: Optional address line for unit, floor, suite, etc.
      example: Suite 430
      type: string
    registrar-api_contact_identifier:
      description: Contact Identifier.
      example: ea95132c15732412d22c1476fa83f27a
      maxLength: 32
      readOnly: true
      type: string
    registrar-api_registrant_contact:
      allOf:
      - $ref: '#/components/schemas/registrar-api_contacts'
      description: Shows contact information for domain registrant.
    registrar-api_domain_response_collection:
      allOf:
      - $ref: '#/components/schemas/registrar-api_api-response-collection'
      - properties:
          result:
            items:
              $ref: '#/components/schemas/registrar-api_domains'
            type: array
    registrar-api_telephone:
      description: User's telephone number
      example: +1 123-123-1234
      maxLength: 20
      nullable: true
      type: string
    registrar-api_registry_statuses:
      description: A comma-separated list of registry status codes. A full list of status codes can be found at [EPP Status Codes](https://www.icann.org/resources/pages/epp-status-codes-2014-06-16-en).
      example: ok,serverTransferProhibited
      type: string
    registrar-api_transfer_in:
      description: Statuses for domain transfers into Cloudflare Registrar.
      properties:
        accept_foa:
          description: Form of authorization has been accepted by the registrant.
          enum:
          - needed
          - ok
          example: needed
          type: string
        approve_transfer:
          description: Shows transfer status with the registry.
          enum:
          - needed
          - ok
          - pending
          - trying
          - rejected
          - unknown
          example: unknown
          type: string
        can_cancel_transfer:
          description: Indicates if cancellation is still possible.
          example: true
          type: boolean
        disable_privacy:
          description: Privacy guards are disabled at the foreign registrar.
          enum:
          - needed
          - ok
          - unknown
          example: ok
          type: string
        enter_auth_code:
          description: Auth code has been entered and verified.
          enum:
          - needed
          - ok
          - pending
          - trying
          - rejected
          example: needed
          type: string
        unlock_domain:
          description: Domain is unlocked at the foreign registrar.
          enum:
          - needed
          - ok
          - pending
          - trying
          - unknown
          example: ok
          type: string
    registrar-api_identifier:
      description: Identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      readOnly: true
      type: string
    registrar-api_last_name:
      description: User's last name
      example: Appleseed
      maxLength: 60
      nullable: true
      type: string
    registrar-api_available:
      description: Shows if a domain is available for transferring into Cloudflare Registrar.
      example: false
      type: boolean
    registrar-api_expires_at:
      description: Shows when domain name registration expires.
      example: '2019-08-28T23:59:59Z'
      format: date-time
      type: string
    registrar-api_result_info:
      properties:
        count:
          description: Total number of results for the requested service
          example: 1
          type: number
        page:
          description: Current page within paginated list of results
          example: 1
          type: number
        per_page:
          description: Number of results per page of results
          example: 20
          type: number
        total_count:
          description: Total results available without any search parameters
          example: 2000
          type: number
      type: object
    registrar-api_auto_renew:
      description: Auto-renew controls whether subscription is automatically renewed upon domain expiration.
      example: true
      type: boolean
    registrar-api_fax:
      description: Contact fax number.
      example: 123-867-5309
      type: string
    registrar-api_contact_properties:
      properties:
        address:
          $ref: '#/components/schemas/registrar-api_address'
        address2:
          $ref: '#/components/schemas/registrar-api_address2'
        city:
          $ref: '#/components/schemas/registrar-api_city'
        country:
          $ref: '#/components/schemas/registrar-api_country'
        email:
          $ref: '#/components/schemas/registrar-api_email'
        fax:
          $ref: '#/components/schemas/registrar-api_fax'
        first_name:
          $ref: '#/components/schemas/registrar-api_first_name'
        id:
          $ref: '#/components/schemas/registrar-api_contact_identifier'
        last_name:
          $ref: '#/components/schemas/registrar-api_last_name'
        organization:
          $ref: '#/components/schemas/registrar-api_organization'
        phone:
          $ref: '#/components/schemas/registrar-api_telephone'
        state:
          $ref: '#/components/schemas/registrar-api_state'
        zip:
          $ref: '#/components/schemas/registrar-api_zipcode'
      required:
      - first_name
      - last_name
      - address
      - city
      - state
      - zip
      - country
      - phone
      - organization
      type: object
    registrar-api_domain_name:
      description: Domain name.
      example: cloudflare.com
      type: string
    registrar-api_domain_properties:
      properties:
        available:
          $ref: '#/components/schemas/registrar-api_available'
        can_register:
          $ref: '#/components/schemas/registrar-api_can_register'
        created_at:
          $ref: '#/components/schemas/registrar-api_created_at'
        current_registrar:
          $ref: '#/components/schemas/registrar-api_current_registrar'
        expires_at:
          $ref: '#/components/schemas/registrar-api_expires_at'
        id:
          $ref: '#/components/schemas/registrar-api_domain_identifier'
        locked:
          $ref: '#/components/schemas/registrar-api_locked'
        registrant_contact:
          $ref: '#/components/schemas/registrar-api_registrant_contact'
        registry_statuses:
          $ref: '#/components/schemas/registrar-api_registry_statuses'
        supported_tld:
          $ref: '#/components/schemas/registrar-api_supported_tld'
        transfer_in:
          $ref: '#/components/schemas/registrar-api_transfer_in'
        updated_at:
          $ref: '#/components/schemas/registrar-api_updated_at'
      type: object
    registrar-api_domain_update_properties:
      properties:
        auto_renew:
          $ref: '#/components/schemas/registrar-api_auto_renew'
        locked:
          $ref: '#/components/schemas/registrar-api_locked'
        privacy:
          $ref: '#/components/schemas/registrar-api_privacy'
      type: object
    registrar-api_api-response-collection:
      allOf:
      - $ref: '#/components/schemas/registrar-api_api-response-common'
      - properties:
          result:
            items: {}
            nullable: true
            type: array
          result_info:
            $ref: '#/components/schemas/registrar-api_result_info'
      type: object
    registrar-api_address:
      description: Address.
      example: 123 Sesame St.
      type: string
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/apigateway/
x-hasEquivalentPaths: true
