openapi: 3.2.0
info:
  description: 'To get started using Cloudflare''s products and services via the API, refer to [how to interact with Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/), which covers using tools like [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform) and the [official SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows who is making requests and what permissions you have. Create an API token to grant access to the API to perform actions.


    To create an API token, from the Cloudflare dashboard, go to My Profile > API Tokens and select Create Token. For more information on how to create and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).'
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: APIs.io Engineering Platform Cloudflare DNS Settings for an Account API
  version: 4.0.0
tags:
- name: DNS Settings for an Account
paths:
  /accounts/{account_id}/dns_settings:
    get:
      description: Show DNS settings for an account
      operationId: dns-settings-for-an-account-list-dns-settings
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/dns-settings_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/dns-settings_dns_response_single'
                - $ref: '#/components/schemas/dns-settings_api-response-common-failure'
          description: Show DNS Settings response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dns-settings_dns_response_single'
          description: Show DNS Settings response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Show DNS Settings
      tags:
      - DNS Settings for an Account
      x-cfPermissionsRequired:
        enum:
        - '#dns_records:read'
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
    patch:
      description: Update DNS settings for an account
      operationId: dns-settings-for-an-account-update-dns-settings
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/dns-settings_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/dns-settings_account_settings'
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/dns-settings_dns_response_single'
                - $ref: '#/components/schemas/dns-settings_api-response-common-failure'
          description: Show DNS Settings response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dns-settings_dns_response_single'
          description: Show DNS Settings response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Update DNS Settings
      tags:
      - DNS Settings for an Account
      x-cfPermissionsRequired:
        enum:
        - '#dns_records:read'
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
components:
  schemas:
    dns-settings_soa:
      description: Components of the zone's SOA record.
      properties:
        expire:
          description: Time in seconds of being unable to query the primary server after which secondary servers should stop serving the zone.
          example: 604800
          maximum: 2419200.0
          minimum: 86400
          type: number
        min_ttl:
          description: The time to live (TTL) for negative caching of records within the zone.
          example: 1800
          maximum: 86400
          minimum: 60
          type: number
        mname:
          description: The primary nameserver, which may be used for outbound zone transfers.
          example: kristina.ns.cloudflare.com
          type: string
        refresh:
          description: Time in seconds after which secondary servers should re-check the SOA record to see if the zone has been updated.
          example: 10000
          maximum: 86400
          minimum: 600
          type: number
        retry:
          description: Time in seconds after which secondary servers should retry queries after the primary server was unresponsive.
          example: 2400
          maximum: 86400
          minimum: 600
          type: number
        rname:
          description: The email address of the zone administrator, with the first label representing the local part of the email address.
          example: admin.example.com
          type: string
        ttl:
          description: The time to live (TTL) of the SOA record itself.
          example: 3600
          maximum: 86400
          minimum: 300
          type: number
      required:
      - mname
      - rname
      - refresh
      - retry
      - expire
      - min_ttl
      - ttl
      type: object
    dns-settings_flatten_all_cnames:
      description: Whether to flatten all CNAME records in the zone. Note that, due to DNS limitations, a CNAME record at the zone apex will always be flattened.
      example: false
      type: boolean
    dns-settings_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/dns-settings_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/dns-settings_messages'
          example: []
        result:
          enum:
          - null
          type:
          - object
          - 'null'
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    dns-settings_dns-settings:
      properties:
        flatten_all_cnames:
          $ref: '#/components/schemas/dns-settings_flatten_all_cnames'
        foundation_dns:
          $ref: '#/components/schemas/dns-settings_foundation_dns'
        multi_provider:
          $ref: '#/components/schemas/dns-settings_multi_provider'
        nameservers:
          $ref: '#/components/schemas/dns-settings_nameservers'
        ns_ttl:
          $ref: '#/components/schemas/dns-settings_ns_ttl'
        secondary_overrides:
          $ref: '#/components/schemas/dns-settings_secondary_overrides'
        soa:
          $ref: '#/components/schemas/dns-settings_soa'
        zone_mode:
          $ref: '#/components/schemas/dns-settings_zone_mode'
      type: object
    dns-settings_multi_provider:
      description: Whether to enable multi-provider DNS, which causes Cloudflare to activate the zone even when non-Cloudflare NS records exist, and to respect NS records at the zone apex during outbound zone transfers.
      example: false
      type: boolean
    dns-settings_secondary_overrides:
      description: Allows a Secondary DNS zone to use (proxied) override records and CNAME flattening at the zone apex.
      example: false
      type: boolean
    dns-settings_identifier:
      description: Identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      type: string
    dns-settings_zone_mode:
      description: Whether the zone mode is a regular or CDN/DNS only zone.
      enum:
      - standard
      - cdn_only
      - dns_only
      example: dns_only
      type: string
    dns-settings_foundation_dns:
      description: Whether to enable Foundation DNS Advanced Nameservers on the zone.
      example: false
      type: boolean
    dns-settings_ns_ttl:
      description: The time to live (TTL) of the zone's nameserver (NS) records.
      example: 86400
      maximum: 86400
      minimum: 30
      type: number
    dns-settings_api-response-single:
      allOf:
      - $ref: '#/components/schemas/dns-settings_api-response-common'
      type: object
    dns-settings_account_settings:
      properties:
        zone_defaults:
          $ref: '#/components/schemas/dns-settings_dns-settings'
      type: object
    dns-settings_nameservers:
      description: Settings determining the nameservers through which the zone should be available.
      properties:
        type:
          description: Nameserver type
          enum:
          - cloudflare.standard
          - cloudflare.standard.random
          - custom.account
          - custom.tenant
          - custom.zone
          example: cloudflare.standard
          type: string
      required:
      - type
      type: object
    dns-settings_dns_response_single:
      allOf:
      - $ref: '#/components/schemas/dns-settings_api-response-single'
      - properties:
          result:
            $ref: '#/components/schemas/dns-settings_account_settings'
        type: object
    dns-settings_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/dns-settings_messages'
        messages:
          $ref: '#/components/schemas/dns-settings_messages'
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      type: object
    dns-settings_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
  securitySchemes:
    api_email:
      in: header
      name: X-Auth-Email
      type: apiKey
    api_key:
      in: header
      name: X-Auth-Key
      type: apiKey
    api_token:
      scheme: bearer
      type: http
    user_service_key:
      in: header
      name: X-Auth-User-Service-Key
      type: apiKey
