openapi: 3.0.0
info:
  version: "1.0.0"
  x-release: v4
  title: APIs.io Engineering Platform Amazon API Gateway 2014 11 13 Magic Site ACLs API
  description: <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: apigateway
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/apigateway-2015-07-09.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: https://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: http://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
- url: https://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: Magic Site ACLs
paths:
  /accounts/{account_id}/magic/sites/{site_id}/acls:
    get:
      description: Lists Site ACLs associated with an account.
      operationId: magic-site-acls-list-acls
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      - in: path
        name: site_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_api-response-common-failure'
          description: List Site ACLs response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_acls_collection_response'
          description: List Site ACLs response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform List Site ACLs
      tags:
      - Magic Site ACLs
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    post:
      description: Creates a new Site ACL.
      operationId: magic-site-acls-create-acl
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      - in: path
        name: site_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/magic_acls_add_single_request'
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_api-response-common-failure'
          description: Create Site ACL response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_acl_single_response'
          description: Create Site ACL response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Create a new Site ACL
      tags:
      - Magic Site ACLs
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
  /accounts/{account_id}/magic/sites/{site_id}/acls/{acl_id}:
    delete:
      description: Remove a specific Site ACL.
      operationId: magic-site-acls-delete-acl
      parameters:
      - in: path
        name: site_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      - in: path
        name: acl_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_api-response-common-failure'
          description: Delete Site ACL response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_acl_deleted_response'
          description: Delete Site ACL response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Delete Site ACL
      tags:
      - Magic Site ACLs
      x-cfPermissionsRequired:
        enum:
        - '#organization:edit'
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    get:
      description: Get a specific Site ACL.
      operationId: magic-site-acls-acl-details
      parameters:
      - in: path
        name: site_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      - in: path
        name: acl_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_api-response-common-failure'
          description: Site ACL Details response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_acl_single_response'
          description: Site ACL Details response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Site ACL Details
      tags:
      - Magic Site ACLs
      x-cfPermissionsRequired:
        enum:
        - '#organization:read'
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    patch:
      description: Patch a specific Site ACL.
      operationId: magic-site-acls-patch-acl
      parameters:
      - in: path
        name: site_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      - in: path
        name: acl_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/magic_acl_update_request'
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_api-response-common-failure'
          description: Patch Site ACL response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_acl_modified_response'
          description: Patch Site ACL response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Patch Site ACL
      tags:
      - Magic Site ACLs
      x-cfPermissionsRequired:
        enum:
        - '#organization:edit'
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    put:
      description: Update a specific Site ACL.
      operationId: magic-site-acls-update-acl
      parameters:
      - in: path
        name: site_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      - in: path
        name: acl_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/magic_acl_update_request'
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_api-response-common-failure'
          description: Update Site ACL response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_acl_modified_response'
          description: Update Site ACL response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Update Site ACL
      tags:
      - Magic Site ACLs
      x-cfPermissionsRequired:
        enum:
        - '#organization:edit'
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
components:
  schemas:
    magic_acl_single_response:
      allOf:
      - $ref: '#/components/schemas/magic_api-response-single'
      - properties:
          result:
            $ref: '#/components/schemas/magic_acl'
    magic_ip-address:
      description: A valid IPv4 address.
      example: 192.0.2.1
      type: string
    magic_api-response-single:
      allOf:
      - $ref: '#/components/schemas/magic_api-response-common'
      - properties:
          result:
            anyOf:
            - nullable: true
              type: object
            - nullable: true
              type: string
      type: object
    magic_forward_locally:
      description: The desired forwarding action for this ACL policy. If set to "false", the policy will forward traffic to Cloudflare. If set to "true", the policy will forward traffic locally on the Magic Connector. If not included in request, will default to false.
      type: boolean
    magic_acls_add_single_request:
      description: Bidirectional ACL policy for local network traffic within a site.
      properties:
        description:
          description: Description for the ACL.
          example: Allows local traffic between PIN pads and cash register.
          type: string
        forward_locally:
          $ref: '#/components/schemas/magic_forward_locally'
        lan_1:
          $ref: '#/components/schemas/magic_lan-acl-configuration'
        lan_2:
          $ref: '#/components/schemas/magic_lan-acl-configuration'
        name:
          description: The name of the ACL.
          example: PIN Pad - Cash Register
          type: string
        protocols:
          items:
            description: Array of allowed communication protocols between configured LANs. If no protocols are provided, all protocols are allowed.
            enum:
            - tcp
            - udp
            - icmp
            type: string
          type: array
      required:
      - name
      - lan_1
      - lan_2
      type: object
    magic_acl_modified_response:
      allOf:
      - $ref: '#/components/schemas/magic_api-response-single'
      - properties:
          result:
            $ref: '#/components/schemas/magic_acl'
    magic_acl-subnet:
      oneOf:
      - $ref: '#/components/schemas/magic_ip-address'
      - $ref: '#/components/schemas/magic_cidr'
    magic_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/magic_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/magic_messages'
          example: []
        result:
          enum:
          - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    magic_cidr:
      description: A valid CIDR notation representing an IP range.
      example: 192.0.2.0/24
      type: string
    magic_port:
      example: 1
      type: integer
    magic_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    magic_lan-acl-configuration:
      properties:
        lan_id:
          description: The identifier for the LAN you want to create an ACL policy with.
          type: string
        lan_name:
          description: The name of the LAN based on the provided lan_id.
          type: string
        ports:
          description: Array of ports on the provided LAN that will be included in the ACL. If no ports are provided, communication on any port on this LAN is allowed.
          items:
            $ref: '#/components/schemas/magic_port'
          type: array
        subnets:
          description: Array of subnet IPs within the LAN that will be included in the ACL. If no subnets are provided, communication on any subnets on this LAN are allowed.
          items:
            $ref: '#/components/schemas/magic_acl-subnet'
          type: array
      required:
      - lan_id
      type: object
    magic_acl_update_request:
      properties:
        description:
          description: Description for the ACL.
          example: Allows local traffic between PIN pads and cash register.
          type: string
        forward_locally:
          $ref: '#/components/schemas/magic_forward_locally'
        lan_1:
          $ref: '#/components/schemas/magic_lan-acl-configuration'
        lan_2:
          $ref: '#/components/schemas/magic_lan-acl-configuration'
        name:
          description: The name of the ACL.
          example: PIN Pad - Cash Register
          type: string
        protocols:
          items:
            description: Array of allowed communication protocols between configured LANs. If no protocols are provided, all protocols are allowed.
            enum:
            - tcp
            - udp
            - icmp
            type: string
          type: array
      type: object
    magic_identifier:
      description: Identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      readOnly: true
      type: string
    magic_acl:
      description: Bidirectional ACL policy for network traffic within a site.
      properties:
        description:
          description: Description for the ACL.
          example: Allows local traffic between PIN pads and cash register.
          type: string
        forward_locally:
          $ref: '#/components/schemas/magic_forward_locally'
        id:
          $ref: '#/components/schemas/magic_identifier'
        lan_1:
          $ref: '#/components/schemas/magic_lan-acl-configuration'
        lan_2:
          $ref: '#/components/schemas/magic_lan-acl-configuration'
        name:
          description: The name of the ACL.
          example: PIN Pad - Cash Register
          type: string
        protocols:
          items:
            description: Array of allowed communication protocols between configured LANs. If no protocols are provided, all protocols are allowed.
            enum:
            - tcp
            - udp
            - icmp
            type: string
          type: array
      type: object
    magic_acls_collection_response:
      allOf:
      - $ref: '#/components/schemas/magic_api-response-single'
      - properties:
          result:
            items:
              $ref: '#/components/schemas/magic_acl'
            type: array
    magic_acl_deleted_response:
      allOf:
      - $ref: '#/components/schemas/magic_api-response-single'
      - properties:
          result:
            $ref: '#/components/schemas/magic_acl'
    magic_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/magic_messages'
        messages:
          $ref: '#/components/schemas/magic_messages'
        result:
          anyOf:
          - type: object
          - items: {}
            type: array
          - type: string
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/apigateway/
x-hasEquivalentPaths: true
