openapi: 3.2.0
info:
  description: 'To get started using Cloudflare''s products and services via the API, refer to [how to interact with Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/), which covers using tools like [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform) and the [official SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows who is making requests and what permissions you have. Create an API token to grant access to the API to perform actions.


    To create an API token, from the Cloudflare dashboard, go to My Profile > API Tokens and select Create Token. For more information on how to create and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).'
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: APIs.io Engineering Platform Cloudflare Zero Trust Risk Scoring API
  version: 4.0.0
tags:
- name: Zero Trust Risk Scoring
paths:
  /accounts/{account_id}/zt_risk_scoring/{user_id}:
    get:
      operationId: dlp-risk-score-summary-get-for-user
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          type: string
      - in: path
        name: user_id
        required: true
        schema:
          format: uuid
          type: string
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dlp_api-response-common-failure'
          description: Failed to get risk events
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/dlp_api-response-collection'
                - properties:
                    result:
                      $ref: '#/components/schemas/dlp_RiskEvents'
                  type: object
          description: Risk events
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Get risk event/score information for a specific user
      tags:
      - Zero Trust Risk Scoring
  /accounts/{account_id}/zt_risk_scoring/{user_id}/reset:
    post:
      operationId: dlp-risk-score-reset-post
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          type: string
      - in: path
        name: user_id
        required: true
        schema:
          format: uuid
          type: string
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dlp_api-response-common-failure'
          description: Dataset creation failed
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/dlp_api-response-single'
                - properties:
                    result:
                      $ref: '#/components/schemas/dlp_Empty'
                  type: object
          description: Dataset created successfully
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Clear the risk score for a particular user
      tags:
      - Zero Trust Risk Scoring
  /accounts/{account_id}/zt_risk_scoring/behaviors:
    get:
      operationId: dlp-risk-score-behaviors-get
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          type: string
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dlp_api-response-common-failure'
          description: Failed to get risk scoring behaviors
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/dlp_api-response-single'
                - properties:
                    result:
                      $ref: '#/components/schemas/dlp_Behaviors'
                  type: object
          description: Risk scoring behaviors
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Get all behaviors and associated configuration
      tags:
      - Zero Trust Risk Scoring
      x-api-token-group:
      - Teams Read
      - Teams Write
    put:
      operationId: dlp-risk-score-behaviors-put
      parameters:
      - description: Account ID
        in: path
        name: account_id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/dlp_UpdateBehaviors'
        description: Behaviors
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dlp_api-response-common-failure'
          description: Dataset creation failed
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/dlp_api-response-single'
                - properties:
                    result:
                      $ref: '#/components/schemas/dlp_UpdateBehaviors'
                  type: object
          description: Dataset created successfully
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Update configuration for risk behaviors
      tags:
      - Zero Trust Risk Scoring
      x-api-token-group:
      - Teams Write
  /accounts/{account_id}/zt_risk_scoring/summary:
    get:
      operationId: dlp-risk-score-summary-get
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          type: string
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dlp_api-response-common-failure'
          description: Failed to get risk scores
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/dlp_api-response-collection'
                - properties:
                    result:
                      $ref: '#/components/schemas/dlp_RiskSummary'
                  type: object
          description: Risk score for all users in the account
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Get risk score info for all users in the account
      tags:
      - Zero Trust Risk Scoring
components:
  schemas:
    dlp_Empty:
      type:
      - object
      - 'null'
    dlp_RiskEvents:
      properties:
        email:
          type: string
        events:
          items:
            $ref: '#/components/schemas/dlp_RiskEvent'
          type: array
        last_reset_time:
          format: date-time
          type:
          - string
          - 'null'
        name:
          type: string
        risk_level:
          allOf:
          - $ref: '#/components/schemas/dlp_RiskLevel'
      required:
      - name
      - email
      - events
      type: object
    dlp_Behavior:
      properties:
        description:
          type: string
        enabled:
          type: boolean
        name:
          type: string
        risk_level:
          $ref: '#/components/schemas/dlp_RiskLevel'
      required:
      - name
      - description
      - risk_level
      - enabled
      type: object
    dlp_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/dlp_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/dlp_messages'
          example: []
        result:
          enum:
          - null
          type:
          - object
          - 'null'
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    dlp_UpdateBehaviors:
      properties:
        behaviors:
          additionalProperties:
            $ref: '#/components/schemas/dlp_UpdateBehavior'
          type: object
      required:
      - behaviors
      type: object
    dlp_RiskEvent:
      properties:
        event_details: {}
        id:
          type: string
        name:
          type: string
        risk_level:
          $ref: '#/components/schemas/dlp_RiskLevel'
        timestamp:
          format: date-time
          type: string
      required:
      - id
      - risk_level
      - name
      - timestamp
      type: object
    dlp_api-response-collection:
      allOf:
      - $ref: '#/components/schemas/dlp_api-response-common'
      - properties:
          result_info:
            $ref: '#/components/schemas/dlp_result_info'
      type: object
    dlp_UserRiskInfo:
      properties:
        email:
          type: string
        event_count:
          minimum: 0
          type: integer
        last_event:
          format: date-time
          type: string
        max_risk_level:
          $ref: '#/components/schemas/dlp_RiskLevel'
        name:
          type: string
        user_id:
          format: uuid
          type: string
      required:
      - user_id
      - name
      - email
      - max_risk_level
      - event_count
      - last_event
      type: object
    dlp_RiskLevel:
      enum:
      - low
      - medium
      - high
      type: string
    dlp_UpdateBehavior:
      properties:
        enabled:
          type: boolean
        risk_level:
          $ref: '#/components/schemas/dlp_RiskLevel'
      required:
      - risk_level
      - enabled
      type: object
    dlp_api-response-single:
      allOf:
      - $ref: '#/components/schemas/dlp_api-response-common'
      type: object
    dlp_result_info:
      properties:
        count:
          description: Total number of results for the requested service
          example: 1
          type: number
        page:
          description: Current page within paginated list of results
          example: 1
          type: number
        per_page:
          description: Number of results per page of results
          example: 20
          type: number
        total_count:
          description: Total results available without any search parameters
          example: 2000
          type: number
      type: object
    dlp_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    dlp_RiskSummary:
      properties:
        users:
          items:
            $ref: '#/components/schemas/dlp_UserRiskInfo'
          type: array
      required:
      - users
      type: object
    dlp_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/dlp_messages'
        messages:
          $ref: '#/components/schemas/dlp_messages'
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      type: object
    dlp_Behaviors:
      properties:
        behaviors:
          additionalProperties:
            $ref: '#/components/schemas/dlp_Behavior'
          type: object
      required:
      - behaviors
      type: object
  securitySchemes:
    api_email:
      in: header
      name: X-Auth-Email
      type: apiKey
    api_key:
      in: header
      name: X-Auth-Key
      type: apiKey
    api_token:
      scheme: bearer
      type: http
    user_service_key:
      in: header
      name: X-Auth-User-Service-Key
      type: apiKey
