openapi: 3.2.0
info:
  description: 'To get started using Cloudflare''s products and services via the API, refer to [how to interact with Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/), which covers using tools like [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform) and the [official SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows who is making requests and what permissions you have. Create an API token to grant access to the API to perform actions.


    To create an API token, from the Cloudflare dashboard, go to My Profile > API Tokens and select Create Token. For more information on how to create and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).'
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: APIs.io Engineering Platform Cloudflare IP Intelligence API
  version: 4.0.0
tags:
- name: IP Intelligence
paths:
  /accounts/{account_id}/intel/ip:
    get:
      operationId: ip-intelligence-get-ip-overview
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/intel_identifier'
      - in: query
        name: ipv4
        schema:
          type: string
      - in: query
        name: ipv6
        schema:
          type: string
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/intel_schemas-response'
                - $ref: '#/components/schemas/intel_api-response-common-failure'
          description: Get IP Overview response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/intel_schemas-response'
          description: Get IP Overview response
      security:
      - api_token: []
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Get IP Overview
      tags:
      - IP Intelligence
components:
  schemas:
    intel_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/intel_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/intel_messages'
          example: []
        result:
          enum:
          - null
          type:
          - object
          - 'null'
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    intel_identifier:
      description: Identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      readOnly: true
      type: string
    intel_api-response-collection:
      allOf:
      - $ref: '#/components/schemas/intel_api-response-common'
      - properties:
          result:
            items: {}
            type:
            - array
            - 'null'
          result_info:
            $ref: '#/components/schemas/intel_result_info'
      type: object
    intel_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/intel_messages'
        messages:
          $ref: '#/components/schemas/intel_messages'
        result:
          anyOf:
          - type: object
          - items: {}
            type: array
          - type: string
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    intel_schemas-response:
      allOf:
      - $ref: '#/components/schemas/intel_api-response-collection'
      - properties:
          result:
            items:
              $ref: '#/components/schemas/intel_schemas-ip'
            type: array
    intel_ipv6:
      example: '2001:0DB8::'
      format: ipv6
      type: string
    intel_result_info:
      properties:
        count:
          description: Total number of results for the requested service
          example: 1
          type: number
        page:
          description: Current page within paginated list of results
          example: 1
          type: number
        per_page:
          description: Number of results per page of results
          example: 20
          type: number
        total_count:
          description: Total results available without any search parameters
          example: 2000
          type: number
      type: object
    intel_ip:
      anyOf:
      - $ref: '#/components/schemas/intel_ipv4'
      - $ref: '#/components/schemas/intel_ipv6'
    intel_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    intel_ipv4:
      example: 192.0.2.0
      format: ipv4
      type: string
    intel_schemas-ip:
      properties:
        belongs_to_ref:
          description: Specifies a reference to the autonomous systems (AS) that the IP address belongs to.
          properties:
            country:
              example: US
              type: string
            description:
              example: CLOUDFLARENET
              type: string
            id:
              example: autonomous-system--2fa28d71-3549-5a38-af05-770b79ad6ea8
            type:
              description: Infrastructure type of this ASN.
              enum:
              - hosting_provider
              - isp
              - organization
              example: hosting_provider
              type: string
            value:
              type: string
          type: object
        ip:
          $ref: '#/components/schemas/intel_ip'
        risk_types:
          example:
          - id: 131
            name: Phishing
            super_category_id: 21
  securitySchemes:
    api_email:
      in: header
      name: X-Auth-Email
      type: apiKey
    api_key:
      in: header
      name: X-Auth-Key
      type: apiKey
    api_token:
      scheme: bearer
      type: http
    user_service_key:
      in: header
      name: X-Auth-User-Service-Key
      type: apiKey
