openapi: 3.0.0
info:
  version: "1.0.0"
  x-release: v4
  title: 'APIs.io Engineering Platform Amazon API Gateway 2014 11 13 #Action=ListSigningCertificates API'
  description: <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: apigateway
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/apigateway-2015-07-09.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: https://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: http://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
- url: https://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#Action=ListSigningCertificates'
paths:
  /#Action=ListSigningCertificates:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    get:
      x-aws-operation-name: ListSigningCertificates
      operationId: GET_ListSigningCertificates
      description: <p>Returns information about the signing certificates associated with the specified IAM user. If none exists, the operation returns an empty list.</p> <p>Although each user is limited to a small number of signing certificates, you can still paginate the results using the <code>MaxItems</code> and <code>Marker</code> parameters.</p> <p>If the <code>UserName</code> field is not specified, the user name is determined implicitly based on the Amazon Web Services access key ID used to sign the request for this operation. This operation works for access keys under the Amazon Web Services account. Consequently, you can use this operation to manage Amazon Web Services account root user credentials even if the Amazon Web Services account has no associated users.</p>
      responses:
        '200':
          description: Success
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/ListSigningCertificatesResponse'
        '480':
          description: NoSuchEntityException
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/NoSuchEntityException'
        '481':
          description: ServiceFailureException
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/ServiceFailureException'
      parameters:
      - name: UserName
        in: query
        required: false
        description: '<p>The name of the IAM user whose signing certificates you want to examine.</p> <p>This parameter allows (through its <a href="http://wikipedia.org/wiki/regex">regex pattern</a>) a string of characters consisting of upper and lowercase alphanumeric characters with no spaces. You can also include any of the following characters: _+=,.@-</p>'
        schema:
          type: string
          pattern: '[\w+=,.@-]+'
          minLength: 1
          maxLength: 128
      - name: Marker
        in: query
        required: false
        description: Use this parameter only when paginating results and only after you receive a response indicating that the results are truncated. Set it to the value of the <code>Marker</code> element in the response that you received to indicate where the next call should start.
        schema:
          type: string
          pattern: '[\u0020-\u00FF]+'
          minLength: 1
          maxLength: 320
      - name: MaxItems
        in: query
        required: false
        description: <p>Use this only when paginating results to indicate the maximum number of items you want in the response. If additional items exist beyond the maximum you specify, the <code>IsTruncated</code> response element is <code>true</code>.</p> <p>If you do not include this parameter, the number of items defaults to 100. Note that IAM might return fewer results, even when there are more results available. In that case, the <code>IsTruncated</code> response element returns <code>true</code>, and <code>Marker</code> contains a value to include in the subsequent call that tells the service where to continue from.</p>
        schema:
          type: integer
          minimum: 1
          maximum: 1000
      - name: Action
        in: query
        required: true
        schema:
          type: string
          enum:
          - ListSigningCertificates
      - name: Version
        in: query
        required: true
        schema:
          type: string
          enum:
          - 2010-05-08
      tags:
      - '#Action=ListSigningCertificates'
    post:
      x-aws-operation-name: ListSigningCertificates
      operationId: POST_ListSigningCertificates
      description: <p>Returns information about the signing certificates associated with the specified IAM user. If none exists, the operation returns an empty list.</p> <p>Although each user is limited to a small number of signing certificates, you can still paginate the results using the <code>MaxItems</code> and <code>Marker</code> parameters.</p> <p>If the <code>UserName</code> field is not specified, the user name is determined implicitly based on the Amazon Web Services access key ID used to sign the request for this operation. This operation works for access keys under the Amazon Web Services account. Consequently, you can use this operation to manage Amazon Web Services account root user credentials even if the Amazon Web Services account has no associated users.</p>
      responses:
        '200':
          description: Success
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/ListSigningCertificatesResponse'
        '480':
          description: NoSuchEntityException
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/NoSuchEntityException'
        '481':
          description: ServiceFailureException
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/ServiceFailureException'
      requestBody:
        content:
          text/xml:
            schema:
              $ref: '#/components/schemas/ListSigningCertificatesRequest'
      parameters:
      - name: MaxItems
        in: query
        schema:
          type: string
        description: Pagination limit
        required: false
      - name: Marker
        in: query
        schema:
          type: string
        description: Pagination token
        required: false
      - name: Action
        in: query
        required: true
        schema:
          type: string
          enum:
          - ListSigningCertificates
      - name: Version
        in: query
        required: true
        schema:
          type: string
          enum:
          - 2010-05-08
      tags:
      - '#Action=ListSigningCertificates'
components:
  parameters:
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
  schemas:
    statusType:
      type: string
      enum:
      - Active
      - Inactive
    certificateListType:
      type: array
      description: <p>Contains a list of signing certificates.</p> <p>This data type is used as a response element in the <a>ListSigningCertificates</a> operation.</p>
      items:
        $ref: '#/components/schemas/SigningCertificate'
    userNameType:
      type: string
      pattern: '[\w+=,.@-]+'
      minLength: 1
      maxLength: 64
    responseMarkerType:
      type: string
    markerType:
      type: string
      pattern: '[\u0020-\u00FF]+'
      minLength: 1
      maxLength: 320
    certificateIdType:
      type: string
      pattern: '[\w]+'
      minLength: 24
      maxLength: 128
    booleanType:
      type: boolean
    ListSigningCertificatesResponse:
      type: object
      required:
      - Certificates
      example:
        Certificates:
        - CertificateBody: '-----BEGIN CERTIFICATE-----<certificate-body>-----END CERTIFICATE-----'
          CertificateId: TA7SMP42TDN5Z26OBPJE7EXAMPLE
          Status: Active
          UploadDate: 2013-06-06 21:40:08+00:00
          UserName: Bob
      properties:
        Certificates:
          allOf:
          - $ref: '#/components/schemas/certificateListType'
          - description: A list of the user's signing certificate information.
        IsTruncated:
          allOf:
          - $ref: '#/components/schemas/booleanType'
          - description: A flag that indicates whether there are more items to return. If your results were truncated, you can make a subsequent pagination request using the <code>Marker</code> request parameter to retrieve more items. Note that IAM might return fewer than the <code>MaxItems</code> number of results even when there are more results available. We recommend that you check <code>IsTruncated</code> after every call to ensure that you receive all your results.
        Marker:
          allOf:
          - $ref: '#/components/schemas/responseMarkerType'
          - description: When <code>IsTruncated</code> is <code>true</code>, this element is present and contains the value to use for the <code>Marker</code> parameter in a subsequent pagination request.
      description: 'Contains the response to a successful <a>ListSigningCertificates</a> request. '
    certificateBodyType:
      type: string
      pattern: '[\u0009\u000A\u000D\u0020-\u00FF]+'
      minLength: 1
      maxLength: 16384
    NoSuchEntityException: {}
    dateType:
      type: string
      format: date-time
    ListSigningCertificatesRequest:
      type: object
      title: ListSigningCertificatesRequest
      properties:
        UserName:
          allOf:
          - $ref: '#/components/schemas/existingUserNameType'
          - description: '<p>The name of the IAM user whose signing certificates you want to examine.</p> <p>This parameter allows (through its <a href="http://wikipedia.org/wiki/regex">regex pattern</a>) a string of characters consisting of upper and lowercase alphanumeric characters with no spaces. You can also include any of the following characters: _+=,.@-</p>'
        Marker:
          allOf:
          - $ref: '#/components/schemas/markerType'
          - description: Use this parameter only when paginating results and only after you receive a response indicating that the results are truncated. Set it to the value of the <code>Marker</code> element in the response that you received to indicate where the next call should start.
        MaxItems:
          allOf:
          - $ref: '#/components/schemas/maxItemsType'
          - description: <p>Use this only when paginating results to indicate the maximum number of items you want in the response. If additional items exist beyond the maximum you specify, the <code>IsTruncated</code> response element is <code>true</code>.</p> <p>If you do not include this parameter, the number of items defaults to 100. Note that IAM might return fewer results, even when there are more results available. In that case, the <code>IsTruncated</code> response element returns <code>true</code>, and <code>Marker</code> contains a value to include in the subsequent call that tells the service where to continue from.</p>
    maxItemsType:
      type: integer
      minimum: 1
      maximum: 1000
    ServiceFailureException: {}
    existingUserNameType:
      type: string
      pattern: '[\w+=,.@-]+'
      minLength: 1
      maxLength: 128
    SigningCertificate:
      type: object
      required:
      - UserName
      - CertificateId
      - CertificateBody
      - Status
      properties:
        UserName:
          allOf:
          - $ref: '#/components/schemas/userNameType'
          - description: The name of the user the signing certificate is associated with.
        CertificateId:
          allOf:
          - $ref: '#/components/schemas/certificateIdType'
          - description: The ID for the signing certificate.
        CertificateBody:
          allOf:
          - $ref: '#/components/schemas/certificateBodyType'
          - description: The contents of the signing certificate.
        Status:
          allOf:
          - $ref: '#/components/schemas/statusType'
          - description: The status of the signing certificate. <code>Active</code> means that the key is valid for API calls, while <code>Inactive</code> means it is not.
        UploadDate:
          allOf:
          - $ref: '#/components/schemas/dateType'
          - description: The date when the signing certificate was uploaded.
      description: <p>Contains information about an X.509 signing certificate.</p> <p>This data type is used as a response element in the <a>UploadSigningCertificate</a> and <a>ListSigningCertificates</a> operations. </p>
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/apigateway/
x-hasEquivalentPaths: true
