openapi: 3.0.0
info:
  version: 2015-07-09
  x-release: v4
  title: APIs.io Engineering Platform Amazon API Gateway 2014 11 13 Botnet Threat Feed API
  description: <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: apigateway
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/apigateway-2015-07-09.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: https://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: http://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
- url: https://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: Botnet Threat Feed
paths:
  /accounts/{account_id}/botnet_feed/asn/{asn_id}/day_report:
    get:
      description: Gets all the data the botnet tracking database has for a given ASN registered to user account for given date. If no date is given, it will return results for the previous day.
      operationId: botnet-threat-feed-get-day-report
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/dos_identifier'
      - in: path
        name: asn_id
        required: true
        schema:
          $ref: '#/components/schemas/dos_asn'
      - in: query
        name: date
        schema:
          $ref: '#/components/schemas/dos_timestamp'
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dos_api-response-common-failure'
          description: Get botnet feed report for day response failure
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/dos_api-response-common'
                - properties:
                    result:
                      properties:
                        cidr:
                          example: 1.1.1.1/32
                          type: string
                        date:
                          example: '2014-01-01T05:20:00.12345Z'
                          format: date-time
                          type: string
                        offense_count:
                          example: 1000
                          type: integer
                      type: object
                  type: object
                type: object
          description: Get botnet feed report for day
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Get daily report
      tags:
      - Botnet Threat Feed
      x-api-token-group:
      - DDoS Botnet Feed Write
      - DDoS Botnet Feed Read
  /accounts/{account_id}/botnet_feed/asn/{asn_id}/full_report:
    get:
      description: Gets all the data the botnet threat feed tracking database has for a given ASN registered to user account.
      operationId: botnet-threat-feed-get-full-report
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/dos_identifier'
      - in: path
        name: asn_id
        required: true
        schema:
          $ref: '#/components/schemas/dos_asn'
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dos_api-response-common-failure'
          description: Get full botnet feed report response failure
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/dos_api-response-common'
                - properties:
                    result:
                      properties:
                        cidr:
                          example: 1.1.1.1/32
                          type: string
                        date:
                          example: '2014-01-01T05:20:00.12345Z'
                          format: date-time
                          type: string
                        offense_count:
                          example: 1000
                          type: integer
                      type: object
                  type: object
                type: object
          description: Get full botnet feed report
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Get full report
      tags:
      - Botnet Threat Feed
      x-api-token-group:
      - DDoS Botnet Feed Write
      - DDoS Botnet Feed Read
  /accounts/{account_id}/botnet_feed/configs/asn:
    get:
      description: Gets a list of all ASNs registered for a user for the DDoS Botnet Feed API.
      operationId: botnet-threat-feed-list-asn
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/dos_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dos_api-response-common-failure'
          description: Get list of ASNs response failure
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/dos_api-response-common'
                - properties:
                    result:
                      properties:
                        asn:
                          example: 13335
                          type: integer
                      type: object
                  type: object
                type: object
          description: Get list of ASNs response
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Get list of ASNs
      tags:
      - Botnet Threat Feed
      x-api-token-group:
      - DDoS Botnet Feed Write
      - DDoS Botnet Feed Read
  /accounts/{account_id}/botnet_feed/configs/asn/{asn_id}:
    delete:
      description: Delete an ASN from botnet threat feed for a given user.
      operationId: botnet-threat-feed-delete-asn
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/dos_identifier'
      - in: path
        name: asn_id
        required: true
        schema:
          $ref: '#/components/schemas/dos_asn'
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dos_api-response-common-failure'
          description: Delete ASN response failure
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/dos_api-response-common'
                - properties:
                    result:
                      properties:
                        asn:
                          example: 13335
                          type: integer
                      type: object
                  type: object
                type: object
          description: Delete ASN response
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Delete an ASN
      tags:
      - Botnet Threat Feed
      x-api-token-group:
      - DDoS Botnet Feed Write
components:
  schemas:
    dos_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    dos_asn:
      type: integer
    dos_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/dos_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/dos_messages'
          example: []
        result:
          enum:
          - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    dos_identifier:
      description: Identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      type: string
    dos_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/dos_messages'
        messages:
          $ref: '#/components/schemas/dos_messages'
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      type: object
    dos_timestamp:
      example: '2014-01-01T05:20:00.12345Z'
      format: date-time
      type: string
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/apigateway/
x-hasEquivalentPaths: true
