openapi: 3.2.0
info:
  title: Postman Webhooks API
  description: The Postman API enables you to programmatically access data stored in your Postman account.
  version: '1.0'
  termsOfService: https://www.postman.com/legal/terms/
  contact:
    name: Postman Support
    email: help@postman.com
    url: https://www.postman.com/community/
servers:
- url: https://api.getpostman.com
- url: https://api.eu.postman.com
security:
- PostmanApiKey: []
- scimApiKey: []
tags:
- name: Webhooks
  description: The **Webhooks** endpoints enable you to manage custom webhooks.
paths:
  /webhooks:
    post:
      summary: APIs.io Engineering Platform Create a webhook
      description: Creates a webhook that triggers a collection with a custom payload. You can get the webhook's URL from the `webhookUrl` property in the endpoint's response.
      operationId: createWebhook
      tags:
      - Webhooks
      requestBody:
        $ref: '#/components/requestBodies/createWebhook'
      responses:
        '200':
          $ref: '#/components/responses/createWebhook'
        '400':
          $ref: '#/components/responses/createWebhookParamMissing400Error'
        '401':
          $ref: '#/components/responses/common401Error'
        '403':
          $ref: '#/components/responses/featureUnavailable403Error'
        '500':
          $ref: '#/components/responses/common500ErrorServerError'
      parameters:
      - $ref: '#/components/parameters/workspaceQuery'
components:
  responses:
    createWebhook:
      description: Successful Response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/createWebhookResponse'
          example:
            webhook:
              id: 1f0df51a-8658-4ee8-a2a1-d2567dfa09a9
              name: Test Webhook
              collection: 12345678-12ece9e1-2abf-4edc-8e34-de66e74114d2
              webhookUrl: https://newman-api.getpostman.com/run/12345678/267a6e99-b6da-407c-a96f-03be2d6282fb
              uid: 12345678-1f0df51a-8658-4ee8-a2a1-d2567dfa09a9
    featureUnavailable403Error:
      description: Feature Unavailable
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/featureUnavailable403Error'
          example:
            value:
              type: https://api.postman.com/problems/forbidden
              title: Forbidden
              detail: This feature isn't available in your region.
              status: 403
    createWebhookParamMissing400Error:
      description: Missing Parameter
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/createWebhookParamMissing400Error'
          example:
            error:
              name: paramMissingError
              message: Parameter is missing in the request.
              details:
                param:
                - collection
    common401Error:
      description: Unauthorized
      content:
        application/problem+json:
          schema:
            type: object
            properties:
              type:
                type: string
                format: uri-reference
                description: The [URI reference](https://www.rfc-editor.org/rfc/rfc3986) that identifies the type of problem.
                example: https://api.postman.com/problems/unauthorized
              title:
                type: string
                description: A short summary of the problem.
                example: Unauthorized
              detail:
                type: string
                description: Information about the error.
                example: Unauthorized
              status:
                type: integer
                format: http-status-code
                description: The error's HTTP status code.
                example: 401
          example:
            type: https://api.postman.com/problems/unauthorized
            title: Unauthorized
            detail: Unauthorized
            status: 401
    common500ErrorServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: object
                properties:
                  name:
                    type: string
                    description: The error name.
                    example: serverError
                  message:
                    type: string
                    description: The error message.
                    example: An error has occurred on the server.
          example:
            error:
              name: serverError
              message: An error has occurred on the server.
  schemas:
    createWebhookResponse:
      title: Successful Response
      type: object
      properties:
        webhook:
          type: object
          properties:
            id:
              type: string
              description: The webhook's ID.
              example: 1f0df51a-8658-4ee8-a2a1-d2567dfa09a9
            name:
              type: string
              description: The webhook's name.
              example: Test Webhook
            collection:
              type: string
              format: uid
              description: The unique ID of the collection that triggers when calling this webhook.
              example: 12345678-12ece9e1-2abf-4edc-8e34-de66e74114d2
            webhookUrl:
              type: string
              description: The webhook's URL.
              example: https://newman-api.getpostman.com/run/12345678/267a6e99-b6da-407c-a96f-03be2d6282fb
            uid:
              type: string
              format: uid
              description: The webhook's unique ID.
              example: 12345678-1f0df51a-8658-4ee8-a2a1-d2567dfa09a9
    createWebhookRequest:
      title: Create Webhook Request Body
      type: object
      properties:
        webhook:
          type: object
          required:
          - name
          - collection
          properties:
            collection:
              type: string
              format: uid
              description: The unique ID of the collection to trigger when calling this webhook.
              example: 12345678-12ece9e1-2abf-4edc-8e34-de66e74114d2
            environment:
              type: string
              format: uid
              description: The unique ID of the environment to trigger when calling this webhook.
              example: 12345678-d9c7dc8f-904e-4bba-99b5-4d490aae1957
            name:
              type: string
              description: The webhook's name. On success, the system creates a new monitor with this name in the **Monitors** tab.
              example: Test Webhook
    workspaceId:
      type: string
      example: 1f0df51a-8658-4ee8-a2a1-d2567dfa09a9
    createWebhookParamMissing400Error:
      type: object
      properties:
        error:
          type: object
          properties:
            name:
              type: string
              description: The error name.
              example: paramMissingError
            message:
              type: string
              description: The error message.
              example: Parameter is missing in the request.
            details:
              type: object
              description: Information about the error.
              properties:
                param:
                  type: array
                  description: Information about the missing parameter.
                  items:
                    type: string
                  example:
                  - collection
    featureUnavailable403Error:
      title: Feature Unavailable
      type: object
      properties:
        type:
          type: string
          format: uri-reference
          description: The [URI reference](https://www.rfc-editor.org/rfc/rfc3986) that identifies the type of problem.
          example: https://api.postman.com/problems/forbidden
        title:
          type: string
          description: A short summary of the problem.
          example: Forbidden
        detail:
          type: string
          description: Information about the error.
          example: This feature isn't available in your region.
        status:
          type: integer
          format: http-status-code
          description: The error's HTTP status code.
          example: 403
  requestBodies:
    createWebhook:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/createWebhookRequest'
          example:
            webhook:
              name: Test Webhook
              collection: 12345678-12ece9e1-2abf-4edc-8e34-de66e74114d2
  parameters:
    workspaceQuery:
      name: workspace
      in: query
      description: The workspace's ID.
      schema:
        $ref: '#/components/schemas/workspaceId'
  securitySchemes:
    PostmanApiKey:
      type: apiKey
      in: header
      name: x-api-key
    scimApiKey:
      type: apiKey
      in: header
      name: Authorization
      description: A valid [SCIM API key](https://learning.postman.com/docs/administration/scim-provisioning/scim-provisioning-overview/#generating-scim-api-key) for calls to SCIM endpoints.
