openapi: 3.2.0
info:
  description: 'To get started using Cloudflare''s products and services via the API, refer to [how to interact with Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/), which covers using tools like [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform) and the [official SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows who is making requests and what permissions you have. Create an API token to grant access to the API to perform actions.


    To create an API token, from the Cloudflare dashboard, go to My Profile > API Tokens and select Create Token. For more information on how to create and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).'
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: APIs.io Engineering Platform Cloudflare Zero Trust Risk Scoring Integrations API
  version: 4.0.0
tags:
- name: Zero Trust Risk Scoring Integrations
paths:
  /accounts/{account_id}/zt_risk_scoring/integrations:
    get:
      operationId: dlp-zt-risk-score-integration-list
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          type: string
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dlp_api-response-common-failure'
          description: List failure response
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/dlp_api-response-single'
                - properties:
                    result:
                      $ref: '#/components/schemas/dlp_RiskScoreIntegrationArray'
                  type: object
          description: List response
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform List all risk score integrations for the account.
      tags:
      - Zero Trust Risk Scoring Integrations
      x-api-token-group:
      - Teams Read
      - Teams Write
    post:
      operationId: dlp-zt-risk-score-integration-create
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/dlp_CreateIntegrationBody'
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dlp_api-response-common-failure'
          description: Create failure response
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/dlp_api-response-single'
                - properties:
                    result:
                      $ref: '#/components/schemas/dlp_RiskScoreIntegration'
                  type: object
          description: Create response
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Create new risk score integration.
      tags:
      - Zero Trust Risk Scoring Integrations
      x-api-token-group:
      - Teams Write
  /accounts/{account_id}/zt_risk_scoring/integrations/{integration_id}:
    delete:
      operationId: dlp-zt-risk-score-integration-delete
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          type: string
      - in: path
        name: integration_id
        required: true
        schema:
          format: uuid
          type: string
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dlp_api-response-common-failure'
          description: Delete failure response
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/dlp_api-response-single'
                - properties:
                    result:
                      $ref: '#/components/schemas/dlp_Empty'
                  type: object
          description: Delete response
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Delete a risk score integration.
      tags:
      - Zero Trust Risk Scoring Integrations
    get:
      operationId: dlp-zt-risk-score-integration-get
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          type: string
      - in: path
        name: integration_id
        required: true
        schema:
          format: uuid
          type: string
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dlp_api-response-common-failure'
          description: Get failure response
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/dlp_api-response-single'
                - properties:
                    result:
                      $ref: '#/components/schemas/dlp_RiskScoreIntegration'
                  type: object
          description: Get response
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Get risk score integration by id.
      tags:
      - Zero Trust Risk Scoring Integrations
    put:
      description: Overwrite the reference_id, tenant_url, and active values with the ones provided
      operationId: dlp-zt-risk-score-integration-update
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          type: string
      - in: path
        name: integration_id
        required: true
        schema:
          format: uuid
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/dlp_UpdateIntegrationBody'
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dlp_api-response-common-failure'
          description: Update failure response
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/dlp_api-response-single'
                - properties:
                    result:
                      $ref: '#/components/schemas/dlp_RiskScoreIntegration'
                  type: object
          description: Update response
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Update a risk score integration.
      tags:
      - Zero Trust Risk Scoring Integrations
  /accounts/{account_id}/zt_risk_scoring/integrations/reference_id/{reference_id}:
    get:
      operationId: dlp-zt-risk-score-integration-get-by-reference-id
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          type: string
      - in: path
        name: reference_id
        required: true
        schema:
          type: string
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dlp_api-response-common-failure'
          description: Get failure response
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/dlp_api-response-single'
                - properties:
                    result:
                      $ref: '#/components/schemas/dlp_RiskScoreIntegration'
                  type: object
          description: Get response
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Get risk score integration by reference id.
      tags:
      - Zero Trust Risk Scoring Integrations
components:
  schemas:
    dlp_api-response-single:
      allOf:
      - $ref: '#/components/schemas/dlp_api-response-common'
      type: object
    dlp_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/dlp_messages'
        messages:
          $ref: '#/components/schemas/dlp_messages'
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      type: object
    dlp_CreateIntegrationBody:
      properties:
        integration_type:
          $ref: '#/components/schemas/dlp_RiskScoreIntegrationType'
        reference_id:
          description: 'A reference id that can be supplied by the client. Currently this should be set to the Access-Okta IDP ID (a UUIDv4).

            https://developers.cloudflare.com/api/operations/access-identity-providers-get-an-access-identity-provider'
          type:
          - string
          - 'null'
        tenant_url:
          description: The base url of the tenant, e.g. "https://tenant.okta.com"
          format: uri
          type: string
      required:
      - integration_type
      - tenant_url
      type: object
    dlp_Empty:
      type:
      - object
      - 'null'
    dlp_RiskScoreIntegrationArray:
      items:
        $ref: '#/components/schemas/dlp_RiskScoreIntegration'
      type: array
    dlp_UpdateIntegrationBody:
      properties:
        active:
          description: Whether this integration is enabled. If disabled, no risk changes will be exported to the third-party.
          type: boolean
        reference_id:
          description: 'A reference id that can be supplied by the client. Currently this should be set to the Access-Okta IDP ID (a UUIDv4).

            https://developers.cloudflare.com/api/operations/access-identity-providers-get-an-access-identity-provider'
          type:
          - string
          - 'null'
        tenant_url:
          description: The base url of the tenant, e.g. "https://tenant.okta.com"
          format: uri
          type: string
      required:
      - tenant_url
      - active
      type: object
    dlp_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    dlp_RiskScoreIntegrationType:
      enum:
      - Okta
      type: string
    dlp_RiskScoreIntegration:
      properties:
        account_tag:
          description: The Cloudflare account tag.
          type: string
        active:
          description: Whether this integration is enabled and should export changes in risk score.
          type: boolean
        created_at:
          description: When the integration was created in RFC3339 format.
          format: date-time
          type: string
        id:
          description: The id of the integration, a UUIDv4.
          format: uuid
          type: string
        integration_type:
          $ref: '#/components/schemas/dlp_RiskScoreIntegrationType'
        reference_id:
          description: 'A reference ID defined by the client.

            Should be set to the Access-Okta IDP integration ID.

            Useful when the risk-score integration needs to be associated with a secondary asset and recalled using that ID.'
          type: string
        tenant_url:
          description: The base URL for the tenant. E.g. "https://tenant.okta.com"
          type: string
        well_known_url:
          description: The URL for the Shared Signals Framework configuration, e.g. "/.well-known/sse-configuration/{integration_uuid}/". https://openid.net/specs/openid-sse-framework-1_0.html#rfc.section.6.2.1
          type: string
      required:
      - id
      - account_tag
      - integration_type
      - reference_id
      - tenant_url
      - well_known_url
      - active
      - created_at
      type: object
    dlp_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/dlp_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/dlp_messages'
          example: []
        result:
          enum:
          - null
          type:
          - object
          - 'null'
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
  securitySchemes:
    api_email:
      in: header
      name: X-Auth-Email
      type: apiKey
    api_key:
      in: header
      name: X-Auth-Key
      type: apiKey
    api_token:
      scheme: bearer
      type: http
    user_service_key:
      in: header
      name: X-Auth-User-Service-Key
      type: apiKey
