openapi: 3.0.0
info:
  version: "1.0.0"
  x-release: v4
  title: APIs.io Engineering Platform Amazon API Gateway 2014 11 13 DNS Settings for an Account API
  description: <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: apigateway
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/apigateway-2015-07-09.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: https://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: http://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
- url: https://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: DNS Settings for an Account
paths:
  /accounts/{account_id}/dns_settings:
    get:
      description: Show DNS settings for an account
      operationId: dns-settings-for-an-account-list-dns-settings
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/dns-settings_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/dns-settings_dns_response_single'
                - $ref: '#/components/schemas/dns-settings_api-response-common-failure'
          description: Show DNS Settings response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dns-settings_dns_response_single'
          description: Show DNS Settings response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Show DNS Settings
      tags:
      - DNS Settings for an Account
      x-cfPermissionsRequired:
        enum:
        - '#dns_records:read'
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
    patch:
      description: Update DNS settings for an account
      operationId: dns-settings-for-an-account-update-dns-settings
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/dns-settings_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/dns-settings_account_settings'
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/dns-settings_dns_response_single'
                - $ref: '#/components/schemas/dns-settings_api-response-common-failure'
          description: Show DNS Settings response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dns-settings_dns_response_single'
          description: Show DNS Settings response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Update DNS Settings
      tags:
      - DNS Settings for an Account
      x-cfPermissionsRequired:
        enum:
        - '#dns_records:read'
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
components:
  schemas:
    dns-settings_api-response-single:
      allOf:
      - $ref: '#/components/schemas/dns-settings_api-response-common'
      type: object
    dns-settings_secondary_overrides:
      description: Allows a Secondary DNS zone to use (proxied) override records and CNAME flattening at the zone apex.
      example: false
      type: boolean
    dns-settings_foundation_dns:
      description: Whether to enable Foundation DNS Advanced Nameservers on the zone.
      example: false
      type: boolean
    dns-settings_ns_ttl:
      description: The time to live (TTL) of the zone's nameserver (NS) records.
      example: 86400
      maximum: 86400
      minimum: 30
      type: number
    dns-settings_multi_provider:
      description: Whether to enable multi-provider DNS, which causes Cloudflare to activate the zone even when non-Cloudflare NS records exist, and to respect NS records at the zone apex during outbound zone transfers.
      example: false
      type: boolean
    dns-settings_zone_mode:
      description: Whether the zone mode is a regular or CDN/DNS only zone.
      enum:
      - standard
      - cdn_only
      - dns_only
      example: dns_only
      type: string
    dns-settings_dns-settings:
      properties:
        flatten_all_cnames:
          $ref: '#/components/schemas/dns-settings_flatten_all_cnames'
        foundation_dns:
          $ref: '#/components/schemas/dns-settings_foundation_dns'
        multi_provider:
          $ref: '#/components/schemas/dns-settings_multi_provider'
        nameservers:
          $ref: '#/components/schemas/dns-settings_nameservers'
        ns_ttl:
          $ref: '#/components/schemas/dns-settings_ns_ttl'
        secondary_overrides:
          $ref: '#/components/schemas/dns-settings_secondary_overrides'
        soa:
          $ref: '#/components/schemas/dns-settings_soa'
        zone_mode:
          $ref: '#/components/schemas/dns-settings_zone_mode'
      type: object
    dns-settings_account_settings:
      properties:
        zone_defaults:
          $ref: '#/components/schemas/dns-settings_dns-settings'
      type: object
    dns-settings_soa:
      description: Components of the zone's SOA record.
      properties:
        expire:
          description: Time in seconds of being unable to query the primary server after which secondary servers should stop serving the zone.
          example: 604800
          maximum: 2419200.0
          minimum: 86400
          type: number
        min_ttl:
          description: The time to live (TTL) for negative caching of records within the zone.
          example: 1800
          maximum: 86400
          minimum: 60
          type: number
        mname:
          description: The primary nameserver, which may be used for outbound zone transfers.
          example: kristina.ns.cloudflare.com
          type: string
        refresh:
          description: Time in seconds after which secondary servers should re-check the SOA record to see if the zone has been updated.
          example: 10000
          maximum: 86400
          minimum: 600
          type: number
        retry:
          description: Time in seconds after which secondary servers should retry queries after the primary server was unresponsive.
          example: 2400
          maximum: 86400
          minimum: 600
          type: number
        rname:
          description: The email address of the zone administrator, with the first label representing the local part of the email address.
          example: admin.example.com
          type: string
        ttl:
          description: The time to live (TTL) of the SOA record itself.
          example: 3600
          maximum: 86400
          minimum: 300
          type: number
      required:
      - mname
      - rname
      - refresh
      - retry
      - expire
      - min_ttl
      - ttl
      type: object
    dns-settings_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    dns-settings_identifier:
      description: Identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      type: string
    dns-settings_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/dns-settings_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/dns-settings_messages'
          example: []
        result:
          enum:
          - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    dns-settings_nameservers:
      description: Settings determining the nameservers through which the zone should be available.
      properties:
        type:
          description: Nameserver type
          enum:
          - cloudflare.standard
          - cloudflare.standard.random
          - custom.account
          - custom.tenant
          - custom.zone
          example: cloudflare.standard
          type: string
      required:
      - type
      type: object
    dns-settings_dns_response_single:
      allOf:
      - $ref: '#/components/schemas/dns-settings_api-response-single'
      - properties:
          result:
            $ref: '#/components/schemas/dns-settings_account_settings'
        type: object
    dns-settings_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/dns-settings_messages'
        messages:
          $ref: '#/components/schemas/dns-settings_messages'
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      type: object
    dns-settings_flatten_all_cnames:
      description: Whether to flatten all CNAME records in the zone. Note that, due to DNS limitations, a CNAME record at the zone apex will always be flattened.
      example: false
      type: boolean
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/apigateway/
x-hasEquivalentPaths: true
