openapi: 3.2.0
info:
  description: 'To get started using Cloudflare''s products and services via the API, refer to [how to interact with Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/), which covers using tools like [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform) and the [official SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows who is making requests and what permissions you have. Create an API token to grant access to the API to perform actions.


    To create an API token, from the Cloudflare dashboard, go to My Profile > API Tokens and select Create Token. For more information on how to create and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).'
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: APIs.io Engineering Platform Cloudflare Workers KV Stored Data Analytics API
  version: 4.0.0
tags:
- name: Workers KV Stored Data Analytics
paths:
  /accounts/{account_id}/storage/analytics/stored:
    get:
      description: Retrieves Workers KV stored data metrics for the given account.
      operationId: workers-kv-stored-data-analytics-query-stored-data-analytics
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/workers-kv_identifier'
      - in: query
        name: query
        schema:
          allOf:
          - $ref: '#/components/schemas/workers-kv_query'
          - properties:
              dimensions:
                example:
                - namespaceId
                items:
                  enum:
                  - namespaceId
              filters:
                example: namespaceId==a4e8cbb7-1b58-4990-925e-e026d40c4c64
              metrics:
                default: '["storedBytes"]'
                example:
                - storedBytes
                - storedKeys
                items:
                  enum:
                  - storedBytes
                  - storedKeys
              sort:
                example:
                - +storedBytes
                - -namespaceId
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - allOf:
                  - $ref: '#/components/schemas/workers-kv_api-response-common'
                  - properties:
                      result:
                        $ref: '#/components/schemas/workers-kv_result'
                    type: object
                - $ref: '#/components/schemas/workers-kv_api-response-common-failure'
          description: Query Stored Data Analytics response failure
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/workers-kv_api-response-common'
                - properties:
                    result:
                      $ref: '#/components/schemas/workers-kv_components-schemas-result'
                  type: object
          description: Query Stored Data Analytics response
      security:
      - api_token: []
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Query Stored Data Analytics
      tags:
      - Workers KV Stored Data Analytics
      x-api-token-group:
      - Workers KV Storage Write
      - Workers KV Storage Read
components:
  schemas:
    workers-kv_components-schemas-result:
      allOf:
      - $ref: '#/components/schemas/workers-kv_result'
      - properties:
          data:
            example:
            - metrics:
              - - 2
                - 4
              - - 16
                - 32
          max:
            example:
              storedBytes: 32
              storedKeys: 4
          min:
            example:
              storedBytes: 16
              storedKeys: 2
          query:
            $ref: '#/components/schemas/workers-kv_query'
          totals:
            example:
              storedBytes: 48
              storedKeys: 6
    workers-kv_result:
      description: Metrics on Workers KV requests.
      properties:
        data:
          items:
            properties:
              dimensions:
                items:
                  type: string
                type: array
              metrics:
                description: List of metrics returned by the query.
                items:
                  items:
                    format: float
                    type: number
                  type: array
                type: array
            required:
            - metrics
            type: object
          type:
          - array
          - 'null'
        data_lag:
          description: Number of seconds between current time and last processed event, i.e. how many seconds of data could be missing.
          example: 0
          minimum: 0
          type: number
        max:
          additionalProperties:
            type: number
          description: Maximum results for each metric.
          type: object
        min:
          additionalProperties:
            type: number
          description: Minimum results for each metric.
          type: object
        query:
          $ref: '#/components/schemas/workers-kv_query'
        rows:
          description: Total number of rows in the result.
          example: 2
          minimum: 0
          type: number
        time_intervals:
          description: Time interval buckets by beginning and ending
          items:
            items:
              example: '2019-01-02T02:20:00Z'
              format: date-time
              maxItems: 2
              minItems: 2
              type: string
            type: array
          type: array
        totals:
          additionalProperties:
            type: number
          description: Total results for metrics across all data.
          type: object
      required:
      - rows
      - data
      - data_lag
      - min
      - max
      - totals
      - query
      type: object
    workers-kv_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    workers-kv_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/workers-kv_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/workers-kv_messages'
          example: []
        result:
          type:
          - object
          - 'null'
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    workers-kv_query:
      description: For specifying result metrics.
      properties:
        dimensions:
          default: '[]'
          description: Can be used to break down the data by given attributes.
          items:
            description: For drilling down on metrics.
            type: string
          type: array
        filters:
          default: '""'
          description: 'Used to filter rows by one or more dimensions. Filters can be combined using OR and AND boolean logic. AND takes precedence over OR in all the expressions. The OR operator is defined using a comma (,) or OR keyword surrounded by whitespace. The AND operator is defined using a semicolon (;) or AND keyword surrounded by whitespace. Note that the semicolon is a reserved character in URLs (rfc1738) and needs to be percent-encoded as %3B. Comparison options are:


            Operator                  | Name                            | URL Encoded

            --------------------------|---------------------------------|--------------------------

            ==                        | Equals                          | %3D%3D

            !=                        | Does not equals                 | !%3D

            >                        | Greater Than                    | %3E

            <                         | Less Than                       | %3C

            >=                       | Greater than or equal to        | %3E%3D

            <=                        | Less than or equal to           | %3C%3D     .'
          type: string
        limit:
          default: 10000
          description: Limit number of returned metrics.
          type: integer
        metrics:
          description: One or more metrics to compute.
          items:
            description: A quantitative measurement of KV usage.
            type: string
          type: array
        since:
          default: <6 hours ago>
          description: Start of time interval to query, defaults to 6 hours before request received.
          example: '2019-01-02T02:20:00Z'
          format: date-time
          type: string
        sort:
          default: '[]'
          description: Array of dimensions or metrics to sort by, each dimension/metric may be prefixed by - (descending) or + (ascending).
          items:
            type: string
          type: array
        until:
          default: <now>
          description: End of time interval to query, defaults to current time.
          example: '2019-01-02T03:20:00Z'
          format: date-time
          type: string
      type: object
    workers-kv_identifier:
      description: Identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      readOnly: true
      type: string
    workers-kv_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/workers-kv_messages'
        messages:
          $ref: '#/components/schemas/workers-kv_messages'
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      type: object
  securitySchemes:
    api_email:
      in: header
      name: X-Auth-Email
      type: apiKey
    api_key:
      in: header
      name: X-Auth-Key
      type: apiKey
    api_token:
      scheme: bearer
      type: http
    user_service_key:
      in: header
      name: X-Auth-User-Service-Key
      type: apiKey
