openapi: 3.2.0
info:
  description: 'To get started using Cloudflare''s products and services via the API, refer to [how to interact with Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/), which covers using tools like [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform) and the [official SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows who is making requests and what permissions you have. Create an API token to grant access to the API to perform actions.


    To create an API token, from the Cloudflare dashboard, go to My Profile > API Tokens and select Create Token. For more information on how to create and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).'
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: APIs.io Engineering Platform Cloudflare Magic Site App Configs API
  version: 4.0.0
tags:
- name: Magic Site App Configs
paths:
  /accounts/{account_id}/magic/sites/{site_id}/app_configs:
    get:
      description: Lists App Configs associated with a site.
      operationId: magic-site-app-configs-list-app-configs
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      - in: path
        name: site_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_api-response-common-failure'
          description: List App Configs response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_app_configs_collection_response'
          description: List App Configs response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform List App Configs
      tags:
      - Magic Site App Configs
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    post:
      description: Creates a new App Config for a site
      operationId: magic-site-app-configs-add-app-config
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      - in: path
        name: site_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/magic_app_config_add_single_request'
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_api-response-common-failure'
          description: Create Site App Config response failure
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_app_config_single_response'
          description: Create Site App Config response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Create a new App Config
      tags:
      - Magic Site App Configs
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
  /accounts/{account_id}/magic/sites/{site_id}/app_configs/{app_config_id}:
    delete:
      description: Deletes specific App Config associated with a site.
      operationId: magic-site-app-configs-delete-app-config
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      - in: path
        name: site_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      - in: path
        name: app_config_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_api-response-common-failure'
          description: Delete App Config response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_app_config_single_response'
          description: Delete App Config response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Delete App Config
      tags:
      - Magic Site App Configs
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    put:
      description: Updates an App Config for a site
      operationId: magic-site-app-configs-update-app-config
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      - in: path
        name: site_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      - in: path
        name: app_config_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/magic_app_config_update_request'
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_api-response-common-failure'
          description: Update Site App Config response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_app_config_single_response'
          description: Update Site App Config response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Update an App Config
      tags:
      - Magic Site App Configs
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
components:
  schemas:
    magic_managed_app_id:
      description: Managed app ID.
      example: cloudflare
      type: string
    magic_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    magic_app_config_single_response:
      allOf:
      - $ref: '#/components/schemas/magic_apps-response-object'
      - properties:
          result:
            $ref: '#/components/schemas/magic_app_config'
    magic_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/magic_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/magic_messages'
          example: []
        result:
          enum:
          - null
          type:
          - object
          - 'null'
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    magic_app_config:
      allOf:
      - properties:
          breakout:
            $ref: '#/components/schemas/magic_app_breakout'
          id:
            $ref: '#/components/schemas/magic_identifier'
          priority:
            $ref: '#/components/schemas/magic_app_priority'
          site_id:
            $ref: '#/components/schemas/magic_identifier'
        required:
        - id
        - site_id
      - oneOf:
        - properties:
            account_app_id:
              $ref: '#/components/schemas/magic_account_app_id'
          required:
          - account_app_id
          title: Account App
        - properties:
            managed_app_id:
              $ref: '#/components/schemas/magic_managed_app_id'
          required:
          - managed_app_id
          title: Managed App
      description: Traffic decision configuration for an app.
      type: object
    magic_app_config_add_single_request:
      allOf:
      - oneOf:
        - properties:
            account_app_id:
              $ref: '#/components/schemas/magic_account_app_id'
          required:
          - account_app_id
          title: Account App
        - properties:
            managed_app_id:
              $ref: '#/components/schemas/magic_managed_app_id'
          required:
          - managed_app_id
          title: Managed App
      - anyOf:
        - required:
          - breakout
          title: Breakout
        - required:
          - priority
          title: Prioritize
      - properties:
          breakout:
            $ref: '#/components/schemas/magic_app_breakout'
          priority:
            $ref: '#/components/schemas/magic_app_priority'
      type: object
    magic_app_config_update_request:
      properties:
        account_app_id:
          $ref: '#/components/schemas/magic_account_app_id'
        breakout:
          $ref: '#/components/schemas/magic_app_breakout'
        managed_app_id:
          $ref: '#/components/schemas/magic_managed_app_id'
        priority:
          $ref: '#/components/schemas/magic_app_priority'
      type: object
    magic_app_configs_collection_response:
      allOf:
      - $ref: '#/components/schemas/magic_apps-response-object'
      - properties:
          result:
            items:
              $ref: '#/components/schemas/magic_app_config'
            type: array
    magic_apps-response-object:
      properties:
        errors:
          $ref: '#/components/schemas/magic_messages'
        messages:
          $ref: '#/components/schemas/magic_messages'
        result:
          type:
          - object
          - 'null'
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    magic_account_app_id:
      description: Magic account app ID.
      example: ac60d3d0435248289d446cedd870bcf4
      type: string
    magic_app_priority:
      description: Priority of traffic. 0 is default, anything greater is prioritized. (Currently only 0 and 1 are supported)
      maximum: 1
      minimum: 0
      type: integer
    magic_app_breakout:
      description: Whether to breakout traffic to the app's endpoints directly. Null preserves default behavior.
      example: true
      type: boolean
    magic_identifier:
      description: Identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      readOnly: true
      type: string
  securitySchemes:
    api_email:
      in: header
      name: X-Auth-Email
      type: apiKey
    api_key:
      in: header
      name: X-Auth-Key
      type: apiKey
    api_token:
      scheme: bearer
      type: http
    user_service_key:
      in: header
      name: X-Auth-User-Service-Key
      type: apiKey
