openapi: 3.2.0
info:
  description: 'To get started using Cloudflare''s products and services via the API, refer to [how to interact with Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/), which covers using tools like [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform) and the [official SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows who is making requests and what permissions you have. Create an API token to grant access to the API to perform actions.


    To create an API token, from the Cloudflare dashboard, go to My Profile > API Tokens and select Create Token. For more information on how to create and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).'
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: APIs.io Engineering Platform Cloudflare Calls Apps API
  version: 4.0.0
tags:
- name: Calls Apps
paths:
  /accounts/{account_id}/calls/apps:
    get:
      description: Lists all apps in the Cloudflare account
      operationId: calls-apps-list
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/calls_account_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/calls_api-response-common-failure'
          description: List apps response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/calls_app_response_collection'
          description: List apps response
      security:
      - api_token: []
      summary: APIs.io Engineering Platform List apps
      tags:
      - Calls Apps
      x-api-token-group:
      - Calls Write
      - Calls Read
    post:
      description: Creates a new Cloudflare calls app. An app is an unique enviroment where each Session can access all Tracks within the app.
      operationId: calls-apps-create-a-new-app
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/calls_account_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/calls_app_editable_fields'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/calls_app_response_single_with_secret'
          description: Created a new app
      security:
      - api_token: []
      summary: APIs.io Engineering Platform Create a new app
      tags:
      - Calls Apps
      x-api-token-group:
      - Calls Write
  /accounts/{account_id}/calls/apps/{app_id}:
    delete:
      description: Deletes an app from Cloudflare Calls
      operationId: calls-apps-delete-app
      parameters:
      - in: path
        name: app_id
        required: true
        schema:
          $ref: '#/components/schemas/calls_identifier'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/calls_account_identifier'
      responses:
        4XX:
          content:
            application/json: {}
          description: Delete app response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/calls_app_response_single'
          description: Delete app response
      security:
      - api_token: []
      summary: APIs.io Engineering Platform Delete app
      tags:
      - Calls Apps
      x-api-token-group:
      - Calls Write
    get:
      description: Fetches details for a single Calls app.
      operationId: calls-apps-retrieve-app-details
      parameters:
      - in: path
        name: app_id
        required: true
        schema:
          $ref: '#/components/schemas/calls_identifier'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/calls_account_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/calls_api-response-common-failure'
          description: Retrieve app details response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/calls_app_response_single'
          description: Retrieve app details response
      security:
      - api_token: []
      summary: APIs.io Engineering Platform Retrieve app details
      tags:
      - Calls Apps
      x-api-token-group:
      - Calls Write
      - Calls Read
    put:
      description: Edit details for a single app.
      operationId: calls-apps-update-app-details
      parameters:
      - in: path
        name: app_id
        required: true
        schema:
          $ref: '#/components/schemas/calls_identifier'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/calls_account_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/calls_app_editable_fields'
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/calls_api-response-common-failure'
          description: Edit app details response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/calls_app_response_single'
          description: Edit app details response
      security:
      - api_token: []
      summary: APIs.io Engineering Platform Edit app details
      tags:
      - Calls Apps
      x-api-token-group:
      - Calls Write
components:
  schemas:
    calls_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/calls_messages'
        messages:
          $ref: '#/components/schemas/calls_messages'
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      type: object
    calls_api-response-single:
      allOf:
      - $ref: '#/components/schemas/calls_api-response-common'
      type: object
    calls_app_response_single:
      allOf:
      - $ref: '#/components/schemas/calls_api-response-single'
      - properties:
          result:
            $ref: '#/components/schemas/calls_app'
    calls_app_response_single_with_secret:
      allOf:
      - $ref: '#/components/schemas/calls_api-response-single'
      - properties:
          result:
            $ref: '#/components/schemas/calls_app_with_secret'
    calls_app_editable_fields:
      properties:
        name:
          $ref: '#/components/schemas/calls_name'
      type: object
    calls_created:
      description: The date and time the item was created.
      example: '2014-01-02T02:20:00Z'
      format: date-time
      type: string
    calls_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/calls_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/calls_messages'
          example: []
        result:
          enum:
          - null
          type:
          - object
          - 'null'
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    calls_identifier:
      description: A Cloudflare-generated unique identifier for a item.
      example: 2a95132c15732412d22c1476fa83f27a
      maxLength: 32
      minLength: 32
      type: string
    calls_turn_key:
      description: Bearer token
      example: 66bcf64aa8907b9f9d90ac17746a77ce394c393b92b3916633dc02846e608ad4
      maxLength: 64
      minLength: 64
      type: string
    calls_app_response_collection:
      allOf:
      - $ref: '#/components/schemas/calls_api-response-common'
      - properties:
          result:
            items:
              $ref: '#/components/schemas/calls_turn_key'
            type: array
    calls_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    calls_modified:
      description: The date and time the item was last modified.
      example: '2014-01-02T02:20:00Z'
      format: date-time
      type: string
    calls_account_identifier:
      description: The account identifier tag.
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      type: string
    calls_app:
      properties:
        created:
          $ref: '#/components/schemas/calls_created'
        modified:
          $ref: '#/components/schemas/calls_modified'
        name:
          $ref: '#/components/schemas/calls_name'
        uid:
          $ref: '#/components/schemas/calls_identifier'
      type: object
    calls_name:
      default: ''
      description: A short description of Calls app, not shown to end users.
      example: production-realtime-app
      type: string
    calls_secret:
      description: Bearer token
      example: 66bcf64aa8907b9f9d90ac17746a77ce394c393b92b3916633dc02846e608ad4
      maxLength: 64
      minLength: 64
      type: string
    calls_app_with_secret:
      properties:
        created:
          $ref: '#/components/schemas/calls_created'
        modified:
          $ref: '#/components/schemas/calls_modified'
        name:
          $ref: '#/components/schemas/calls_name'
        secret:
          $ref: '#/components/schemas/calls_secret'
        uid:
          $ref: '#/components/schemas/calls_identifier'
      type: object
  securitySchemes:
    api_email:
      in: header
      name: X-Auth-Email
      type: apiKey
    api_key:
      in: header
      name: X-Auth-Key
      type: apiKey
    api_token:
      scheme: bearer
      type: http
    user_service_key:
      in: header
      name: X-Auth-User-Service-Key
      type: apiKey
