openapi: 3.2.0
info:
  description: 'To get started using Cloudflare''s products and services via the API, refer to [how to interact with Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/), which covers using tools like [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform) and the [official SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows who is making requests and what permissions you have. Create an API token to grant access to the API to perform actions.


    To create an API token, from the Cloudflare dashboard, go to My Profile > API Tokens and select Create Token. For more information on how to create and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).'
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: APIs.io Engineering Platform Cloudflare Magic Site ACLs API
  version: 4.0.0
tags:
- name: Magic Site ACLs
paths:
  /accounts/{account_id}/magic/sites/{site_id}/acls:
    get:
      description: Lists Site ACLs associated with an account.
      operationId: magic-site-acls-list-acls
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      - in: path
        name: site_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_api-response-common-failure'
          description: List Site ACLs response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_acls_collection_response'
          description: List Site ACLs response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform List Site ACLs
      tags:
      - Magic Site ACLs
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    post:
      description: Creates a new Site ACL.
      operationId: magic-site-acls-create-acl
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      - in: path
        name: site_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/magic_acls_add_single_request'
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_api-response-common-failure'
          description: Create Site ACL response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_acl_single_response'
          description: Create Site ACL response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Create a new Site ACL
      tags:
      - Magic Site ACLs
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
  /accounts/{account_id}/magic/sites/{site_id}/acls/{acl_id}:
    delete:
      description: Remove a specific Site ACL.
      operationId: magic-site-acls-delete-acl
      parameters:
      - in: path
        name: site_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      - in: path
        name: acl_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_api-response-common-failure'
          description: Delete Site ACL response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_acl_deleted_response'
          description: Delete Site ACL response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Delete Site ACL
      tags:
      - Magic Site ACLs
      x-cfPermissionsRequired:
        enum:
        - '#organization:edit'
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    get:
      description: Get a specific Site ACL.
      operationId: magic-site-acls-acl-details
      parameters:
      - in: path
        name: site_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      - in: path
        name: acl_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_api-response-common-failure'
          description: Site ACL Details response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_acl_single_response'
          description: Site ACL Details response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Site ACL Details
      tags:
      - Magic Site ACLs
      x-cfPermissionsRequired:
        enum:
        - '#organization:read'
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    patch:
      description: Patch a specific Site ACL.
      operationId: magic-site-acls-patch-acl
      parameters:
      - in: path
        name: site_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      - in: path
        name: acl_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/magic_acl_update_request'
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_api-response-common-failure'
          description: Patch Site ACL response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_acl_modified_response'
          description: Patch Site ACL response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Patch Site ACL
      tags:
      - Magic Site ACLs
      x-cfPermissionsRequired:
        enum:
        - '#organization:edit'
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    put:
      description: Update a specific Site ACL.
      operationId: magic-site-acls-update-acl
      parameters:
      - in: path
        name: site_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      - in: path
        name: acl_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/magic_acl_update_request'
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_api-response-common-failure'
          description: Update Site ACL response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_acl_modified_response'
          description: Update Site ACL response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Update Site ACL
      tags:
      - Magic Site ACLs
      x-cfPermissionsRequired:
        enum:
        - '#organization:edit'
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
components:
  schemas:
    magic_port:
      example: 1
      type: integer
    magic_acl_modified_response:
      allOf:
      - $ref: '#/components/schemas/magic_api-response-single'
      - properties:
          result:
            $ref: '#/components/schemas/magic_acl'
    magic_cidr:
      description: A valid CIDR notation representing an IP range.
      example: 192.0.2.0/24
      type: string
    magic_lan-acl-configuration:
      properties:
        lan_id:
          description: The identifier for the LAN you want to create an ACL policy with.
          type: string
        lan_name:
          description: The name of the LAN based on the provided lan_id.
          type: string
        ports:
          description: Array of ports on the provided LAN that will be included in the ACL. If no ports are provided, communication on any port on this LAN is allowed.
          items:
            $ref: '#/components/schemas/magic_port'
          type: array
        subnets:
          description: Array of subnet IPs within the LAN that will be included in the ACL. If no subnets are provided, communication on any subnets on this LAN are allowed.
          items:
            $ref: '#/components/schemas/magic_acl-subnet'
          type: array
      required:
      - lan_id
      type: object
    magic_forward_locally:
      description: The desired forwarding action for this ACL policy. If set to "false", the policy will forward traffic to Cloudflare. If set to "true", the policy will forward traffic locally on the Magic Connector. If not included in request, will default to false.
      type: boolean
    magic_acls_add_single_request:
      description: Bidirectional ACL policy for local network traffic within a site.
      properties:
        description:
          description: Description for the ACL.
          example: Allows local traffic between PIN pads and cash register.
          type: string
        forward_locally:
          $ref: '#/components/schemas/magic_forward_locally'
        lan_1:
          $ref: '#/components/schemas/magic_lan-acl-configuration'
        lan_2:
          $ref: '#/components/schemas/magic_lan-acl-configuration'
        name:
          description: The name of the ACL.
          example: PIN Pad - Cash Register
          type: string
        protocols:
          items:
            description: Array of allowed communication protocols between configured LANs. If no protocols are provided, all protocols are allowed.
            enum:
            - tcp
            - udp
            - icmp
            type: string
          type: array
      required:
      - name
      - lan_1
      - lan_2
      type: object
    magic_api-response-single:
      allOf:
      - $ref: '#/components/schemas/magic_api-response-common'
      - properties:
          result:
            anyOf:
            - type:
              - object
              - 'null'
            - type:
              - string
              - 'null'
      type: object
    magic_acl_single_response:
      allOf:
      - $ref: '#/components/schemas/magic_api-response-single'
      - properties:
          result:
            $ref: '#/components/schemas/magic_acl'
    magic_acl-subnet:
      oneOf:
      - $ref: '#/components/schemas/magic_ip-address'
      - $ref: '#/components/schemas/magic_cidr'
    magic_acl_deleted_response:
      allOf:
      - $ref: '#/components/schemas/magic_api-response-single'
      - properties:
          result:
            $ref: '#/components/schemas/magic_acl'
    magic_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/magic_messages'
        messages:
          $ref: '#/components/schemas/magic_messages'
        result:
          anyOf:
          - type: object
          - items: {}
            type: array
          - type: string
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    magic_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    magic_acl_update_request:
      properties:
        description:
          description: Description for the ACL.
          example: Allows local traffic between PIN pads and cash register.
          type: string
        forward_locally:
          $ref: '#/components/schemas/magic_forward_locally'
        lan_1:
          $ref: '#/components/schemas/magic_lan-acl-configuration'
        lan_2:
          $ref: '#/components/schemas/magic_lan-acl-configuration'
        name:
          description: The name of the ACL.
          example: PIN Pad - Cash Register
          type: string
        protocols:
          items:
            description: Array of allowed communication protocols between configured LANs. If no protocols are provided, all protocols are allowed.
            enum:
            - tcp
            - udp
            - icmp
            type: string
          type: array
      type: object
    magic_ip-address:
      description: A valid IPv4 address.
      example: 192.0.2.1
      type: string
    magic_acls_collection_response:
      allOf:
      - $ref: '#/components/schemas/magic_api-response-single'
      - properties:
          result:
            items:
              $ref: '#/components/schemas/magic_acl'
            type: array
    magic_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/magic_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/magic_messages'
          example: []
        result:
          enum:
          - null
          type:
          - object
          - 'null'
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    magic_identifier:
      description: Identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      readOnly: true
      type: string
    magic_acl:
      description: Bidirectional ACL policy for network traffic within a site.
      properties:
        description:
          description: Description for the ACL.
          example: Allows local traffic between PIN pads and cash register.
          type: string
        forward_locally:
          $ref: '#/components/schemas/magic_forward_locally'
        id:
          $ref: '#/components/schemas/magic_identifier'
        lan_1:
          $ref: '#/components/schemas/magic_lan-acl-configuration'
        lan_2:
          $ref: '#/components/schemas/magic_lan-acl-configuration'
        name:
          description: The name of the ACL.
          example: PIN Pad - Cash Register
          type: string
        protocols:
          items:
            description: Array of allowed communication protocols between configured LANs. If no protocols are provided, all protocols are allowed.
            enum:
            - tcp
            - udp
            - icmp
            type: string
          type: array
      type: object
  securitySchemes:
    api_email:
      in: header
      name: X-Auth-Email
      type: apiKey
    api_key:
      in: header
      name: X-Auth-Key
      type: apiKey
    api_token:
      scheme: bearer
      type: http
    user_service_key:
      in: header
      name: X-Auth-User-Service-Key
      type: apiKey
