openapi: 3.2.0
info:
  description: 'To get started using Cloudflare''s products and services via the API, refer to [how to interact with Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/), which covers using tools like [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform) and the [official SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows who is making requests and what permissions you have. Create an API token to grant access to the API to perform actions.


    To create an API token, from the Cloudflare dashboard, go to My Profile > API Tokens and select Create Token. For more information on how to create and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).'
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: APIs.io Engineering Platform Cloudflare Magic Site WANs API
  version: 4.0.0
tags:
- name: Magic Site WANs
paths:
  /accounts/{account_id}/magic/sites/{site_id}/wans:
    get:
      description: Lists Site WANs associated with an account.
      operationId: magic-site-wans-list-wans
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      - in: path
        name: site_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_api-response-common-failure'
          description: List Site WANs response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_wans_collection_response'
          description: List Site WANs response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform List Site WANs
      tags:
      - Magic Site WANs
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    post:
      description: Creates a new Site WAN.
      operationId: magic-site-wans-create-wan
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      - in: path
        name: site_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/magic_wans_add_single_request'
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_api-response-common-failure'
          description: Create Site WAN response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_wans_collection_response'
          description: Create Site WAN response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Create a new Site WAN
      tags:
      - Magic Site WANs
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
  /accounts/{account_id}/magic/sites/{site_id}/wans/{wan_id}:
    delete:
      description: Remove a specific Site WAN.
      operationId: magic-site-wans-delete-wan
      parameters:
      - in: path
        name: site_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      - in: path
        name: wan_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_api-response-common-failure'
          description: Delete Site WAN response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_wan_deleted_response'
          description: Delete Site WAN response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Delete Site WAN
      tags:
      - Magic Site WANs
      x-cfPermissionsRequired:
        enum:
        - '#organization:edit'
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    get:
      description: Get a specific Site WAN.
      operationId: magic-site-wans-wan-details
      parameters:
      - in: path
        name: site_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      - in: path
        name: wan_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_api-response-common-failure'
          description: Site WAN Details response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_wan_single_response'
          description: Site WAN Details response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Site WAN Details
      tags:
      - Magic Site WANs
      x-cfPermissionsRequired:
        enum:
        - '#organization:read'
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    patch:
      description: Patch a specific Site WAN.
      operationId: magic-site-wans-patch-wan
      parameters:
      - in: path
        name: site_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      - in: path
        name: wan_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/magic_wan_update_request'
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_api-response-common-failure'
          description: Patch Site WAN response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_wan_modified_response'
          description: Patch Site WAN response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Patch Site WAN
      tags:
      - Magic Site WANs
      x-cfPermissionsRequired:
        enum:
        - '#organization:edit'
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    put:
      description: Update a specific Site WAN.
      operationId: magic-site-wans-update-wan
      parameters:
      - in: path
        name: site_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      - in: path
        name: wan_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/magic_wan_update_request'
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_api-response-common-failure'
          description: Update Site WAN response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_wan_modified_response'
          description: Update Site WAN response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Update Site WAN
      tags:
      - Magic Site WANs
      x-cfPermissionsRequired:
        enum:
        - '#organization:edit'
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
components:
  schemas:
    magic_cidr:
      description: A valid CIDR notation representing an IP range.
      example: 192.0.2.0/24
      type: string
    magic_ip-address:
      description: A valid IPv4 address.
      example: 192.0.2.1
      type: string
    magic_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    magic_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/magic_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/magic_messages'
          example: []
        result:
          enum:
          - null
          type:
          - object
          - 'null'
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    magic_wan_static_addressing:
      description: (optional) if omitted, use DHCP. Submit secondary_address when site is in high availability mode.
      properties:
        address:
          $ref: '#/components/schemas/magic_cidr'
        gateway_address:
          $ref: '#/components/schemas/magic_ip-address'
        secondary_address:
          $ref: '#/components/schemas/magic_cidr'
      required:
      - address
      - gateway_address
      type: object
    magic_wans_add_single_request:
      properties:
        name:
          type: string
        physport:
          $ref: '#/components/schemas/magic_port'
        priority:
          type: integer
        static_addressing:
          $ref: '#/components/schemas/magic_wan_static_addressing'
        vlan_tag:
          $ref: '#/components/schemas/magic_vlan_tag'
      required:
      - physport
      - vlan_tag
      type: object
    magic_port:
      example: 1
      type: integer
    magic_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/magic_messages'
        messages:
          $ref: '#/components/schemas/magic_messages'
        result:
          anyOf:
          - type: object
          - items: {}
            type: array
          - type: string
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    magic_api-response-single:
      allOf:
      - $ref: '#/components/schemas/magic_api-response-common'
      - properties:
          result:
            anyOf:
            - type:
              - object
              - 'null'
            - type:
              - string
              - 'null'
      type: object
    magic_wan_update_request:
      properties:
        name:
          type: string
        physport:
          $ref: '#/components/schemas/magic_port'
        priority:
          type: integer
        static_addressing:
          $ref: '#/components/schemas/magic_wan_static_addressing'
        vlan_tag:
          $ref: '#/components/schemas/magic_vlan_tag'
      type: object
    magic_wan_deleted_response:
      allOf:
      - $ref: '#/components/schemas/magic_api-response-single'
      - properties:
          result:
            $ref: '#/components/schemas/magic_wan'
    magic_wan_single_response:
      allOf:
      - $ref: '#/components/schemas/magic_api-response-single'
      - properties:
          result:
            $ref: '#/components/schemas/magic_wan'
    magic_wan:
      properties:
        id:
          $ref: '#/components/schemas/magic_identifier'
        name:
          type: string
        physport:
          $ref: '#/components/schemas/magic_port'
        priority:
          description: Priority of WAN for traffic loadbalancing.
          type: integer
        site_id:
          $ref: '#/components/schemas/magic_identifier'
        static_addressing:
          $ref: '#/components/schemas/magic_wan_static_addressing'
        vlan_tag:
          $ref: '#/components/schemas/magic_vlan_tag'
      type: object
    magic_wan_modified_response:
      allOf:
      - $ref: '#/components/schemas/magic_api-response-single'
      - properties:
          result:
            $ref: '#/components/schemas/magic_wan'
    magic_vlan_tag:
      description: VLAN port number.
      example: 0
      type: integer
    magic_identifier:
      description: Identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      readOnly: true
      type: string
    magic_wans_collection_response:
      allOf:
      - $ref: '#/components/schemas/magic_api-response-single'
      - properties:
          result:
            items:
              $ref: '#/components/schemas/magic_wan'
            type: array
  securitySchemes:
    api_email:
      in: header
      name: X-Auth-Email
      type: apiKey
    api_key:
      in: header
      name: X-Auth-Key
      type: apiKey
    api_token:
      scheme: bearer
      type: http
    user_service_key:
      in: header
      name: X-Auth-User-Service-Key
      type: apiKey
