openapi: 3.2.0
info:
  description: 'To get started using Cloudflare''s products and services via the API, refer to [how to interact with Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/), which covers using tools like [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform) and the [official SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows who is making requests and what permissions you have. Create an API token to grant access to the API to perform actions.


    To create an API token, from the Cloudflare dashboard, go to My Profile > API Tokens and select Create Token. For more information on how to create and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).'
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: APIs.io Engineering Platform Cloudflare DLP Settings API
  version: 4.0.0
tags:
- name: DLP Settings
paths:
  /accounts/{account_id}/dlp/limits:
    get:
      operationId: dlp-limits-get
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          type: string
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dlp_api-response-common-failure'
          description: Limits get failed
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/dlp_api-response-single'
                - properties:
                    result:
                      $ref: '#/components/schemas/dlp_Limits'
                  type: object
          description: Limits retrieved successfully
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Fetch limits associated with DLP for account
      tags:
      - DLP Settings
  /accounts/{account_id}/dlp/patterns/validate:
    post:
      description: 'Validates whether this pattern is a valid regular expression. Rejects it if

        the regular expression is too complex or can match an unbounded-length

        string. The regex will be rejected if it uses `*` or `+`. Bound the maximum

        number of characters that can be matched using a range, e.g. `{1,100}`.'
      operationId: dlp-pattern-validate
      parameters:
      - description: Account ID
        in: path
        name: account_id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/dlp_RegexValidationQuery'
        description: Validation query
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dlp_api-response-common-failure'
          description: Failed to validate
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/dlp_api-response-single'
                - properties:
                    result:
                      $ref: '#/components/schemas/dlp_RegexValidationResult'
                  type: object
          description: Validation response
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Validate a DLP regex pattern
      tags:
      - DLP Settings
  /accounts/{account_id}/dlp/payload_log:
    get:
      operationId: dlp-payload-log-get
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          type: string
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dlp_api-response-common-failure'
          description: Failed to get payload log settings
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/dlp_api-response-single'
                - properties:
                    result:
                      $ref: '#/components/schemas/dlp_PayloadLogSetting'
                  type: object
          description: Payload log settings
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Get payload log settings
      tags:
      - DLP Settings
    put:
      operationId: dlp-payload-log-put
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/dlp_PayloadLogSettingUpdate'
        description: New payload log settings
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dlp_api-response-common-failure'
          description: Failed to set payload log settings
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/dlp_api-response-single'
                - properties:
                    result:
                      $ref: '#/components/schemas/dlp_PayloadLogSetting'
                  type: object
          description: Payload log settings
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Set payload log settings
      tags:
      - DLP Settings
components:
  schemas:
    dlp_api-response-single:
      allOf:
      - $ref: '#/components/schemas/dlp_api-response-common'
      type: object
    dlp_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/dlp_messages'
        messages:
          $ref: '#/components/schemas/dlp_messages'
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      type: object
    dlp_RegexValidationQuery:
      properties:
        max_match_bytes:
          description: 'Maximum number of bytes that the regular expression can match.


            If this is `null` then there is no limit on the length. Patterns can use

            `*` and `+`. Otherwise repeats should use a range `{m,n}` to restrict

            patterns to the length. If this field is missing, then a default length

            limit is used.


            Note that the length is specified in bytes. Since regular expressions

            use UTF-8 the pattern `.` can match up to 4 bytes. Hence `.{1,256}`

            has a maximum length of 1024 bytes.'
          format: int32
          minimum: 0
          type:
          - integer
          - 'null'
        regex:
          type: string
      required:
      - regex
      type: object
    dlp_RegexValidationResult:
      properties:
        valid:
          type: boolean
      required:
      - valid
      type: object
    dlp_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    dlp_Limits:
      properties:
        max_dataset_cells:
          format: int64
          minimum: 0
          type: integer
      required:
      - max_dataset_cells
      type: object
    dlp_PayloadLogSetting:
      properties:
        public_key:
          type:
          - string
          - 'null'
        updated_at:
          format: date-time
          type: string
      required:
      - updated_at
      type: object
    dlp_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/dlp_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/dlp_messages'
          example: []
        result:
          enum:
          - null
          type:
          - object
          - 'null'
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    dlp_PayloadLogSettingUpdate:
      properties:
        public_key:
          type:
          - string
          - 'null'
      type: object
  securitySchemes:
    api_email:
      in: header
      name: X-Auth-Email
      type: apiKey
    api_key:
      in: header
      name: X-Auth-Key
      type: apiKey
    api_token:
      scheme: bearer
      type: http
    user_service_key:
      in: header
      name: X-Auth-User-Service-Key
      type: apiKey
