openapi: 3.2.0
info:
  description: 'To get started using Cloudflare''s products and services via the API, refer to [how to interact with Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/), which covers using tools like [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform) and the [official SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows who is making requests and what permissions you have. Create an API token to grant access to the API to perform actions.


    To create an API token, from the Cloudflare dashboard, go to My Profile > API Tokens and select Create Token. For more information on how to create and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).'
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: APIs.io Engineering Platform Cloudflare User's Invites API
  version: 4.0.0
tags:
- name: User's Invites
paths:
  /user/invites:
    get:
      description: Lists all invitations associated with my user.
      operationId: user'-s-invites-list-invitations
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/iam_api-response-common-failure'
          description: List Invitations response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/iam_schemas-collection_invite_response'
          description: List Invitations response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform List Invitations
      tags:
      - User's Invites
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
  /user/invites/{invite_id}:
    get:
      description: Gets the details of an invitation.
      operationId: user'-s-invites-invitation-details
      parameters:
      - in: path
        name: invite_id
        required: true
        schema:
          $ref: '#/components/schemas/iam_invite_components-schemas-identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/iam_api-response-common-failure'
          description: Invitation Details response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/iam_single_invite_response'
          description: Invitation Details response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Invitation Details
      tags:
      - User's Invites
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    patch:
      description: Responds to an invitation.
      operationId: user'-s-invites-respond-to-invitation
      parameters:
      - in: path
        name: invite_id
        required: true
        schema:
          $ref: '#/components/schemas/iam_invite_components-schemas-identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                status:
                  description: Status of your response to the invitation (rejected or accepted).
                  enum:
                  - accepted
                  - rejected
                  example: accepted
              required:
              - status
              type: object
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/iam_api-response-common-failure'
          description: Respond to Invitation response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/iam_single_invite_response'
          description: Respond to Invitation response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Respond to Invitation
      tags:
      - User's Invites
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
components:
  schemas:
    iam_invited_member_email:
      description: Email address of the user to add to the organization.
      example: user@example.com
      maxLength: 90
      type: string
    iam_role_components-schemas-identifier:
      description: Role identifier tag.
      example: 3536bcfad5faccb999b47003c79917fb
      maxLength: 32
      type: string
    iam_invite_components-schemas-identifier:
      description: Invite identifier tag.
      example: 4f5f0c14a2a41d5063dd301b2f829f04
      maxLength: 32
      readOnly: true
      type: string
    iam_components-schemas-name:
      description: Role Name.
      example: Organization Admin
      maxLength: 120
      readOnly: true
      type: string
    iam_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/iam_messages'
        messages:
          $ref: '#/components/schemas/iam_messages'
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      type: object
    iam_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    iam_schemas-expires_on:
      description: When the invite is no longer active.
      example: '2014-01-01T05:20:00Z'
      format: date-time
      readOnly: true
      type: string
    iam_invited_by:
      description: The email address of the user who created the invite.
      example: user@example.com
      maxLength: 90
      type: string
    iam_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/iam_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/iam_messages'
          example: []
        result:
          enum:
          - null
          type:
          - object
          - 'null'
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    iam_invited_on:
      description: When the invite was sent.
      example: '2014-01-01T05:20:00Z'
      format: date-time
      readOnly: true
      type: string
    iam_schemas-collection_invite_response:
      allOf:
      - $ref: '#/components/schemas/iam_api-response-collection'
      - properties:
          result:
            items:
              $ref: '#/components/schemas/iam_schemas-invite'
            type: array
        type: object
    iam_api-response-collection:
      allOf:
      - $ref: '#/components/schemas/iam_api-response-common'
      - properties:
          result:
            items: {}
            type:
            - array
            - 'null'
          result_info:
            $ref: '#/components/schemas/iam_result_info'
      type: object
    iam_result_info:
      properties:
        count:
          description: Total number of results for the requested service
          example: 1
          type: number
        page:
          description: Current page within paginated list of results
          example: 1
          type: number
        per_page:
          description: Number of results per page of results
          example: 20
          type: number
        total_count:
          description: Total results available without any search parameters
          example: 2000
          type: number
      type: object
    iam_schemas-role:
      properties:
        description:
          $ref: '#/components/schemas/iam_description'
        id:
          $ref: '#/components/schemas/iam_role_components-schemas-identifier'
        name:
          $ref: '#/components/schemas/iam_components-schemas-name'
        permissions:
          $ref: '#/components/schemas/iam_schemas-permissions'
      required:
      - id
      - name
      - description
      - permissions
      type: object
    iam_schemas-invite:
      allOf:
      - $ref: '#/components/schemas/iam_user_invite'
      type: object
    iam_user_invite:
      allOf:
      - $ref: '#/components/schemas/iam_base'
      - properties:
          status:
            description: Current status of the invitation.
            enum:
            - pending
            - accepted
            - rejected
            - expired
            example: accepted
    iam_schemas-permissions:
      description: Access permissions for this User.
      items:
        example: '#zones:read'
        maxLength: 160
        type: string
      readOnly: true
      type: array
    iam_single_invite_response:
      allOf:
      - $ref: '#/components/schemas/iam_api-response-single'
      - properties:
          result:
            type: object
        type: object
    iam_base:
      properties:
        expires_on:
          $ref: '#/components/schemas/iam_schemas-expires_on'
        id:
          $ref: '#/components/schemas/iam_invite_components-schemas-identifier'
        invited_by:
          $ref: '#/components/schemas/iam_invited_by'
        invited_member_email:
          $ref: '#/components/schemas/iam_invited_member_email'
        invited_member_id:
          description: ID of the user to add to the organization.
          example: 5a7805061c76ada191ed06f989cc3dac
          maxLength: 32
          readOnly: true
          type:
          - string
          - 'null'
        invited_on:
          $ref: '#/components/schemas/iam_invited_on'
        organization_id:
          description: ID of the organization the user will be added to.
          example: 5a7805061c76ada191ed06f989cc3dac
          maxLength: 32
          readOnly: true
          type: string
        organization_name:
          description: Organization name.
          example: Cloudflare, Inc.
          maxLength: 100
          readOnly: true
          type: string
        roles:
          description: Roles to be assigned to this user.
          items:
            $ref: '#/components/schemas/iam_schemas-role'
          type: array
      required:
      - invited_member_id
      - organization_id
      type: object
    iam_api-response-single:
      allOf:
      - $ref: '#/components/schemas/iam_api-response-common'
      type: object
    iam_description:
      description: Description of role's permissions.
      example: Administrative access to the entire Organization
      readOnly: true
      type: string
  securitySchemes:
    api_email:
      in: header
      name: X-Auth-Email
      type: apiKey
    api_key:
      in: header
      name: X-Auth-Key
      type: apiKey
    api_token:
      scheme: bearer
      type: http
    user_service_key:
      in: header
      name: X-Auth-User-Service-Key
      type: apiKey
