openapi: 3.2.0
info:
  description: 'To get started using Cloudflare''s products and services via the API, refer to [how to interact with Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/), which covers using tools like [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform) and the [official SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows who is making requests and what permissions you have. Create an API token to grant access to the API to perform actions.


    To create an API token, from the Cloudflare dashboard, go to My Profile > API Tokens and select Create Token. For more information on how to create and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).'
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: APIs.io Engineering Platform Cloudflare Stream Webhook API
  version: 4.0.0
tags:
- name: Stream Webhook
paths:
  /accounts/{account_id}/stream/webhook:
    delete:
      description: Deletes a webhook.
      operationId: stream-webhook-delete-webhooks
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/stream_account_identifier'
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stream_api-response-common-failure'
          description: Delete webhooks response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stream_deleted_response'
          description: Delete webhooks response
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Delete webhooks
      tags:
      - Stream Webhook
      x-api-token-group:
      - Stream Write
    get:
      description: Retrieves a list of webhooks.
      operationId: stream-webhook-view-webhooks
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/stream_account_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stream_api-response-common-failure'
          description: View webhooks response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stream_webhook_response_single'
          description: View webhooks response
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform View webhooks
      tags:
      - Stream Webhook
      x-api-token-group:
      - Stream Write
      - Stream Read
    put:
      description: Creates a webhook notification.
      operationId: stream-webhook-create-webhooks
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/stream_account_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/stream_webhook_request'
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stream_api-response-common-failure'
          description: Create webhooks response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stream_webhook_response_single'
          description: Create webhooks response
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Create webhooks
      tags:
      - Stream Webhook
      x-api-token-group:
      - Stream Write
components:
  schemas:
    stream_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    stream_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/stream_messages'
        messages:
          $ref: '#/components/schemas/stream_messages'
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      type: object
    stream_account_identifier:
      description: The account identifier tag.
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      type: string
    stream_deleted_response:
      allOf:
      - $ref: '#/components/schemas/stream_api-response-single'
      - properties:
          result:
            example: ok
            type: string
    stream_webhook_request:
      properties:
        notificationUrl:
          $ref: '#/components/schemas/stream_notificationUrl'
      required:
      - notificationUrl
    stream_api-response-single:
      allOf:
      - $ref: '#/components/schemas/stream_api-response-common'
      type: object
    stream_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/stream_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/stream_messages'
          example: []
        result:
          enum:
          - null
          type:
          - object
          - 'null'
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    stream_webhook_response_single:
      allOf:
      - $ref: '#/components/schemas/stream_api-response-single'
      - properties:
          result:
            type: object
    stream_notificationUrl:
      description: The URL where webhooks will be sent.
      example: https://example.com
      format: uri
      type: string
  securitySchemes:
    api_email:
      in: header
      name: X-Auth-Email
      type: apiKey
    api_key:
      in: header
      name: X-Auth-Key
      type: apiKey
    api_token:
      scheme: bearer
      type: http
    user_service_key:
      in: header
      name: X-Auth-User-Service-Key
      type: apiKey
