openapi: 3.0.0
info:
  version: "1.0.0"
  x-release: v4
  title: APIs.io Engineering Platform Amazon API Gateway 2014 11 13 API Tags API
  description: <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: apigateway
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/apigateway-2015-07-09.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: https://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: http://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
- url: https://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: API Tags
  description: The **API Tags** endpoints enable you to manage API tags with Postman's [tagging](https://learning.postman.com/docs/designing-and-developing-your-api/managing-apis/#tagging-apis) feature. Tagging is available on Postman [**Enterprise** plans](https://www.postman.com/pricing/).
paths:
  /apis/{apiId}/tags:
    parameters:
    - $ref: '#/components/parameters/apiId'
    - $ref: '#/components/parameters/v10Accept'
    get:
      summary: APIs.io Engineering Platform Get an API's tags
      description: Gets all the tags associated with an API.
      operationId: getApiTags
      tags:
      - API Tags
      responses:
        '200':
          $ref: '#/components/responses/tagGetPut'
        '400':
          $ref: '#/components/responses/v10HeaderMissing'
        '401':
          $ref: '#/components/responses/tag401Error'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                anyOf:
                - $ref: '#/components/schemas/tag403Error'
                - $ref: '#/components/schemas/featureUnavailable403Error'
              examples:
                Forbidden:
                  $ref: '#/components/examples/tag403Error'
                Feature Unavailable:
                  $ref: '#/components/examples/featureUnavailable403Error'
        '404':
          $ref: '#/components/responses/tag404Error'
        '500':
          $ref: '#/components/responses/tag500Error'
    put:
      summary: APIs.io Engineering Platform Update an API's tags
      description: Updates an API's associated tags. This endpoint replaces all existing tags with those you pass in the request body.
      operationId: updateApiTags
      tags:
      - API Tags
      requestBody:
        $ref: '#/components/requestBodies/tagUpdateTags'
      responses:
        '200':
          $ref: '#/components/responses/tagGetPut'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                anyOf:
                - $ref: '#/components/schemas/tag400Error'
                - $ref: '#/components/schemas/v10HeaderMissing'
              examples:
                Bad Request:
                  $ref: '#/components/examples/tag400Error'
                Missing v10 Accept Header:
                  $ref: '#/components/examples/v10HeaderMissing'
        '401':
          $ref: '#/components/responses/tag401Error'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                anyOf:
                - $ref: '#/components/schemas/tag403Error'
                - $ref: '#/components/schemas/featureUnavailable403Error'
              examples:
                Forbidden:
                  $ref: '#/components/examples/tag403Error'
                Feature Unavailable:
                  $ref: '#/components/examples/featureUnavailable403Error'
        '404':
          $ref: '#/components/responses/tag404Error'
        '500':
          $ref: '#/components/responses/tag500Error'
components:
  schemas:
    tag403Error:
      title: Forbidden
      type: object
      properties:
        type:
          type: string
          format: uri-reference
          description: The [URI reference](https://www.rfc-editor.org/rfc/rfc3986) that identifies the type of problem.
          example: https://api.postman.com/problems/forbidden
        title:
          type: string
          description: A short summary of the problem.
          example: Access Denied
        detail:
          type: string
          description: Information about the error.
          example: The tags feature is only available to enterprise teams
        status:
          type: integer
          format: http-status-code
          description: The error's HTTP status code.
          example: 403
    tag500Error:
      title: Unexpected Error
      type: object
      properties:
        type:
          type: string
          format: uri-reference
          description: The [URI reference](https://www.rfc-editor.org/rfc/rfc3986) that identifies the type of problem.
          example: https://api.postman.com/problems/internal-server-error
        title:
          type: string
          description: A short summary of the problem.
          example: Something went wrong
        detail:
          type: string
          description: Information about the error.
          example: Something went wrong while fetching entities having the provided slug.
        status:
          type: integer
          format: http-status-code
          description: The error's HTTP status code.
          example: 500
        instance:
          type: string
          example: /tags/hello-world/entities
          description: The URI reference that identifies the specific occurrence of the problem.
    tag400Error:
      title: Bad Request
      type: object
      properties:
        type:
          type: string
          format: uri-reference
          description: The [URI reference](https://www.rfc-editor.org/rfc/rfc3986) that identifies the type of problem.
          example: https://api.postman.com/problems/badrequest
        title:
          type: string
          description: A short summary of the problem.
          example: Bad Request
        detail:
          type: string
          description: Information about the error.
          example: body/tags/0/slug must NOT have more than 64 characters
        status:
          type: integer
          format: http-status-code
          description: The error's HTTP status code.
          example: 400
    tag404Error:
      title: Not Found
      type: object
      properties:
        type:
          type: string
          format: uri-reference
          description: The [URI reference](https://www.rfc-editor.org/rfc/rfc3986) that identifies the type of problem.
          example: https://api.postman.com/problems/not-found
        title:
          type: string
          description: A short summary of the problem.
          example: Resource Not Found
        detail:
          type: string
          description: Information about the error.
          example: Slug 'needs-review' does not exist.
        status:
          type: integer
          format: http-status-code
          description: The error's HTTP status code.
          example: 404
        instance:
          type: string
          description: The URI reference that identifies the specific occurrence of the problem.
          example: /tags/needs-review/entities
    v10HeaderMissing:
      title: Missing v10 Accept Header
      type: object
      properties:
        name:
          type: string
          description: The error name.
          example: instanceNotFoundError
        message:
          type: string
          description: The error message.
          example: API not found. For v10 and later APIs, ensure that your request sends the "application/vnd.api.v10+json" Accept header.
    tagGetPut:
      title: Success Response
      type: object
      properties:
        tags:
          type: array
          maxItems: 5
          minItems: 0
          description: A list of associated tags.
          items:
            type: object
            description: Information about the tag.
            properties:
              slug:
                type: string
                pattern: ^[a-z][a-z0-9-]*[a-z0-9]+$
                minLength: 2
                maxLength: 64
                description: The tag's ID within a team or individual (non-team) user scope.
                example: needs-review
    tag401Error:
      title: Unauthorized
      type: object
      properties:
        type:
          type: string
          format: uri-reference
          description: The [URI reference](https://www.rfc-editor.org/rfc/rfc3986) that identifies the type of problem.
          example: https://api.postman.com/problems/unauthorized
        title:
          type: string
          description: A short summary of the problem.
          example: Unauthorized
        detail:
          type: string
          description: Information about the error.
          example: The request lacks valid credentials.
        status:
          type: integer
          format: http-status-code
          description: The error's HTTP status code.
          example: 401
    featureUnavailable403Error:
      title: Feature Unavailable
      type: object
      properties:
        type:
          type: string
          format: uri-reference
          description: The [URI reference](https://www.rfc-editor.org/rfc/rfc3986) that identifies the type of problem.
          example: https://api.postman.com/problems/forbidden
        title:
          type: string
          description: A short summary of the problem.
          example: Forbidden
        detail:
          type: string
          description: Information about the error.
          example: This feature isn't available in your region.
        status:
          type: integer
          format: http-status-code
          description: The error's HTTP status code.
          example: 403
  examples:
    tag403Error:
      value:
        type: https://api.postman.com/problems/forbidden
        title: Access Denied
        detail: The tags feature is only available to enterprise teams
        status: 403
    v10HeaderMissing:
      value:
        name: instanceNotFoundError
        message: API not found. For v10 and later APIs, ensure that your request sends the "application/vnd.api.v10+json" Accept header.
    featureUnavailable403Error:
      value:
        type: https://api.postman.com/problems/forbidden
        title: Forbidden
        detail: This feature isn't available in your region.
        status: 403
    tag400Error:
      value:
        title: Bad Request
        detail: body/tags/0/slug must NOT have more than 64 characters
        status: 400
  responses:
    tag404Error:
      description: Not Found
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/tag404Error'
          example:
            type: https://api.postman.com/problems/not-found
            title: Resource Not Found
            detail: Slug 'needs-review' does not exist.
            status: 404
            instance: /tags/needs-review/entities
    tag500Error:
      description: Unexpected Error
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/tag500Error'
          example:
            type: https://api.postman.com/problems/internal-server-error
            title: Something went wrong
            detail: Something went wrong while fetching entities having the provided slug.
            status: 500
            instance: /tags/needs-review/entities
    v10HeaderMissing:
      description: Missing v10 Accept Header
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/v10HeaderMissing'
          examples:
            Missing v10 Accept Header:
              $ref: '#/components/examples/v10HeaderMissing'
    tagGetPut:
      description: Success Response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/tagGetPut'
          example:
            tags:
            - slug: needs-review
            - slug: test-api
    tag401Error:
      description: Unauthorized
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/tag401Error'
          example:
            type: https://api.postman.com/problems/unauthorized
            title: Unauthorized
            detail: The request lacks valid credentials.
            status: 401
  parameters:
    v10Accept:
      name: Accept
      in: header
      required: true
      description: The `application/vnd.api.v10+json` request header required to use the endpoint.
      schema:
        type: string
        enum:
        - application/vnd.api.v10+json
        example: application/vnd.api.v10+json
    apiId:
      name: apiId
      in: path
      required: true
      description: The API's ID.
      schema:
        type: string
        example: 90ca9f5a-c4c4-11ed-afa1-0242ac120002
  requestBodies:
    tagUpdateTags:
      content:
        application/json:
          schema:
            title: Update Tags
            type: object
            required:
            - tags
            properties:
              tags:
                type: array
                minItems: 0
                maxItems: 5
                description: A list of the associated tags as slugs.
                items:
                  type: object
                  description: Information about the tag.
                  required:
                  - slug
                  properties:
                    slug:
                      type: string
                      pattern: ^[a-z][a-z0-9-]*[a-z0-9]+$
                      minLength: 2
                      maxLength: 64
                      description: The tag's ID within a team or individual (non-team) user scope.
                      example: needs-review
          example:
            tags:
            - slug: needs-review
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/apigateway/
x-hasEquivalentPaths: true
