openapi: 3.2.0
info:
  description: 'To get started using Cloudflare''s products and services via the API, refer to [how to interact with Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/), which covers using tools like [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform) and the [official SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows who is making requests and what permissions you have. Create an API token to grant access to the API to perform actions.


    To create an API token, from the Cloudflare dashboard, go to My Profile > API Tokens and select Create Token. For more information on how to create and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).'
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: APIs.io Engineering Platform Cloudflare Zero Trust Lists API
  version: 4.0.0
tags:
- name: Zero Trust Lists
paths:
  /accounts/{account_id}/gateway/lists:
    get:
      description: Fetches all Zero Trust lists for an account.
      operationId: zero-trust-lists-list-zero-trust-lists
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/zero-trust-gateway_identifier'
      - in: query
        name: type
        schema:
          $ref: '#/components/schemas/zero-trust-gateway_schemas-type'
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/zero-trust-gateway_schemas-response_collection'
                - $ref: '#/components/schemas/zero-trust-gateway_api-response-common-failure'
          description: List Zero Trust lists response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/zero-trust-gateway_schemas-response_collection'
          description: List Zero Trust lists response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform List Zero Trust lists
      tags:
      - Zero Trust Lists
    post:
      description: Creates a new Zero Trust list.
      operationId: zero-trust-lists-create-zero-trust-list
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/zero-trust-gateway_identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                description:
                  $ref: '#/components/schemas/zero-trust-gateway_description'
                items:
                  $ref: '#/components/schemas/zero-trust-gateway_items'
                name:
                  $ref: '#/components/schemas/zero-trust-gateway_name'
                type:
                  $ref: '#/components/schemas/zero-trust-gateway_schemas-type'
              required:
              - name
              - type
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/zero-trust-gateway_single_response_with_list_items'
                - $ref: '#/components/schemas/zero-trust-gateway_api-response-common-failure'
          description: Create Zero Trust list response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/zero-trust-gateway_single_response_with_list_items'
          description: Create Zero Trust list response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Create Zero Trust list
      tags:
      - Zero Trust Lists
  /accounts/{account_id}/gateway/lists/{list_id}:
    delete:
      description: Deletes a Zero Trust list.
      operationId: zero-trust-lists-delete-zero-trust-list
      parameters:
      - in: path
        name: list_id
        required: true
        schema:
          $ref: '#/components/schemas/zero-trust-gateway_schemas-uuid'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/zero-trust-gateway_identifier'
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/zero-trust-gateway_empty_response'
                - $ref: '#/components/schemas/zero-trust-gateway_api-response-common-failure'
          description: Delete Zero Trust list response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/zero-trust-gateway_empty_response'
          description: Delete Zero Trust list response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Delete Zero Trust list
      tags:
      - Zero Trust Lists
    get:
      description: Fetches a single Zero Trust list.
      operationId: zero-trust-lists-zero-trust-list-details
      parameters:
      - in: path
        name: list_id
        required: true
        schema:
          $ref: '#/components/schemas/zero-trust-gateway_schemas-uuid'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/zero-trust-gateway_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/zero-trust-gateway_schemas-single_response'
                - $ref: '#/components/schemas/zero-trust-gateway_api-response-common-failure'
          description: Get Zero Trust list details response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/zero-trust-gateway_schemas-single_response'
          description: Get Zero Trust list details response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Get Zero Trust list details
      tags:
      - Zero Trust Lists
    patch:
      description: Appends or removes an item from a configured Zero Trust list.
      operationId: zero-trust-lists-patch-zero-trust-list
      parameters:
      - in: path
        name: list_id
        required: true
        schema:
          $ref: '#/components/schemas/zero-trust-gateway_schemas-uuid'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/zero-trust-gateway_identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                append:
                  $ref: '#/components/schemas/zero-trust-gateway_items'
                remove:
                  description: A list of the item values you want to remove.
                  items:
                    $ref: '#/components/schemas/zero-trust-gateway_value'
                  type: array
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/zero-trust-gateway_schemas-single_response'
                - $ref: '#/components/schemas/zero-trust-gateway_api-response-common-failure'
          description: Patch Zero Trust list response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/zero-trust-gateway_schemas-single_response'
          description: Patch Zero Trust list response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Patch Zero Trust list
      tags:
      - Zero Trust Lists
    put:
      description: Updates a configured Zero Trust list.
      operationId: zero-trust-lists-update-zero-trust-list
      parameters:
      - in: path
        name: list_id
        required: true
        schema:
          $ref: '#/components/schemas/zero-trust-gateway_schemas-uuid'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/zero-trust-gateway_identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                description:
                  $ref: '#/components/schemas/zero-trust-gateway_description'
                name:
                  $ref: '#/components/schemas/zero-trust-gateway_name'
              required:
              - name
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/zero-trust-gateway_schemas-single_response'
                - $ref: '#/components/schemas/zero-trust-gateway_api-response-common-failure'
          description: Update Zero Trust list response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/zero-trust-gateway_schemas-single_response'
          description: Update Zero Trust list response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Update Zero Trust list
      tags:
      - Zero Trust Lists
  /accounts/{account_id}/gateway/lists/{list_id}/items:
    get:
      description: Fetches all items in a single Zero Trust list.
      operationId: zero-trust-lists-zero-trust-list-items
      parameters:
      - in: path
        name: list_id
        required: true
        schema:
          $ref: '#/components/schemas/zero-trust-gateway_schemas-uuid'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/zero-trust-gateway_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/zero-trust-gateway_list_item_response_collection'
                - $ref: '#/components/schemas/zero-trust-gateway_api-response-common-failure'
          description: Get Zero Trust list items response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/zero-trust-gateway_list_item_response_collection'
          description: Get Zero Trust list items response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Get Zero Trust list items
      tags:
      - Zero Trust Lists
components:
  schemas:
    zero-trust-gateway_api-response-collection:
      allOf:
      - $ref: '#/components/schemas/zero-trust-gateway_api-response-common'
      - properties:
          result_info:
            $ref: '#/components/schemas/zero-trust-gateway_result_info'
      type: object
    zero-trust-gateway_schemas-response_collection:
      allOf:
      - $ref: '#/components/schemas/zero-trust-gateway_api-response-collection'
      - properties:
          result:
            items:
              $ref: '#/components/schemas/zero-trust-gateway_lists'
            type: array
    zero-trust-gateway_schemas-type:
      description: The type of list.
      enum:
      - SERIAL
      - URL
      - DOMAIN
      - EMAIL
      - IP
      example: SERIAL
      type: string
    zero-trust-gateway_identifier:
      example: 699d98642c564d2e855e9661899b7252
      type: string
    zero-trust-gateway_schemas-uuid:
      description: API Resource UUID tag.
      example: f174e90a-fafe-4643-bbbc-4a0ed4fc8415
      maxLength: 36
      type: string
    zero-trust-gateway_schemas-single_response:
      allOf:
      - $ref: '#/components/schemas/zero-trust-gateway_api-response-single'
      - properties:
          result:
            $ref: '#/components/schemas/zero-trust-gateway_lists'
    zero-trust-gateway_api-response-single:
      allOf:
      - $ref: '#/components/schemas/zero-trust-gateway_api-response-common'
      type: object
    zero-trust-gateway_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/zero-trust-gateway_messages'
        messages:
          $ref: '#/components/schemas/zero-trust-gateway_messages'
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      type: object
    zero-trust-gateway_count:
      description: The number of items in the list.
      example: 20
      readOnly: true
      type: number
    zero-trust-gateway_empty_response:
      allOf:
      - $ref: '#/components/schemas/zero-trust-gateway_api-response-single'
      - properties:
          result:
            type: object
    zero-trust-gateway_name:
      description: The name of the list.
      example: Admin Serial Numbers
      type: string
    zero-trust-gateway_result_info:
      properties:
        count:
          description: Total number of results for the requested service
          example: 1
          type: number
        page:
          description: Current page within paginated list of results
          example: 1
          type: number
        per_page:
          description: Number of results per page of results
          example: 20
          type: number
        total_count:
          description: Total results available without any search parameters
          example: 2000
          type: number
      type: object
    zero-trust-gateway_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    zero-trust-gateway_description_item:
      description: The description of the list item, if present
      example: Austin office IP
      minimum: 0
      type: string
    zero-trust-gateway_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/zero-trust-gateway_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/zero-trust-gateway_messages'
          example: []
        result:
          enum:
          - null
          type:
          - object
          - 'null'
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    zero-trust-gateway_list_item_response_collection:
      allOf:
      - $ref: '#/components/schemas/zero-trust-gateway_api-response-collection'
      - properties:
          result:
            items:
              $ref: '#/components/schemas/zero-trust-gateway_items'
            type: array
      - properties:
          result_info:
            properties:
              count:
                description: Total results returned based on your search parameters.
                example: 1
                type: number
              page:
                description: Current page within paginated list of results.
                example: 1
                type: number
              per_page:
                description: Number of results per page of results.
                example: 20
                type: number
              total_count:
                description: Total results available without any search parameters.
                example: 2000
                type: number
            type: object
    zero-trust-gateway_value:
      description: The value of the item in a list.
      example: 8GE8721REF
      type: string
    zero-trust-gateway_single_response_with_list_items:
      allOf:
      - $ref: '#/components/schemas/zero-trust-gateway_api-response-single'
      - properties:
          result:
            properties:
              created_at:
                $ref: '#/components/schemas/zero-trust-gateway_timestamp'
              description:
                $ref: '#/components/schemas/zero-trust-gateway_description'
              id:
                $ref: '#/components/schemas/zero-trust-gateway_schemas-uuid'
              items:
                $ref: '#/components/schemas/zero-trust-gateway_items'
              name:
                $ref: '#/components/schemas/zero-trust-gateway_name'
              type:
                $ref: '#/components/schemas/zero-trust-gateway_schemas-type'
              updated_at:
                $ref: '#/components/schemas/zero-trust-gateway_timestamp'
    zero-trust-gateway_timestamp:
      example: '2014-01-01T05:20:00.12345Z'
      format: date-time
      type: string
    zero-trust-gateway_description:
      description: The description of the list.
      example: The serial numbers for administrators
      type: string
    zero-trust-gateway_items:
      description: The items in the list.
      items:
        properties:
          created_at:
            $ref: '#/components/schemas/zero-trust-gateway_timestamp'
          description:
            $ref: '#/components/schemas/zero-trust-gateway_description_item'
          value:
            $ref: '#/components/schemas/zero-trust-gateway_value'
        type: object
      type: array
    zero-trust-gateway_lists:
      properties:
        count:
          $ref: '#/components/schemas/zero-trust-gateway_count'
        created_at:
          $ref: '#/components/schemas/zero-trust-gateway_timestamp'
        description:
          $ref: '#/components/schemas/zero-trust-gateway_description'
        id:
          $ref: '#/components/schemas/zero-trust-gateway_schemas-uuid'
        name:
          $ref: '#/components/schemas/zero-trust-gateway_name'
        type:
          $ref: '#/components/schemas/zero-trust-gateway_schemas-type'
        updated_at:
          $ref: '#/components/schemas/zero-trust-gateway_timestamp'
      type: object
  securitySchemes:
    api_email:
      in: header
      name: X-Auth-Email
      type: apiKey
    api_key:
      in: header
      name: X-Auth-Key
      type: apiKey
    api_token:
      scheme: bearer
      type: http
    user_service_key:
      in: header
      name: X-Auth-User-Service-Key
      type: apiKey
