openapi: 3.0.0
info:
  version: 2015-07-09
  x-release: v4
  title: APIs.io Engineering Platform Amazon API Gateway 2014 11 13 Load Balancer Healthcheck Events API
  description: <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: apigateway
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/apigateway-2015-07-09.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: https://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: http://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
- url: https://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: Load Balancer Healthcheck Events
paths:
  /user/load_balancing_analytics/events:
    get:
      description: List origin health changes.
      operationId: load-balancer-healthcheck-events-list-healthcheck-events
      parameters:
      - in: query
        name: until
        schema:
          $ref: '#/components/schemas/load-balancing_until'
      - in: query
        name: pool_name
        schema:
          $ref: '#/components/schemas/load-balancing_pool_name'
      - in: query
        name: origin_healthy
        schema:
          $ref: '#/components/schemas/load-balancing_origin_healthy'
      - in: query
        name: pool_id
        schema:
          $ref: '#/components/schemas/load-balancing_schemas-identifier'
      - in: query
        name: since
        schema:
          description: Start date and time of requesting data period in the ISO8601 format.
          example: '2016-11-11T12:00:00Z'
          format: date-time
          type: string
      - in: query
        name: origin_name
        schema:
          description: The name for the origin to filter.
          example: primary-dc-1
          type: string
      - in: query
        name: pool_healthy
        schema:
          default: true
          description: If true, filter events where the pool status is healthy. If false, filter events where the pool status is unhealthy.
          example: true
          type: boolean
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/load-balancing_components-schemas-response_collection'
                - $ref: '#/components/schemas/load-balancing_api-response-common-failure'
          description: List Healthcheck Events response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/load-balancing_components-schemas-response_collection'
          description: List Healthcheck Events response
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform List Healthcheck Events
      tags:
      - Load Balancer Healthcheck Events
      x-api-token-group:
      - 'Load Balancing: Monitors and Pools Read'
components:
  schemas:
    load-balancing_schemas-name:
      description: A human-identifiable name for the origin.
      example: app-server-1
      type: string
    load-balancing_origin_healthy:
      default: true
      description: If true, filter events where the origin status is healthy. If false, filter events where the origin status is unhealthy.
      example: true
      type: boolean
    load-balancing_origin-failure-reason:
      description: Failure reason for un-healthy origin health check.
      example: No failures
      type: string
    load-balancing_origin-changed:
      description: Whether the origin has changed health status.
      example: true
      type: boolean
    load-balancing_pool_name:
      description: The name for the pool to filter.
      example: primary-dc
      type: string
    load-balancing_address:
      description: The IP address (IPv4 or IPv6) of the origin, or its publicly addressable hostname. Hostnames entered here should resolve directly to the origin, and not be a hostname proxied by Cloudflare. To set an internal/reserved address, virtual_network_id must also be set.
      example: 0.0.0.0
      type: string
    load-balancing_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/load-balancing_messages'
        messages:
          $ref: '#/components/schemas/load-balancing_messages'
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    load-balancing_result_info:
      properties:
        count:
          description: Total number of results for the requested service
          example: 1
          type: number
        page:
          description: Current page within paginated list of results
          example: 1
          type: number
        per_page:
          description: Number of results per page of results
          example: 20
          type: number
        total_count:
          description: Total results available without any search parameters
          example: 2000
          type: number
      type: object
    load-balancing_origin-analytics:
      properties:
        address:
          $ref: '#/components/schemas/load-balancing_address'
        changed:
          $ref: '#/components/schemas/load-balancing_origin-changed'
        enabled:
          $ref: '#/components/schemas/load-balancing_schemas-enabled'
        failure_reason:
          $ref: '#/components/schemas/load-balancing_origin-failure-reason'
        healthy:
          $ref: '#/components/schemas/load-balancing_origin-healthy'
        ip:
          $ref: '#/components/schemas/load-balancing_origin-ip'
        name:
          $ref: '#/components/schemas/load-balancing_schemas-name'
      type: object
    load-balancing_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    load-balancing_components-schemas-response_collection:
      allOf:
      - $ref: '#/components/schemas/load-balancing_api-response-collection'
      - properties:
          result:
            items:
              $ref: '#/components/schemas/load-balancing_analytics'
            type: array
    load-balancing_schemas-identifier:
      example: 17b5962d775c646f3f9725cbc7a53df4
      type: string
    load-balancing_api-response-collection:
      allOf:
      - $ref: '#/components/schemas/load-balancing_api-response-common'
      - properties:
          result_info:
            $ref: '#/components/schemas/load-balancing_result_info'
      type: object
    load-balancing_until:
      description: End date and time of requesting data period in the ISO8601 format.
      example: '2016-11-11T13:00:00Z'
      format: date-time
      type: string
    load-balancing_analytics:
      properties:
        id:
          default: 1
          type: integer
        origins:
          example:
          - address: 198.51.100.4
            changed: true
            enabled: true
            failure_reason: No failures
            healthy: true
            ip: 198.51.100.4
            name: some-origin
          items:
            $ref: '#/components/schemas/load-balancing_origin-analytics'
          type: array
        pool:
          example:
            changed: true
            healthy: true
            id: 74bc6a8b9b0dda3d651707a2928bad0c
            minimum_origins: 1
            name: some-pool
          type: object
        timestamp:
          example: '2014-01-01T05:20:00.12345Z'
          format: date-time
          type: string
      type: object
    load-balancing_schemas-enabled:
      default: true
      description: Whether to enable (the default) this origin within the pool. Disabled origins will not receive traffic and are excluded from health checks. The origin will only be disabled for the current pool.
      example: true
      type: boolean
    load-balancing_origin-healthy:
      description: Whether the origin is reported as healthy.
      example: true
      type: boolean
    load-balancing_origin-ip:
      description: The IP address (IPv4 or IPv6) of the origin.
      example: 198.51.100.4
      type: string
    load-balancing_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/load-balancing_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/load-balancing_messages'
          example: []
        result:
          enum:
          - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/apigateway/
x-hasEquivalentPaths: true
