openapi: 3.2.0
info:
  description: 'To get started using Cloudflare''s products and services via the API, refer to [how to interact with Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/), which covers using tools like [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform) and the [official SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows who is making requests and what permissions you have. Create an API token to grant access to the API to perform actions.


    To create an API token, from the Cloudflare dashboard, go to My Profile > API Tokens and select Create Token. For more information on how to create and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).'
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: APIs.io Engineering Platform Cloudflare Cloudflare Images Keys API
  version: 4.0.0
tags:
- name: Cloudflare Images Keys
paths:
  /accounts/{account_id}/images/v1/keys:
    get:
      description: Lists your signing keys. These can be found on your Cloudflare Images dashboard.
      operationId: cloudflare-images-keys-list-signing-keys
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/images_account_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/images_image_key_response_collection'
                - $ref: '#/components/schemas/images_api-response-common-failure'
          description: List Signing Keys response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/images_image_key_response_collection'
          description: List Signing Keys response
      security:
      - api_token: []
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform List Signing Keys
      tags:
      - Cloudflare Images Keys
      x-api-token-group:
      - Images Read
      - Images Write
  /accounts/{account_id}/images/v1/keys/{signing_key_name}:
    delete:
      description: 'Delete signing key with specified name. Returns all keys available.

        When last key is removed, a new default signing key will be generated.

        '
      operationId: cloudflare-images-keys-delete-signing-key
      parameters:
      - in: path
        name: signing_key_name
        required: true
        schema:
          $ref: '#/components/schemas/images_signing_key_identifier'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/images_account_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/images_image_key_response_collection'
                - $ref: '#/components/schemas/images_api-response-common-failure'
          description: Delete Signing Key response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/images_image_key_response_collection'
          description: Delete Signing Key response
      security:
      - api_token: []
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Delete Signing Key
      tags:
      - Cloudflare Images Keys
    put:
      description: Create a new signing key with specified name. Returns all keys available.
      operationId: cloudflare-images-keys-add-signing-key
      parameters:
      - in: path
        name: signing_key_name
        required: true
        schema:
          $ref: '#/components/schemas/images_signing_key_identifier'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/images_account_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/images_image_key_response_collection'
                - $ref: '#/components/schemas/images_api-response-common-failure'
          description: Add Signing Key response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/images_image_key_response_collection'
          description: Add Signing Key response
      security:
      - api_token: []
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Create a new Signing Key
      tags:
      - Cloudflare Images Keys
components:
  schemas:
    images_image_key_response_collection:
      allOf:
      - $ref: '#/components/schemas/images_api-response-common'
      - properties:
          result:
            $ref: '#/components/schemas/images_image_keys_response'
    images_image_key_value:
      description: Key value.
      example: Oix0bbNaT8Rge9PuyxUBrjI6zrgnsyJ5=
      readOnly: true
      type: string
    images_image_keys_response:
      properties:
        keys:
          items:
            $ref: '#/components/schemas/images_image_keys'
          type: array
      type: object
    images_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/images_messages'
        messages:
          $ref: '#/components/schemas/images_messages'
        result:
          anyOf:
          - type: object
          - items: {}
            type: array
          - type: string
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    images_image_key_name:
      description: Key name.
      example: default
      readOnly: true
      type: string
    images_image_keys:
      properties:
        name:
          $ref: '#/components/schemas/images_image_key_name'
        value:
          $ref: '#/components/schemas/images_image_key_value'
      type: object
    images_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    images_account_identifier:
      description: Account identifier tag.
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      readOnly: true
      type: string
    images_signing_key_identifier:
      example: someKey
      maxLength: 20
      pattern: ^[a-zA-Z0-9]$
      type: string
    images_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/images_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/images_messages'
          example: []
        result:
          enum:
          - null
          type:
          - object
          - 'null'
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
  securitySchemes:
    api_email:
      in: header
      name: X-Auth-Email
      type: apiKey
    api_key:
      in: header
      name: X-Auth-Key
      type: apiKey
    api_token:
      scheme: bearer
      type: http
    user_service_key:
      in: header
      name: X-Auth-User-Service-Key
      type: apiKey
