openapi: 3.2.0
info:
  description: 'To get started using Cloudflare''s products and services via the API, refer to [how to interact with Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/), which covers using tools like [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform) and the [official SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows who is making requests and what permissions you have. Create an API token to grant access to the API to perform actions.


    To create an API token, from the Cloudflare dashboard, go to My Profile > API Tokens and select Create Token. For more information on how to create and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).'
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: APIs.io Engineering Platform Cloudflare Accounts API
  version: 4.0.0
tags:
- name: Accounts
paths:
  /accounts:
    get:
      description: List all accounts you have ownership or verified access to.
      operationId: accounts-list-accounts
      parameters:
      - in: query
        name: name
        schema:
          description: Name of the account.
          example: example.com
          readOnly: true
          type: string
      - in: query
        name: page
        schema:
          default: 1
          description: Page number of paginated results.
          minimum: 1
          type: number
      - in: query
        name: per_page
        schema:
          default: 20
          description: Maximum number of results per page.
          maximum: 50
          minimum: 5
          type: number
      - in: query
        name: direction
        schema:
          description: Direction to order results.
          enum:
          - asc
          - desc
          example: desc
          type: string
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/iam_api-response-common-failure'
          description: List Accounts response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/iam_response_collection_accounts'
          description: List Accounts response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform List Accounts
      tags:
      - Accounts
      x-cfPermissionsRequired:
        enum:
        - '#organization:read'
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
    post:
      description: Create an account (only available for tenant admins at this time)
      operationId: account-creation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/iam_create-account'
        description: Parameters for account creation
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/iam_api-response-common-failure'
          description: Account Creation Failure Response
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/iam_response_single_account'
          description: Account Creation Success Response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Create an account
      tags:
      - Accounts
      x-cfPermissionsRequired:
        enum:
        - '#organization:edit'
      x-cfPlanAvailability:
        business: false
        enterprise: false
        free: false
        pro: false
  /accounts/{account_id}:
    delete:
      description: Delete a specific account (only available for tenant admins at this time). This is a permanent operation that will delete any zones or other resources under the account
      operationId: account-deletion
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          description: The account ID of the account to be deleted
          type: string
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/iam_api-response-common-failure'
          description: Account Deletion Failure Response
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/iam_api-response-single-id'
          description: Account Deletion Success Response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Delete a specific account
      tags:
      - Accounts
      x-cfPermissionsRequired:
        enum:
        - '#organization:edit'
      x-cfPlanAvailability:
        business: false
        enterprise: false
        free: false
        pro: false
    get:
      description: Get information about a specific account that you are a member of.
      operationId: accounts-account-details
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/iam_account_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/iam_api-response-common-failure'
          description: Account Details response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/iam_response_single_account'
          description: Account Details response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Account Details
      tags:
      - Accounts
      x-cfPermissionsRequired:
        enum:
        - '#organization:read'
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
    put:
      description: Update an existing account.
      operationId: accounts-update-account
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/iam_account_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/iam_components-schemas-account'
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/iam_api-response-common-failure'
          description: Update Account response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/iam_response_single_account'
          description: Update Account response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Update Account
      tags:
      - Accounts
      x-cfPermissionsRequired:
        enum:
        - '#organization:edit'
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
components:
  schemas:
    iam_api-response-collection:
      allOf:
      - $ref: '#/components/schemas/iam_api-response-common'
      - properties:
          result:
            items: {}
            type:
            - array
            - 'null'
          result_info:
            $ref: '#/components/schemas/iam_result_info'
      type: object
    iam_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/iam_messages'
        messages:
          $ref: '#/components/schemas/iam_messages'
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      type: object
    iam_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    iam_result_info:
      properties:
        count:
          description: Total number of results for the requested service
          example: 1
          type: number
        page:
          description: Current page within paginated list of results
          example: 1
          type: number
        per_page:
          description: Number of results per page of results
          example: 20
          type: number
        total_count:
          description: Total results available without any search parameters
          example: 2000
          type: number
      type: object
    iam_account_identifier:
      description: Account identifier tag.
      example: eb78d65290b24279ba6f44721b3ea3c4
      maxLength: 32
      readOnly: true
      type: string
    iam_components-schemas-account:
      allOf:
      - $ref: '#/components/schemas/iam_account'
    iam_common_components-schemas-identifier:
      description: Identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      readOnly: true
      type: string
    iam_api-response-single:
      allOf:
      - $ref: '#/components/schemas/iam_api-response-common'
      type: object
    iam_api-response-single-id:
      allOf:
      - $ref: '#/components/schemas/iam_api-response-common'
      - properties:
          result:
            properties:
              id:
                $ref: '#/components/schemas/iam_common_components-schemas-identifier'
            required:
            - id
            type:
            - object
            - 'null'
      type: object
    iam_response_collection_accounts:
      allOf:
      - $ref: '#/components/schemas/iam_api-response-collection'
      - properties:
          result:
            items:
              $ref: '#/components/schemas/iam_account'
            type: array
        type: object
      title: Response with a list of accounts
    iam_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/iam_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/iam_messages'
          example: []
        result:
          enum:
          - null
          type:
          - object
          - 'null'
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    iam_response_single_account:
      allOf:
      - $ref: '#/components/schemas/iam_api-response-single'
      - properties:
          result:
            $ref: '#/components/schemas/iam_account'
        type: object
      title: Response with a single account
    iam_create-account:
      properties:
        name:
          description: Account name
          type: string
        type:
          description: the type of account being created. For self-serve customers, use standard. for enterprise customers, use enterprise.
          enum:
          - standard
          - enterprise
          example: standard
        unit:
          description: information related to the tenant unit, and optionally, an id of the unit to create the account on. see https://developers.cloudflare.com/tenant/how-to/manage-accounts/
          properties:
            id:
              description: Tenant unit ID
              example: f267e341f3dd4697bd3b9f71dd96247f
              type: string
          type: object
      required:
      - name
      - type
      title: Create account
      type: object
    iam_account:
      properties:
        created_on:
          description: Timestamp for the creation of the account
          example: '2014-03-01T12:21:02.0000Z'
          format: date-time
          readOnly: true
          type: string
        id:
          $ref: '#/components/schemas/iam_common_components-schemas-identifier'
        name:
          description: Account name
          example: Demo Account
          maxLength: 100
          type: string
        settings:
          description: Account settings
          properties:
            abuse_contact_email:
              description: Sets an abuse contact email to notify for abuse reports.
              type: string
            default_nameservers:
              default: cloudflare.standard
              description: 'Specifies the default nameservers to be used for new zones added to this account.


                - `cloudflare.standard` for Cloudflare-branded nameservers

                - `custom.account` for account custom nameservers

                - `custom.tenant` for tenant custom nameservers


                See [Custom Nameservers](https://developers.cloudflare.com/dns/additional-options/custom-nameservers/)

                for more information.'
              enum:
              - cloudflare.standard
              - custom.account
              - custom.tenant
              type: string
            enforce_twofactor:
              default: false
              description: 'Indicates whether membership in this account requires that

                Two-Factor Authentication is enabled'
              type: boolean
            use_account_custom_ns_by_default:
              default: false
              deprecated: true
              description: 'Indicates whether new zones should use the account-level custom

                nameservers by default.


                Deprecated in favor of `default_nameservers`.'
              type: boolean
          type: object
      required:
      - id
      - name
      type: object
  securitySchemes:
    api_email:
      in: header
      name: X-Auth-Email
      type: apiKey
    api_key:
      in: header
      name: X-Auth-Key
      type: apiKey
    api_token:
      scheme: bearer
      type: http
    user_service_key:
      in: header
      name: X-Auth-User-Service-Key
      type: apiKey
