openapi: 3.2.0
info:
  title: Postman Global Variables API
  description: The Postman API enables you to programmatically access data stored in your Postman account.
  version: '1.0'
  termsOfService: https://www.postman.com/legal/terms/
  contact:
    name: Postman Support
    email: help@postman.com
    url: https://www.postman.com/community/
servers:
- url: https://api.getpostman.com
- url: https://api.eu.postman.com
security:
- PostmanApiKey: []
- scimApiKey: []
tags:
- name: Global Variables
  description: The **Global Variables** endpoints enable you to manage global variables. Global variables are available throughout a workspace and have the broadest scope in Postman.
paths:
  /workspaces/{workspaceId}/global-variables:
    parameters:
    - $ref: '#/components/parameters/workspaceId'
    get:
      summary: APIs.io Engineering Platform Get global variables
      description: Gets a workspace's global variables.
      operationId: getWorkspaceGlobalVariables
      tags:
      - Global Variables
      responses:
        '200':
          $ref: '#/components/responses/getWorkspaceGlobalVariables'
        '500':
          $ref: '#/components/responses/globalVariables500Error'
    put:
      summary: APIs.io Engineering Platform Update global variables
      description: Updates and replaces a workspace's global variables. This endpoint replaces all existing global variables with the variables you pass in the request body.
      operationId: updateWorkspaceGlobalVariables
      tags:
      - Global Variables
      requestBody:
        $ref: '#/components/requestBodies/updateWorkspaceGlobalVariables'
      responses:
        '200':
          $ref: '#/components/responses/updateWorkspaceGlobalVariables'
        '500':
          $ref: '#/components/responses/globalVariables500Error'
components:
  requestBodies:
    updateWorkspaceGlobalVariables:
      content:
        application/json:
          schema:
            type: object
            properties:
              values:
                type: array
                description: A list of the workspace's global variables.
                items:
                  $ref: '#/components/schemas/globalVariable'
          example:
            values:
            - key: api-key
              type: secret
              value: PMAK-XXXX
              enabled: true
            - key: collection_uid
              type: default
              value: 12345678-12ece9e1-2abf-4edc-8e34-de66e74114d2
              enabled: true
  responses:
    getWorkspaceGlobalVariables:
      description: Successful Response
      content:
        application/json:
          schema:
            type: object
            description: Information about the workspace's global variables.
            properties:
              values:
                type: array
                description: A list of the workspace's global variables.
                items:
                  $ref: '#/components/schemas/globalVariable'
          example:
            values:
            - key: api-key
              type: secret
              value: PMAK-XXXX
              enabled: true
            - key: collection_uid
              type: default
              value: 12345678-12ece9e1-2abf-4edc-8e34-de66e74114d2
              enabled: true
    updateWorkspaceGlobalVariables:
      description: Successful Response
      content:
        application/json:
          schema:
            type: object
            description: Information about the workspace's updated global variables.
            properties:
              values:
                type: array
                description: A list of the workspace's global variables.
                items:
                  $ref: '#/components/schemas/globalVariable'
          example:
            values:
            - key: api-key
              type: secret
              value: PMAK-XXXX
              enabled: true
            - key: collection_uid
              type: default
              value: 12345678-12ece9e1-2abf-4edc-8e34-de66e74114d2
              enabled: true
    globalVariables500Error:
      description: Internal Server Error
      content:
        application/problem+json:
          schema:
            type: object
            properties:
              type:
                type: string
                format: uri-reference
                description: The [URI reference](https://www.rfc-editor.org/rfc/rfc3986) that identifies the type of problem.
                example: https://api.postman.com/problems/servererror
              title:
                type: string
                description: A short summary of the problem.
                example: Internal server error
              detail:
                type: string
                description: Information about the error.
                example: Details about the error
          example:
            type: https://api.postman.com/problems/servererror
            title: Internal server error
            detail: Details about the error
  parameters:
    workspaceId:
      name: workspaceId
      in: path
      required: true
      description: The workspace's ID.
      schema:
        $ref: '#/components/schemas/workspaceId'
  schemas:
    globalVariable:
      title: Global Variable
      type: object
      description: Information about the global variable.
      properties:
        key:
          type: string
          description: The variable's name.
          example: variableName
        type:
          type: string
          description: The [type](https://learning.postman.com/docs/sending-requests/variables/#variable-types) of variable.
          enum:
          - default
          - secret
          example: default
        value:
          type: string
          description: The variable's value.
          example: variableValue
        enabled:
          type: boolean
          description: If true, the variable is enabled.
          example: true
    workspaceId:
      type: string
      example: 1f0df51a-8658-4ee8-a2a1-d2567dfa09a9
  securitySchemes:
    PostmanApiKey:
      type: apiKey
      in: header
      name: x-api-key
    scimApiKey:
      type: apiKey
      in: header
      name: Authorization
      description: A valid [SCIM API key](https://learning.postman.com/docs/administration/scim-provisioning/scim-provisioning-overview/#generating-scim-api-key) for calls to SCIM endpoints.
