openapi: 3.2.0
info:
  description: 'To get started using Cloudflare''s products and services via the API, refer to [how to interact with Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/), which covers using tools like [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform) and the [official SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows who is making requests and what permissions you have. Create an API token to grant access to the API to perform actions.


    To create an API token, from the Cloudflare dashboard, go to My Profile > API Tokens and select Create Token. For more information on how to create and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).'
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: APIs.io Engineering Platform Cloudflare Access Authentication Logs API
  version: 4.0.0
tags:
- name: Access Authentication Logs
paths:
  /accounts/{account_id}/access/logs/access_requests:
    get:
      description: Gets a list of Access authentication audit logs for an account.
      operationId: access-authentication-logs-get-access-authentication-logs
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/access_identifier'
      - description: The maximum number of log entries to retrieve.
        example: 25
        in: query
        name: limit
        schema:
          default: 25
          type: integer
      - description: The chronological sorting order for the logs.
        example: desc
        in: query
        name: direction
        schema:
          default: desc
          enum:
          - desc
          - asc
      - description: The earliest event timestamp to query.
        in: query
        name: since
        schema:
          example: '2020-07-01T05:20:00Z'
          format: date-time
          type: string
      - description: The latest event timestamp to query.
        in: query
        name: until
        schema:
          example: '2020-10-01T05:20:00Z'
          format: date-time
          type: string
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_api-response-common-failure'
          description: Get Access authentication logs response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_access-requests_components-schemas-response_collection'
          description: Get Access authentication logs response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Get Access authentication logs
      tags:
      - Access Authentication Logs
      x-api-token-group:
      - 'Access: Audit Logs Read'
components:
  schemas:
    access_app_domain:
      description: The URL of the Access application.
      example: test.example.com/admin
      type: string
    access_app_uid:
      description: The unique identifier for the Access application.
      example: df7e2w5f-02b7-4d9d-af26-8d1988fca630
      type: string
    access_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    access_connection:
      description: The IdP used to authenticate.
      example: saml
      type: string
    access_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/access_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/access_messages'
          example: []
        result:
          enum:
          - null
          type:
          - object
          - 'null'
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    access_access-requests:
      properties:
        action:
          $ref: '#/components/schemas/access_action'
        allowed:
          $ref: '#/components/schemas/access_allowed'
        app_domain:
          $ref: '#/components/schemas/access_app_domain'
        app_uid:
          $ref: '#/components/schemas/access_app_uid'
        connection:
          $ref: '#/components/schemas/access_connection'
        created_at:
          $ref: '#/components/schemas/access_timestamp'
        ip_address:
          $ref: '#/components/schemas/access_ip'
        ray_id:
          $ref: '#/components/schemas/access_ray_id'
        user_email:
          $ref: '#/components/schemas/access_schemas-email'
      type: object
    access_ip:
      description: The IP address of the authenticating user.
      example: 198.41.129.166
      type: string
    access_access-requests_components-schemas-response_collection:
      allOf:
      - $ref: '#/components/schemas/access_api-response-common'
      - properties:
          result:
            items:
              $ref: '#/components/schemas/access_access-requests'
            type: array
    access_schemas-email:
      description: The email address of the authenticating user.
      example: user@example.com
      format: email
      type: string
    access_ray_id:
      description: The unique identifier for the request to Cloudflare.
      example: 187d944c61940c77
      maxLength: 16
      type: string
    access_action:
      description: The event that occurred, such as a login attempt.
      example: login
      type: string
    access_timestamp:
      example: '2014-01-01T05:20:00.12345Z'
      format: date-time
      type: string
    access_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/access_messages'
        messages:
          $ref: '#/components/schemas/access_messages'
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      type: object
    access_allowed:
      default: false
      description: The result of the authentication event.
      type: boolean
    access_identifier:
      description: Identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      type: string
  securitySchemes:
    api_email:
      in: header
      name: X-Auth-Email
      type: apiKey
    api_key:
      in: header
      name: X-Auth-Key
      type: apiKey
    api_token:
      scheme: bearer
      type: http
    user_service_key:
      in: header
      name: X-Auth-User-Service-Key
      type: apiKey
