openapi: 3.2.0
info:
  description: 'To get started using Cloudflare''s products and services via the API, refer to [how to interact with Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/), which covers using tools like [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform) and the [official SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows who is making requests and what permissions you have. Create an API token to grant access to the API to perform actions.


    To create an API token, from the Cloudflare dashboard, go to My Profile > API Tokens and select Create Token. For more information on how to create and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).'
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: APIs.io Engineering Platform Cloudflare Magic Connectors API
  version: 4.0.0
tags:
- name: Magic Connectors
paths:
  /accounts/{account_id}/magic/connectors:
    get:
      operationId: mconn-connector-list
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/mconn_account_id'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mconn_customer_connector_list_response'
          description: OK
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mconn_bad_response'
          description: Bad Request
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mconn_bad_response'
          description: Unauthorized
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mconn_bad_response'
          description: Forbidden
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mconn_bad_response'
          description: Internal Server Error
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform List Connectors
      tags:
      - Magic Connectors
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
  /accounts/{account_id}/magic/connectors/{connector_id}:
    get:
      operationId: mconn-connector-fetch
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/mconn_account_id'
      - in: path
        name: connector_id
        required: true
        schema:
          $ref: '#/components/schemas/mconn_uuid'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mconn_customer_connector_fetch_response'
          description: OK
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mconn_bad_response'
          description: Bad Request
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mconn_bad_response'
          description: Unauthorized
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mconn_bad_response'
          description: Forbidden
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mconn_bad_response'
          description: Internal Server Error
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Fetch Connector
      tags:
      - Magic Connectors
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    patch:
      operationId: mconn-connector-update
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/mconn_account_id'
      - in: path
        name: connector_id
        required: true
        schema:
          $ref: '#/components/schemas/mconn_uuid'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/mconn_customer_connector_update_request'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mconn_customer_connector_update_response'
          description: OK
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mconn_bad_response'
          description: Bad Request
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mconn_bad_response'
          description: Unauthorized
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mconn_bad_response'
          description: Forbidden
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mconn_bad_response'
          description: Internal Server Error
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Update Connector
      tags:
      - Magic Connectors
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    put:
      operationId: mconn-connector-replace
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/mconn_account_id'
      - in: path
        name: connector_id
        required: true
        schema:
          $ref: '#/components/schemas/mconn_uuid'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/mconn_customer_connector_update_request'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mconn_customer_connector_update_response'
          description: OK
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mconn_bad_response'
          description: Bad Request
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mconn_bad_response'
          description: Unauthorized
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mconn_bad_response'
          description: Forbidden
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mconn_bad_response'
          description: Internal Server Error
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Replace Connector
      tags:
      - Magic Connectors
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
components:
  schemas:
    mconn_bad_response:
      allOf:
      - $ref: '#/components/schemas/mconn_response'
      - properties:
          errors:
            items:
              $ref: '#/components/schemas/mconn_coded_message'
            minLength: 1
            type: array
          result:
            $ref: '#/components/schemas/mconn_none'
    mconn_customer_connector_fetch_response:
      allOf:
      - $ref: '#/components/schemas/mconn_good_response'
      - properties:
          result:
            $ref: '#/components/schemas/mconn_customer_connector'
    mconn_good_response:
      allOf:
      - $ref: '#/components/schemas/mconn_response'
      - properties:
          errors:
            items:
              $ref: '#/components/schemas/mconn_coded_message'
            maxLength: 0
            type: array
    mconn_customer_device:
      properties:
        id:
          $ref: '#/components/schemas/mconn_uuid'
        serial_number:
          type: string
      required:
      - id
      type: object
    mconn_response:
      properties:
        messages:
          items:
            $ref: '#/components/schemas/mconn_coded_message'
          type: array
        success:
          type: boolean
      required:
      - result
      - success
      - errors
      - messages
      type: object
    mconn_customer_connector_update_response:
      allOf:
      - $ref: '#/components/schemas/mconn_good_response'
      - properties:
          result:
            $ref: '#/components/schemas/mconn_customer_connector'
    mconn_customer_connector_list_response:
      allOf:
      - $ref: '#/components/schemas/mconn_good_response'
      - properties:
          result:
            items:
              $ref: '#/components/schemas/mconn_customer_connector'
            type: array
    mconn_customer_connector:
      properties:
        activated:
          type: boolean
        device:
          $ref: '#/components/schemas/mconn_customer_device'
        id:
          $ref: '#/components/schemas/mconn_uuid'
        interrupt_window_duration_hours:
          type: number
        interrupt_window_hour_of_day:
          type: number
        last_heartbeat:
          type: string
        last_seen_version:
          type: string
        last_updated:
          type: string
        notes:
          type: string
        timezone:
          type: string
      required:
      - id
      - notes
      - activated
      - last_updated
      - timezone
      - interrupt_window_hour_of_day
      - interrupt_window_duration_hours
      type: object
    mconn_coded_message:
      properties:
        code:
          minimum: 1000
          type: integer
        message:
          type: string
      required:
      - code
      - message
      type: object
    mconn_uuid:
      type: string
    mconn_none:
      type:
      - object
      - 'null'
    mconn_account_id:
      description: Account identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      readOnly: true
      type: string
    mconn_customer_connector_update_request:
      $ref: '#/components/schemas/mconn_customer_connector_fields'
    mconn_customer_connector_fields:
      properties:
        activated:
          type: boolean
        interrupt_window_duration_hours:
          type: number
        interrupt_window_hour_of_day:
          type: number
        notes:
          type: string
        timezone:
          type: string
      type: object
  securitySchemes:
    api_email:
      in: header
      name: X-Auth-Email
      type: apiKey
    api_key:
      in: header
      name: X-Auth-Key
      type: apiKey
    api_token:
      scheme: bearer
      type: http
    user_service_key:
      in: header
      name: X-Auth-User-Service-Key
      type: apiKey
