openapi: 3.0.0
info:
  version: 2015-07-09
  x-release: v4
  title: APIs.io Engineering Platform Amazon API Gateway 2014 11 13 Radar Traffic Anomalies API
  description: <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: apigateway
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/apigateway-2015-07-09.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: https://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: http://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
- url: https://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: Radar Traffic Anomalies
paths:
  /radar/traffic_anomalies:
    get:
      description: "Internet traffic anomalies are signals that might point to an outage,\n        These alerts are automatically detected by Radar and then manually verified by our team.\n        This endpoint returns the latest alerts.\n        "
      operationId: radar-get-traffic-anomalies
      parameters:
      - description: Limit the number of objects in the response.
        in: query
        name: limit
        schema:
          description: Limit the number of objects in the response.
          example: 5
          type: integer
      - description: Number of objects to skip before grabbing results.
        in: query
        name: offset
        schema:
          description: Number of objects to skip before grabbing results.
          type: integer
      - description: Shorthand date ranges for the last X days - use when you don't need specific start and end dates.
        in: query
        name: dateRange
        schema:
          description: Shorthand date ranges for the last X days - use when you don't need specific start and end dates.
          example: 7d
          pattern: ^((([1-9]|[1-9][0-9]|[1-2][0-9][0-9]|3[0-5][0-9]|36[0-4])[d](control)?)|(([1-9]|[1-4][0-9]|5[0-2])[w](control)?))$
          type: string
      - description: Start of the date range (inclusive).
        in: query
        name: dateStart
        schema:
          description: Start of the date range (inclusive).
          example: '2023-09-01T11:41:33.782Z'
          format: date-time
          type: string
      - description: End of the date range (inclusive).
        in: query
        name: dateEnd
        schema:
          description: End of the date range (inclusive).
          example: '2023-09-01T11:41:33.782Z'
          format: date-time
          type: string
      - in: query
        name: status
        schema:
          enum:
          - VERIFIED
          - UNVERIFIED
          type: string
      - description: Single ASN as integer.
        in: query
        name: asn
        schema:
          description: Single ASN as integer.
          example: '174'
          type: integer
      - description: Location Alpha2 code.
        in: query
        name: location
        schema:
          description: Location Alpha2 code.
          example: US
          type: string
      - description: Format results are returned in.
        in: query
        name: format
        schema:
          description: Format results are returned in.
          enum:
          - JSON
          - CSV
          example: json
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  result:
                    properties:
                      trafficAnomalies:
                        items:
                          properties:
                            asnDetails:
                              properties:
                                asn:
                                  example: '189'
                                  type: string
                                locations:
                                  properties:
                                    code:
                                      example: US
                                      type: string
                                    name:
                                      example: United States
                                      type: string
                                  required:
                                  - code
                                  - name
                                  type: object
                                name:
                                  example: LUMEN-LEGACY-L3-PARTITION
                                  type: string
                              required:
                              - asn
                              - name
                              type: object
                            endDate:
                              example: '2023-08-03T23:15:00Z'
                              type: string
                            locationDetails:
                              properties:
                                code:
                                  example: US
                                  type: string
                                name:
                                  example: United States
                                  type: string
                              required:
                              - code
                              - name
                              type: object
                            startDate:
                              example: '2023-08-02T23:15:00Z'
                              type: string
                            status:
                              example: UNVERIFIED
                              type: string
                            type:
                              example: LOCATION
                              type: string
                            uuid:
                              example: 55a57f33-8bc0-4984-b4df-fdaff72df39d
                              type: string
                            visibleInDataSources:
                              items:
                                type: string
                              type: array
                          required:
                          - uuid
                          - type
                          - status
                          - startDate
                          type: object
                        type: array
                    required:
                    - trafficAnomalies
                    type: object
                  success:
                    example: true
                    type: boolean
                required:
                - result
                - success
                type: object
          description: List of Internet traffic anomalies
        '400':
          content:
            application/json:
              schema:
                properties:
                  errors:
                    items:
                      properties:
                        message:
                          type: string
                      required:
                      - message
                      type: object
                    type: array
                  result:
                    type: object
                  success:
                    example: false
                    type: boolean
                required:
                - result
                - success
                - errors
                type: object
          description: Bad Request
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Get latest Internet traffic anomalies.
      tags:
      - Radar Traffic Anomalies
      x-cfPermissionsRequired:
        enum:
        - com.cloudflare.api.user.read
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
  /radar/traffic_anomalies/locations:
    get:
      description: "Internet traffic anomalies are signals that might point to an outage,\n        These alerts are automatically detected by Radar and then manually verified by our team.\n        This endpoint returns the sum of alerts grouped by location.\n        "
      operationId: radar-get-traffic-anomalies-top
      parameters:
      - description: Limit the number of objects in the response.
        in: query
        name: limit
        schema:
          description: Limit the number of objects in the response.
          example: 5
          type: integer
      - description: Shorthand date ranges for the last X days - use when you don't need specific start and end dates.
        in: query
        name: dateRange
        schema:
          description: Shorthand date ranges for the last X days - use when you don't need specific start and end dates.
          example: 7d
          pattern: ^((([1-9]|[1-9][0-9]|[1-2][0-9][0-9]|3[0-5][0-9]|36[0-4])[d](control)?)|(([1-9]|[1-4][0-9]|5[0-2])[w](control)?))$
          type: string
      - description: Start of the date range (inclusive).
        in: query
        name: dateStart
        schema:
          description: Start of the date range (inclusive).
          example: '2023-09-01T11:41:33.782Z'
          format: date-time
          type: string
      - description: End of the date range (inclusive).
        in: query
        name: dateEnd
        schema:
          description: End of the date range (inclusive).
          example: '2023-09-01T11:41:33.782Z'
          format: date-time
          type: string
      - in: query
        name: status
        schema:
          enum:
          - VERIFIED
          - UNVERIFIED
          type: string
      - description: Format results are returned in.
        in: query
        name: format
        schema:
          description: Format results are returned in.
          enum:
          - JSON
          - CSV
          example: json
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  result:
                    properties:
                      trafficAnomalies:
                        items:
                          properties:
                            clientCountryAlpha2:
                              example: PT
                              type: string
                            clientCountryName:
                              example: Portugal
                              type: string
                            value:
                              example: '5'
                              type: string
                          required:
                          - clientCountryAlpha2
                          - clientCountryName
                          - value
                          type: object
                        type: array
                    required:
                    - trafficAnomalies
                    type: object
                  success:
                    example: true
                    type: boolean
                required:
                - result
                - success
                type: object
          description: List of locations with number of traffic anomalies
        '400':
          content:
            application/json:
              schema:
                properties:
                  errors:
                    items:
                      properties:
                        message:
                          type: string
                      required:
                      - message
                      type: object
                    type: array
                  result:
                    type: object
                  success:
                    example: false
                    type: boolean
                required:
                - result
                - success
                - errors
                type: object
          description: Bad Request
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Get top locations by total traffic anomalies generated.
      tags:
      - Radar Traffic Anomalies
      x-cfPermissionsRequired:
        enum:
        - com.cloudflare.api.user.read
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
components:
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/apigateway/
x-hasEquivalentPaths: true
