openapi: 3.0.0
info:
  version: 2015-07-09
  x-release: v4
  title: APIs.io Engineering Platform Amazon API Gateway 2014 11 13 Worker Deployments (Deprecated) API
  description: <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: apigateway
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/apigateway-2015-07-09.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: https://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: http://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
- url: https://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: Worker Deployments (Deprecated)
paths:
  /accounts/{account_id}/workers/deployments/by-script/{script_id}:
    get:
      deprecated: true
      operationId: worker-deployments-(-deprecated)-list-deployments
      parameters:
      - in: path
        name: script_id
        required: true
        schema:
          $ref: '#/components/schemas/workers_script_identifier'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/workers_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/workers_deployments-list-response'
                - $ref: '#/components/schemas/workers_api-response-common-failure'
          description: List Deployments response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/workers_deployments-list-response'
          description: List Deployments response
      security:
      - api_token: []
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform List Deployments
      tags:
      - Worker Deployments (Deprecated)
      x-api-token-group:
      - Workers Tail Read
      - Workers Scripts Write
      - Workers Scripts Read
      x-cfDeprecation:
        description: This endpoint and its related APIs are deprecated in favor of the `/accounts/{account_id}/workers/scripts/{script_name}/versions` equivalent APIs.
        display: true
        id: worker_deployments_deprecation
      x-cfPermissionsRequired:
        enum:
        - com.cloudflare.edge.worker.deployment.list
  /accounts/{account_id}/workers/deployments/by-script/{script_id}/detail/{deployment_id}:
    get:
      deprecated: true
      operationId: worker-deployments-(-deprecated)-get-deployment-detail
      parameters:
      - in: path
        name: deployment_id
        required: true
        schema:
          $ref: '#/components/schemas/workers_deployment_identifier'
      - in: path
        name: script_id
        required: true
        schema:
          $ref: '#/components/schemas/workers_script_identifier'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/workers_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/workers_deployments-single-response'
                - $ref: '#/components/schemas/workers_api-response-common-failure'
          description: Get Deployment Detail response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/workers_deployments-single-response'
          description: Get Deployment Detail response
      security:
      - api_token: []
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Get Deployment Detail
      tags:
      - Worker Deployments (Deprecated)
      x-api-token-group:
      - Workers Tail Read
      - Workers Scripts Write
      - Workers Scripts Read
      x-cfDeprecation:
        description: This endpoint and its related APIs are deprecated in favor of the `/accounts/{account_id}/workers/scripts/{script_name}/versions` equivalent APIs.
        display: true
        id: worker_deployments_deprecation
      x-cfPermissionsRequired:
        enum:
        - com.cloudflare.edge.worker.deployment.read
components:
  schemas:
    workers_version-item-short:
      properties:
        id:
          example: 18f97339-c287-4872-9bdd-e2135c07ec12
          readOnly: true
          type: string
        metadata:
          example:
            author_email: user@example.com
            author_id: 408cbcdfd4dda4617efef40b04d168a1
            created_on: '2022-11-08T17:19:29.176266Z'
            modified_on: '2022-11-08T17:19:29.176266Z'
            source: api
          readOnly: true
          type: object
        number:
          example: 1
          readOnly: true
          type: number
      type: object
    workers_identifier:
      description: Identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      type: string
    workers_deployments-list-response:
      allOf:
      - $ref: '#/components/schemas/workers_api-response-common'
      - properties:
          result:
            properties:
              items:
                example:
                - id: bcf48806-b317-4351-9ee7-36e7d557d4de
                  metadata:
                    author_email: user@example.com
                    author_id: 408cbcdfd4dda4617efef40b04d168a1
                    created_on: '2022-11-15T18:25:44.442097Z'
                    modified_on: '2022-11-15T18:25:44.442097Z'
                    source: api
                  number: 2
                - id: 18f97339-c287-4872-9bdd-e2135c07ec12
                  metadata:
                    author_email: user@example.com
                    author_id: 408cbcdfd4dda4617efef40b04d168a1
                    created_on: '2022-11-08T17:30:56.968096Z'
                    modified_on: '2022-11-08T17:30:56.968096Z'
                    source: api
                  number: 1
                items:
                  $ref: '#/components/schemas/workers_version-item-short'
                type: array
              latest:
                example:
                  id: bcf48806-b317-4351-9ee7-36e7d557d4de
                  metadata:
                    author_email: user@example.com
                    author_id: 408cbcdfd4dda4617efef40b04d168a1
                    created_on: '2022-11-15T18:25:44.442097Z'
                    modified_on: '2022-11-15T18:25:44.442097Z'
                    source: api
                  number: 2
                  resources:
                    bindings:
                    - json: example_binding
                      name: JSON_VAR
                      type: json
                    script:
                      etag: 13a3240e8fb414561b0366813b0b8f42b3e6cfa0d9e70e99835dae83d0d8a794
                      handlers:
                      - fetch
                      last_deployed_from: api
                    script_runtime:
                      usage_model: bundled
                type: object
            type: object
    workers_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    workers_script_identifier:
      example: 8ee82b3a2c0f42928b8f14dae4a97121
      maxLength: 32
      readOnly: true
      type: string
    workers_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/workers_messages'
        messages:
          $ref: '#/components/schemas/workers_messages'
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      type: object
    workers_deployment_identifier:
      example: bcf48806-b317-4351-9ee7-36e7d557d4de
      maxLength: 36
      readOnly: true
      type: string
    workers_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/workers_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/workers_messages'
          example: []
        result:
          enum:
          - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    workers_deployments-single-response:
      allOf:
      - $ref: '#/components/schemas/workers_api-response-common'
      - properties:
          result:
            properties:
              id:
                example: 18f97339-c287-4872-9bdd-e2135c07ec12
                type: string
              metadata:
                example:
                  author_email: user@example.com
                  author_id: 408cbcdfd4dda4617efef40b04d168a1
                  created_on: '2022-11-08T17:19:29.176266Z'
                  modified_on: '2022-11-08T17:19:29.176266Z'
                  source: api
                type: object
              number:
                example: 1
                type: number
              resources:
                example:
                  bindings:
                  - json: example_binding
                    name: JSON_VAR
                    type: json
                  script:
                    etag: 13a3240e8fb414561b0366813b0b8f42b3e6cfa0d9e70e99835dae83d0d8a794
                    handlers:
                    - fetch
                    last_deployed_from: api
                  script_runtime:
                    usage_model: bundled
                type: object
            type: object
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/apigateway/
x-hasEquivalentPaths: true
