openapi: 3.0.0
info:
  version: "1.0.0"
  x-release: v4
  title: APIs.io Engineering Platform Amazon API Gateway 2014 11 13 Device Managed Networks API
  description: <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: apigateway
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/apigateway-2015-07-09.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: https://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: http://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
- url: https://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: Device Managed Networks
paths:
  /accounts/{account_id}/devices/networks:
    get:
      description: Fetches a list of managed networks for an account.
      operationId: device-managed-networks-list-device-managed-networks
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/teams-devices_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/teams-devices_components-schemas-response_collection'
                - $ref: '#/components/schemas/teams-devices_api-response-common-failure'
          description: List your device managed networks response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/teams-devices_components-schemas-response_collection'
          description: List your device managed networks response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform List your device managed networks
      tags:
      - Device Managed Networks
      x-api-token-group:
      - Teams Read
      - Teams Write
    post:
      description: Creates a new device managed network.
      operationId: device-managed-networks-create-device-managed-network
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/teams-devices_identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                config:
                  $ref: '#/components/schemas/teams-devices_schemas-config_request'
                name:
                  $ref: '#/components/schemas/teams-devices_device-managed-networks_components-schemas-name'
                type:
                  $ref: '#/components/schemas/teams-devices_components-schemas-type'
              required:
              - name
              - type
              - config
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/teams-devices_components-schemas-single_response'
                - $ref: '#/components/schemas/teams-devices_api-response-common-failure'
          description: Create a device managed networks response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/teams-devices_components-schemas-single_response'
          description: Create a device managed networks response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Create a device managed network
      tags:
      - Device Managed Networks
      x-api-token-group:
      - Teams Write
  /accounts/{account_id}/devices/networks/{network_id}:
    delete:
      description: Deletes a device managed network and fetches a list of the remaining device managed networks for an account.
      operationId: device-managed-networks-delete-device-managed-network
      parameters:
      - in: path
        name: network_id
        required: true
        schema:
          $ref: '#/components/schemas/teams-devices_uuid'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/teams-devices_identifier'
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/teams-devices_components-schemas-response_collection'
                - $ref: '#/components/schemas/teams-devices_api-response-common-failure'
          description: Delete a device managed network response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/teams-devices_components-schemas-response_collection'
          description: Delete a device managed network response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Delete a device managed network
      tags:
      - Device Managed Networks
      x-api-token-group:
      - Teams Write
    get:
      description: Fetches details for a single managed network.
      operationId: device-managed-networks-device-managed-network-details
      parameters:
      - in: path
        name: network_id
        required: true
        schema:
          $ref: '#/components/schemas/teams-devices_uuid'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/teams-devices_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/teams-devices_components-schemas-single_response'
                - $ref: '#/components/schemas/teams-devices_api-response-common-failure'
          description: Get device managed network details response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/teams-devices_components-schemas-single_response'
          description: Get device managed network details response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Get device managed network details
      tags:
      - Device Managed Networks
      x-api-token-group:
      - Teams Read
      - Teams Write
    put:
      description: Updates a configured device managed network.
      operationId: device-managed-networks-update-device-managed-network
      parameters:
      - in: path
        name: network_id
        required: true
        schema:
          $ref: '#/components/schemas/teams-devices_uuid'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/teams-devices_identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                config:
                  $ref: '#/components/schemas/teams-devices_schemas-config_request'
                name:
                  $ref: '#/components/schemas/teams-devices_device-managed-networks_components-schemas-name'
                type:
                  $ref: '#/components/schemas/teams-devices_components-schemas-type'
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/teams-devices_components-schemas-single_response'
                - $ref: '#/components/schemas/teams-devices_api-response-common-failure'
          description: Update a device managed network response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/teams-devices_components-schemas-single_response'
          description: Update a device managed network response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Update a device managed network
      tags:
      - Device Managed Networks
      x-api-token-group:
      - Teams Write
components:
  schemas:
    teams-devices_components-schemas-type:
      description: The type of device managed network.
      enum:
      - tls
      example: tls
      type: string
    teams-devices_device-managed-networks:
      properties:
        config:
          $ref: '#/components/schemas/teams-devices_schemas-config_response'
        name:
          $ref: '#/components/schemas/teams-devices_device-managed-networks_components-schemas-name'
        network_id:
          $ref: '#/components/schemas/teams-devices_uuid'
        type:
          $ref: '#/components/schemas/teams-devices_components-schemas-type'
      type: object
    teams-devices_api-response-single:
      allOf:
      - $ref: '#/components/schemas/teams-devices_api-response-common'
      - properties:
          result:
            anyOf:
            - type: object
            - type: string
            nullable: true
            type: object
      type: object
    teams-devices_device-managed-networks_components-schemas-name:
      description: The name of the device managed network. This name must be unique.
      example: managed-network-1
      type: string
    teams-devices_result_info:
      properties:
        count:
          description: Total number of results for the requested service
          example: 1
          type: number
        page:
          description: Current page within paginated list of results
          example: 1
          type: number
        per_page:
          description: Number of results per page of results
          example: 20
          type: number
        total_count:
          description: Total results available without any search parameters
          example: 2000
          type: number
      type: object
    teams-devices_tls_config_response:
      description: The Managed Network TLS Config Response.
      properties:
        sha256:
          description: The SHA-256 hash of the TLS certificate presented by the host found at tls_sockaddr. If absent, regular certificate verification (trusted roots, valid timestamp, etc) will be used to validate the certificate.
          example: b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c
          type: string
        tls_sockaddr:
          description: A network address of the form "host:port" that the WARP client will use to detect the presence of a TLS host.
          example: foobar:1234
          type: string
      required:
      - tls_sockaddr
      type: object
    teams-devices_components-schemas-response_collection:
      allOf:
      - $ref: '#/components/schemas/teams-devices_api-response-collection'
      - properties:
          result:
            items:
              $ref: '#/components/schemas/teams-devices_device-managed-networks'
            type: array
    teams-devices_schemas-config_response:
      description: The configuration object containing information for the WARP client to detect the managed network.
      example:
        sha256: b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c
        tls_sockaddr: foo.bar:1234
      oneOf:
      - $ref: '#/components/schemas/teams-devices_tls_config_response'
      type: object
    teams-devices_tls_config_request:
      properties:
        sha256:
          description: The SHA-256 hash of the TLS certificate presented by the host found at tls_sockaddr. If absent, regular certificate verification (trusted roots, valid timestamp, etc) will be used to validate the certificate.
          example: b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c
          type: string
        tls_sockaddr:
          description: A network address of the form "host:port" that the WARP client will use to detect the presence of a TLS host.
          example: foobar:1234
          type: string
      required:
      - tls_sockaddr
      type: object
    teams-devices_uuid:
      description: API UUID.
      example: f174e90a-fafe-4643-bbbc-4a0ed4fc8415
      maxLength: 36
      type: string
    teams-devices_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/teams-devices_messages'
        messages:
          $ref: '#/components/schemas/teams-devices_messages'
        result:
          anyOf:
          - type: object
          - items: {}
            type: array
          - type: string
        success:
          description: Whether the API call was successful.
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    teams-devices_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/teams-devices_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/teams-devices_messages'
          example: []
        result:
          enum:
          - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    teams-devices_schemas-config_request:
      description: The configuration object containing information for the WARP client to detect the managed network.
      example:
        sha256: b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c
        tls_sockaddr: foo.bar:1234
      oneOf:
      - $ref: '#/components/schemas/teams-devices_tls_config_request'
      type: object
    teams-devices_identifier:
      example: 699d98642c564d2e855e9661899b7252
    teams-devices_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    teams-devices_components-schemas-single_response:
      allOf:
      - $ref: '#/components/schemas/teams-devices_api-response-single'
      - properties:
          result:
            $ref: '#/components/schemas/teams-devices_device-managed-networks'
    teams-devices_api-response-collection:
      allOf:
      - $ref: '#/components/schemas/teams-devices_api-response-common'
      - properties:
          result:
            items: {}
            nullable: true
            type: array
          result_info:
            $ref: '#/components/schemas/teams-devices_result_info'
      type: object
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/apigateway/
x-hasEquivalentPaths: true
