openapi: 3.2.0
info:
  description: 'To get started using Cloudflare''s products and services via the API, refer to [how to interact with Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/), which covers using tools like [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform) and the [official SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows who is making requests and what permissions you have. Create an API token to grant access to the API to perform actions.


    To create an API token, from the Cloudflare dashboard, go to My Profile > API Tokens and select Create Token. For more information on how to create and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).'
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: APIs.io Engineering Platform Cloudflare Workers AI Text to Image API
  version: 4.0.0
tags:
- name: Workers AI Text to Image
paths:
  /accounts/{account_id}/ai/run/@cf/bytedance/stable-diffusion-xl-lightning:
    post:
      operationId: workers-ai-post-run-cf-bytedance-stable-diffusion-xl-lightning
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          example: 023e105f4ecef8ad9ca31a8372d0c353
          type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                guidance:
                  default: 7.5
                  type: number
                height:
                  maximum: 2048
                  minimum: 256
                  type: integer
                image:
                  items:
                    type: number
                  type: array
                image_b64:
                  type: string
                mask:
                  items:
                    type: number
                  type: array
                negative_prompt:
                  type: string
                num_steps:
                  default: 20
                  maximum: 20
                  type: integer
                prompt:
                  minLength: 1
                  type: string
                seed:
                  type: integer
                strength:
                  default: 1
                  type: number
                width:
                  maximum: 2048
                  minimum: 256
                  type: integer
              required:
              - prompt
              type: object
      responses:
        '200':
          content:
            image/png:
              schema:
                properties:
                  result:
                    format: binary
                    type: string
                  success:
                    default: 'true'
                    type: boolean
                type: object
          description: Successful response
        '400':
          content:
            application/json:
              schema:
                properties:
                  errors:
                    items:
                      properties:
                        code:
                          type: string
                        message:
                          type: string
                      required:
                      - code
                      - message
                      type: object
                    type: array
                  result:
                    type: object
                  success:
                    type: boolean
                required:
                - errors
                - success
                - result
                type: object
          description: Bad request
      security:
      - api_token: []
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Execute @cf/bytedance/stable-diffusion-xl-lightning model.
      tags:
      - Workers AI Text to Image
      x-cfPermissionsRequired:
        enum:
        - com.cloudflare.api.account.ai
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
  /accounts/{account_id}/ai/run/@cf/lykon/dreamshaper-8-lcm:
    post:
      operationId: workers-ai-post-run-cf-lykon-dreamshaper-8-lcm
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          example: 023e105f4ecef8ad9ca31a8372d0c353
          type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                guidance:
                  default: 7.5
                  type: number
                height:
                  maximum: 2048
                  minimum: 256
                  type: integer
                image:
                  items:
                    type: number
                  type: array
                image_b64:
                  type: string
                mask:
                  items:
                    type: number
                  type: array
                negative_prompt:
                  type: string
                num_steps:
                  default: 20
                  maximum: 20
                  type: integer
                prompt:
                  minLength: 1
                  type: string
                seed:
                  type: integer
                strength:
                  default: 1
                  type: number
                width:
                  maximum: 2048
                  minimum: 256
                  type: integer
              required:
              - prompt
              type: object
      responses:
        '200':
          content:
            image/png:
              schema:
                properties:
                  result:
                    format: binary
                    type: string
                  success:
                    default: 'true'
                    type: boolean
                type: object
          description: Successful response
        '400':
          content:
            application/json:
              schema:
                properties:
                  errors:
                    items:
                      properties:
                        code:
                          type: string
                        message:
                          type: string
                      required:
                      - code
                      - message
                      type: object
                    type: array
                  result:
                    type: object
                  success:
                    type: boolean
                required:
                - errors
                - success
                - result
                type: object
          description: Bad request
      security:
      - api_token: []
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Execute @cf/lykon/dreamshaper-8-lcm model.
      tags:
      - Workers AI Text to Image
      x-cfPermissionsRequired:
        enum:
        - com.cloudflare.api.account.ai
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
  /accounts/{account_id}/ai/run/@cf/runwayml/stable-diffusion-v1-5-img2img:
    post:
      operationId: workers-ai-post-run-cf-runwayml-stable-diffusion-v1-5-img2img
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          example: 023e105f4ecef8ad9ca31a8372d0c353
          type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                guidance:
                  default: 7.5
                  type: number
                height:
                  maximum: 2048
                  minimum: 256
                  type: integer
                image:
                  items:
                    type: number
                  type: array
                image_b64:
                  type: string
                mask:
                  items:
                    type: number
                  type: array
                negative_prompt:
                  type: string
                num_steps:
                  default: 20
                  maximum: 20
                  type: integer
                prompt:
                  minLength: 1
                  type: string
                seed:
                  type: integer
                strength:
                  default: 1
                  type: number
                width:
                  maximum: 2048
                  minimum: 256
                  type: integer
              required:
              - prompt
              type: object
      responses:
        '200':
          content:
            image/png:
              schema:
                properties:
                  result:
                    format: binary
                    type: string
                  success:
                    default: 'true'
                    type: boolean
                type: object
          description: Successful response
        '400':
          content:
            application/json:
              schema:
                properties:
                  errors:
                    items:
                      properties:
                        code:
                          type: string
                        message:
                          type: string
                      required:
                      - code
                      - message
                      type: object
                    type: array
                  result:
                    type: object
                  success:
                    type: boolean
                required:
                - errors
                - success
                - result
                type: object
          description: Bad request
      security:
      - api_token: []
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Execute @cf/runwayml/stable-diffusion-v1-5-img2img model.
      tags:
      - Workers AI Text to Image
      x-cfPermissionsRequired:
        enum:
        - com.cloudflare.api.account.ai
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
  /accounts/{account_id}/ai/run/@cf/runwayml/stable-diffusion-v1-5-inpainting:
    post:
      operationId: workers-ai-post-run-cf-runwayml-stable-diffusion-v1-5-inpainting
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          example: 023e105f4ecef8ad9ca31a8372d0c353
          type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                guidance:
                  default: 7.5
                  type: number
                height:
                  maximum: 2048
                  minimum: 256
                  type: integer
                image:
                  items:
                    type: number
                  type: array
                image_b64:
                  type: string
                mask:
                  items:
                    type: number
                  type: array
                negative_prompt:
                  type: string
                num_steps:
                  default: 20
                  maximum: 20
                  type: integer
                prompt:
                  minLength: 1
                  type: string
                seed:
                  type: integer
                strength:
                  default: 1
                  type: number
                width:
                  maximum: 2048
                  minimum: 256
                  type: integer
              required:
              - prompt
              type: object
      responses:
        '200':
          content:
            image/png:
              schema:
                properties:
                  result:
                    format: binary
                    type: string
                  success:
                    default: 'true'
                    type: boolean
                type: object
          description: Successful response
        '400':
          content:
            application/json:
              schema:
                properties:
                  errors:
                    items:
                      properties:
                        code:
                          type: string
                        message:
                          type: string
                      required:
                      - code
                      - message
                      type: object
                    type: array
                  result:
                    type: object
                  success:
                    type: boolean
                required:
                - errors
                - success
                - result
                type: object
          description: Bad request
      security:
      - api_token: []
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Execute @cf/runwayml/stable-diffusion-v1-5-inpainting model.
      tags:
      - Workers AI Text to Image
      x-cfPermissionsRequired:
        enum:
        - com.cloudflare.api.account.ai
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
  /accounts/{account_id}/ai/run/@cf/stabilityai/stable-diffusion-xl-base-1.0:
    post:
      operationId: workers-ai-post-run-cf-stabilityai-stable-diffusion-xl-base-1-0
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          example: 023e105f4ecef8ad9ca31a8372d0c353
          type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                guidance:
                  default: 7.5
                  type: number
                height:
                  maximum: 2048
                  minimum: 256
                  type: integer
                image:
                  items:
                    type: number
                  type: array
                image_b64:
                  type: string
                mask:
                  items:
                    type: number
                  type: array
                negative_prompt:
                  type: string
                num_steps:
                  default: 20
                  maximum: 20
                  type: integer
                prompt:
                  minLength: 1
                  type: string
                seed:
                  type: integer
                strength:
                  default: 1
                  type: number
                width:
                  maximum: 2048
                  minimum: 256
                  type: integer
              required:
              - prompt
              type: object
      responses:
        '200':
          content:
            image/png:
              schema:
                properties:
                  result:
                    format: binary
                    type: string
                  success:
                    default: 'true'
                    type: boolean
                type: object
          description: Successful response
        '400':
          content:
            application/json:
              schema:
                properties:
                  errors:
                    items:
                      properties:
                        code:
                          type: string
                        message:
                          type: string
                      required:
                      - code
                      - message
                      type: object
                    type: array
                  result:
                    type: object
                  success:
                    type: boolean
                required:
                - errors
                - success
                - result
                type: object
          description: Bad request
      security:
      - api_token: []
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Execute @cf/stabilityai/stable-diffusion-xl-base-1.0 model.
      tags:
      - Workers AI Text to Image
      x-cfPermissionsRequired:
        enum:
        - com.cloudflare.api.account.ai
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
components:
  securitySchemes:
    api_email:
      in: header
      name: X-Auth-Email
      type: apiKey
    api_key:
      in: header
      name: X-Auth-Key
      type: apiKey
    api_token:
      scheme: bearer
      type: http
    user_service_key:
      in: header
      name: X-Auth-User-Service-Key
      type: apiKey
