openapi: 3.0.0
info:
  version: "1.0.0"
  x-release: v4
  title: APIs.io Engineering Platform Amazon API Gateway 2014 11 13 Meta API
  description: <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: apigateway
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/apigateway-2015-07-09.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: https://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: http://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
- url: https://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: Meta
  description: Endpoints that give information about the API.
paths:
  /:
    get:
      summary: APIs.io Engineering Platform GitHub API Root
      description: Get Hypermedia links to resources accessible in GitHub's REST API
      tags:
      - Meta
      operationId: meta/root
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/root'
              examples:
                default:
                  $ref: '#/components/examples/root'
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: true
        category: meta
        subcategory: meta
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/enterprise-server@3.9/rest/meta/meta#github-api-root
  /meta:
    get:
      summary: APIs.io Engineering Platform Get GitHub Enterprise Server meta information
      description: ''
      tags:
      - Meta
      operationId: meta/get
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/enterprise-server@3.9/rest/meta/meta#get-apiname-meta-information
      parameters: []
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/api-overview'
              examples:
                default:
                  $ref: '#/components/examples/api-overview'
        '304':
          $ref: '#/components/responses/not_modified'
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: true
        category: meta
        subcategory: meta
  /octocat:
    get:
      summary: APIs.io Engineering Platform Get Octocat
      description: Get the octocat as ASCII art
      tags:
      - Meta
      operationId: meta/get-octocat
      parameters:
      - name: s
        in: query
        description: The words to show in Octocat's speech bubble
        schema:
          type: string
        required: false
      responses:
        '200':
          description: Response
          content:
            application/octocat-stream:
              schema:
                type: string
              examples:
                default:
                  $ref: '#/components/examples/octocat'
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/enterprise-server@3.9/rest/meta/meta#get-octocat
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: true
        category: meta
        subcategory: meta
  /zen:
    get:
      summary: APIs.io Engineering Platform Get the Zen of GitHub
      description: Get a random sentence from the Zen of GitHub
      tags:
      - Meta
      operationId: meta/get-zen
      externalDocs:
        description: API method documentation
        url: https://docs.github.com/enterprise-server@3.9/rest/meta/meta#get-the-zen-of-github
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                type: string
              examples:
                default:
                  summary: Example response
                  value: Responsive is better than fast
      x-github:
        githubCloudOnly: false
        enabledForGitHubApps: true
        category: meta
        subcategory: meta
components:
  examples:
    octocat:
      value: "               MMM.           .MMM\n               MMMMMMMMMMMMMMMMMMM\n               MMMMMMMMMMMMMMMMMMM      ___________________________________\n              MMMMMMMMMMMMMMMMMMMMM    |                                   |\n             MMMMMMMMMMMMMMMMMMMMMMM   | Avoid administrative distraction. |\n            MMMMMMMMMMMMMMMMMMMMMMMM   |_   _______________________________|\n            MMMM::- -:::::::- -::MMMM    |/\n             MM~:~ 00~:::::~ 00~:~MM\n        .. MMMMM::.00:::+:::.00::MMMMM ..\n              .MM::::: ._. :::::MM.\n                 MMMM;:::::;MMMM\n          -MM        MMMMMMM\n          ^  M+     MMMMMMMMM\n              MMMMMMM MM MM MM\n                   MM MM MM MM\n                   MM MM MM MM\n                .~~MM~MM~MM~MM~~.\n             ~~~~MM:~MM~~~MM~:MM~~~~\n            ~~~~~~==~==~~~==~==~~~~~~\n             ~~~~~~==~==~==~==~~~~~~\n                 :~==~==~==~==~~\n"
    root:
      value:
        current_user_url: https://api.github.com/user
        current_user_authorizations_html_url: https://github.com/settings/connections/applications{/client_id}
        authorizations_url: https://api.github.com/authorizations
        code_search_url: https://api.github.com/search/code?q={query}{&page,per_page,sort,order}
        commit_search_url: https://api.github.com/search/commits?q={query}{&page,per_page,sort,order}
        emails_url: https://api.github.com/user/emails
        emojis_url: https://api.github.com/emojis
        events_url: https://api.github.com/events
        feeds_url: https://api.github.com/feeds
        followers_url: https://api.github.com/user/followers
        following_url: https://api.github.com/user/following{/target}
        gists_url: https://api.github.com/gists{/gist_id}
        hub_url: https://api.github.com/hub
        issue_search_url: https://api.github.com/search/issues?q={query}{&page,per_page,sort,order}
        issues_url: https://api.github.com/issues
        keys_url: https://api.github.com/user/keys
        label_search_url: https://api.github.com/search/labels?q={query}&repository_id={repository_id}{&page,per_page}
        notifications_url: https://api.github.com/notifications
        organization_url: https://api.github.com/orgs/{org}
        organization_repositories_url: https://api.github.com/orgs/{org}/repos{?type,page,per_page,sort}
        organization_teams_url: https://api.github.com/orgs/{org}/teams
        public_gists_url: https://api.github.com/gists/public
        rate_limit_url: https://api.github.com/rate_limit
        repository_url: https://api.github.com/repos/{owner}/{repo}
        repository_search_url: https://api.github.com/search/repositories?q={query}{&page,per_page,sort,order}
        current_user_repositories_url: https://api.github.com/user/repos{?type,page,per_page,sort}
        starred_url: https://api.github.com/user/starred{/owner}{/repo}
        starred_gists_url: https://api.github.com/gists/starred
        topic_search_url: https://api.github.com/search/topics?q={query}{&page,per_page}
        user_url: https://api.github.com/users/{user}
        user_organizations_url: https://api.github.com/user/orgs
        user_repositories_url: https://api.github.com/users/{user}/repos{?type,page,per_page,sort}
        user_search_url: https://api.github.com/search/users?q={query}{&page,per_page,sort,order}
    api-overview:
      value:
        verifiable_password_authentication: true
        packages:
        - 192.0.2.1
        actions_macos:
        - 192.0.2.1
        dependabot:
        - 192.0.2.1
        domains:
          website:
          - '*.example.com'
          codespaces:
          - '*.example.com'
          copilot:
          - '*.example.com'
          packages:
          - '*.example.com'
        installed_version: 3.9.0
  schemas:
    api-overview:
      title: Api Overview
      description: Api Overview
      type: object
      properties:
        verifiable_password_authentication:
          type: boolean
          example: true
        packages:
          type: array
          items:
            type: string
          example:
          - 192.0.2.1
        actions_macos:
          type: array
          items:
            type: string
          example:
          - 192.0.2.1
        dependabot:
          type: array
          items:
            type: string
          example:
          - 192.0.2.1
        domains:
          type: object
          properties:
            website:
              type: array
              items:
                type: string
                example:
                - example.com
            codespaces:
              type: array
              items:
                type: string
                example:
                - example.com
            copilot:
              type: array
              items:
                type: string
                example:
                - example.com
            packages:
              type: array
              items:
                type: string
                example:
                - example.com
            actions:
              type: array
              items:
                type: string
                example:
                - example.com
        installed_version:
          type: string
          example: 3.9.0
      required:
      - verifiable_password_authentication
    root:
      type: object
      properties:
        current_user_url:
          type: string
          format: uri-template
        current_user_authorizations_html_url:
          type: string
          format: uri-template
        authorizations_url:
          type: string
          format: uri-template
        code_search_url:
          type: string
          format: uri-template
        commit_search_url:
          type: string
          format: uri-template
        emails_url:
          type: string
          format: uri-template
        emojis_url:
          type: string
          format: uri-template
        events_url:
          type: string
          format: uri-template
        feeds_url:
          type: string
          format: uri-template
        followers_url:
          type: string
          format: uri-template
        following_url:
          type: string
          format: uri-template
        gists_url:
          type: string
          format: uri-template
        hub_url:
          type: string
          format: uri-template
          deprecated: true
        issue_search_url:
          type: string
          format: uri-template
        issues_url:
          type: string
          format: uri-template
        keys_url:
          type: string
          format: uri-template
        label_search_url:
          type: string
          format: uri-template
        notifications_url:
          type: string
          format: uri-template
        organization_url:
          type: string
          format: uri-template
        organization_repositories_url:
          type: string
          format: uri-template
        organization_teams_url:
          type: string
          format: uri-template
        public_gists_url:
          type: string
          format: uri-template
        rate_limit_url:
          type: string
          format: uri-template
        repository_url:
          type: string
          format: uri-template
        repository_search_url:
          type: string
          format: uri-template
        current_user_repositories_url:
          type: string
          format: uri-template
        starred_url:
          type: string
          format: uri-template
        starred_gists_url:
          type: string
          format: uri-template
        topic_search_url:
          type: string
          format: uri-template
        user_url:
          type: string
          format: uri-template
        user_organizations_url:
          type: string
          format: uri-template
        user_repositories_url:
          type: string
          format: uri-template
        user_search_url:
          type: string
          format: uri-template
      required:
      - current_user_url
      - current_user_authorizations_html_url
      - authorizations_url
      - code_search_url
      - commit_search_url
      - emails_url
      - emojis_url
      - events_url
      - feeds_url
      - followers_url
      - following_url
      - gists_url
      - issue_search_url
      - issues_url
      - keys_url
      - label_search_url
      - notifications_url
      - organization_url
      - organization_repositories_url
      - organization_teams_url
      - public_gists_url
      - rate_limit_url
      - repository_url
      - repository_search_url
      - current_user_repositories_url
      - starred_url
      - starred_gists_url
      - user_url
      - user_organizations_url
      - user_repositories_url
      - user_search_url
  responses:
    not_modified:
      description: Not modified
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/apigateway/
x-hasEquivalentPaths: true
