openapi: 3.2.0
info:
  description: 'To get started using Cloudflare''s products and services via the API, refer to [how to interact with Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/), which covers using tools like [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform) and the [official SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows who is making requests and what permissions you have. Create an API token to grant access to the API to perform actions.


    To create an API token, from the Cloudflare dashboard, go to My Profile > API Tokens and select Create Token. For more information on how to create and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).'
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: APIs.io Engineering Platform Cloudflare Sinkhole Config API
  version: 4.0.0
tags:
- name: Sinkhole Config
paths:
  /accounts/{account_id}/intel/sinkholes:
    get:
      operationId: sinkhole-config-get-sinkholes
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/intel-sinkholes_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/intel-sinkholes_get_sinkholes_response'
          description: Successful Response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform List sinkholes owned by this account
      tags:
      - Sinkhole Config
      x-api-token-group:
      - Intel Read
components:
  schemas:
    intel-sinkholes_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    intel-sinkholes_identifier:
      description: Identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      readOnly: true
      type: string
    intel-sinkholes_name:
      description: The name of the sinkhole
      type: string
    intel-sinkholes_id:
      description: The unique identifier for the sinkhole
      type: integer
    intel-sinkholes_sinkhole_item:
      example:
        account_tag: 233f45e61fd1f7e21e1e154ede4q2859
        created_on: '2023-05-12T12:21:56.777653Z'
        description: user specified description 1
        id: 1
        modified_on: '2023-06-18T03:13:34.123321Z'
        name: sinkhole_1
        r2_bucket: my_bucket
        r2_id: <r2_id>
      properties:
        account_tag:
          description: The account tag that owns this sinkhole
          type: string
        created_on:
          description: The date and time when the sinkhole was created
          format: date-time
          type: string
        id:
          $ref: '#/components/schemas/intel-sinkholes_id'
        modified_on:
          description: The date and time when the sinkhole was last modified
          format: date-time
          type: string
        name:
          $ref: '#/components/schemas/intel-sinkholes_name'
        r2_bucket:
          description: The name of the R2 bucket to store results
          type: string
        r2_id:
          description: The id of the R2 instance
          type: string
    intel-sinkholes_get_sinkholes_response:
      allOf:
      - $ref: '#/components/schemas/intel-sinkholes_api-response-common'
      - properties:
          result:
            example:
            - account_tag: 233f45e61fd1f7e21e1e154ede4q2859
              created_on: '2023-05-12T12:21:56.777653Z'
              description: user specified description 1
              id: 1
              modified_on: '2023-06-18T03:13:34.123321Z'
              name: sinkhole_1
              r2_bucket: my_bucket
              r2_id: <r2_id>
            - account_tag: 233f45e61fd1f7e21e1e154ede4q2859
              created_on: '2023-05-21T21:43:52.867525Z'
              description: user specified description 2
              id: 2
              modified_on: '2023-06-28T18:46:18.764425Z'
              name: sinkhole_1
              r2_bucket: my_bucket
              r2_id: <r2_id>
            items:
              $ref: '#/components/schemas/intel-sinkholes_sinkhole_item'
            type: array
    intel-sinkholes_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/intel-sinkholes_messages'
        messages:
          $ref: '#/components/schemas/intel-sinkholes_messages'
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      type: object
  securitySchemes:
    api_email:
      in: header
      name: X-Auth-Email
      type: apiKey
    api_key:
      in: header
      name: X-Auth-Key
      type: apiKey
    api_token:
      scheme: bearer
      type: http
    user_service_key:
      in: header
      name: X-Auth-User-Service-Key
      type: apiKey
