openapi: 3.0.0
info:
  version: "1.0.0"
  x-release: v4
  title: APIs.io Engineering Platform Amazon API Gateway 2014 11 13 Transfer Collection Items API
  description: <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: apigateway
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/apigateway-2015-07-09.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: https://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: http://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
- url: https://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: Transfer Collection Items
  description: The **Transfer Collection Items** endpoints enable you to move collection items between different collections or folders.
paths:
  /collection-folders-transfers:
    post:
      summary: APIs.io Engineering Platform Transfer folders
      description: Copies or moves folders into a collection or folder.
      operationId: transferCollectionFolders
      tags:
      - Transfer Collection Items
      requestBody:
        $ref: '#/components/requestBodies/transferCollectionItems'
      responses:
        '200':
          $ref: '#/components/responses/transferCollectionItems200Error'
        '400':
          $ref: '#/components/responses/transferCollectionItems400Error'
        '500':
          $ref: '#/components/responses/common500Error'
  /collection-requests-transfers:
    post:
      summary: APIs.io Engineering Platform Transfer requests
      description: Copies or moves requests into a collection or folder.
      operationId: transferCollectionRequests
      tags:
      - Transfer Collection Items
      requestBody:
        $ref: '#/components/requestBodies/transferCollectionItems'
      responses:
        '200':
          $ref: '#/components/responses/transferCollectionItems200Error'
        '400':
          $ref: '#/components/responses/transferCollectionItems400Error'
        '500':
          $ref: '#/components/responses/common500Error'
  /collection-responses-transfers:
    post:
      summary: APIs.io Engineering Platform Transfer responses
      description: Copies or moves responses into a request.
      operationId: transferCollectionResponses
      tags:
      - Transfer Collection Items
      requestBody:
        $ref: '#/components/requestBodies/transferCollectionItems'
      responses:
        '200':
          $ref: '#/components/responses/transferCollectionItems200Error'
        '400':
          $ref: '#/components/responses/transferCollectionItems400Error'
        '500':
          $ref: '#/components/responses/common500Error'
components:
  responses:
    transferCollectionItems200Error:
      description: Successful Response
      content:
        application/json:
          schema:
            type: object
            properties:
              ids:
                type: array
                description: A list of the transferred collection request, response, or folder UIDs.
                items:
                  type: string
                  format: uid
                  example: 12345678-a9b481c1-3e78-4af7-8db0-dce3f3f3c105
          example:
            ids:
            - 12345678-a9b481c1-3e78-4af7-8db0-dce3f3f3c105
    common500Error:
      description: Internal Server Error
      content:
        application/problem+json:
          schema:
            type: object
            properties:
              type:
                type: string
                format: uri-reference
                description: The [URI reference](https://www.rfc-editor.org/rfc/rfc3986) that identifies the type of problem.
                example: https://api.postman.com/problems/internal-server-error
              title:
                type: string
                description: A short summary of the problem.
                example: Internal Server Error
              detail:
                type: string
                description: Information about the error.
                example: Internal Server Error
          example:
            type: https://api.postman.com/problems/internal-server-error
            title: Internal Server Error
            detail: Internal Server Error
    transferCollectionItems400Error:
      description: Bad Request
      content:
        application/problem+json:
          schema:
            type: object
            properties:
              type:
                type: string
                format: uri-reference
                description: The [URI reference](https://www.rfc-editor.org/rfc/rfc3986) that identifies the type of problem.
                example: https://api.postman.com/problems/bad-request
              title:
                type: string
                description: A short summary of the problem.
                example: Cannot transfer response to target model type folder
              detail:
                type: object
                description: Information about the error.
                additionalProperties: true
          example:
            type: https://api.postman.com/problems/bad-request
            title: Cannot transfer response to target model type folder
            detail: {}
  schemas:
    transferCollectionItems:
      title: Transfer Items Payload
      type: object
      required:
      - ids
      - target
      - location
      - mode
      properties:
        ids:
          type: array
          description: A list of collection request, response, or folder UIDs to transfer.
          items:
            type: string
            format: uid
            example: 12345678-a9b481c1-3e78-4af7-8db0-dce3f3f3c105
        mode:
          type: string
          description: The transfer operation to perform.
          enum:
          - copy
          - move
          example: move
        target:
          type: object
          description: Information about the item transfer's destination location.
          required:
          - model
          - id
          properties:
            id:
              type: string
              format: uid
              example: 12345678-b91270fa-048d-4f5f-a033-8b5523bf053f
              description: The UID of the destination collection, folder, or request.
            model:
              type: string
              description: The collection, folder, or request the items will be transferred to. For response transfers, use the `request` value.
              enum:
              - collection
              - folder
              - request
              example: request
        location:
          type: object
          description: 'The transferred items'' placement in the target destination:

            - For `start` or `end` — Do not include the `model` and `id` values.

            - For `before` or `after` — Include the `model` and `id` properties.

            '
          required:
          - position
          properties:
            id:
              type: string
              nullable: true
              format: uid
              description: For `before` or `after` positions, the model's UID.
              example: 12345678-80812b16-ac27-45b3-b3eb-793f78530d32
            model:
              type: string
              nullable: true
              description: 'For `before` or `after` positions, the type of item (model) that the transferred item will be positioned by. One of: `folder`, `request`, or `response.`

                '
              example: response
            position:
              type: string
              default: end
              description: The transferred item's position within the destination object.
              enum:
              - start
              - end
              - before
              - after
              example: before
  requestBodies:
    transferCollectionItems:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/transferCollectionItems'
          example:
            ids:
            - 12345678-bcb5648b-eecb-4468-ade7-4efb38431bd1
            target:
              model: collection
              id: 12345678-2ba6b9c4-5327-4c46-9bf3-4ec84b74b720
            location:
              position: end
              model: null
              id: null
            mode: copy
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/apigateway/
x-hasEquivalentPaths: true
