openapi: 3.2.0
info:
  title: APIs.io Engineering Platform Postman Transfer Collection Items API
  description: "The Postman API enables you to programmatically access data stored in your Postman account.\n\n> Certain endpoints may be unavailable depending on your region and/or Postman plan.\n\nFor a comprehensive set of examples of requests and responses, see the [**Postman API** collection](https://www.postman.com/postman/workspace/postman-public-workspace/documentation/12959542-c8142d51-e97c-46b6-bd77-52bb66712c9a).\n\n## Getting started\n\nYou can get started with the Postman API by creating a copy of this definition in your workspace.\n\n### EU users\n\nFor users in the EU with [**Enterprise** plans](https://www.postman.com/pricing/), the Postman API uses the `http://api.eu.postman.com` subdomain. This is available in the definition's list of servers. You can change this by selecting the `http://api.eu.postman.com` subdomain in the **Server** dropdown list below.\n\n## About the Postman API\n\n- You must use a valid API Key to send requests to the API endpoints.\n- The API has [rate and usage limits](https://learning.postman.com/docs/developer/postman-api/postman-api-rate-limits/).\n- The API only responds to HTTPS-secured communications. Any requests sent via HTTP return an HTTP `301` redirect to the corresponding HTTPS resources.\n- The API returns requests responses in JSON format. When an API request returns an error, it is sent in the JSON response as an error key.\n- The request method (verb) determines the nature of action you intend to perform. A request made using the `GET` method implies that you want to fetch something from Postman. The `POST` method implies you want to save something new to Postman.\n- For all requests, API calls respond with their corresponding [HTTP status codes](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes). In the Postman client, the status code also provides help text that details the possible meaning of the response code.\n- When calling the API Builder endpoints, you must send an `Accept` header with the `application/vnd.api.v10+json` value.\n\n### IDs and UIDs\n\nAll items in Postman, such as collections, workspaces, and APIs, have IDs and UIDs:\n\n- An ID is the unique ID assigned to a Postman item. For example, `ec29121c-5203-409f-9e84-e83ffc10f226`.\n- The UID is the **full** ID of a Postman item. This value is the item's unique ID concatenated with the user ID. For example, in the `12345678-ec29121c-5203-409f-9e84-e83ffc10f226` UID:\n    - `12345678` is the user's ID.\n    - `ec29121c-5203-409f-9e84-e83ffc10f226` is the item's ID.\n\n### Enum values\n\nAny documented enum values should be considered partial lists and may change over time.\n\n### 403 response for unavailable features\n\nDepending on your region and/or Postman [plan](https://www.postman.com/pricing/), some endpoints will return an HTTP `403 Forbidden` response with the \"This feature isn't available in your region.\" detail.\n\n### 503 response\n\nAn HTTP `503 Service Unavailable` response from our servers indicates there is an unexpected spike in API access traffic. The server is usually operational within the next five minutes.\n\nIf the outage persists or you receive any other form of an HTTP `5XX` error, [contact support](https://support.postman.com/hc/en-us/requests/new/).\n\n## Authentication\n\nPostman uses API keys for authentication. The API key tells the API server that the request came from you. Everything that you have access to in Postman is accessible with your API key. You can [generate](https://learning.postman.com/docs/developer/postman-api/authentication/#generate-a-postman-api-key) a Postman API key in the [**API keys**](https://postman.postman.co/settings/me/api-keys) section of your Postman account settings.\n\nYou must include an API key in each request to the Postman API with the `X-API-Key` request header. In Postman, you can store your API key as a [vault secret](https://learning.postman.com/docs/sending-requests/postman-vault/postman-vault-secrets/) or an [environment variable](https://www.getpostman.com/docs/environments). The Postman API [collection](https://www.getpostman.com/docs/collections) will use it to make API calls.\n\n### SCIM authentication\n\nWhile all other endpoints in this collection require a Postman API key, the SCIM endpoints require a [SCIM API key](https://learning.postman.com/docs/administration/scim-provisioning/scim-provisioning-overview/#generating-scim-api-key).\n\n### Authentication error response\n\nIf an API key is missing, malformed, or invalid, you will receive an HTTP `401 Unauthorized` response code.\n\n## Rate and usage limits\n\nAPI access [rate limits](https://learning.postman.com/docs/developer/postman-api/postman-api-rate-limits/) apply at a per-user basis in unit time. The limit is **300 requests per minute**. Postman Monitors, the GET `/collections`, and the GET `/workspaces` endpoint have a rate limit of **10 calls in 10 seconds**. Depending on your [plan](https://www.postman.com/pricing/), you may also have [usage limits](https://learning.postman.com/docs/billing/resource-usage/).\n\nWhen you reach your rate or usage limits, the API returns the following HTTP `429 Too Many Requests` status code with one of the following error responses:\n\n- `rateLimited` — Rate limits reached. The response returns the time after which you can resume calls to the Postman API.\n- `serviceLimitExhausted` — Postman API service limits reached. You will need to contact your Postman Team Admin for assistance.\n\n## Support\n\nFor help regarding accessing the Postman API, you can:\n\n- Visit [Postman Support](https://support.postman.com/hc/en-us) or our [Community and Support](https://www.postman.com/community/) sites.\n- Reach out to the [Postman community](https://community.postman.com/).\n- Submit a help request to [Postman support](https://support.postman.com/hc/en-us/requests/new/).\n\n## Policies\n\n- [Postman Terms of Service](http://www.postman.com/legal/terms/)\n- [Postman Privacy Policy](https://www.postman.com/legal/privacy-policy/)\n"
  version: '1.0'
  termsOfService: https://www.postman.com/legal/terms/
  contact:
    name: Postman Support
    email: help@postman.com
    url: https://www.postman.com/community/
servers:
- url: https://api.getpostman.com
- url: https://api.eu.postman.com
security:
- PostmanApiKey: []
- scimApiKey: []
tags:
- name: Transfer Collection Items
  description: The **Transfer Collection Items** endpoints enable you to move collection items between different collections or folders.
paths:
  /collection-folders-transfers:
    post:
      summary: APIs.io Engineering Platform Transfer folders
      description: Copies or moves folders into a collection or folder.
      operationId: transferCollectionFolders
      tags:
      - Transfer Collection Items
      requestBody:
        $ref: '#/components/requestBodies/transferCollectionItems'
      responses:
        '200':
          $ref: '#/components/responses/transferCollectionItems200Error'
        '400':
          $ref: '#/components/responses/transferCollectionItems400Error'
        '500':
          $ref: '#/components/responses/common500Error'
  /collection-requests-transfers:
    post:
      summary: APIs.io Engineering Platform Transfer requests
      description: Copies or moves requests into a collection or folder.
      operationId: transferCollectionRequests
      tags:
      - Transfer Collection Items
      requestBody:
        $ref: '#/components/requestBodies/transferCollectionItems'
      responses:
        '200':
          $ref: '#/components/responses/transferCollectionItems200Error'
        '400':
          $ref: '#/components/responses/transferCollectionItems400Error'
        '500':
          $ref: '#/components/responses/common500Error'
  /collection-responses-transfers:
    post:
      summary: APIs.io Engineering Platform Transfer responses
      description: Copies or moves responses into a request.
      operationId: transferCollectionResponses
      tags:
      - Transfer Collection Items
      requestBody:
        $ref: '#/components/requestBodies/transferCollectionItems'
      responses:
        '200':
          $ref: '#/components/responses/transferCollectionItems200Error'
        '400':
          $ref: '#/components/responses/transferCollectionItems400Error'
        '500':
          $ref: '#/components/responses/common500Error'
components:
  responses:
    transferCollectionItems400Error:
      description: Bad Request
      content:
        application/problem+json:
          schema:
            type: object
            properties:
              type:
                type: string
                format: uri-reference
                description: The [URI reference](https://www.rfc-editor.org/rfc/rfc3986) that identifies the type of problem.
                example: https://api.postman.com/problems/bad-request
              title:
                type: string
                description: A short summary of the problem.
                example: Cannot transfer response to target model type folder
              detail:
                type: object
                description: Information about the error.
                additionalProperties: true
          example:
            type: https://api.postman.com/problems/bad-request
            title: Cannot transfer response to target model type folder
            detail: {}
    transferCollectionItems200Error:
      description: Successful Response
      content:
        application/json:
          schema:
            type: object
            properties:
              ids:
                type: array
                description: A list of the transferred collection request, response, or folder UIDs.
                items:
                  type: string
                  format: uid
                  example: 12345678-a9b481c1-3e78-4af7-8db0-dce3f3f3c105
          example:
            ids:
            - 12345678-a9b481c1-3e78-4af7-8db0-dce3f3f3c105
    common500Error:
      description: Internal Server Error
      content:
        application/problem+json:
          schema:
            type: object
            properties:
              type:
                type: string
                format: uri-reference
                description: The [URI reference](https://www.rfc-editor.org/rfc/rfc3986) that identifies the type of problem.
                example: https://api.postman.com/problems/internal-server-error
              title:
                type: string
                description: A short summary of the problem.
                example: Internal Server Error
              detail:
                type: string
                description: Information about the error.
                example: Internal Server Error
          example:
            type: https://api.postman.com/problems/internal-server-error
            title: Internal Server Error
            detail: Internal Server Error
  requestBodies:
    transferCollectionItems:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/transferCollectionItems'
          example:
            ids:
            - 12345678-bcb5648b-eecb-4468-ade7-4efb38431bd1
            target:
              model: collection
              id: 12345678-2ba6b9c4-5327-4c46-9bf3-4ec84b74b720
            location:
              position: end
              model: null
              id: null
            mode: copy
  schemas:
    transferCollectionItems:
      title: Transfer Items Payload
      type: object
      required:
      - ids
      - target
      - location
      - mode
      properties:
        ids:
          type: array
          description: A list of collection request, response, or folder UIDs to transfer.
          items:
            type: string
            format: uid
            example: 12345678-a9b481c1-3e78-4af7-8db0-dce3f3f3c105
        mode:
          type: string
          description: The transfer operation to perform.
          enum:
          - copy
          - move
          example: move
        target:
          type: object
          description: Information about the item transfer's destination location.
          required:
          - model
          - id
          properties:
            id:
              type: string
              format: uid
              example: 12345678-b91270fa-048d-4f5f-a033-8b5523bf053f
              description: The UID of the destination collection, folder, or request.
            model:
              type: string
              description: The collection, folder, or request the items will be transferred to. For response transfers, use the `request` value.
              enum:
              - collection
              - folder
              - request
              example: request
        location:
          type: object
          description: 'The transferred items'' placement in the target destination:

            - For `start` or `end` — Do not include the `model` and `id` values.

            - For `before` or `after` — Include the `model` and `id` properties.

            '
          required:
          - position
          properties:
            id:
              type:
              - string
              - 'null'
              format: uid
              description: For `before` or `after` positions, the model's UID.
              example: 12345678-80812b16-ac27-45b3-b3eb-793f78530d32
            model:
              type:
              - string
              - 'null'
              description: 'For `before` or `after` positions, the type of item (model) that the transferred item will be positioned by. One of: `folder`, `request`, or `response.`

                '
              example: response
            position:
              type: string
              default: end
              description: The transferred item's position within the destination object.
              enum:
              - start
              - end
              - before
              - after
              example: before
  securitySchemes:
    PostmanApiKey:
      type: apiKey
      in: header
      name: x-api-key
    scimApiKey:
      type: apiKey
      in: header
      name: Authorization
      description: A valid [SCIM API key](https://learning.postman.com/docs/administration/scim-provisioning/scim-provisioning-overview/#generating-scim-api-key) for calls to SCIM endpoints.
