openapi: 3.0.0
info:
  version: 2015-07-09
  x-release: v4
  title: APIs.io Engineering Platform Amazon API Gateway 2014 11 13 Passive DNS by IP API
  description: <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: apigateway
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/apigateway-2015-07-09.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: https://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: http://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
- url: https://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: Passive DNS by IP
paths:
  /accounts/{account_id}/intel/dns:
    get:
      operationId: passive-dns-by-ip-get-passive-dns-by-ip
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/intel_identifier'
      - in: query
        name: start_end_params
        schema:
          $ref: '#/components/schemas/intel_start_end_params'
      - in: query
        name: ipv4
        schema:
          type: string
      - in: query
        name: page
        schema:
          description: Requested page within paginated list of results.
          example: 1
          type: number
      - in: query
        name: per_page
        schema:
          description: Maximum number of results requested.
          example: 20
          type: number
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/intel_components-schemas-single_response'
                - $ref: '#/components/schemas/intel_api-response-common-failure'
          description: Get Passive DNS by IP response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/intel_components-schemas-single_response'
          description: Get Passive DNS by IP response
      security:
      - api_token: []
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Get Passive DNS by IP
      tags:
      - Passive DNS by IP
components:
  schemas:
    intel_start_end_params:
      properties:
        end:
          description: Defaults to the current date.
          example: '2021-04-30'
          format: date
          type: string
        start:
          description: Defaults to 30 days before the end parameter value.
          example: '2021-04-01'
          format: date
          type: string
      type: object
    intel_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    intel_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/intel_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/intel_messages'
          example: []
        result:
          enum:
          - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    intel_components-schemas-single_response:
      allOf:
      - $ref: '#/components/schemas/intel_api-response-single'
      - properties:
          result:
            $ref: '#/components/schemas/intel_passive-dns-by-ip'
    intel_api-response-single:
      allOf:
      - $ref: '#/components/schemas/intel_schemas-api-response-common'
      type: object
    intel_identifier:
      description: Identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      readOnly: true
      type: string
    intel_schemas-api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/intel_messages'
        messages:
          $ref: '#/components/schemas/intel_messages'
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      type: object
    intel_passive-dns-by-ip:
      properties:
        count:
          description: Total results returned based on your search parameters.
          example: 1
          type: number
        page:
          description: Current page within paginated list of results.
          example: 1
          type: number
        per_page:
          description: Number of results per page of results.
          example: 20
          type: number
        reverse_records:
          description: Reverse DNS look-ups observed during the time period.
          items:
            properties:
              first_seen:
                description: First seen date of the DNS record during the time period.
                example: '2021-04-01'
                format: date
                type: string
              hostname:
                description: Hostname that the IP was observed resolving to.
              last_seen:
                description: Last seen date of the DNS record during the time period.
                example: '2021-04-30'
                format: date
                type: string
            type: object
          type: array
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/apigateway/
x-hasEquivalentPaths: true
