openapi: 3.0.0
info:
  version: 2015-07-09
  x-release: v4
  title: APIs.io Engineering Platform Amazon API Gateway 2014 11 13 Access Authentication Logs API
  description: <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: apigateway
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/apigateway-2015-07-09.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: https://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: http://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
- url: https://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: Access Authentication Logs
paths:
  /accounts/{account_id}/access/logs/access_requests:
    get:
      description: Gets a list of Access authentication audit logs for an account.
      operationId: access-authentication-logs-get-access-authentication-logs
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/access_identifier'
      - description: The maximum number of log entries to retrieve.
        example: 25
        in: query
        name: limit
        schema:
          default: 25
          type: integer
      - description: The chronological sorting order for the logs.
        example: desc
        in: query
        name: direction
        schema:
          default: desc
          enum:
          - desc
          - asc
      - description: The earliest event timestamp to query.
        in: query
        name: since
        schema:
          example: '2020-07-01T05:20:00Z'
          format: date-time
          type: string
      - description: The latest event timestamp to query.
        in: query
        name: until
        schema:
          example: '2020-10-01T05:20:00Z'
          format: date-time
          type: string
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_api-response-common-failure'
          description: Get Access authentication logs response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/access_access-requests_components-schemas-response_collection'
          description: Get Access authentication logs response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Get Access authentication logs
      tags:
      - Access Authentication Logs
      x-api-token-group:
      - 'Access: Audit Logs Read'
components:
  schemas:
    access_schemas-email:
      description: The email address of the authenticating user.
      example: user@example.com
      format: email
      type: string
    access_connection:
      description: The IdP used to authenticate.
      example: saml
      type: string
    access_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/access_messages'
        messages:
          $ref: '#/components/schemas/access_messages'
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      type: object
    access_ip:
      description: The IP address of the authenticating user.
      example: 198.41.129.166
      type: string
    access_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/access_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/access_messages'
          example: []
        result:
          enum:
          - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    access_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    access_ray_id:
      description: The unique identifier for the request to Cloudflare.
      example: 187d944c61940c77
      maxLength: 16
      type: string
    access_app_domain:
      description: The URL of the Access application.
      example: test.example.com/admin
      type: string
    access_allowed:
      default: false
      description: The result of the authentication event.
      type: boolean
    access_action:
      description: The event that occurred, such as a login attempt.
      example: login
      type: string
    access_app_uid:
      description: The unique identifier for the Access application.
      example: df7e2w5f-02b7-4d9d-af26-8d1988fca630
      type: string
    access_access-requests:
      properties:
        action:
          $ref: '#/components/schemas/access_action'
        allowed:
          $ref: '#/components/schemas/access_allowed'
        app_domain:
          $ref: '#/components/schemas/access_app_domain'
        app_uid:
          $ref: '#/components/schemas/access_app_uid'
        connection:
          $ref: '#/components/schemas/access_connection'
        created_at:
          $ref: '#/components/schemas/access_timestamp'
        ip_address:
          $ref: '#/components/schemas/access_ip'
        ray_id:
          $ref: '#/components/schemas/access_ray_id'
        user_email:
          $ref: '#/components/schemas/access_schemas-email'
      type: object
    access_timestamp:
      example: '2014-01-01T05:20:00.12345Z'
      format: date-time
      type: string
    access_access-requests_components-schemas-response_collection:
      allOf:
      - $ref: '#/components/schemas/access_api-response-common'
      - properties:
          result:
            items:
              $ref: '#/components/schemas/access_access-requests'
            type: array
    access_identifier:
      description: Identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      type: string
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/apigateway/
x-hasEquivalentPaths: true
