openapi: 3.0.0
info:
  version: 2015-07-09
  x-release: v4
  title: APIs.io Engineering Platform Amazon API Gateway 2014 11 13 Pages Domains API
  description: <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: apigateway
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/apigateway-2015-07-09.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: https://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: http://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
- url: https://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: Pages Domains
paths:
  /accounts/{account_id}/pages/projects/{project_name}/domains:
    get:
      description: Fetch a list of all domains associated with a Pages project.
      operationId: pages-domains-get-domains
      parameters:
      - in: path
        name: project_name
        required: true
        schema:
          $ref: '#/components/schemas/pages_project_name'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/pages_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/pages_domain-response-collection'
                - $ref: '#/components/schemas/pages_api-response-common-failure'
          description: Get domains response failure.
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pages_domain-response-collection'
          description: Get domains response.
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Get domains
      tags:
      - Pages Domains
    post:
      description: Add a new domain for the Pages project.
      operationId: pages-domains-add-domain
      parameters:
      - in: path
        name: project_name
        required: true
        schema:
          $ref: '#/components/schemas/pages_project_name'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/pages_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/pages_domains-post'
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/pages_domain-response-single'
                - $ref: '#/components/schemas/pages_api-response-common-failure'
          description: Add domain response failure.
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pages_domain-response-single'
          description: Add domain response.
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Add domain
      tags:
      - Pages Domains
  /accounts/{account_id}/pages/projects/{project_name}/domains/{domain_name}:
    delete:
      description: Delete a Pages project's domain.
      operationId: pages-domains-delete-domain
      parameters:
      - in: path
        name: domain_name
        required: true
        schema:
          $ref: '#/components/schemas/pages_domain_name'
      - in: path
        name: project_name
        required: true
        schema:
          $ref: '#/components/schemas/pages_project_name'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/pages_identifier'
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        4xx:
          content:
            application/json:
              schema:
                allOf:
                - example:
                    errors: []
                    messages: []
                    result: null
                    success: true
                - $ref: '#/components/schemas/pages_api-response-common-failure'
          description: Delete domain response failure.
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/pages_api-response-common'
                - properties:
                    result:
                      nullable: true
                      type: object
                  type: object
          description: Delete domain response.
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Delete domain
      tags:
      - Pages Domains
    get:
      description: Fetch a single domain.
      operationId: pages-domains-get-domain
      parameters:
      - in: path
        name: domain_name
        required: true
        schema:
          $ref: '#/components/schemas/pages_domain_name'
      - in: path
        name: project_name
        required: true
        schema:
          $ref: '#/components/schemas/pages_project_name'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/pages_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/pages_domain-response-single'
                - $ref: '#/components/schemas/pages_api-response-common-failure'
          description: Get domain response failure.
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pages_domain-response-single'
          description: Get domain response.
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Get domain
      tags:
      - Pages Domains
    patch:
      description: Retry the validation status of a single domain.
      operationId: pages-domains-patch-domain
      parameters:
      - in: path
        name: domain_name
        required: true
        schema:
          $ref: '#/components/schemas/pages_domain_name'
      - in: path
        name: project_name
        required: true
        schema:
          $ref: '#/components/schemas/pages_project_name'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/pages_identifier'
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/pages_domain-response-single'
                - $ref: '#/components/schemas/pages_api-response-common-failure'
          description: Patch domain response failure.
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pages_domain-response-single'
          description: Patch domain response.
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Patch domain
      tags:
      - Pages Domains
components:
  schemas:
    pages_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/pages_messages'
          example:
          - code: 7003
            message: No route for the URI.
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/pages_messages'
          example: []
        result:
          nullable: true
          type: object
        success:
          description: Whether the API call was successful.
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    pages_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/pages_messages'
        messages:
          $ref: '#/components/schemas/pages_messages'
        success:
          description: Whether the API call was successful
          enum:
          - false
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    pages_api-response-single:
      allOf:
      - $ref: '#/components/schemas/pages_api-response-common'
      - properties:
          result:
            nullable: true
            type: object
      type: object
    pages_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    pages_domain-object:
      properties:
        certificate_authority:
          enum:
          - google
          - lets_encrypt
          example: lets_encrypt
          readOnly: true
          type: string
        created_on:
          readOnly: true
          type: string
        domain_id:
          readOnly: true
          type: string
        id:
          readOnly: true
          type: string
        name:
          example: example.com
          type: string
        status:
          enum:
          - initializing
          - pending
          - active
          - deactivated
          - blocked
          - error
          readOnly: true
          type: string
        validation_data:
          properties:
            error_message:
              type: string
            method:
              enum:
              - http
              - txt
              type: string
            status:
              enum:
              - initializing
              - pending
              - active
              - deactivated
              - error
              type: string
            txt_name:
              type: string
            txt_value:
              type: string
          readOnly: true
          type: object
        verification_data:
          properties:
            error_message:
              type: string
            status:
              enum:
              - pending
              - active
              - deactivated
              - blocked
              - error
              type: string
          readOnly: true
          type: object
        zone_tag:
          readOnly: true
          type: string
      type: object
    pages_api-response-pagination:
      properties:
        result_info:
          properties:
            count:
              description: The number of items on the current page.
              example: 1
              type: integer
            page:
              description: The page currently being requested.
              example: 1
              type: integer
            per_page:
              description: The number of items per page being returned.
              example: 100
              type: integer
            total_count:
              description: The total count of items.
              example: 1
              type: integer
            total_pages:
              description: The total count of pages.
              example: 1
              type: integer
          required:
          - page
          - per_page
          - count
          - total_count
          type: object
      type: object
    pages_project_name:
      description: Name of the project.
      example: this-is-my-project-01
      pattern: ^[a-z0-9][a-z0-9-]*$
      type: string
    pages_domains-post:
      properties:
        name:
          example: example.com
          type: string
      type: object
    pages_domain-response-single:
      allOf:
      - $ref: '#/components/schemas/pages_api-response-single'
      - properties:
          result:
            $ref: '#/components/schemas/pages_domain-object'
    pages_domain_name:
      description: Name of the domain.
      example: this-is-my-domain-01.com
      pattern: ^[a-z0-9][a-z0-9-]*$
      type: string
    pages_identifier:
      description: Identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      readOnly: true
      type: string
    pages_domain-response-collection:
      allOf:
      - $ref: '#/components/schemas/pages_api-response-common'
      - $ref: '#/components/schemas/pages_api-response-pagination'
      - properties:
          result:
            items:
              $ref: '#/components/schemas/pages_domain-object'
            type: array
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/apigateway/
x-hasEquivalentPaths: true
