openapi: 3.0.0
info:
  version: 2015-07-09
  x-release: v4
  title: APIs.io Engineering Platform Amazon API Gateway 2014 11 13 Global Variables API
  description: <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: apigateway
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/apigateway-2015-07-09.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: https://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: http://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
- url: https://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: Global Variables
  description: The **Global Variables** endpoints enable you to manage global [variables](https://learning.postman.com/docs/sending-requests/variables/). Global variables are available throughout a workspace and have the broadest scope in Postman.
paths:
  /workspaces/{workspaceId}/global-variables:
    parameters:
    - $ref: '#/components/parameters/workspaceId'
    get:
      summary: APIs.io Engineering Platform Get global variables
      description: Gets a workspace's global [variables](https://learning.postman.com/docs/sending-requests/variables/#variable-scopes).
      operationId: getWorkspaceGlobalVariables
      tags:
      - Global Variables
      responses:
        '200':
          $ref: '#/components/responses/getWorkspaceGlobalVariables'
        '500':
          $ref: '#/components/responses/globalVariables500Error'
    put:
      summary: APIs.io Engineering Platform Update global variables
      description: Updates and replaces a workspace's global [variables](https://learning.postman.com/docs/sending-requests/variables/#variable-scopes). This endpoint replaces all existing global variables with the variables you pass in the request body.
      operationId: updateWorkspaceGlobalVariables
      tags:
      - Global Variables
      requestBody:
        $ref: '#/components/requestBodies/updateWorkspaceGlobalVariables'
      responses:
        '200':
          $ref: '#/components/responses/updateWorkspaceGlobalVariables'
        '500':
          $ref: '#/components/responses/globalVariables500Error'
components:
  schemas:
    workspaceId:
      type: string
      example: 1f0df51a-8658-4ee8-a2a1-d2567dfa09a9
    globalVariable:
      title: Global Variable
      type: object
      description: Information about the global variable.
      properties:
        key:
          type: string
          description: The variable's name.
          example: variableName
        type:
          type: string
          description: The [type](https://learning.postman.com/docs/sending-requests/variables/#variable-types) of variable.
          enum:
          - default
          - secret
          example: default
        value:
          type: string
          description: The variable's value.
          example: variableValue
        enabled:
          type: boolean
          description: If true, the variable is enabled.
          example: true
  responses:
    updateWorkspaceGlobalVariables:
      description: Successful Response
      content:
        application/json:
          schema:
            type: object
            description: Information about the workspace's updated global variables.
            properties:
              values:
                type: array
                description: A list of the workspace's global variables.
                items:
                  $ref: '#/components/schemas/globalVariable'
          example:
            values:
            - key: api-key
              type: secret
              value: PMAK-XXXX
              enabled: true
            - key: collection_uid
              type: default
              value: 12345678-12ece9e1-2abf-4edc-8e34-de66e74114d2
              enabled: true
    getWorkspaceGlobalVariables:
      description: Successful Response
      content:
        application/json:
          schema:
            type: object
            description: Information about the workspace's global variables.
            properties:
              values:
                type: array
                description: A list of the workspace's global variables.
                items:
                  $ref: '#/components/schemas/globalVariable'
          example:
            values:
            - key: api-key
              type: secret
              value: PMAK-XXXX
              enabled: true
            - key: collection_uid
              type: default
              value: 12345678-12ece9e1-2abf-4edc-8e34-de66e74114d2
              enabled: true
    globalVariables500Error:
      description: Internal Server Error
      content:
        application/problem+json:
          schema:
            type: object
            properties:
              type:
                type: string
                format: uri-reference
                description: The [URI reference](https://www.rfc-editor.org/rfc/rfc3986) that identifies the type of problem.
                example: https://api.postman.com/problems/servererror
              title:
                type: string
                description: A short summary of the problem.
                example: Internal server error
              detail:
                type: string
                description: Information about the error.
                example: Details about the error
          example:
            type: https://api.postman.com/problems/servererror
            title: Internal server error
            detail: Details about the error
  requestBodies:
    updateWorkspaceGlobalVariables:
      content:
        application/json:
          schema:
            type: object
            properties:
              values:
                type: array
                description: A list of the workspace's global variables.
                items:
                  $ref: '#/components/schemas/globalVariable'
          example:
            values:
            - key: api-key
              type: secret
              value: PMAK-XXXX
              enabled: true
            - key: collection_uid
              type: default
              value: 12345678-12ece9e1-2abf-4edc-8e34-de66e74114d2
              enabled: true
  parameters:
    workspaceId:
      name: workspaceId
      in: path
      required: true
      description: The workspace's ID.
      schema:
        $ref: '#/components/schemas/workspaceId'
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/apigateway/
x-hasEquivalentPaths: true
