openapi: 3.2.0
info:
  description: 'To get started using Cloudflare''s products and services via the API, refer to [how to interact with Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/), which covers using tools like [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform) and the [official SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows who is making requests and what permissions you have. Create an API token to grant access to the API to perform actions.


    To create an API token, from the Cloudflare dashboard, go to My Profile > API Tokens and select Create Token. For more information on how to create and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).'
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: APIs.io Engineering Platform Cloudflare Worker Deployments API
  version: 4.0.0
tags:
- name: Worker Deployments
paths:
  /accounts/{account_id}/workers/scripts/{script_name}/deployments:
    get:
      description: List of Worker Deployments. The first deployment in the list is the latest deployment actively serving traffic.
      operationId: worker-deployments-list-deployments
      parameters:
      - in: path
        name: script_name
        required: true
        schema:
          $ref: '#/components/schemas/workers_schemas-script_name'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/workers_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/workers_schemas-deployments-list-response'
                - $ref: '#/components/schemas/workers_api-response-common-failure'
          description: List Deployments response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/workers_schemas-deployments-list-response'
          description: List Deployments response
      security:
      - api_token: []
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform List Deployments
      tags:
      - Worker Deployments
      x-api-token-group:
      - Workers Tail Read
      - Workers Scripts Write
      - Workers Scripts Read
      x-cfPermissionsRequired:
        enum:
        - com.cloudflare.edge.worker.deployment.list
    post:
      description: Deployments configure how [Worker Versions](https://developers.cloudflare.com/api/operations/worker-versions-list-versions) are deployed to traffic. A deployment can consist of one or two versions of a Worker.
      operationId: worker-deployments-create-deployment
      parameters:
      - in: path
        name: script_name
        required: true
        schema:
          $ref: '#/components/schemas/workers_schemas-script_name'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/workers_identifier'
      - description: If set to true, the deployment will be created even if normally blocked by something such rolling back to an older version when a secret has changed.
        in: query
        name: force
        schema:
          type: boolean
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/workers_deployments-create-body'
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/workers_schemas-deployments-single-response'
                - $ref: '#/components/schemas/workers_api-response-common-failure'
          description: Create Deployment response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/workers_schemas-deployments-single-response'
          description: Create Deployment response
      security:
      - api_token: []
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Create Deployment
      tags:
      - Worker Deployments
      x-api-token-group:
      - Workers Scripts Write
      x-cfPermissionsRequired:
        enum:
        - com.cloudflare.edge.worker.deployment.edit
components:
  schemas:
    workers_schemas-deployment_identifier:
      example: dc78f0bc-05c5-46b7-bb4e-137f55930378
      maxLength: 36
      type: string
    workers_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/workers_messages'
        messages:
          $ref: '#/components/schemas/workers_messages'
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      type: object
    workers_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/workers_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/workers_messages'
          example: []
        result:
          enum:
          - null
          type:
          - object
          - 'null'
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    workers_schemas-deployments-single-response:
      allOf:
      - $ref: '#/components/schemas/workers_api-response-common'
      - properties:
          result:
            allOf:
            - $ref: '#/components/schemas/workers_deployments-base'
            - oneOf:
              - $ref: '#/components/schemas/workers_deployments-strategy-percentage'
        type: object
    workers_deployments-strategy-percentage:
      properties:
        strategy:
          enum:
          - percentage
          type: string
        versions:
          items:
            properties:
              percentage:
                example: 100
                maximum: 100
                minimum: 0.01
                type: number
              version_id:
                $ref: '#/components/schemas/workers_schemas-version_identifier'
            required:
            - version_id
            - percentage
            type: object
          type: array
      required:
      - strategy
      - versions
      type: object
    workers_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    workers_identifier:
      description: Identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      type: string
    workers_deployments-create-body:
      allOf:
      - $ref: '#/components/schemas/workers_deployments-base'
      - oneOf:
        - $ref: '#/components/schemas/workers_deployments-strategy-percentage'
    workers_schemas-script_name:
      description: Name of the script.
      example: this-is_my_script-01
      pattern: ^[a-z0-9_][a-z0-9-_]*$
      type: string
    workers_schemas-version_identifier:
      example: bcf48806-b317-4351-9ee7-36e7d557d4de
      maxLength: 36
      type: string
    workers_schemas-deployments-list-response:
      allOf:
      - $ref: '#/components/schemas/workers_api-response-common'
      - properties:
          result:
            properties:
              deployments:
                items:
                  allOf:
                  - $ref: '#/components/schemas/workers_deployments-base'
                  - oneOf:
                    - $ref: '#/components/schemas/workers_deployments-strategy-percentage'
                type: array
            type: object
        type: object
    workers_deployments-base:
      properties:
        annotations:
          properties:
            workers/message:
              description: Human-readable message about the deployment.
              example: Deploy bug fix.
              maxLength: 50
              type: string
          type: object
        author_email:
          example: user@example.com
          readOnly: true
          type: string
        created_on:
          example: '2022-11-08T17:19:29.176266Z'
          readOnly: true
          type: string
        id:
          allOf:
          - $ref: '#/components/schemas/workers_schemas-deployment_identifier'
          readOnly: true
        source:
          example: api
          readOnly: true
          type: string
        strategy:
          type: string
      type: object
  securitySchemes:
    api_email:
      in: header
      name: X-Auth-Email
      type: apiKey
    api_key:
      in: header
      name: X-Auth-Key
      type: apiKey
    api_token:
      scheme: bearer
      type: http
    user_service_key:
      in: header
      name: X-Auth-User-Service-Key
      type: apiKey
