openapi: 3.0.0
info:
  version: 2015-07-09
  x-release: v4
  title: APIs.io Engineering Platform Amazon API Gateway 2014 11 13 User API
  description: <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: apigateway
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/apigateway-2015-07-09.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: https://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: http://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
- url: https://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: User
paths:
  /user:
    get:
      operationId: user-user-details
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/iam_api-response-common-failure'
          description: User Details response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/iam_single_user_response'
          description: User Details response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform User Details
      tags:
      - User
      x-cfPermissionsRequired:
        enum:
        - com.cloudflare.api.user.read
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
    patch:
      description: Edit part of your user details.
      operationId: user-edit-user
      requestBody:
        content:
          application/json:
            schema:
              properties:
                country:
                  $ref: '#/components/schemas/iam_country'
                first_name:
                  $ref: '#/components/schemas/iam_first_name'
                last_name:
                  $ref: '#/components/schemas/iam_last_name'
                telephone:
                  $ref: '#/components/schemas/iam_telephone'
                zipcode:
                  $ref: '#/components/schemas/iam_zipcode'
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/iam_api-response-common-failure'
          description: Edit User response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/iam_single_user_response'
          description: Edit User response
      security:
      - api_token: []
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Edit User
      tags:
      - User
      x-cfPermissionsRequired:
        enum:
        - com.cloudflare.api.user.update
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
  /me:
    get:
      summary: APIs.io Engineering Platform Get authenticated user
      description: 'Gets information about the authenticated user.


        **Note:**


        - This API returns a different response for users with the [Guest and Partner roles](https://learning.postman.com/docs/collaborating-in-postman/roles-and-permissions/#team-roles).

        - The `flow_count` response only returns for users on [Free plans](https://www.postman.com/pricing/).

        '
      operationId: getAuthenticatedUser
      tags:
      - User
      responses:
        '200':
          $ref: '#/components/responses/getAuthenticatedUser'
        '401':
          $ref: '#/components/responses/common401Error'
        '500':
          $ref: '#/components/responses/common500ErrorServerError'
components:
  schemas:
    iam_last_name:
      description: User's last name
      example: Appleseed
      maxLength: 60
      nullable: true
      type: string
    iam_country:
      description: The country in which the user lives.
      example: US
      maxLength: 30
      nullable: true
      type: string
    iam_first_name:
      description: User's first name
      example: John
      maxLength: 60
      nullable: true
      type: string
    iam_zipcode:
      description: The zipcode or postal code where the user lives.
      example: '12345'
      maxLength: 20
      nullable: true
      type: string
    iam_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/iam_messages'
        messages:
          $ref: '#/components/schemas/iam_messages'
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      type: object
    getAuthenticatedUser:
      title: Successful Response
      type: object
      properties:
        user:
          type: object
          description: Information about the authenticated user.
          properties:
            id:
              type: number
              description: The user's Postman ID.
              example: 12345678
            username:
              type: string
              description: The user's username.
              example: taylor-lee
            email:
              type: string
              format: email
              description: The user's email address.
              example: taylor.lee@example.com
            fullName:
              type: string
              description: The user's full name.
              example: Taylor Lee
            avatar:
              type: string
              format: url
              nullable: true
              description: The user's avatar image URL.
              example: https://example.com/user/r5u9qpvmujfjf6lbqmga.jpg
            isPublic:
              type: boolean
              description: If true, the user's information is public and visible to all users.
              example: true
            teamId:
              type: integer
              description: The team ID the user is assigned to. This returns a `0` value if the user is not assigned to a team.
              example: 123
            teamName:
              type: string
              description: The name of the team the user is assigned to.
              example: Test Team
            teamDomain:
              type: string
              description: The team's Postman domain ID.
              example: test-team
            roles:
              type: array
              description: A list of the user's assigned [roles](https://learning.postman.com/docs/collaborating-in-postman/roles-and-permissions/#team-roles).
              items:
                type: string
                default: user
                example: user
        operations:
          type: array
          description: Information about operations and their usage limits. This object does not return for users with the [Guest and Partner role](https://learning.postman.com/docs/collaborating-in-postman/roles-and-permissions/#team-roles).
          items:
            type: object
            properties:
              limit:
                type: number
                description: The operation's limit value.
                example: 1000000
              name:
                type: string
                description: The operation's name.
                example: mock_usage
              overage:
                type: number
                description: The operation's overage value.
                example: 0
              usage:
                type: number
                description: The operation's current usage value.
                example: 110276
    iam_api-response-single:
      allOf:
      - $ref: '#/components/schemas/iam_api-response-common'
      type: object
    iam_single_user_response:
      allOf:
      - $ref: '#/components/schemas/iam_api-response-single'
      - properties:
          result:
            type: object
        type: object
    iam_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/iam_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/iam_messages'
          example: []
        result:
          enum:
          - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    iam_telephone:
      description: User's telephone number
      example: +1 123-123-1234
      maxLength: 20
      nullable: true
      type: string
    iam_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
  responses:
    common500ErrorServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: object
                properties:
                  name:
                    type: string
                    description: The error name.
                    example: serverError
                  message:
                    type: string
                    description: The error message.
                    example: An error has occurred on the server.
          example:
            error:
              name: serverError
              message: An error has occurred on the server.
    getAuthenticatedUser:
      description: Successful Response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/getAuthenticatedUser'
          example:
            user:
              id: 12345678
              username: taylor-lee
              email: taylor.lee@example.com
              fullName: Taylor Lee
              avatar: https://res.cloudinary.com/postman/image/upload/t_user_profile_300/v1/user/default-6
              isPublic: true
              teamId: 123
              teamName: Test Team
              teamDomain: test-team
              roles:
              - user
              - flow-editor
              - community-manager
            operations:
            - name: api_object_usage
              limit: 99999999
              usage: 8872
              overage: 0
            - name: collection_run_limit
              limit: 99999999
              usage: 226
              overage: 0
            - name: file_storage_limit
              limit: 1
              usage: 0.28
              overage: 0
            - name: flow_requests
              limit: 1000000
              usage: 1852
              overage: 0
            - name: performance_test_limit
              limit: 99999999
              usage: 10
              overage: 0
            - name: reusable_packages
              limit: 100
              usage: 48
              overage: 0
            - name: test_data_retrieval
              limit: 1000
              usage: 180
              overage: 0
            - name: test_data_storage
              limit: 10
              usage: 0.55
              overage: 0
            - name: postbot_calls
              limit: 2500
              usage: 0
              overage: 0
            - name: mock_usage
              limit: 1000000
              usage: 79948
              overage: 0
            - name: monitor_request_runs
              limit: 15000000
              usage: 4493710
              overage: 0
            - name: api_usage
              limit: 1000000
              usage: 10788
              overage: 0
    common401Error:
      description: Unauthorized
      content:
        application/problem+json:
          schema:
            type: object
            properties:
              type:
                type: string
                format: uri-reference
                description: The [URI reference](https://www.rfc-editor.org/rfc/rfc3986) that identifies the type of problem.
                example: https://api.postman.com/problems/unauthorized
              title:
                type: string
                description: A short summary of the problem.
                example: Unauthorized
              detail:
                type: string
                description: Information about the error.
                example: Unauthorized
              status:
                type: integer
                format: http-status-code
                description: The error's HTTP status code.
                example: 401
          example:
            type: https://api.postman.com/problems/unauthorized
            title: Unauthorized
            detail: Unauthorized
            status: 401
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/apigateway/
x-hasEquivalentPaths: true
