openapi: 3.0.0
info:
  version: "1.0.0"
  x-release: v4
  title: APIs.io Engineering Platform Amazon API Gateway 2014 11 13 Priority Intelligence Requirements (PIR) API
  description: <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: apigateway
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/apigateway-2015-07-09.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: https://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: http://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
- url: https://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: Priority Intelligence Requirements (PIR)
paths:
  /accounts/{account_identifier}/cloudforce-one/requests/priority:
    post:
      operationId: cloudforce-one-priority-list
      parameters:
      - in: path
        name: account_identifier
        required: true
        schema:
          $ref: '#/components/schemas/cloudforce-one_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/cloudforce-one_priority-list'
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cloudforce-one_api-response-common-failure'
          description: List priorities response failure
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/cloudforce-one_api-response-common'
                - properties:
                    result:
                      items:
                        $ref: '#/components/schemas/cloudforce-one_priority-item'
                      type: array
          description: List priorities response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform List Priority Intelligence Requirements
      tags:
      - Priority Intelligence Requirements (PIR)
  /accounts/{account_identifier}/cloudforce-one/requests/priority/{priority_identifer}:
    delete:
      operationId: cloudforce-one-priority-delete
      parameters:
      - in: path
        name: account_identifier
        required: true
        schema:
          $ref: '#/components/schemas/cloudforce-one_identifier'
      - in: path
        name: priority_identifer
        required: true
        schema:
          $ref: '#/components/schemas/cloudforce-one_uuid'
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cloudforce-one_api-response-common-failure'
          description: Delete priority response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cloudforce-one_api-response-common'
          description: Delete priority response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Delete a Priority Intelligence Requirement
      tags:
      - Priority Intelligence Requirements (PIR)
    get:
      operationId: cloudforce-one-priority-get
      parameters:
      - in: path
        name: account_identifier
        required: true
        schema:
          $ref: '#/components/schemas/cloudforce-one_identifier'
      - in: path
        name: priority_identifer
        required: true
        schema:
          $ref: '#/components/schemas/cloudforce-one_uuid'
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cloudforce-one_api-response-common-failure'
          description: Get priority response failure
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/cloudforce-one_api-response-common'
                - properties:
                    result:
                      $ref: '#/components/schemas/cloudforce-one_request-item'
          description: Get priority response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Get a Priority Intelligence Requirement
      tags:
      - Priority Intelligence Requirements (PIR)
    put:
      operationId: cloudforce-one-priority-update
      parameters:
      - in: path
        name: account_identifier
        required: true
        schema:
          $ref: '#/components/schemas/cloudforce-one_identifier'
      - in: path
        name: priority_identifer
        required: true
        schema:
          $ref: '#/components/schemas/cloudforce-one_uuid'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/cloudforce-one_priority-edit'
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cloudforce-one_api-response-common-failure'
          description: Update priority response failure
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/cloudforce-one_api-response-common'
                - properties:
                    result:
                      $ref: '#/components/schemas/cloudforce-one_request-item'
          description: Update priority response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Update a Priority Intelligence Requirement
      tags:
      - Priority Intelligence Requirements (PIR)
  /accounts/{account_identifier}/cloudforce-one/requests/priority/new:
    post:
      operationId: cloudforce-one-priority-new
      parameters:
      - in: path
        name: account_identifier
        required: true
        schema:
          $ref: '#/components/schemas/cloudforce-one_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/cloudforce-one_priority-edit'
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cloudforce-one_api-response-common-failure'
          description: Create priority response  failure
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/cloudforce-one_api-response-common'
                - properties:
                    result:
                      $ref: '#/components/schemas/cloudforce-one_priority-item'
          description: Create priority response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Create a New Priority Intelligence Requirement
      tags:
      - Priority Intelligence Requirements (PIR)
  /accounts/{account_identifier}/cloudforce-one/requests/priority/quota:
    get:
      operationId: cloudforce-one-priority-quota
      parameters:
      - in: path
        name: account_identifier
        required: true
        schema:
          $ref: '#/components/schemas/cloudforce-one_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cloudforce-one_api-response-common-failure'
          description: Get priority quota response failure
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/cloudforce-one_api-response-common'
                - properties:
                    result:
                      $ref: '#/components/schemas/cloudforce-one_quota'
          description: Get priority quota response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Get Priority Intelligence Requirement Quota
      tags:
      - Priority Intelligence Requirements (PIR)
components:
  schemas:
    cloudforce-one_uuid:
      description: UUID
      example: f174e90a-fafe-4643-bbbc-4a0ed4fc8415
      maxLength: 36
      type: string
    cloudforce-one_quota:
      properties:
        anniversary_date:
          allOf:
          - $ref: '#/components/schemas/cloudforce-one_time'
          - description: Anniversary date is when annual quota limit is refresh
          - example: '2022-01-01T00:00:00Z'
        quarter_anniversary_date:
          allOf:
          - $ref: '#/components/schemas/cloudforce-one_time'
          - description: Quater anniversary date is when quota limit is refreshed each quarter
          - example: '2022-04-01T00:00:00Z'
        quota:
          description: Tokens for the quarter
          example: 120
          type: integer
        remaining:
          description: Tokens remaining for the quarter
          example: 64
          type: integer
      title: Quota
      type: object
    cloudforce-one_request-content:
      description: Request content
      example: What regions were most effected by the recent DoS?
      type: string
    cloudforce-one_priority-edit:
      properties:
        labels:
          $ref: '#/components/schemas/cloudforce-one_labels'
        priority:
          description: Priority
          example: 1
          type: integer
        requirement:
          description: Requirement
          example: DoS attacks carried out by CVEs
          type: string
        tlp:
          $ref: '#/components/schemas/cloudforce-one_tlp'
      required:
      - labels
      - priority
      - requirement
      - tlp
      title: Priority Editable Attributes
      type: object
    cloudforce-one_request-type:
      description: Requested information from request
      example: Victomology
      type: string
    cloudforce-one_identifier:
      description: Identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      readOnly: true
      type: string
    cloudforce-one_tlp:
      description: The CISA defined Traffic Light Protocol (TLP)
      enum:
      - clear
      - amber
      - amber-strict
      - green
      - red
      title: TLP
      type: string
    cloudforce-one_time:
      example: '2022-04-01T05:20:00Z'
      format: date-time
      type: string
    cloudforce-one_request-status:
      description: Request Status
      enum:
      - open
      - accepted
      - reported
      - approved
      - completed
      - declined
      title: Request Status
      type: string
    cloudforce-one_request-item:
      properties:
        completed:
          $ref: '#/components/schemas/cloudforce-one_time'
        content:
          $ref: '#/components/schemas/cloudforce-one_request-content'
        created:
          $ref: '#/components/schemas/cloudforce-one_time'
        id:
          $ref: '#/components/schemas/cloudforce-one_uuid'
        message_tokens:
          description: Tokens for the request messages
          example: 1
          type: integer
        priority:
          $ref: '#/components/schemas/cloudforce-one_time'
        readable_id:
          $ref: '#/components/schemas/cloudforce-one_request-readable-id'
        request:
          $ref: '#/components/schemas/cloudforce-one_request-type'
        status:
          $ref: '#/components/schemas/cloudforce-one_request-status'
        summary:
          $ref: '#/components/schemas/cloudforce-one_request-summary'
        tlp:
          $ref: '#/components/schemas/cloudforce-one_tlp'
        tokens:
          description: Tokens for the request
          example: 16
          type: integer
        updated:
          $ref: '#/components/schemas/cloudforce-one_time'
      required:
      - id
      - created
      - updated
      - content
      - priority
      - request
      - summary
      - tlp
      title: Request Item
      type: object
    cloudforce-one_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/cloudforce-one_messages'
        messages:
          $ref: '#/components/schemas/cloudforce-one_messages'
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      type: object
    cloudforce-one_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    cloudforce-one_request-summary:
      description: Brief description of the request
      example: DoS attack
      type: string
    cloudforce-one_priority-list:
      properties:
        page:
          description: Page number of results
          type: integer
        per_page:
          description: Number of results per page
          example: 10
          type: integer
      required:
      - page
      - per_page
      title: Priority List Parameters
      type: object
    cloudforce-one_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/cloudforce-one_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/cloudforce-one_messages'
          example: []
        result:
          enum:
          - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    cloudforce-one_request-readable-id:
      description: Readable Request ID
      example: RFI-2022-000001
      title: Request Readable ID
      type: string
    cloudforce-one_priority-item:
      properties:
        created:
          allOf:
          - $ref: '#/components/schemas/cloudforce-one_time'
          - description: Priority creation time
        id:
          $ref: '#/components/schemas/cloudforce-one_uuid'
        labels:
          $ref: '#/components/schemas/cloudforce-one_labels'
        priority:
          description: Priority
          example: 1
          type: integer
        requirement:
          description: Requirement
          example: DoS attacks carried out by CVEs
          type: string
        tlp:
          $ref: '#/components/schemas/cloudforce-one_tlp'
        updated:
          allOf:
          - $ref: '#/components/schemas/cloudforce-one_time'
          - description: Priority last updated time
      required:
      - id
      - created
      - updated
      - labels
      - priority
      - requirement
      - tlp
      title: Priority Item
      type: object
    cloudforce-one_labels:
      description: List of labels
      example:
      - DoS
      - CVE
      items:
        type: string
      title: Labels
      type: array
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/apigateway/
x-hasEquivalentPaths: true
