openapi: 3.0.0
info:
  version: "1.0.0"
  x-release: v4
  title: APIs.io Engineering Platform Amazon API Gateway 2014 11 13 Magic Account Apps API
  description: <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: apigateway
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/apigateway-2015-07-09.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: https://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: http://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
- url: https://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: Magic Account Apps
paths:
  /accounts/{account_id}/magic/apps:
    get:
      description: Lists Apps associated with an account.
      operationId: magic-account-apps-list-apps
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_api-response-common-failure'
          description: List Apps response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_apps_collection_response'
          description: List Apps response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform List Apps
      tags:
      - Magic Account Apps
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    post:
      description: Creates a new App for an account
      operationId: magic-account-apps-add-app
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/magic_app_add_single_request'
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_api-response-common-failure'
          description: Create Account App response failure
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_app_single_response'
          description: Create Account App response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Create a new App
      tags:
      - Magic Account Apps
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
  /accounts/{account_id}/magic/apps/{account_app_id}:
    delete:
      description: Deletes specific Account App.
      operationId: magic-account-apps-delete-app
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      - in: path
        name: account_app_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_api-response-common-failure'
          description: Delete App response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_app_single_response'
          description: Delete App response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Delete Account App
      tags:
      - Magic Account Apps
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    put:
      description: Updates an Account App
      operationId: magic-account-apps-update-app
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      - in: path
        name: account_app_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/magic_app_update_request'
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_api-response-common-failure'
          description: Update App response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_app_single_response'
          description: Update App response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Update an App
      tags:
      - Magic Account Apps
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
components:
  schemas:
    magic_apps-response-array:
      properties:
        errors:
          $ref: '#/components/schemas/magic_messages'
        messages:
          $ref: '#/components/schemas/magic_messages'
        result:
          items: {}
          nullable: true
          type: array
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    magic_managed_app_id:
      description: Managed app ID.
      example: cloudflare
      type: string
    magic_identifier:
      description: Identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      readOnly: true
      type: string
    magic_managed_app:
      description: Managed app defined by Cloudflare.
      properties:
        hostnames:
          $ref: '#/components/schemas/magic_app_hostnames'
        ip_subnets:
          $ref: '#/components/schemas/magic_app_subnets'
        managed_app_id:
          $ref: '#/components/schemas/magic_managed_app_id'
        name:
          $ref: '#/components/schemas/magic_app_name'
        type:
          $ref: '#/components/schemas/magic_app_type'
      required:
      - managed_app_id
      title: Managed App
      type: object
    magic_app_single_response:
      allOf:
      - $ref: '#/components/schemas/magic_apps-response-object'
      - properties:
          result:
            $ref: '#/components/schemas/magic_account_app'
    magic_account_app:
      description: Custom app defined for an account.
      properties:
        account_app_id:
          $ref: '#/components/schemas/magic_account_app_id'
        hostnames:
          $ref: '#/components/schemas/magic_app_hostnames'
        ip_subnets:
          $ref: '#/components/schemas/magic_app_subnets'
        name:
          $ref: '#/components/schemas/magic_app_name'
        type:
          $ref: '#/components/schemas/magic_app_type'
      required:
      - account_app_id
      title: Account App
      type: object
    magic_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    magic_app_type:
      description: Category of the app.
      example: Development
      type: string
    magic_app_hostnames:
      description: FQDNs to associate with traffic decisions.
      items:
        example: auth.cloudflare.com
        type: string
      type: array
    magic_account_app_id:
      description: Magic account app ID.
      example: ac60d3d0435248289d446cedd870bcf4
      type: string
    magic_apps-response-object:
      properties:
        errors:
          $ref: '#/components/schemas/magic_messages'
        messages:
          $ref: '#/components/schemas/magic_messages'
        result:
          nullable: true
          type: object
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    magic_cidr:
      description: A valid CIDR notation representing an IP range.
      example: 192.0.2.0/24
      type: string
    magic_app_subnets:
      description: CIDRs to associate with traffic decisions.
      items:
        allOf:
        - $ref: '#/components/schemas/magic_cidr'
        - example: 1.1.1.1/32
      type: array
    magic_app_name:
      description: Display name for the app.
      example: Cloudflare Dashboard
      type: string
    magic_apps_collection_response:
      allOf:
      - $ref: '#/components/schemas/magic_apps-response-array'
      - properties:
          result:
            items:
              $ref: '#/components/schemas/magic_app'
            type: array
    magic_app_update_request:
      anyOf:
      - required:
        - name
        title: Update App Name
      - required:
        - type
        title: Update App Type
      - required:
        - hostnames
        title: Update App Hostnames
      - required:
        - ip_subnets
        title: Update App Subnets
      properties:
        hostnames:
          $ref: '#/components/schemas/magic_app_hostnames'
        ip_subnets:
          $ref: '#/components/schemas/magic_app_subnets'
        name:
          $ref: '#/components/schemas/magic_app_name'
        type:
          $ref: '#/components/schemas/magic_app_type'
      type: object
    magic_app_add_single_request:
      anyOf:
      - required:
        - hostnames
        title: Hostnames
      - required:
        - ip_subnets
        title: Subnets
      properties:
        hostnames:
          $ref: '#/components/schemas/magic_app_hostnames'
        ip_subnets:
          $ref: '#/components/schemas/magic_app_subnets'
        name:
          $ref: '#/components/schemas/magic_app_name'
        type:
          $ref: '#/components/schemas/magic_app_type'
      required:
      - name
      - type
      type: object
    magic_app:
      description: Collection of Hostnames and/or IP Subnets to associate with traffic decisions.
      oneOf:
      - $ref: '#/components/schemas/magic_account_app'
      - $ref: '#/components/schemas/magic_managed_app'
      type: object
    magic_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/magic_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/magic_messages'
          example: []
        result:
          enum:
          - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/apigateway/
x-hasEquivalentPaths: true
