openapi: 3.0.0
info:
  version: 2015-07-09
  x-release: v4
  title: APIs.io Engineering Platform Amazon API Gateway 2014 11 13 DLP Settings API
  description: <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: apigateway
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/apigateway-2015-07-09.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: https://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: http://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
- url: https://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: DLP Settings
paths:
  /accounts/{account_id}/dlp/limits:
    get:
      operationId: dlp-limits-get
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          type: string
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dlp_api-response-common-failure'
          description: Limits get failed
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/dlp_api-response-single'
                - properties:
                    result:
                      $ref: '#/components/schemas/dlp_Limits'
                  type: object
          description: Limits retrieved successfully
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Fetch limits associated with DLP for account
      tags:
      - DLP Settings
  /accounts/{account_id}/dlp/patterns/validate:
    post:
      description: 'Validates whether this pattern is a valid regular expression. Rejects it if

        the regular expression is too complex or can match an unbounded-length

        string. The regex will be rejected if it uses `*` or `+`. Bound the maximum

        number of characters that can be matched using a range, e.g. `{1,100}`.'
      operationId: dlp-pattern-validate
      parameters:
      - description: Account ID
        in: path
        name: account_id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/dlp_RegexValidationQuery'
        description: Validation query
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dlp_api-response-common-failure'
          description: Failed to validate
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/dlp_api-response-single'
                - properties:
                    result:
                      $ref: '#/components/schemas/dlp_RegexValidationResult'
                  type: object
          description: Validation response
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Validate a DLP regex pattern
      tags:
      - DLP Settings
  /accounts/{account_id}/dlp/payload_log:
    get:
      operationId: dlp-payload-log-get
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          type: string
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dlp_api-response-common-failure'
          description: Failed to get payload log settings
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/dlp_api-response-single'
                - properties:
                    result:
                      $ref: '#/components/schemas/dlp_PayloadLogSetting'
                  type: object
          description: Payload log settings
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Get payload log settings
      tags:
      - DLP Settings
    put:
      operationId: dlp-payload-log-put
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/dlp_PayloadLogSettingUpdate'
        description: New payload log settings
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dlp_api-response-common-failure'
          description: Failed to set payload log settings
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/dlp_api-response-single'
                - properties:
                    result:
                      $ref: '#/components/schemas/dlp_PayloadLogSetting'
                  type: object
          description: Payload log settings
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Set payload log settings
      tags:
      - DLP Settings
components:
  schemas:
    dlp_api-response-single:
      allOf:
      - $ref: '#/components/schemas/dlp_api-response-common'
      type: object
    dlp_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/dlp_messages'
        messages:
          $ref: '#/components/schemas/dlp_messages'
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      type: object
    dlp_RegexValidationResult:
      properties:
        valid:
          type: boolean
      required:
      - valid
      type: object
    dlp_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/dlp_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/dlp_messages'
          example: []
        result:
          enum:
          - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    dlp_Limits:
      properties:
        max_dataset_cells:
          format: int64
          minimum: 0
          type: integer
      required:
      - max_dataset_cells
      type: object
    dlp_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    dlp_PayloadLogSettingUpdate:
      properties:
        public_key:
          nullable: true
          type: string
      type: object
    dlp_PayloadLogSetting:
      properties:
        public_key:
          nullable: true
          type: string
        updated_at:
          format: date-time
          type: string
      required:
      - updated_at
      type: object
    dlp_RegexValidationQuery:
      properties:
        max_match_bytes:
          description: 'Maximum number of bytes that the regular expression can match.


            If this is `null` then there is no limit on the length. Patterns can use

            `*` and `+`. Otherwise repeats should use a range `{m,n}` to restrict

            patterns to the length. If this field is missing, then a default length

            limit is used.


            Note that the length is specified in bytes. Since regular expressions

            use UTF-8 the pattern `.` can match up to 4 bytes. Hence `.{1,256}`

            has a maximum length of 1024 bytes.'
          format: int32
          minimum: 0
          nullable: true
          type: integer
        regex:
          type: string
      required:
      - regex
      type: object
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/apigateway/
x-hasEquivalentPaths: true
