openapi: 3.2.0
info:
  description: 'To get started using Cloudflare''s products and services via the API, refer to [how to interact with Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/), which covers using tools like [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform) and the [official SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows who is making requests and what permissions you have. Create an API token to grant access to the API to perform actions.


    To create an API token, from the Cloudflare dashboard, go to My Profile > API Tokens and select Create Token. For more information on how to create and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).'
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: APIs.io Engineering Platform Cloudflare Email Routing Destination Addresses API
  version: 4.0.0
tags:
- name: Email Routing Destination Addresses
paths:
  /accounts/{account_id}/email/routing/addresses:
    get:
      description: Lists existing destination addresses.
      operationId: email-routing-destination-addresses-list-destination-addresses
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/email_identifier'
      - in: query
        name: page
        schema:
          default: 1
          description: Page number of paginated results.
          minimum: 1
          type: number
      - in: query
        name: per_page
        schema:
          default: 20
          description: Maximum number of results per page.
          maximum: 50
          minimum: 5
          type: number
      - in: query
        name: direction
        schema:
          default: asc
          description: Sorts results in an ascending or descending order.
          enum:
          - asc
          - desc
          example: asc
          type: string
      - in: query
        name: verified
        schema:
          default: true
          description: Filter by verified destination addresses.
          enum:
          - true
          - false
          example: true
          type: boolean
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/email_destination_addresses_response_collection'
          description: List destination addresses response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform List destination addresses
      tags:
      - Email Routing Destination Addresses
      x-api-token-group:
      - Email Routing Addresses Read
      x-cfPermissionsRequired:
        enum:
        - com.cloudflare.api.account.email.routing.address.list
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
    post:
      description: Create a destination address to forward your emails to. Destination addresses need to be verified before they can be used.
      operationId: email-routing-destination-addresses-create-a-destination-address
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/email_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/email_create_destination_address_properties'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/email_destination_address_response_single'
          description: Create a destination address response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Create a destination address
      tags:
      - Email Routing Destination Addresses
      x-cfPermissionsRequired:
        enum:
        - com.cloudflare.api.account.email.routing.address.create
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
  /accounts/{account_id}/email/routing/addresses/{destination_address_identifier}:
    delete:
      description: Deletes a specific destination address.
      operationId: email-routing-destination-addresses-delete-destination-address
      parameters:
      - in: path
        name: destination_address_identifier
        required: true
        schema:
          $ref: '#/components/schemas/email_destination_address_identifier'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/email_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/email_destination_address_response_single'
          description: Delete destination address response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Delete destination address
      tags:
      - Email Routing Destination Addresses
      x-cfPermissionsRequired:
        enum:
        - com.cloudflare.api.account.email.routing.address.delete
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
    get:
      description: Gets information for a specific destination email already created.
      operationId: email-routing-destination-addresses-get-a-destination-address
      parameters:
      - in: path
        name: destination_address_identifier
        required: true
        schema:
          $ref: '#/components/schemas/email_destination_address_identifier'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/email_identifier'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/email_destination_address_response_single'
          description: Get a destination address response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Get a destination address
      tags:
      - Email Routing Destination Addresses
      x-api-token-group:
      - Email Routing Addresses Read
      x-cfPermissionsRequired:
        enum:
        - com.cloudflare.api.account.email.routing.address.read
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
components:
  schemas:
    email_result_info:
      properties:
        count:
          description: Total number of results for the requested service
          example: 1
          type: number
        page:
          description: Current page within paginated list of results
          example: 1
          type: number
        per_page:
          description: Number of results per page of results
          example: 20
          type: number
        total_count:
          description: Total results available without any search parameters
          example: 2000
          type: number
      type: object
    email_api-response-single:
      allOf:
      - $ref: '#/components/schemas/email_api-response-common'
      type: object
    email_destination_address_response_single:
      allOf:
      - $ref: '#/components/schemas/email_api-response-single'
      - properties:
          result:
            $ref: '#/components/schemas/email_addresses'
    email_created:
      description: The date and time the destination address has been created.
      example: '2014-01-02T02:20:00Z'
      format: date-time
      readOnly: true
      type: string
    email_destination_address_tag:
      deprecated: true
      description: Destination address tag. (Deprecated, replaced by destination address identifier)
      example: ea95132c15732412d22c1476fa83f27a
      maxLength: 32
      readOnly: true
      type: string
    email_destination_addresses_response_collection:
      allOf:
      - $ref: '#/components/schemas/email_api-response-collection'
      - properties:
          result:
            items:
              $ref: '#/components/schemas/email_addresses'
            type: array
          result_info:
            properties:
              count:
                example: 1
              page:
                example: 1
              per_page:
                example: 20
              total_count:
                example: 1
            type: object
    email_identifier:
      description: Identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      type: string
    email_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    email_verified:
      description: The date and time the destination address has been verified. Null means not verified yet.
      example: '2014-01-02T02:20:00Z'
      format: date-time
      readOnly: true
      type: string
    email_create_destination_address_properties:
      properties:
        email:
          $ref: '#/components/schemas/email_email'
      required:
      - email
      type: object
    email_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/email_messages'
        messages:
          $ref: '#/components/schemas/email_messages'
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      type: object
    email_addresses:
      allOf:
      - $ref: '#/components/schemas/email_destination_address_properties'
      type: object
    email_destination_address_properties:
      properties:
        created:
          $ref: '#/components/schemas/email_created'
        email:
          $ref: '#/components/schemas/email_email'
        id:
          $ref: '#/components/schemas/email_destination_address_identifier'
        modified:
          $ref: '#/components/schemas/email_modified'
        tag:
          $ref: '#/components/schemas/email_destination_address_tag'
        verified:
          $ref: '#/components/schemas/email_verified'
      type: object
    email_modified:
      description: The date and time the destination address was last modified.
      example: '2014-01-02T02:20:00Z'
      format: date-time
      readOnly: true
      type: string
    email_email:
      description: The contact email address of the user.
      example: user@example.com
      maxLength: 90
      type: string
    email_api-response-collection:
      allOf:
      - $ref: '#/components/schemas/email_api-response-common'
      - properties:
          result_info:
            $ref: '#/components/schemas/email_result_info'
      type: object
    email_destination_address_identifier:
      description: Destination address identifier.
      example: ea95132c15732412d22c1476fa83f27a
      maxLength: 32
      readOnly: true
      type: string
  securitySchemes:
    api_email:
      in: header
      name: X-Auth-Email
      type: apiKey
    api_key:
      in: header
      name: X-Auth-Key
      type: apiKey
    api_token:
      scheme: bearer
      type: http
    user_service_key:
      in: header
      name: X-Auth-User-Service-Key
      type: apiKey
