openapi: 3.2.0
info:
  description: 'To get started using Cloudflare''s products and services via the API, refer to [how to interact with Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/), which covers using tools like [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform) and the [official SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows who is making requests and what permissions you have. Create an API token to grant access to the API to perform actions.


    To create an API token, from the Cloudflare dashboard, go to My Profile > API Tokens and select Create Token. For more information on how to create and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).'
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: APIs.io Engineering Platform Cloudflare DLS Regional Services API
  version: 4.0.0
tags:
- name: DLS Regional Services
paths:
  /accounts/{account_id}/addressing/regional_hostnames/regions:
    get:
      description: List all Regional Services regions available for use by this account.
      operationId: dls-account-regional-hostnames-account-list-regions
      parameters:
      - $ref: '#/components/parameters/dls_account_id'
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/dls_api-response-common-failure'
          description: Failure to list regions
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/dls_api-response-collection'
                - properties:
                    result:
                      items:
                        properties:
                          key:
                            $ref: '#/components/schemas/dls_region_key'
                          label:
                            description: Human-readable text label for the region
                            example: Canada
                            type: string
                        type: object
                      type: array
          description: List regions response
      security:
      - api_email: []
        api_key: []
      - api_token: []
      summary: APIs.io Engineering Platform List Regions
      tags:
      - DLS Regional Services
      x-api-token-group:
      - DNS Read
components:
  schemas:
    dls_identifier:
      description: Identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      readOnly: true
      type: string
    dls_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/dls_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/dls_messages'
          example: []
        result:
          enum:
          - null
          type:
          - object
          - 'null'
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    dls_region_key:
      description: Identifying key for the region
      example: ca
      type: string
    dls_api-response-collection:
      allOf:
      - $ref: '#/components/schemas/dls_api-response-common'
      - properties:
          result:
            items: {}
            type:
            - array
            - 'null'
          result_info:
            $ref: '#/components/schemas/dls_result_info'
      type: object
    dls_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    dls_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/dls_messages'
        messages:
          $ref: '#/components/schemas/dls_messages'
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      type: object
    dls_result_info:
      properties:
        count:
          description: Total number of results for the requested service
          example: 1
          type: number
        page:
          description: Current page within paginated list of results
          example: 1
          type: number
        per_page:
          description: Number of results per page of results
          example: 20
          type: number
        total_count:
          description: Total results available without any search parameters
          example: 2000
          type: number
      type: object
  parameters:
    dls_account_id:
      in: path
      name: account_id
      required: true
      schema:
        $ref: '#/components/schemas/dls_identifier'
  securitySchemes:
    api_email:
      in: header
      name: X-Auth-Email
      type: apiKey
    api_key:
      in: header
      name: X-Auth-Key
      type: apiKey
    api_token:
      scheme: bearer
      type: http
    user_service_key:
      in: header
      name: X-Auth-User-Service-Key
      type: apiKey
