openapi: 3.2.0
info:
  description: 'To get started using Cloudflare''s products and services via the API, refer to [how to interact with Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/), which covers using tools like [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform) and the [official SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows who is making requests and what permissions you have. Create an API token to grant access to the API to perform actions.


    To create an API token, from the Cloudflare dashboard, go to My Profile > API Tokens and select Create Token. For more information on how to create and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).'
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: APIs.io Engineering Platform Cloudflare User's Organizations API
  version: 4.0.0
tags:
- name: User's Organizations
paths:
  /user/organizations:
    get:
      description: Lists organizations the user is associated with.
      operationId: user'-s-organizations-list-organizations
      parameters:
      - in: query
        name: name
        schema:
          $ref: '#/components/schemas/iam_schemas-name'
      - in: query
        name: page
        schema:
          default: 1
          description: Page number of paginated results.
          minimum: 1
          type: number
      - in: query
        name: per_page
        schema:
          default: 20
          description: Number of organizations per page.
          maximum: 50
          minimum: 5
          type: number
      - in: query
        name: order
        schema:
          description: Field to order organizations by.
          enum:
          - id
          - name
          - status
          example: status
          type: string
      - in: query
        name: direction
        schema:
          description: Direction to order organizations.
          enum:
          - asc
          - desc
          example: desc
          type: string
      - in: query
        name: match
        schema:
          default: all
          description: Whether to match all search requirements or at least one (any).
          enum:
          - any
          - all
          type: string
      - in: query
        name: status
        schema:
          description: Whether the user is a member of the organization or has an inivitation pending.
          enum:
          - member
          - invited
          example: member
          type: string
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/iam_api-response-common-failure'
          description: List Organizations response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/iam_collection_organization_response'
          description: List Organizations response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform List Organizations
      tags:
      - User's Organizations
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
  /user/organizations/{organization_id}:
    delete:
      description: Removes association to an organization.
      operationId: user'-s-organizations-leave-organization
      parameters:
      - in: path
        name: organization_id
        required: true
        schema:
          $ref: '#/components/schemas/iam_common_components-schemas-identifier'
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/iam_api-response-common-failure'
          description: Leave Organization response failure
        '200':
          content:
            application/json:
              schema:
                properties:
                  id:
                    $ref: '#/components/schemas/iam_common_components-schemas-identifier'
                type: object
          description: Leave Organization response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Leave Organization
      tags:
      - User's Organizations
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    get:
      description: Gets a specific organization the user is associated with.
      operationId: user'-s-organizations-organization-details
      parameters:
      - in: path
        name: organization_id
        required: true
        schema:
          $ref: '#/components/schemas/iam_common_components-schemas-identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/iam_api-response-common-failure'
          description: Organization Details response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/iam_single_organization_response'
          description: Organization Details response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Organization Details
      tags:
      - User's Organizations
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
components:
  schemas:
    iam_components-schemas-status:
      description: Whether the user is a member of the organization or has an invitation pending.
      enum:
      - member
      - invited
      example: member
      type: string
    iam_api-response-collection:
      allOf:
      - $ref: '#/components/schemas/iam_api-response-common'
      - properties:
          result:
            items: {}
            type:
            - array
            - 'null'
          result_info:
            $ref: '#/components/schemas/iam_result_info'
      type: object
    iam_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/iam_messages'
        messages:
          $ref: '#/components/schemas/iam_messages'
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      type: object
    iam_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    iam_result_info:
      properties:
        count:
          description: Total number of results for the requested service
          example: 1
          type: number
        page:
          description: Current page within paginated list of results
          example: 1
          type: number
        per_page:
          description: Number of results per page of results
          example: 20
          type: number
        total_count:
          description: Total results available without any search parameters
          example: 2000
          type: number
      type: object
    iam_schemas-permissions:
      description: Access permissions for this User.
      items:
        example: '#zones:read'
        maxLength: 160
        type: string
      readOnly: true
      type: array
    iam_common_components-schemas-identifier:
      description: Identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      readOnly: true
      type: string
    iam_single_organization_response:
      allOf:
      - $ref: '#/components/schemas/iam_api-response-single'
      - properties:
          result:
            type: object
        type: object
    iam_api-response-single:
      allOf:
      - $ref: '#/components/schemas/iam_api-response-common'
      type: object
    iam_organization:
      properties:
        id:
          $ref: '#/components/schemas/iam_common_components-schemas-identifier'
        name:
          $ref: '#/components/schemas/iam_schemas-name'
        permissions:
          $ref: '#/components/schemas/iam_schemas-permissions'
        roles:
          description: List of roles that a user has within an organization.
          items:
            example: All Privileges - Super Administrator
            maxLength: 120
            type: string
          readOnly: true
          type: array
        status:
          $ref: '#/components/schemas/iam_components-schemas-status'
      type: object
    iam_collection_organization_response:
      allOf:
      - $ref: '#/components/schemas/iam_api-response-collection'
      - properties:
          result:
            items:
              $ref: '#/components/schemas/iam_organization'
            type: array
        type: object
    iam_schemas-name:
      description: Organization name.
      example: Cloudflare, Inc.
      maxLength: 100
      type: string
    iam_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/iam_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/iam_messages'
          example: []
        result:
          enum:
          - null
          type:
          - object
          - 'null'
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
  securitySchemes:
    api_email:
      in: header
      name: X-Auth-Email
      type: apiKey
    api_key:
      in: header
      name: X-Auth-Key
      type: apiKey
    api_token:
      scheme: bearer
      type: http
    user_service_key:
      in: header
      name: X-Auth-User-Service-Key
      type: apiKey
