openapi: 3.0.0
info:
  version: 2015-07-09
  x-release: v4
  title: APIs.io Engineering Platform Amazon API Gateway 2014 11 13 Cloudflare Tunnel Configuration API
  description: <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: apigateway
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/apigateway-2015-07-09.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: https://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: http://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
- url: https://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: Cloudflare Tunnel Configuration
paths:
  /accounts/{account_id}/cfd_tunnel/{tunnel_id}/configurations:
    get:
      description: Gets the configuration for a remotely-managed tunnel
      operationId: cloudflare-tunnel-configuration-get-configuration
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/tunnel_identifier'
      - in: path
        name: tunnel_id
        required: true
        schema:
          $ref: '#/components/schemas/tunnel_tunnel_id'
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tunnel_api-response-common-failure'
          description: Get configuration response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tunnel_configuration_response'
          description: Get configuration response
      security:
      - api_email: []
        api_key: []
      - api_token: []
      - user_service_key: []
      summary: APIs.io Engineering Platform Get configuration
      tags:
      - Cloudflare Tunnel Configuration
    put:
      description: Adds or updates the configuration for a remotely-managed tunnel.
      operationId: cloudflare-tunnel-configuration-put-configuration
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/tunnel_identifier'
      - in: path
        name: tunnel_id
        required: true
        schema:
          $ref: '#/components/schemas/tunnel_tunnel_id'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                config:
                  $ref: '#/components/schemas/tunnel_config'
              type: object
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tunnel_api-response-common-failure'
          description: Put configuration response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tunnel_configuration_response'
          description: Put configuration response
      security:
      - api_email: []
        api_key: []
      - api_token: []
      - user_service_key: []
      summary: APIs.io Engineering Platform Put configuration
      tags:
      - Cloudflare Tunnel Configuration
components:
  schemas:
    tunnel_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/tunnel_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/tunnel_messages'
          example: []
        result:
          enum:
          - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    tunnel_configuration_response:
      allOf:
      - $ref: '#/components/schemas/tunnel_schemas-api-response-single'
      - properties:
          result:
            $ref: '#/components/schemas/tunnel_configuration'
    tunnel_originRequest:
      description: Configuration parameters for the public hostname specific connection settings between cloudflared and origin server.
      properties:
        access:
          description: For all L7 requests to this hostname, cloudflared will validate each request's Cf-Access-Jwt-Assertion request header.
          properties:
            audTag:
              description: Access applications that are allowed to reach this hostname for this Tunnel. Audience tags can be identified in the dashboard or via the List Access policies API.
              items:
                type: string
              type: array
            required:
              default: false
              description: Deny traffic that has not fulfilled Access authorization.
              type: boolean
            teamName:
              default: Your Zero Trust organization name.
              type: string
          required:
          - audTag
          - teamName
          type: object
        caPool:
          default: ''
          description: Path to the certificate authority (CA) for the certificate of your origin. This option should be used only if your certificate is not signed by Cloudflare.
          type: string
        connectTimeout:
          default: 10
          description: Timeout for establishing a new TCP connection to your origin server. This excludes the time taken to establish TLS, which is controlled by tlsTimeout.
          type: integer
        disableChunkedEncoding:
          description: Disables chunked transfer encoding. Useful if you are running a WSGI server.
          type: boolean
        http2Origin:
          description: Attempt to connect to origin using HTTP2. Origin must be configured as https.
          type: boolean
        httpHostHeader:
          description: Sets the HTTP Host header on requests sent to the local service.
          type: string
        keepAliveConnections:
          default: 100
          description: Maximum number of idle keepalive connections between Tunnel and your origin. This does not restrict the total number of concurrent connections.
          type: integer
        keepAliveTimeout:
          default: 90
          description: Timeout after which an idle keepalive connection can be discarded.
          type: integer
        noHappyEyeballs:
          default: false
          description: Disable the “happy eyeballs” algorithm for IPv4/IPv6 fallback if your local network has misconfigured one of the protocols.
          type: boolean
        noTLSVerify:
          default: false
          description: Disables TLS verification of the certificate presented by your origin. Will allow any certificate from the origin to be accepted.
          type: boolean
        originServerName:
          default: ''
          description: Hostname that cloudflared should expect from your origin server certificate.
          type: string
        proxyType:
          default: ''
          description: 'cloudflared starts a proxy server to translate HTTP traffic into TCP when proxying, for example, SSH or RDP. This configures what type of proxy will be started. Valid options are: "" for the regular proxy and "socks" for a SOCKS5 proxy.

            '
          type: string
        tcpKeepAlive:
          default: 30
          description: The timeout after which a TCP keepalive packet is sent on a connection between Tunnel and the origin server.
          type: integer
        tlsTimeout:
          default: 10
          description: Timeout for completing a TLS handshake to your origin server, if you have chosen to connect Tunnel to an HTTPS server.
          type: integer
      type: object
    tunnel_schemas-api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/tunnel_messages'
        messages:
          $ref: '#/components/schemas/tunnel_messages'
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      type: object
    tunnel_tunnel_id:
      description: UUID of the tunnel.
      example: f70ff985-a4ef-4643-bbbc-4a0ed4fc8415
      format: uuid
      maxLength: 36
      readOnly: true
      type: string
    tunnel_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    tunnel_schemas-config_src:
      default: local
      description: Indicates if this is a locally or remotely configured tunnel. If `local`, manage the tunnel using a YAML file on the origin machine. If `cloudflare`, manage the tunnel's configuration on the Zero Trust dashboard.
      enum:
      - local
      - cloudflare
      example: cloudflare
      type: string
    tunnel_identifier:
      description: Identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      type: string
    tunnel_schemas-api-response-single:
      allOf:
      - $ref: '#/components/schemas/tunnel_schemas-api-response-common'
      type: object
    tunnel_timestamp:
      example: '2014-01-01T05:20:00.12345Z'
      format: date-time
      type: string
    tunnel_ingressRule:
      description: Public hostname
      properties:
        hostname:
          description: Public hostname for this service.
          example: tunnel.example.com
          type: string
        originRequest:
          $ref: '#/components/schemas/tunnel_originRequest'
        path:
          default: ''
          description: Requests with this path route to this public hostname.
          example: subpath
          type: string
        service:
          description: 'Protocol and address of destination server. Supported protocols: http://, https://, unix://, tcp://, ssh://, rdp://, unix+tls://, smb://. Alternatively can return a HTTP status code http_status:[code] e.g. ''http_status:404''.

            '
          example: https://localhost:8001
          type: string
      required:
      - hostname
      - service
      type: object
    tunnel_schemas-config_version:
      description: The version of the Tunnel Configuration.
      type: integer
    tunnel_config:
      description: The tunnel configuration and ingress rules.
      properties:
        ingress:
          description: List of public hostname definitions. At least one ingress rule needs to be defined for the tunnel.
          items:
            $ref: '#/components/schemas/tunnel_ingressRule'
          minItems: 1
          type: array
        originRequest:
          $ref: '#/components/schemas/tunnel_originRequest'
        warp-routing:
          description: Enable private network access from WARP users to private network routes. This is enabled if the tunnel has an assigned route.
          properties:
            enabled:
              default: false
              type: boolean
          readOnly: true
          type: object
      type: object
    tunnel_configuration:
      description: Cloudflare Tunnel configuration
      properties:
        account_id:
          $ref: '#/components/schemas/tunnel_identifier'
        config:
          $ref: '#/components/schemas/tunnel_config'
        created_at:
          $ref: '#/components/schemas/tunnel_timestamp'
        source:
          $ref: '#/components/schemas/tunnel_schemas-config_src'
        tunnel_id:
          $ref: '#/components/schemas/tunnel_tunnel_id'
        version:
          $ref: '#/components/schemas/tunnel_schemas-config_version'
      type: object
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/apigateway/
x-hasEquivalentPaths: true
