openapi: 3.2.0
info:
  description: 'To get started using Cloudflare''s products and services via the API, refer to [how to interact with Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/), which covers using tools like [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform) and the [official SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows who is making requests and what permissions you have. Create an API token to grant access to the API to perform actions.


    To create an API token, from the Cloudflare dashboard, go to My Profile > API Tokens and select Create Token. For more information on how to create and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).'
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: APIs.io Engineering Platform Cloudflare Zero Trust Connectivity Settings API
  version: 4.0.0
tags:
- name: Zero Trust Connectivity Settings
paths:
  /accounts/{account_id}/zerotrust/connectivity_settings:
    get:
      description: Gets the Zero Trust Connectivity Settings for the given account.
      operationId: zero-trust-accounts-get-connectivity-settings
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/tunnel_account_id'
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tunnel_api-response-common-failure'
          description: Get Zero Trust Connectivity Settings response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tunnel_zero_trust_connectivity_settings_response'
          description: Get Zero Trust Connectivity Settings response
      security:
      - api_email: []
        api_key: []
      - api_token: []
      - user_service_key: []
      summary: APIs.io Engineering Platform Get Zero Trust Connectivity Settings
      tags:
      - Zero Trust Connectivity Settings
      x-api-token-group:
      - Teams Report
      - Teams Read
      - Teams Write
    patch:
      description: Updates the Zero Trust Connectivity Settings for the given account.
      operationId: zero-trust-accounts-patch-connectivity-settings
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/tunnel_account_id'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                icmp_proxy_enabled:
                  $ref: '#/components/schemas/tunnel_icmp_proxy_enabled'
                offramp_warp_enabled:
                  $ref: '#/components/schemas/tunnel_offramp_warp_enabled'
              type: object
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tunnel_api-response-common-failure'
          description: Update Zero Trust Connectivity Settings response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tunnel_zero_trust_connectivity_settings_response'
          description: Update Zero Trust Connectivity Settings response
      security:
      - api_email: []
        api_key: []
      - api_token: []
      - user_service_key: []
      summary: APIs.io Engineering Platform Updates the Zero Trust Connectivity Settings
      tags:
      - Zero Trust Connectivity Settings
      x-api-token-group:
      - Teams Write
components:
  schemas:
    tunnel_api-response-single:
      $ref: '#/components/schemas/tunnel_api-response-common'
    tunnel_icmp_proxy_enabled:
      description: A flag to enable the ICMP proxy for the account network.
      example: true
      type: boolean
    tunnel_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    tunnel_offramp_warp_enabled:
      description: A flag to enable WARP to WARP traffic.
      example: true
      type: boolean
    tunnel_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/tunnel_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/tunnel_messages'
          example: []
        result:
          enum:
          - null
          type:
          - object
          - 'null'
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    tunnel_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/tunnel_messages'
        messages:
          $ref: '#/components/schemas/tunnel_messages'
        result:
          anyOf:
          - type: object
          - items: {}
            type: array
          - type: string
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    tunnel_account_id:
      description: Cloudflare account ID
      example: 699d98642c564d2e855e9661899b7252
      maxLength: 32
      type: string
    tunnel_zero_trust_connectivity_settings_response:
      allOf:
      - $ref: '#/components/schemas/tunnel_api-response-single'
      - properties:
          result:
            properties:
              icmp_proxy_enabled:
                $ref: '#/components/schemas/tunnel_icmp_proxy_enabled'
              offramp_warp_enabled:
                $ref: '#/components/schemas/tunnel_offramp_warp_enabled'
            type: object
        type: object
  securitySchemes:
    api_email:
      in: header
      name: X-Auth-Email
      type: apiKey
    api_key:
      in: header
      name: X-Auth-Key
      type: apiKey
    api_token:
      scheme: bearer
      type: http
    user_service_key:
      in: header
      name: X-Auth-User-Service-Key
      type: apiKey
