openapi: 3.0.0
info:
  version: 2015-07-09
  x-release: v4
  title: APIs.io Engineering Platform Amazon API Gateway 2014 11 13 Magic Connectors API
  description: <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: apigateway
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/apigateway-2015-07-09.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: https://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: http://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
- url: https://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: Magic Connectors
paths:
  /accounts/{account_id}/magic/connectors:
    get:
      operationId: mconn-connector-list
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/mconn_account_id'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mconn_customer_connector_list_response'
          description: OK
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mconn_bad_response'
          description: Bad Request
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mconn_bad_response'
          description: Unauthorized
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mconn_bad_response'
          description: Forbidden
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mconn_bad_response'
          description: Internal Server Error
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform List Connectors
      tags:
      - Magic Connectors
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
  /accounts/{account_id}/magic/connectors/{connector_id}:
    get:
      operationId: mconn-connector-fetch
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/mconn_account_id'
      - in: path
        name: connector_id
        required: true
        schema:
          $ref: '#/components/schemas/mconn_uuid'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mconn_customer_connector_fetch_response'
          description: OK
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mconn_bad_response'
          description: Bad Request
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mconn_bad_response'
          description: Unauthorized
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mconn_bad_response'
          description: Forbidden
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mconn_bad_response'
          description: Internal Server Error
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Fetch Connector
      tags:
      - Magic Connectors
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    patch:
      operationId: mconn-connector-update
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/mconn_account_id'
      - in: path
        name: connector_id
        required: true
        schema:
          $ref: '#/components/schemas/mconn_uuid'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/mconn_customer_connector_update_request'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mconn_customer_connector_update_response'
          description: OK
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mconn_bad_response'
          description: Bad Request
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mconn_bad_response'
          description: Unauthorized
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mconn_bad_response'
          description: Forbidden
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mconn_bad_response'
          description: Internal Server Error
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Update Connector
      tags:
      - Magic Connectors
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    put:
      operationId: mconn-connector-replace
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/mconn_account_id'
      - in: path
        name: connector_id
        required: true
        schema:
          $ref: '#/components/schemas/mconn_uuid'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/mconn_customer_connector_update_request'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mconn_customer_connector_update_response'
          description: OK
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mconn_bad_response'
          description: Bad Request
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mconn_bad_response'
          description: Unauthorized
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mconn_bad_response'
          description: Forbidden
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mconn_bad_response'
          description: Internal Server Error
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Replace Connector
      tags:
      - Magic Connectors
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
components:
  schemas:
    mconn_response:
      properties:
        messages:
          items:
            $ref: '#/components/schemas/mconn_coded_message'
          type: array
        success:
          type: boolean
      required:
      - result
      - success
      - errors
      - messages
      type: object
    mconn_customer_connector_fields:
      properties:
        activated:
          type: boolean
        interrupt_window_duration_hours:
          type: number
        interrupt_window_hour_of_day:
          type: number
        notes:
          type: string
        timezone:
          type: string
      type: object
    mconn_customer_device:
      properties:
        id:
          $ref: '#/components/schemas/mconn_uuid'
        serial_number:
          type: string
      required:
      - id
      type: object
    mconn_customer_connector:
      properties:
        activated:
          type: boolean
        device:
          $ref: '#/components/schemas/mconn_customer_device'
        id:
          $ref: '#/components/schemas/mconn_uuid'
        interrupt_window_duration_hours:
          type: number
        interrupt_window_hour_of_day:
          type: number
        last_heartbeat:
          type: string
        last_seen_version:
          type: string
        last_updated:
          type: string
        notes:
          type: string
        timezone:
          type: string
      required:
      - id
      - notes
      - activated
      - last_updated
      - timezone
      - interrupt_window_hour_of_day
      - interrupt_window_duration_hours
      type: object
    mconn_bad_response:
      allOf:
      - $ref: '#/components/schemas/mconn_response'
      - properties:
          errors:
            items:
              $ref: '#/components/schemas/mconn_coded_message'
            minLength: 1
            type: array
          result:
            $ref: '#/components/schemas/mconn_none'
    mconn_good_response:
      allOf:
      - $ref: '#/components/schemas/mconn_response'
      - properties:
          errors:
            items:
              $ref: '#/components/schemas/mconn_coded_message'
            maxLength: 0
            type: array
    mconn_customer_connector_fetch_response:
      allOf:
      - $ref: '#/components/schemas/mconn_good_response'
      - properties:
          result:
            $ref: '#/components/schemas/mconn_customer_connector'
    mconn_customer_connector_update_response:
      allOf:
      - $ref: '#/components/schemas/mconn_good_response'
      - properties:
          result:
            $ref: '#/components/schemas/mconn_customer_connector'
    mconn_account_id:
      description: Account identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      readOnly: true
      type: string
    mconn_customer_connector_list_response:
      allOf:
      - $ref: '#/components/schemas/mconn_good_response'
      - properties:
          result:
            items:
              $ref: '#/components/schemas/mconn_customer_connector'
            type: array
    mconn_none:
      nullable: true
      type: object
    mconn_uuid:
      type: string
    mconn_customer_connector_update_request:
      $ref: '#/components/schemas/mconn_customer_connector_fields'
    mconn_coded_message:
      properties:
        code:
          minimum: 1000
          type: integer
        message:
          type: string
      required:
      - code
      - message
      type: object
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/apigateway/
x-hasEquivalentPaths: true
