openapi: 3.0.0
info:
  version: "1.0.0"
  x-release: v4
  title: APIs.io Engineering Platform Amazon API Gateway 2014 11 13 Load Balancer Regions API
  description: <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: apigateway
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/apigateway-2015-07-09.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: https://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: http://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
- url: https://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: Load Balancer Regions
paths:
  /accounts/{account_id}/load_balancers/regions:
    get:
      description: List all region mappings.
      operationId: load-balancer-regions-list-regions
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/load-balancing_components-schemas-identifier'
      - in: query
        name: subdivision_code
        schema:
          $ref: '#/components/schemas/load-balancing_subdivision_code_a2'
      - in: query
        name: subdivision_code_a2
        schema:
          $ref: '#/components/schemas/load-balancing_subdivision_code_a2'
      - in: query
        name: country_code_a2
        schema:
          description: Two-letter alpha-2 country code followed in ISO 3166-1.
          example: US
          type: string
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/load-balancing_region_components-schemas-response_collection'
                - $ref: '#/components/schemas/load-balancing_api-response-common-failure'
          description: List Regions response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/load-balancing_region_components-schemas-response_collection'
          description: List Regions response
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform List Regions
      tags:
      - Load Balancer Regions
      x-api-token-group:
      - 'Load Balancing: Monitors and Pools Read'
  /accounts/{account_id}/load_balancers/regions/{region_id}:
    get:
      description: Get a single region mapping.
      operationId: load-balancer-regions-get-region
      parameters:
      - in: path
        name: region_id
        required: true
        schema:
          $ref: '#/components/schemas/load-balancing_region_code'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/load-balancing_components-schemas-identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/load-balancing_components-schemas-single_response'
                - $ref: '#/components/schemas/load-balancing_api-response-common-failure'
          description: Get Region response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/load-balancing_components-schemas-single_response'
          description: Get Region response
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Get Region
      tags:
      - Load Balancer Regions
components:
  schemas:
    load-balancing_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    load-balancing_subdivision_code_a2:
      description: Two-letter subdivision code followed in ISO 3166-2.
      example: CA
      type: string
    load-balancing_region_code:
      description: 'A list of Cloudflare regions. WNAM: Western North America, ENAM: Eastern North America, WEU: Western Europe, EEU: Eastern Europe, NSAM: Northern South America, SSAM: Southern South America, OC: Oceania, ME: Middle East, NAF: North Africa, SAF: South Africa, SAS: Southern Asia, SEAS: South East Asia, NEAS: North East Asia).'
      enum:
      - WNAM
      - ENAM
      - WEU
      - EEU
      - NSAM
      - SSAM
      - OC
      - ME
      - NAF
      - SAF
      - SAS
      - SEAS
      - NEAS
      example: WNAM
      type: string
    load-balancing_components-schemas-single_response:
      allOf:
      - $ref: '#/components/schemas/load-balancing_api-response-single'
      - properties:
          result:
            description: A list of countries and subdivisions mapped to a region.
            example:
              iso_standard: Country and subdivision codes follow ISO 3166-1 alpha-2 and ISO 3166-2
              regions:
              - countries:
                - country_code_a2: CA
                  country_name: Canada
                  country_subdivisions:
                  - subdivision_code_a2: AB
                    subdivision_name: Alberta
                  - subdivision_code_a2: BC
                    subdivision_name: British Columbia
                - country_code_a2: HT
                  country_name: Haiti
                - country_code_a2: MX
                  country_name: Mexico
                - country_code_a2: US
                  country_name: United States
                  country_subdivisions:
                  - subdivision_code_a2: AZ
                    subdivision_name: Arizona
                  - subdivision_code_a2: CA
                    subdivision_name: California
                  - subdivision_code_a2: CO
                    subdivision_name: Colorado
                  - subdivision_code_a2: HI
                    subdivision_name: Hawaii
                  - subdivision_code_a2: MN
                    subdivision_name: Minnesota
                  - subdivision_code_a2: MO
                    subdivision_name: Missouri
                  - subdivision_code_a2: NV
                    subdivision_name: Nevada
                  - subdivision_code_a2: OR
                    subdivision_name: Oregon
                  - subdivision_code_a2: TX
                    subdivision_name: Texas
                  - subdivision_code_a2: UT
                    subdivision_name: Utah
                  - subdivision_code_a2: WA
                    subdivision_name: Washington
                region_code: WNAM
            type: object
    load-balancing_region_components-schemas-response_collection:
      allOf:
      - $ref: '#/components/schemas/load-balancing_api-response-single'
      - properties:
          result:
            type: object
    load-balancing_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/load-balancing_messages'
        messages:
          $ref: '#/components/schemas/load-balancing_messages'
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    load-balancing_components-schemas-identifier:
      description: Identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      readOnly: true
      type: string
    load-balancing_api-response-single:
      allOf:
      - $ref: '#/components/schemas/load-balancing_api-response-common'
      - properties:
          result:
            anyOf:
            - nullable: true
              type: object
            - nullable: true
              type: string
      type: object
    load-balancing_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/load-balancing_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/load-balancing_messages'
          example: []
        result:
          enum:
          - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/apigateway/
x-hasEquivalentPaths: true
