openapi: 3.0.0
info:
  version: 2015-07-09
  x-release: v4
  title: 'APIs.io Engineering Platform Amazon API Gateway 2014 11 13 #Action=GetOpenIDConnectProvider API'
  description: <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: apigateway
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/apigateway-2015-07-09.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: https://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: http://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
- url: https://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#Action=GetOpenIDConnectProvider'
paths:
  /#Action=GetOpenIDConnectProvider:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    get:
      x-aws-operation-name: GetOpenIDConnectProvider
      operationId: GET_GetOpenIDConnectProvider
      description: Returns information about the specified OpenID Connect (OIDC) provider resource object in IAM.
      responses:
        '200':
          description: Success
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/GetOpenIDConnectProviderResponse'
        '480':
          description: InvalidInputException
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/InvalidInputException'
        '481':
          description: NoSuchEntityException
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/NoSuchEntityException'
        '482':
          description: ServiceFailureException
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/ServiceFailureException'
      parameters:
      - name: OpenIDConnectProviderArn
        in: query
        required: true
        description: <p>The Amazon Resource Name (ARN) of the OIDC provider resource object in IAM to get information for. You can get a list of OIDC provider resource ARNs by using the <a>ListOpenIDConnectProviders</a> operation.</p> <p>For more information about ARNs, see <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html">Amazon Resource Names (ARNs)</a> in the <i>Amazon Web Services General Reference</i>.</p>
        schema:
          type: string
          description: <p>The Amazon Resource Name (ARN). ARNs are unique identifiers for Amazon Web Services resources.</p> <p>For more information about ARNs, go to <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html">Amazon Resource Names (ARNs)</a> in the <i>Amazon Web Services General Reference</i>. </p>
          minLength: 20
          maxLength: 2048
      - name: Action
        in: query
        required: true
        schema:
          type: string
          enum:
          - GetOpenIDConnectProvider
      - name: Version
        in: query
        required: true
        schema:
          type: string
          enum:
          - 2010-05-08
      tags:
      - '#Action=GetOpenIDConnectProvider'
    post:
      x-aws-operation-name: GetOpenIDConnectProvider
      operationId: POST_GetOpenIDConnectProvider
      description: Returns information about the specified OpenID Connect (OIDC) provider resource object in IAM.
      responses:
        '200':
          description: Success
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/GetOpenIDConnectProviderResponse'
        '480':
          description: InvalidInputException
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/InvalidInputException'
        '481':
          description: NoSuchEntityException
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/NoSuchEntityException'
        '482':
          description: ServiceFailureException
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/ServiceFailureException'
      requestBody:
        content:
          text/xml:
            schema:
              $ref: '#/components/schemas/GetOpenIDConnectProviderRequest'
      parameters:
      - name: Action
        in: query
        required: true
        schema:
          type: string
          enum:
          - GetOpenIDConnectProvider
      - name: Version
        in: query
        required: true
        schema:
          type: string
          enum:
          - 2010-05-08
      tags:
      - '#Action=GetOpenIDConnectProvider'
components:
  parameters:
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
  schemas:
    InvalidInputException: {}
    tagListType:
      type: array
      items:
        $ref: '#/components/schemas/Tag'
      maxItems: 50
    Tag:
      type: object
      required:
      - Key
      - Value
      properties:
        Key:
          allOf:
          - $ref: '#/components/schemas/tagKeyType'
          - description: The key name that can be used to look up or retrieve the associated value. For example, <code>Department</code> or <code>Cost Center</code> are common choices.
        Value:
          allOf:
          - $ref: '#/components/schemas/tagValueType'
          - description: <p>The value associated with this tag. For example, tags with a key name of <code>Department</code> could have values such as <code>Human Resources</code>, <code>Accounting</code>, and <code>Support</code>. Tags with a key name of <code>Cost Center</code> might have values that consist of the number associated with the different cost centers in your company. Typically, many resources have tags with the same key name but with different values.</p> <note> <p>Amazon Web Services always interprets the tag <code>Value</code> as a single string. If you need to store an array, you can store comma-separated values in the string. However, you must interpret the value in your code.</p> </note>
      description: A structure that represents user-provided metadata that can be associated with an IAM resource. For more information about tagging, see <a href="https://docs.aws.amazon.com/IAM/latest/UserGuide/id_tags.html">Tagging IAM resources</a> in the <i>IAM User Guide</i>.
    arnType:
      type: string
      description: <p>The Amazon Resource Name (ARN). ARNs are unique identifiers for Amazon Web Services resources.</p> <p>For more information about ARNs, go to <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html">Amazon Resource Names (ARNs)</a> in the <i>Amazon Web Services General Reference</i>. </p>
      minLength: 20
      maxLength: 2048
    GetOpenIDConnectProviderResponse:
      type: object
      properties:
        Url:
          allOf:
          - $ref: '#/components/schemas/OpenIDConnectProviderUrlType'
          - description: The URL that the IAM OIDC provider resource object is associated with. For more information, see <a>CreateOpenIDConnectProvider</a>.
        ClientIDList:
          allOf:
          - $ref: '#/components/schemas/clientIDListType'
          - description: A list of client IDs (also known as audiences) that are associated with the specified IAM OIDC provider resource object. For more information, see <a>CreateOpenIDConnectProvider</a>.
        ThumbprintList:
          allOf:
          - $ref: '#/components/schemas/thumbprintListType'
          - description: 'A list of certificate thumbprints that are associated with the specified IAM OIDC provider resource object. For more information, see <a>CreateOpenIDConnectProvider</a>. '
        CreateDate:
          allOf:
          - $ref: '#/components/schemas/dateType'
          - description: The date and time when the IAM OIDC provider resource object was created in the Amazon Web Services account.
        Tags:
          allOf:
          - $ref: '#/components/schemas/tagListType'
          - description: A list of tags that are attached to the specified IAM OIDC provider. The returned list of tags is sorted by tag key. For more information about tagging, see <a href="https://docs.aws.amazon.com/IAM/latest/UserGuide/id_tags.html">Tagging IAM resources</a> in the <i>IAM User Guide</i>.
      description: 'Contains the response to a successful <a>GetOpenIDConnectProvider</a> request. '
    clientIDListType:
      type: array
      items:
        $ref: '#/components/schemas/clientIDType'
    tagKeyType:
      type: string
      pattern: '[\p{L}\p{Z}\p{N}_.:/=+\-@]+'
      minLength: 1
      maxLength: 128
    tagValueType:
      type: string
      pattern: '[\p{L}\p{Z}\p{N}_.:/=+\-@]*'
      minLength: 0
      maxLength: 256
    thumbprintType:
      type: string
      description: <p>Contains a thumbprint for an identity provider's server certificate.</p> <p>The identity provider's server certificate thumbprint is the hex-encoded SHA-1 hash value of the self-signed X.509 certificate. This thumbprint is used by the domain where the OpenID Connect provider makes its keys available. The thumbprint is always a 40-character string.</p>
      minLength: 40
      maxLength: 40
    GetOpenIDConnectProviderRequest:
      type: object
      required:
      - OpenIDConnectProviderArn
      title: GetOpenIDConnectProviderRequest
      properties:
        OpenIDConnectProviderArn:
          allOf:
          - $ref: '#/components/schemas/arnType'
          - description: <p>The Amazon Resource Name (ARN) of the OIDC provider resource object in IAM to get information for. You can get a list of OIDC provider resource ARNs by using the <a>ListOpenIDConnectProviders</a> operation.</p> <p>For more information about ARNs, see <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html">Amazon Resource Names (ARNs)</a> in the <i>Amazon Web Services General Reference</i>.</p>
    NoSuchEntityException: {}
    dateType:
      type: string
      format: date-time
    ServiceFailureException: {}
    OpenIDConnectProviderUrlType:
      type: string
      description: Contains a URL that specifies the endpoint for an OpenID Connect provider.
      minLength: 1
      maxLength: 255
    thumbprintListType:
      type: array
      description: Contains a list of thumbprints of identity provider server certificates.
      items:
        $ref: '#/components/schemas/thumbprintType'
    clientIDType:
      type: string
      minLength: 1
      maxLength: 255
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/apigateway/
x-hasEquivalentPaths: true
