openapi: 3.0.0
info:
  version: 2015-07-09
  x-release: v4
  title: 'APIs.io Engineering Platform Amazon API Gateway 2014 11 13 #Action=GetServerCertificate API'
  description: <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: apigateway
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/apigateway-2015-07-09.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: https://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: http://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
- url: https://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#Action=GetServerCertificate'
paths:
  /#Action=GetServerCertificate:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    get:
      x-aws-operation-name: GetServerCertificate
      operationId: GET_GetServerCertificate
      description: <p>Retrieves information about the specified server certificate stored in IAM.</p> <p>For more information about working with server certificates, see <a href="https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_server-certs.html">Working with server certificates</a> in the <i>IAM User Guide</i>. This topic includes a list of Amazon Web Services services that can use the server certificates that you manage with IAM.</p>
      responses:
        '200':
          description: Success
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/GetServerCertificateResponse'
        '480':
          description: NoSuchEntityException
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/NoSuchEntityException'
        '481':
          description: ServiceFailureException
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/ServiceFailureException'
      parameters:
      - name: ServerCertificateName
        in: query
        required: true
        description: '<p>The name of the server certificate you want to retrieve information about.</p> <p>This parameter allows (through its <a href="http://wikipedia.org/wiki/regex">regex pattern</a>) a string of characters consisting of upper and lowercase alphanumeric characters with no spaces. You can also include any of the following characters: _+=,.@-</p>'
        schema:
          type: string
          pattern: '[\w+=,.@-]+'
          minLength: 1
          maxLength: 128
      - name: Action
        in: query
        required: true
        schema:
          type: string
          enum:
          - GetServerCertificate
      - name: Version
        in: query
        required: true
        schema:
          type: string
          enum:
          - 2010-05-08
      tags:
      - '#Action=GetServerCertificate'
    post:
      x-aws-operation-name: GetServerCertificate
      operationId: POST_GetServerCertificate
      description: <p>Retrieves information about the specified server certificate stored in IAM.</p> <p>For more information about working with server certificates, see <a href="https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_server-certs.html">Working with server certificates</a> in the <i>IAM User Guide</i>. This topic includes a list of Amazon Web Services services that can use the server certificates that you manage with IAM.</p>
      responses:
        '200':
          description: Success
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/GetServerCertificateResponse'
        '480':
          description: NoSuchEntityException
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/NoSuchEntityException'
        '481':
          description: ServiceFailureException
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/ServiceFailureException'
      requestBody:
        content:
          text/xml:
            schema:
              $ref: '#/components/schemas/GetServerCertificateRequest'
      parameters:
      - name: Action
        in: query
        required: true
        schema:
          type: string
          enum:
          - GetServerCertificate
      - name: Version
        in: query
        required: true
        schema:
          type: string
          enum:
          - 2010-05-08
      tags:
      - '#Action=GetServerCertificate'
components:
  parameters:
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
  schemas:
    tagListType:
      type: array
      items:
        $ref: '#/components/schemas/Tag'
      maxItems: 50
    Tag:
      type: object
      required:
      - Key
      - Value
      properties:
        Key:
          allOf:
          - $ref: '#/components/schemas/tagKeyType'
          - description: The key name that can be used to look up or retrieve the associated value. For example, <code>Department</code> or <code>Cost Center</code> are common choices.
        Value:
          allOf:
          - $ref: '#/components/schemas/tagValueType'
          - description: <p>The value associated with this tag. For example, tags with a key name of <code>Department</code> could have values such as <code>Human Resources</code>, <code>Accounting</code>, and <code>Support</code>. Tags with a key name of <code>Cost Center</code> might have values that consist of the number associated with the different cost centers in your company. Typically, many resources have tags with the same key name but with different values.</p> <note> <p>Amazon Web Services always interprets the tag <code>Value</code> as a single string. If you need to store an array, you can store comma-separated values in the string. However, you must interpret the value in your code.</p> </note>
      description: A structure that represents user-provided metadata that can be associated with an IAM resource. For more information about tagging, see <a href="https://docs.aws.amazon.com/IAM/latest/UserGuide/id_tags.html">Tagging IAM resources</a> in the <i>IAM User Guide</i>.
    arnType:
      type: string
      description: <p>The Amazon Resource Name (ARN). ARNs are unique identifiers for Amazon Web Services resources.</p> <p>For more information about ARNs, go to <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html">Amazon Resource Names (ARNs)</a> in the <i>Amazon Web Services General Reference</i>. </p>
      minLength: 20
      maxLength: 2048
    pathType:
      type: string
      pattern: (\u002F)|(\u002F[\u0021-\u007F]+\u002F)
      minLength: 1
      maxLength: 512
    GetServerCertificateRequest:
      type: object
      required:
      - ServerCertificateName
      title: GetServerCertificateRequest
      properties:
        ServerCertificateName:
          allOf:
          - $ref: '#/components/schemas/serverCertificateNameType'
          - description: '<p>The name of the server certificate you want to retrieve information about.</p> <p>This parameter allows (through its <a href="http://wikipedia.org/wiki/regex">regex pattern</a>) a string of characters consisting of upper and lowercase alphanumeric characters with no spaces. You can also include any of the following characters: _+=,.@-</p>'
    tagKeyType:
      type: string
      pattern: '[\p{L}\p{Z}\p{N}_.:/=+\-@]+'
      minLength: 1
      maxLength: 128
    tagValueType:
      type: string
      pattern: '[\p{L}\p{Z}\p{N}_.:/=+\-@]*'
      minLength: 0
      maxLength: 256
    GetServerCertificateResponse:
      type: object
      required:
      - ServerCertificate
      properties:
        ServerCertificate:
          allOf:
          - $ref: '#/components/schemas/ServerCertificate'
          - description: A structure containing details about the server certificate.
      description: 'Contains the response to a successful <a>GetServerCertificate</a> request. '
    idType:
      type: string
      pattern: '[\w]+'
      minLength: 16
      maxLength: 128
    certificateChainType:
      type: string
      pattern: '[\u0009\u000A\u000D\u0020-\u00FF]+'
      minLength: 1
      maxLength: 2097152
    certificateBodyType:
      type: string
      pattern: '[\u0009\u000A\u000D\u0020-\u00FF]+'
      minLength: 1
      maxLength: 16384
    serverCertificateNameType:
      type: string
      pattern: '[\w+=,.@-]+'
      minLength: 1
      maxLength: 128
    NoSuchEntityException: {}
    dateType:
      type: string
      format: date-time
    ServiceFailureException: {}
    ServerCertificateMetadata:
      type: object
      required:
      - Path
      - ServerCertificateName
      - ServerCertificateId
      - Arn
      properties:
        Path:
          allOf:
          - $ref: '#/components/schemas/pathType'
          - description: ' The path to the server certificate. For more information about paths, see <a href="https://docs.aws.amazon.com/IAM/latest/UserGuide/Using_Identifiers.html">IAM identifiers</a> in the <i>IAM User Guide</i>. '
        ServerCertificateName:
          allOf:
          - $ref: '#/components/schemas/serverCertificateNameType'
          - description: The name that identifies the server certificate.
        ServerCertificateId:
          allOf:
          - $ref: '#/components/schemas/idType'
          - description: ' The stable and unique string identifying the server certificate. For more information about IDs, see <a href="https://docs.aws.amazon.com/IAM/latest/UserGuide/Using_Identifiers.html">IAM identifiers</a> in the <i>IAM User Guide</i>. '
        Arn:
          allOf:
          - $ref: '#/components/schemas/arnType'
          - description: ' The Amazon Resource Name (ARN) specifying the server certificate. For more information about ARNs and how to use them in policies, see <a href="https://docs.aws.amazon.com/IAM/latest/UserGuide/Using_Identifiers.html">IAM identifiers</a> in the <i>IAM User Guide</i>. '
        UploadDate:
          allOf:
          - $ref: '#/components/schemas/dateType'
          - description: The date when the server certificate was uploaded.
        Expiration:
          allOf:
          - $ref: '#/components/schemas/dateType'
          - description: The date on which the certificate is set to expire.
      description: <p>Contains information about a server certificate without its certificate body, certificate chain, and private key.</p> <p> This data type is used as a response element in the <a>UploadServerCertificate</a> and <a>ListServerCertificates</a> operations. </p>
    ServerCertificate:
      type: object
      required:
      - ServerCertificateMetadata
      - CertificateBody
      properties:
        ServerCertificateMetadata:
          allOf:
          - $ref: '#/components/schemas/ServerCertificateMetadata'
          - description: The meta information of the server certificate, such as its name, path, ID, and ARN.
        CertificateBody:
          allOf:
          - $ref: '#/components/schemas/certificateBodyType'
          - description: The contents of the public key certificate.
        CertificateChain:
          allOf:
          - $ref: '#/components/schemas/certificateChainType'
          - description: The contents of the public key certificate chain.
        Tags:
          allOf:
          - $ref: '#/components/schemas/tagListType'
          - description: A list of tags that are attached to the server certificate. For more information about tagging, see <a href="https://docs.aws.amazon.com/IAM/latest/UserGuide/id_tags.html">Tagging IAM resources</a> in the <i>IAM User Guide</i>.
      description: <p>Contains information about a server certificate.</p> <p> This data type is used as a response element in the <a>GetServerCertificate</a> operation. </p>
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/apigateway/
x-hasEquivalentPaths: true
