openapi: 3.0.0
info:
  version: "1.0.0"
  x-release: v4
  title: APIs.io Engineering Platform Amazon API Gateway 2014 11 13 Webhooks API
  description: <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: apigateway
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/apigateway-2015-07-09.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: https://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: http://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
- url: https://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: Webhooks
  description: The **Webhooks** endpoints enable you to manage [custom webhooks](https://learning.postman.com/docs/running-collections/collection-webhooks/).
paths:
  /webhooks:
    post:
      summary: APIs.io Engineering Platform Create a webhook
      description: Creates a webhook that triggers a collection with a custom payload. You can get the webhook's URL from the `webhookUrl` property in the endpoint's response.
      operationId: createWebhook
      tags:
      - Webhooks
      requestBody:
        $ref: '#/components/requestBodies/createWebhook'
      responses:
        '200':
          $ref: '#/components/responses/createWebhook'
        '400':
          $ref: '#/components/responses/createWebhookParamMissing400Error'
        '401':
          $ref: '#/components/responses/common401Error'
        '403':
          $ref: '#/components/responses/featureUnavailable403Error'
        '500':
          $ref: '#/components/responses/common500ErrorServerError'
      parameters:
      - $ref: '#/components/parameters/workspaceQuery'
components:
  responses:
    createWebhookParamMissing400Error:
      description: Missing Parameter
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/createWebhookParamMissing400Error'
          example:
            error:
              name: paramMissingError
              message: Parameter is missing in the request.
              details:
                param:
                - collection
    common500ErrorServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: object
                properties:
                  name:
                    type: string
                    description: The error name.
                    example: serverError
                  message:
                    type: string
                    description: The error message.
                    example: An error has occurred on the server.
          example:
            error:
              name: serverError
              message: An error has occurred on the server.
    featureUnavailable403Error:
      description: Feature Unavailable
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/featureUnavailable403Error'
          example:
            value:
              type: https://api.postman.com/problems/forbidden
              title: Forbidden
              detail: This feature isn't available in your region.
              status: 403
    createWebhook:
      description: Successful Response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/createWebhookResponse'
          example:
            webhook:
              id: 1f0df51a-8658-4ee8-a2a1-d2567dfa09a9
              name: Test Webhook
              collection: 12345678-12ece9e1-2abf-4edc-8e34-de66e74114d2
              webhookUrl: https://newman-api.getpostman.com/run/12345678/267a6e99-b6da-407c-a96f-03be2d6282fb
              uid: 12345678-1f0df51a-8658-4ee8-a2a1-d2567dfa09a9
    common401Error:
      description: Unauthorized
      content:
        application/problem+json:
          schema:
            type: object
            properties:
              type:
                type: string
                format: uri-reference
                description: The [URI reference](https://www.rfc-editor.org/rfc/rfc3986) that identifies the type of problem.
                example: https://api.postman.com/problems/unauthorized
              title:
                type: string
                description: A short summary of the problem.
                example: Unauthorized
              detail:
                type: string
                description: Information about the error.
                example: Unauthorized
              status:
                type: integer
                format: http-status-code
                description: The error's HTTP status code.
                example: 401
          example:
            type: https://api.postman.com/problems/unauthorized
            title: Unauthorized
            detail: Unauthorized
            status: 401
  schemas:
    workspaceId:
      type: string
      example: 1f0df51a-8658-4ee8-a2a1-d2567dfa09a9
    featureUnavailable403Error:
      title: Feature Unavailable
      type: object
      properties:
        type:
          type: string
          format: uri-reference
          description: The [URI reference](https://www.rfc-editor.org/rfc/rfc3986) that identifies the type of problem.
          example: https://api.postman.com/problems/forbidden
        title:
          type: string
          description: A short summary of the problem.
          example: Forbidden
        detail:
          type: string
          description: Information about the error.
          example: This feature isn't available in your region.
        status:
          type: integer
          format: http-status-code
          description: The error's HTTP status code.
          example: 403
    createWebhookRequest:
      title: Create Webhook Request Body
      type: object
      properties:
        webhook:
          type: object
          required:
          - name
          - collection
          properties:
            collection:
              type: string
              format: uid
              description: The unique ID of the collection to trigger when calling this webhook.
              example: 12345678-12ece9e1-2abf-4edc-8e34-de66e74114d2
            environment:
              type: string
              format: uid
              description: The unique ID of the environment to trigger when calling this webhook.
              example: 12345678-d9c7dc8f-904e-4bba-99b5-4d490aae1957
            name:
              type: string
              description: The webhook's name. On success, the system creates a new monitor with this name in the **Monitors** tab.
              example: Test Webhook
    createWebhookResponse:
      title: Successful Response
      type: object
      properties:
        webhook:
          type: object
          properties:
            id:
              type: string
              description: The webhook's ID.
              example: 1f0df51a-8658-4ee8-a2a1-d2567dfa09a9
            name:
              type: string
              description: The webhook's name.
              example: Test Webhook
            collection:
              type: string
              format: uid
              description: The unique ID of the collection that triggers when calling this webhook.
              example: 12345678-12ece9e1-2abf-4edc-8e34-de66e74114d2
            webhookUrl:
              type: string
              description: The webhook's URL.
              example: https://newman-api.getpostman.com/run/12345678/267a6e99-b6da-407c-a96f-03be2d6282fb
            uid:
              type: string
              format: uid
              description: The webhook's unique ID.
              example: 12345678-1f0df51a-8658-4ee8-a2a1-d2567dfa09a9
    createWebhookParamMissing400Error:
      type: object
      properties:
        error:
          type: object
          properties:
            name:
              type: string
              description: The error name.
              example: paramMissingError
            message:
              type: string
              description: The error message.
              example: Parameter is missing in the request.
            details:
              type: object
              description: Information about the error.
              properties:
                param:
                  type: array
                  description: Information about the missing parameter.
                  items:
                    type: string
                  example:
                  - collection
  requestBodies:
    createWebhook:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/createWebhookRequest'
          example:
            webhook:
              name: Test Webhook
              collection: 12345678-12ece9e1-2abf-4edc-8e34-de66e74114d2
  parameters:
    workspaceQuery:
      name: workspace
      in: query
      description: The workspace's ID.
      schema:
        $ref: '#/components/schemas/workspaceId'
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/apigateway/
x-hasEquivalentPaths: true
