openapi: 3.0.0
info:
  version: 2015-07-09
  x-release: v4
  title: APIs.io Engineering Platform Amazon API Gateway 2014 11 13 Worker Deployments API
  description: <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: apigateway
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/apigateway-2015-07-09.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: https://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: http://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
- url: https://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: Worker Deployments
paths:
  /accounts/{account_id}/workers/scripts/{script_name}/deployments:
    get:
      description: List of Worker Deployments. The first deployment in the list is the latest deployment actively serving traffic.
      operationId: worker-deployments-list-deployments
      parameters:
      - in: path
        name: script_name
        required: true
        schema:
          $ref: '#/components/schemas/workers_schemas-script_name'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/workers_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/workers_schemas-deployments-list-response'
                - $ref: '#/components/schemas/workers_api-response-common-failure'
          description: List Deployments response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/workers_schemas-deployments-list-response'
          description: List Deployments response
      security:
      - api_token: []
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform List Deployments
      tags:
      - Worker Deployments
      x-api-token-group:
      - Workers Tail Read
      - Workers Scripts Write
      - Workers Scripts Read
      x-cfPermissionsRequired:
        enum:
        - com.cloudflare.edge.worker.deployment.list
    post:
      description: Deployments configure how [Worker Versions](https://developers.cloudflare.com/api/operations/worker-versions-list-versions) are deployed to traffic. A deployment can consist of one or two versions of a Worker.
      operationId: worker-deployments-create-deployment
      parameters:
      - in: path
        name: script_name
        required: true
        schema:
          $ref: '#/components/schemas/workers_schemas-script_name'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/workers_identifier'
      - description: If set to true, the deployment will be created even if normally blocked by something such rolling back to an older version when a secret has changed.
        in: query
        name: force
        schema:
          type: boolean
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/workers_deployments-create-body'
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/workers_schemas-deployments-single-response'
                - $ref: '#/components/schemas/workers_api-response-common-failure'
          description: Create Deployment response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/workers_schemas-deployments-single-response'
          description: Create Deployment response
      security:
      - api_token: []
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Create Deployment
      tags:
      - Worker Deployments
      x-api-token-group:
      - Workers Scripts Write
      x-cfPermissionsRequired:
        enum:
        - com.cloudflare.edge.worker.deployment.edit
components:
  schemas:
    workers_deployments-strategy-percentage:
      properties:
        strategy:
          enum:
          - percentage
          type: string
        versions:
          items:
            properties:
              percentage:
                example: 100
                maximum: 100
                minimum: 0.01
                type: number
              version_id:
                $ref: '#/components/schemas/workers_schemas-version_identifier'
            required:
            - version_id
            - percentage
            type: object
          type: array
      required:
      - strategy
      - versions
      type: object
    workers_identifier:
      description: Identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      type: string
    workers_schemas-deployment_identifier:
      example: dc78f0bc-05c5-46b7-bb4e-137f55930378
      maxLength: 36
      type: string
    workers_schemas-deployments-list-response:
      allOf:
      - $ref: '#/components/schemas/workers_api-response-common'
      - properties:
          result:
            properties:
              deployments:
                items:
                  allOf:
                  - $ref: '#/components/schemas/workers_deployments-base'
                  - oneOf:
                    - $ref: '#/components/schemas/workers_deployments-strategy-percentage'
                type: array
            type: object
        type: object
    workers_deployments-base:
      properties:
        annotations:
          properties:
            workers/message:
              description: Human-readable message about the deployment.
              example: Deploy bug fix.
              maxLength: 50
              type: string
          type: object
        author_email:
          example: user@example.com
          readOnly: true
          type: string
        created_on:
          example: '2022-11-08T17:19:29.176266Z'
          readOnly: true
          type: string
        id:
          allOf:
          - $ref: '#/components/schemas/workers_schemas-deployment_identifier'
          readOnly: true
        source:
          example: api
          readOnly: true
          type: string
        strategy:
          type: string
      type: object
    workers_schemas-deployments-single-response:
      allOf:
      - $ref: '#/components/schemas/workers_api-response-common'
      - properties:
          result:
            allOf:
            - $ref: '#/components/schemas/workers_deployments-base'
            - oneOf:
              - $ref: '#/components/schemas/workers_deployments-strategy-percentage'
        type: object
    workers_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    workers_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/workers_messages'
        messages:
          $ref: '#/components/schemas/workers_messages'
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      type: object
    workers_deployments-create-body:
      allOf:
      - $ref: '#/components/schemas/workers_deployments-base'
      - oneOf:
        - $ref: '#/components/schemas/workers_deployments-strategy-percentage'
    workers_schemas-script_name:
      description: Name of the script.
      example: this-is_my_script-01
      pattern: ^[a-z0-9_][a-z0-9-_]*$
      type: string
    workers_schemas-version_identifier:
      example: bcf48806-b317-4351-9ee7-36e7d557d4de
      maxLength: 36
      type: string
    workers_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/workers_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/workers_messages'
          example: []
        result:
          enum:
          - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/apigateway/
x-hasEquivalentPaths: true
