openapi: 3.0.0
info:
  version: "1.0.0"
  x-release: v4
  title: APIs.io Engineering Platform Amazon API Gateway 2014 11 13 Collection Access Keys API
  description: <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: apigateway
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/apigateway-2015-07-09.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: https://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: http://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
- url: https://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: Collection Access Keys
  description: 'The **Collection Access Keys** endpoints enable you to manage your [collection access keys](https://learning.postman.com/docs/developer/postman-api/authentication/#generate-a-collection-access-key). Collection access keys enable you to securely grant other users read-only access to a collection.


    Collection access keys are valid for 60 days. If unused, the access key expires after 60 days. If someone uses the access key, then its expiration date increases by another 60 days.

    '
paths:
  /collection-access-keys:
    get:
      summary: APIs.io Engineering Platform Get collection access keys
      description: 'Gets the authenticated user''s personal and team [collection access keys](https://learning.postman.com/docs/developer/postman-api/authentication/#generate-a-collection-access-key).


        **Note:**


        - The `expiresAfter` property in the response represents the date and time at which the access key expires. Collection access keys are valid for 60 days. If unused, the access key expires after 60 days. If someone uses the access key, then its expiration date increases by another 60 days.

        - If the collection key is unused, the `lastUsedAt` property in the response returns an empty string.

        '
      operationId: getCollectionAccessKeys
      tags:
      - Collection Access Keys
      responses:
        '200':
          $ref: '#/components/responses/getCollectionAccessKeys'
        '400':
          $ref: '#/components/responses/common400ErrorInvalidCursor'
        '401':
          $ref: '#/components/responses/common401Error'
        '403':
          $ref: '#/components/responses/common403ErrorForbidden'
        '500':
          $ref: '#/components/responses/common500ErrorSomethingWrong'
      parameters:
      - $ref: '#/components/parameters/collectionUidQuery'
      - $ref: '#/components/parameters/cursor'
  /collection-access-keys/{keyId}:
    delete:
      summary: APIs.io Engineering Platform Delete a collection access key
      description: 'Deletes a collection access key. To get a collection access key''s ID, use the GET `/collection-access-key` endpoint.


        On success, this returns an HTTP `204 No Content` response.

        '
      operationId: deleteCollectionAccessKey
      tags:
      - Collection Access Keys
      responses:
        '204':
          description: No Content
        '401':
          $ref: '#/components/responses/common401Error'
        '403':
          $ref: '#/components/responses/common403ErrorForbidden'
        '404':
          $ref: '#/components/responses/cakNotFound404Error'
        '500':
          $ref: '#/components/responses/common500ErrorSomethingWrong'
      parameters:
      - $ref: '#/components/parameters/collectionAccessKeyId'
components:
  parameters:
    collectionAccessKeyId:
      name: keyId
      in: path
      required: true
      description: The collection access key's ID.
      schema:
        type: string
        example: Njg5OjU3MDQ1NjYtYmQxZDU3NzktMWVkNS00ZDhjLWI0ZmQtZWRhOGY2Mzg1NTY0
    cursor:
      name: cursor
      in: query
      description: The pointer to the first record of the set of paginated results. To view the next response, use the `nextCursor` value for this parameter.
      schema:
        $ref: '#/components/schemas/cursor'
    collectionUidQuery:
      name: collectionId
      in: query
      description: Filter the results by a collection's unique ID.
      schema:
        type: string
        format: uid
        example: 12345678-12ece9e1-2abf-4edc-8e34-de66e74114d2
  schemas:
    getCollectionAccessKeys:
      title: Collection Access Keys
      type: object
      properties:
        data:
          type: array
          description: A list of collection access keys.
          items:
            type: object
            description: Information about the collection access key.
            properties:
              id:
                type: string
                description: The collection access key's ID.
                example: Njg5OjU3MDQ1NjYtYmQxZDU3NzktMWVkNS00ZDhjLWI0ZmQtZWRhOGY2Mzg1NTY0
              token:
                type: string
                description: The masked collection access key.
                example: PMAT-**********************43BR
              status:
                type: string
                description: The token's active status.
                enum:
                - ACTIVE
                - INACTIVE
                example: ACTIVE
              teamId:
                type: integer
                description: The team ID of the collection access key's owner.
                example: 123
              userId:
                type: integer
                description: The user ID of the collection access key's owner.
                example: 12345678
              collectionId:
                type: string
                format: uid
                description: The collection access key's associated collection ID.
                example: 12345678-12ece9e1-2abf-4edc-8e34-de66e74114d2
              expiresAfter:
                type: string
                format: date-time
                description: The date and time at which the collection access key expires. Collection access keys are valid for 60 days. If unused, the access key expires after 60 days. If someone uses the access key, then its expiration date increases by another 60 days.
                example: '2024-06-11T13:21:11.000Z'
              lastUsedAt:
                type: string
                description: The date and time at which the collection access key was used. If the collection key is unused, this returns an empty string value.
                example: ''
              createdAt:
                type: string
                format: date-time
                example: '2024-04-12T13:21:11.000Z'
                description: The date and time at which the collection access key was created.
              updatedAt:
                type: string
                format: date-time
                description: The date and time at which the collection access key was updated.
                example: '2024-04-12T13:21:11.000Z'
              deletedAt:
                type: string
                format: date-time
                nullable: true
                description: The date and time at which the collection access key was revoked.
                example: '2024-04-12T13:21:11.000Z'
        meta:
          type: object
          description: The response's non-standard metadata information.
          properties:
            nextCursor:
              type: string
              description: The pagination cursor that points to the next record in the results set.
              example: b2Zmc2V0PTEwJmxpbWl0PTEw
            prevCursor:
              type: string
              description: The pagination cursor to previous set of response data.
              example: ''
    cakNotFound404Error:
      title: Key Not Found
      type: object
      properties:
        type:
          type: string
          format: uri-reference
          description: The [URI reference](https://www.rfc-editor.org/rfc/rfc3986) that identifies the type of problem.
          example: https://api.postman.com/problems/not-found
        title:
          type: string
          description: A short summary of the problem.
          example: Not Found
        status:
          type: integer
          format: http-status-code
          description: The error's HTTP status code.
          example: 404
        detail:
          type: string
          description: Information about the error.
          example: The key was not found
    cursor:
      type: string
      example: RnJpIEZlYiAyNCAyMDIzIDEzOjI0OjA5IEdNVCswMDAwIChDb29yZGluYXRlZCBVbml2ZXJzYWwgVGltZSk=
  responses:
    getCollectionAccessKeys:
      description: Successful Response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/getCollectionAccessKeys'
          example:
            data:
            - id: Njg5OjU3MDQ1NjYtYmQxZDU3NzktMWVkNS00ZDhjLWI0ZmQtZWRhOGY2Mzg1NTY0
              token: PMAT-**********************43BR
              status: ACTIVE
              teamId: 123
              userId: 12345678
              collectionId: 12345678-12ece9e1-2abf-4edc-8e34-de66e74114d2
              expiresAfter: '2024-06-11T13:21:11.000Z'
              lastUsedAt: ''
              createdAt: '2024-04-12T13:21:11.000Z'
              updatedAt: '2024-04-09T11:00:53.000Z'
            - id: K7yJPzQ18BC7Snm09PXL12RMmnq57hQorFJW8JnCKhQ11JmNQiTlgXnQ1p93jGYN
              token: PMAT-**********************51FZ
              status: ACTIVE
              teamId: 123
              userId: 56781234
              collectionId: 56781234-68e5e7ac-c134-45f4-9770-40e72f3fc474
              expiresAfter: '2024-06-11T13:21:11.000Z'
              lastUsedAt: '2024-04-29T08:24:23.000Z'
              createdAt: '2024-04-22T10:11:00.000Z'
              updatedAt: '2024-04-22T10:11:00.000Z'
            meta:
              nextCursor: b2Zmc2V0PTEwJmxpbWl0PTEw
              prevCursor: ''
    cakNotFound404Error:
      description: Not Found
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/cakNotFound404Error'
          example:
            type: https://api.postman.com/problems/not-found
            title: Not Found
            status: 404
            detail: The key was not found
    common401Error:
      description: Unauthorized
      content:
        application/problem+json:
          schema:
            type: object
            properties:
              type:
                type: string
                format: uri-reference
                description: The [URI reference](https://www.rfc-editor.org/rfc/rfc3986) that identifies the type of problem.
                example: https://api.postman.com/problems/unauthorized
              title:
                type: string
                description: A short summary of the problem.
                example: Unauthorized
              detail:
                type: string
                description: Information about the error.
                example: Unauthorized
              status:
                type: integer
                format: http-status-code
                description: The error's HTTP status code.
                example: 401
          example:
            type: https://api.postman.com/problems/unauthorized
            title: Unauthorized
            detail: Unauthorized
            status: 401
    common400ErrorInvalidCursor:
      description: Bad Request
      content:
        application/problem+json:
          schema:
            type: object
            properties:
              type:
                type: string
                format: uri-reference
                description: The [URI reference](https://www.rfc-editor.org/rfc/rfc3986) that identifies the type of problem.
                example: https://api.postman.com/problems/bad-request
              title:
                type: string
                description: A short summary of the problem.
                example: Malformed request
              detail:
                type: string
                description: Information about the error.
                example: Invalid cursor
              status:
                type: integer
                format: http-status-code
                description: The error's HTTP status code.
                example: 400
          example:
            type: https://api.postman.com/problems/bad-request
            title: Malformed request
            detail: Invalid cursor
            status: 400
    common500ErrorSomethingWrong:
      description: Internal Server Error
      content:
        application/problem+json:
          schema:
            type: object
            properties:
              type:
                type: string
                format: uri-reference
                description: The [URI reference](https://www.rfc-editor.org/rfc/rfc3986) that identifies the type of problem.
                example: https://api.postman.com/problems/internal-server-error
              title:
                type: string
                description: A short summary of the problem.
                example: Something went wrong
              detail:
                type: string
                description: An explanation about the problem.
                example: Something went wrong
              status:
                type: integer
                format: http-status-code
                description: The HTTP status code generated by the origin server.
                example: 500
          example:
            type: https://api.postman.com/problems/internal-server-error
            title: Something went wrong
            detail: Something went wrong
            status: 500
    common403ErrorForbidden:
      description: Forbidden
      content:
        application/problem+json:
          schema:
            type: object
            properties:
              type:
                type: string
                format: uri-reference
                description: The [URI reference](https://www.rfc-editor.org/rfc/rfc3986) that identifies the type of problem.
                example: https://api.postman.com/problems/forbidden
              title:
                type: string
                description: A short summary of the problem.
                example: Forbidden
              status:
                type: number
                format: http-status-code
                description: The error's HTTP status code.
                example: 403
              detail:
                type: string
                description: Information about the error.
                example: Forbidden
          example:
            type: https://api.postman.com/problems/forbidden
            title: Forbidden
            detail: Forbidden
            status: 403
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/apigateway/
x-hasEquivalentPaths: true
