openapi: 3.2.0
info:
  description: 'To get started using Cloudflare''s products and services via the API, refer to [how to interact with Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/), which covers using tools like [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform) and the [official SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows who is making requests and what permissions you have. Create an API token to grant access to the API to perform actions.


    To create an API token, from the Cloudflare dashboard, go to My Profile > API Tokens and select Create Token. For more information on how to create and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).'
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: APIs.io Engineering Platform Cloudflare Load Balancer Regions API
  version: 4.0.0
tags:
- name: Load Balancer Regions
paths:
  /accounts/{account_id}/load_balancers/regions:
    get:
      description: List all region mappings.
      operationId: load-balancer-regions-list-regions
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/load-balancing_components-schemas-identifier'
      - in: query
        name: subdivision_code
        schema:
          $ref: '#/components/schemas/load-balancing_subdivision_code_a2'
      - in: query
        name: subdivision_code_a2
        schema:
          $ref: '#/components/schemas/load-balancing_subdivision_code_a2'
      - in: query
        name: country_code_a2
        schema:
          description: Two-letter alpha-2 country code followed in ISO 3166-1.
          example: US
          type: string
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/load-balancing_region_components-schemas-response_collection'
                - $ref: '#/components/schemas/load-balancing_api-response-common-failure'
          description: List Regions response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/load-balancing_region_components-schemas-response_collection'
          description: List Regions response
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform List Regions
      tags:
      - Load Balancer Regions
      x-api-token-group:
      - 'Load Balancing: Monitors and Pools Read'
  /accounts/{account_id}/load_balancers/regions/{region_id}:
    get:
      description: Get a single region mapping.
      operationId: load-balancer-regions-get-region
      parameters:
      - in: path
        name: region_id
        required: true
        schema:
          $ref: '#/components/schemas/load-balancing_region_code'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/load-balancing_components-schemas-identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/load-balancing_components-schemas-single_response'
                - $ref: '#/components/schemas/load-balancing_api-response-common-failure'
          description: Get Region response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/load-balancing_components-schemas-single_response'
          description: Get Region response
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Get Region
      tags:
      - Load Balancer Regions
components:
  schemas:
    load-balancing_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    load-balancing_api-response-single:
      allOf:
      - $ref: '#/components/schemas/load-balancing_api-response-common'
      - properties:
          result:
            anyOf:
            - type:
              - object
              - 'null'
            - type:
              - string
              - 'null'
      type: object
    load-balancing_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/load-balancing_messages'
        messages:
          $ref: '#/components/schemas/load-balancing_messages'
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    load-balancing_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/load-balancing_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/load-balancing_messages'
          example: []
        result:
          enum:
          - null
          type:
          - object
          - 'null'
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    load-balancing_region_components-schemas-response_collection:
      allOf:
      - $ref: '#/components/schemas/load-balancing_api-response-single'
      - properties:
          result:
            type: object
    load-balancing_components-schemas-identifier:
      description: Identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      readOnly: true
      type: string
    load-balancing_subdivision_code_a2:
      description: Two-letter subdivision code followed in ISO 3166-2.
      example: CA
      type: string
    load-balancing_components-schemas-single_response:
      allOf:
      - $ref: '#/components/schemas/load-balancing_api-response-single'
      - properties:
          result:
            description: A list of countries and subdivisions mapped to a region.
            example:
              iso_standard: Country and subdivision codes follow ISO 3166-1 alpha-2 and ISO 3166-2
              regions:
              - countries:
                - country_code_a2: CA
                  country_name: Canada
                  country_subdivisions:
                  - subdivision_code_a2: AB
                    subdivision_name: Alberta
                  - subdivision_code_a2: BC
                    subdivision_name: British Columbia
                - country_code_a2: HT
                  country_name: Haiti
                - country_code_a2: MX
                  country_name: Mexico
                - country_code_a2: US
                  country_name: United States
                  country_subdivisions:
                  - subdivision_code_a2: AZ
                    subdivision_name: Arizona
                  - subdivision_code_a2: CA
                    subdivision_name: California
                  - subdivision_code_a2: CO
                    subdivision_name: Colorado
                  - subdivision_code_a2: HI
                    subdivision_name: Hawaii
                  - subdivision_code_a2: MN
                    subdivision_name: Minnesota
                  - subdivision_code_a2: MO
                    subdivision_name: Missouri
                  - subdivision_code_a2: NV
                    subdivision_name: Nevada
                  - subdivision_code_a2: OR
                    subdivision_name: Oregon
                  - subdivision_code_a2: TX
                    subdivision_name: Texas
                  - subdivision_code_a2: UT
                    subdivision_name: Utah
                  - subdivision_code_a2: WA
                    subdivision_name: Washington
                region_code: WNAM
            type: object
    load-balancing_region_code:
      description: 'A list of Cloudflare regions. WNAM: Western North America, ENAM: Eastern North America, WEU: Western Europe, EEU: Eastern Europe, NSAM: Northern South America, SSAM: Southern South America, OC: Oceania, ME: Middle East, NAF: North Africa, SAF: South Africa, SAS: Southern Asia, SEAS: South East Asia, NEAS: North East Asia).'
      enum:
      - WNAM
      - ENAM
      - WEU
      - EEU
      - NSAM
      - SSAM
      - OC
      - ME
      - NAF
      - SAF
      - SAS
      - SEAS
      - NEAS
      example: WNAM
      type: string
  securitySchemes:
    api_email:
      in: header
      name: X-Auth-Email
      type: apiKey
    api_key:
      in: header
      name: X-Auth-Key
      type: apiKey
    api_token:
      scheme: bearer
      type: http
    user_service_key:
      in: header
      name: X-Auth-User-Service-Key
      type: apiKey
