openapi: 3.0.0
info:
  version: 2015-07-09
  x-release: v4
  title: APIs.io Engineering Platform Amazon API Gateway 2014 11 13 Collection to API API
  description: <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: apigateway
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/apigateway-2015-07-09.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: https://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: http://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
- url: https://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: Collection to API
  description: The **Collection to API** endpoints enable you to transform your Postman Collections into API definitions.
paths:
  /collections/{collectionId}/transformations:
    parameters:
    - $ref: '#/components/parameters/collectionId'
    get:
      summary: APIs.io Engineering Platform Transform collection to OpenAPI
      description: 'Transforms an existing Postman Collection into a stringified OpenAPI definition.


        **Note:**


        This does not create an API.

        '
      operationId: transformCollectionToOpenAPI
      tags:
      - Collection to API
      responses:
        '200':
          $ref: '#/components/responses/transformCollectionToOpenAPI'
        '401':
          $ref: '#/components/responses/collectionToApi401Error'
        '404':
          $ref: '#/components/responses/collectionToApi404Error'
        '500':
          $ref: '#/components/responses/collectionToApi500Error'
      parameters:
      - $ref: '#/components/parameters/collectionTransformFormat'
components:
  responses:
    collectionToApi500Error:
      description: Internal Server Error
      content:
        application/problem+json:
          schema:
            type: object
            properties:
              type:
                type: string
                format: uri-reference
                description: The [URI reference](https://www.rfc-editor.org/rfc/rfc3986) that identifies the type of problem.
                example: https://api.postman.com/problems/internal-server-error
              title:
                type: string
                description: A short summary of the problem.
                example: Internal Server Error
              detail:
                type: string
                description: Information about the error.
                example: Internal Server Error
              status:
                type: integer
                format: http-status-code
                description: The error's HTTP status code.
                example: 500
              instance:
                type: string
                description: The URI reference that identifies the specific occurrence of the problem.
                example: /collections/{collectionId}/apis
          example:
            type: https://api.postman.com/problems/internal-server-error
            title: Internal Server Error
            detail: Internal Server Error
            status: 500
            instance: /collections/{collectionId}/apis
    collectionToApi401Error:
      description: Unauthorized
      content:
        application/problem+json:
          schema:
            type: object
            properties:
              type:
                type: string
                format: uri-reference
                description: The [URI reference](https://www.rfc-editor.org/rfc/rfc3986) that identifies the type of problem.
                example: https://api.postman.com/problems/unauthorized
              title:
                type: string
                description: A short summary of the problem.
                example: Unauthorized
              detail:
                type: string
                description: Information about the error.
                example: Unauthorized
              status:
                type: integer
                format: http-status-code
                description: The error's HTTP status code.
                example: 401
              instance:
                type: string
                description: The URI reference that identifies the specific occurrence of the problem.
                example: /collections/{collectionId}/apis
          example:
            type: https://api.postman.com/problems/unauthorized
            title: Unauthorized
            detail: Unauthorized
            status: 401
            instance: /collections/{collectionId}/apis
    transformCollectionToOpenAPI:
      description: Successful Response
      content:
        application/json:
          schema:
            type: object
            properties:
              output:
                type: string
                description: The collection's transformed output, in a stringified OpenAPI format.
                example: "{\n    \"openapi\": \"3.0.3\",\n    \"info\": {\n        \"title\": \"Collection to API\",\n        \"version\": \"1.0.0\",\n        \"contact\": {}\n    },\n    \"servers\": [\n        {\n            \"url\": \"http://api.getpostman.com/\"\n        }\n    ],\n    \"paths\": {},\n    \"tags\": []\n}\n"
          example:
            output: "{\n    \"openapi\": \"3.0.3\",\n    \"info\": {\n        \"title\": \"Collection to API\",\n        \"version\": \"1.0.0\",\n        \"contact\": {}\n    },\n    \"servers\": [\n        {\n            \"url\": \"http://api.getpostman.com/\"\n        }\n    ],\n    \"paths\": {},\n    \"tags\": []\n}\n"
    collectionToApi404Error:
      description: Not Found
      content:
        application/problem+json:
          schema:
            type: object
            properties:
              type:
                type: string
                format: uri-reference
                description: The [URI reference](https://www.rfc-editor.org/rfc/rfc3986) that identifies the type of problem.
                example: https://api.postman.com/problems/not-found
              title:
                type: string
                description: A short summary of the problem.
                example: Not Found
              detail:
                type: string
                description: Information about the error.
                example: Not Found
              status:
                type: integer
                format: http-status-code
                description: The error's HTTP status code.
                example: 404
              instance:
                type: string
                description: The URI reference that identifies the specific occurrence of the problem.
                example: /collections/{collectionId}/apis
          example:
            type: https://api.postman.com/problems/not-found
            title: Not Found
            detail: Not Found
            status: 404
            instance: /collections/{collectionId}/apis
  parameters:
    collectionId:
      name: collectionId
      in: path
      required: true
      description: The collection's ID.
      schema:
        type: string
        example: 12ece9e1-2abf-4edc-8e34-de66e74114d2
    collectionTransformFormat:
      name: format
      in: query
      description: Return the OpenAPI definition in the given format.
      schema:
        type: string
        default: json
        enum:
        - json
        - yaml
        example: json
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/apigateway/
x-hasEquivalentPaths: true
