openapi: 3.0.0
info:
  version: "1.0.0"
  x-release: v4
  title: APIs.io Engineering Platform Amazon API Gateway 2014 11 13 Zero Trust Audit SSH Settings API
  description: <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: apigateway
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/apigateway-2015-07-09.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: https://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: http://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
- url: https://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: Zero Trust Audit SSH Settings
paths:
  /accounts/{account_id}/gateway/audit_ssh_settings:
    get:
      description: Get all Zero Trust Audit SSH settings for an account.
      operationId: zero-trust-get-audit-ssh-settings
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/zero-trust-gateway_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/zero-trust-gateway_audit_ssh_settings_components-schemas-single_response'
                - $ref: '#/components/schemas/zero-trust-gateway_api-response-common-failure'
          description: Get Zero Trust Audit SSH Settings response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/zero-trust-gateway_audit_ssh_settings_components-schemas-single_response'
          description: Get Zero Trust Audit SSH settings response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Get Zero Trust Audit SSH settings
      tags:
      - Zero Trust Audit SSH Settings
    put:
      description: Updates Zero Trust Audit SSH settings.
      operationId: zero-trust-update-audit-ssh-settings
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/zero-trust-gateway_identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                public_key:
                  $ref: '#/components/schemas/zero-trust-gateway_public_key'
                seed_id:
                  $ref: '#/components/schemas/zero-trust-gateway_audit_ssh_settings_components-schemas-uuid'
              required:
              - public_key
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/zero-trust-gateway_audit_ssh_settings_components-schemas-single_response'
                - $ref: '#/components/schemas/zero-trust-gateway_api-response-common-failure'
          description: Update Zero Trust Audit SSH Setting response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/zero-trust-gateway_audit_ssh_settings_components-schemas-single_response'
          description: Update Zero Trust Audit SSH Setting response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Update Zero Trust Audit SSH settings
      tags:
      - Zero Trust Audit SSH Settings
components:
  schemas:
    zero-trust-gateway_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    zero-trust-gateway_audit_ssh_settings_components-schemas-uuid:
      description: Seed ID
      example: f174e90a-fafe-4643-bbbc-4a0ed4fc8415
      maxLength: 36
      type: string
    zero-trust-gateway_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/zero-trust-gateway_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/zero-trust-gateway_messages'
          example: []
        result:
          enum:
          - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    zero-trust-gateway_timestamp:
      example: '2014-01-01T05:20:00.12345Z'
      format: date-time
      type: string
    zero-trust-gateway_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/zero-trust-gateway_messages'
        messages:
          $ref: '#/components/schemas/zero-trust-gateway_messages'
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      type: object
    zero-trust-gateway_identifier:
      example: 699d98642c564d2e855e9661899b7252
      type: string
    zero-trust-gateway_api-response-single:
      allOf:
      - $ref: '#/components/schemas/zero-trust-gateway_api-response-common'
      type: object
    zero-trust-gateway_public_key:
      description: SSH encryption public key
      example: 1pyl6I1tL7xfJuFYVzXlUW8uXXlpxegHXBzGCBKaSFA=
      type: string
    zero-trust-gateway_audit_ssh_settings_components-schemas-single_response:
      allOf:
      - $ref: '#/components/schemas/zero-trust-gateway_api-response-single'
      - properties:
          result:
            $ref: '#/components/schemas/zero-trust-gateway_settings'
    zero-trust-gateway_settings:
      properties:
        created_at:
          $ref: '#/components/schemas/zero-trust-gateway_timestamp'
        public_key:
          $ref: '#/components/schemas/zero-trust-gateway_public_key'
        seed_id:
          $ref: '#/components/schemas/zero-trust-gateway_audit_ssh_settings_components-schemas-uuid'
        updated_at:
          $ref: '#/components/schemas/zero-trust-gateway_timestamp'
      type: object
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/apigateway/
x-hasEquivalentPaths: true
