openapi: 3.2.0
info:
  description: 'To get started using Cloudflare''s products and services via the API, refer to [how to interact with Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/), which covers using tools like [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform) and the [official SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows who is making requests and what permissions you have. Create an API token to grant access to the API to perform actions.


    To create an API token, from the Cloudflare dashboard, go to My Profile > API Tokens and select Create Token. For more information on how to create and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).'
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: APIs.io Engineering Platform Cloudflare Account Load Balancer Search API
  version: 4.0.0
tags:
- name: Account Load Balancer Search
paths:
  /accounts/{account_id}/load_balancers/search:
    get:
      description: Search for Load Balancing resources.
      operationId: account-load-balancer-search-search-resources
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/load-balancing_components-schemas-identifier'
      - in: query
        name: search_params
        schema:
          $ref: '#/components/schemas/load-balancing_search_params'
      - in: query
        name: page
        schema:
          minimum: 1
          type: number
      - in: query
        name: per_page
        schema:
          default: 25
          maximum: 1000
          minimum: 1
          type: number
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - allOf:
                  - $ref: '#/components/schemas/load-balancing_api-response-collection'
                  - $ref: '#/components/schemas/load-balancing_search_result'
                - $ref: '#/components/schemas/load-balancing_api-response-common-failure'
          description: Search Resources response failure
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/load-balancing_api-response-collection'
                - $ref: '#/components/schemas/load-balancing_search_result'
          description: Search Resources response
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Search Resources
      tags:
      - Account Load Balancer Search
      x-api-token-group:
      - 'Load Balancing: Monitors and Pools Read'
components:
  schemas:
    load-balancing_search_result:
      properties:
        result:
          $ref: '#/components/schemas/load-balancing_search'
      type: object
    load-balancing_resource_reference:
      description: A reference to a load balancer resource.
      properties:
        reference_type:
          description: When listed as a reference, the type (direction) of the reference.
          enum:
          - referral
          - referrer
          type: string
        references:
          description: A list of references to (referrer) or from (referral) this resource.
          example:
          - reference_type: referrer
            resource_id: 699d98642c564d2e855e9661899b7252
            resource_name: www.example.com
            resource_type: load_balancer
          - reference_type: referral
            resource_id: f1aba936b94213e5b8dca0c0dbf1f9cc
            resource_name: Login page monitor
            resource_type: monitor
          items:
            description: A reference to a load balancer resource.
            type: object
          type: array
        resource_id:
          example: 17b5962d775c646f3f9725cbc7a53df4
        resource_name:
          description: The human-identifiable name of the resource.
          example: primary-dc-1
          type: string
        resource_type:
          description: The type of the resource.
          enum:
          - load_balancer
          - monitor
          - pool
          example: pool
          type: string
      type: object
    load-balancing_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    load-balancing_search_params:
      properties:
        query:
          default: ''
          description: Search query term.
          example: primary
          type: string
        references:
          default: ''
          description: The type of references to include ("*" for all).
          enum:
          - ''
          - '*'
          - referral
          - referrer
          example: '*'
          type: string
      type: object
    load-balancing_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/load-balancing_messages'
        messages:
          $ref: '#/components/schemas/load-balancing_messages'
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    load-balancing_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/load-balancing_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/load-balancing_messages'
          example: []
        result:
          enum:
          - null
          type:
          - object
          - 'null'
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    load-balancing_components-schemas-identifier:
      description: Identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      readOnly: true
      type: string
    load-balancing_result_info:
      properties:
        count:
          description: Total number of results for the requested service
          example: 1
          type: number
        page:
          description: Current page within paginated list of results
          example: 1
          type: number
        per_page:
          description: Number of results per page of results
          example: 20
          type: number
        total_count:
          description: Total results available without any search parameters
          example: 2000
          type: number
      type: object
    load-balancing_search:
      properties:
        resources:
          description: A list of resources matching the search query.
          items:
            $ref: '#/components/schemas/load-balancing_resource_reference'
          type: array
      type: object
    load-balancing_api-response-collection:
      allOf:
      - $ref: '#/components/schemas/load-balancing_api-response-common'
      - properties:
          result_info:
            $ref: '#/components/schemas/load-balancing_result_info'
      type: object
  securitySchemes:
    api_email:
      in: header
      name: X-Auth-Email
      type: apiKey
    api_key:
      in: header
      name: X-Auth-Key
      type: apiKey
    api_token:
      scheme: bearer
      type: http
    user_service_key:
      in: header
      name: X-Auth-User-Service-Key
      type: apiKey
