openapi: 3.2.0
info:
  title: Postman API Tags API
  description: The Postman API enables you to programmatically access data stored in your Postman account.
  version: '1.0'
  termsOfService: https://www.postman.com/legal/terms/
  contact:
    name: Postman Support
    email: help@postman.com
    url: https://www.postman.com/community/
servers:
- url: https://api.getpostman.com
- url: https://api.eu.postman.com
security:
- PostmanApiKey: []
- scimApiKey: []
tags:
- name: API Tags
  description: The **API Tags** endpoints enable you to manage API tags with Postman's tagging feature. Tagging is available on Postman **Enterprise** plans.
paths:
  /apis/{apiId}/tags:
    parameters:
    - $ref: '#/components/parameters/apiId'
    - $ref: '#/components/parameters/v10Accept'
    get:
      summary: APIs.io Engineering Platform Get an API's tags
      description: Gets all the tags associated with an API.
      operationId: getApiTags
      tags:
      - API Tags
      responses:
        '200':
          $ref: '#/components/responses/tagGetPut'
        '400':
          $ref: '#/components/responses/v10HeaderMissing'
        '401':
          $ref: '#/components/responses/tag401Error'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                anyOf:
                - $ref: '#/components/schemas/tag403Error'
                - $ref: '#/components/schemas/featureUnavailable403Error'
              examples:
                Forbidden:
                  $ref: '#/components/examples/tag403Error'
                Feature Unavailable:
                  $ref: '#/components/examples/featureUnavailable403Error'
        '404':
          $ref: '#/components/responses/tag404Error'
        '500':
          $ref: '#/components/responses/tag500Error'
    put:
      summary: APIs.io Engineering Platform Update an API's tags
      description: Updates an API's associated tags. This endpoint replaces all existing tags with those you pass in the request body.
      operationId: updateApiTags
      tags:
      - API Tags
      requestBody:
        $ref: '#/components/requestBodies/tagUpdateTags'
      responses:
        '200':
          $ref: '#/components/responses/tagGetPut'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                anyOf:
                - $ref: '#/components/schemas/tag400Error'
                - $ref: '#/components/schemas/v10HeaderMissing'
              examples:
                Bad Request:
                  $ref: '#/components/examples/tag400Error'
                Missing v10 Accept Header:
                  $ref: '#/components/examples/v10HeaderMissing'
        '401':
          $ref: '#/components/responses/tag401Error'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                anyOf:
                - $ref: '#/components/schemas/tag403Error'
                - $ref: '#/components/schemas/featureUnavailable403Error'
              examples:
                Forbidden:
                  $ref: '#/components/examples/tag403Error'
                Feature Unavailable:
                  $ref: '#/components/examples/featureUnavailable403Error'
        '404':
          $ref: '#/components/responses/tag404Error'
        '500':
          $ref: '#/components/responses/tag500Error'
components:
  schemas:
    tag500Error:
      title: Unexpected Error
      type: object
      properties:
        type:
          type: string
          format: uri-reference
          description: The [URI reference](https://www.rfc-editor.org/rfc/rfc3986) that identifies the type of problem.
          example: https://api.postman.com/problems/internal-server-error
        title:
          type: string
          description: A short summary of the problem.
          example: Something went wrong
        detail:
          type: string
          description: Information about the error.
          example: Something went wrong while fetching entities having the provided slug.
        status:
          type: integer
          format: http-status-code
          description: The error's HTTP status code.
          example: 500
        instance:
          type: string
          example: /tags/hello-world/entities
          description: The URI reference that identifies the specific occurrence of the problem.
    v10HeaderMissing:
      title: Missing v10 Accept Header
      type: object
      properties:
        name:
          type: string
          description: The error name.
          example: instanceNotFoundError
        message:
          type: string
          description: The error message.
          example: API not found. For v10 and later APIs, ensure that your request sends the "application/vnd.api.v10+json" Accept header.
    tag401Error:
      title: Unauthorized
      type: object
      properties:
        type:
          type: string
          format: uri-reference
          description: The [URI reference](https://www.rfc-editor.org/rfc/rfc3986) that identifies the type of problem.
          example: https://api.postman.com/problems/unauthorized
        title:
          type: string
          description: A short summary of the problem.
          example: Unauthorized
        detail:
          type: string
          description: Information about the error.
          example: The request lacks valid credentials.
        status:
          type: integer
          format: http-status-code
          description: The error's HTTP status code.
          example: 401
    featureUnavailable403Error:
      title: Feature Unavailable
      type: object
      properties:
        type:
          type: string
          format: uri-reference
          description: The [URI reference](https://www.rfc-editor.org/rfc/rfc3986) that identifies the type of problem.
          example: https://api.postman.com/problems/forbidden
        title:
          type: string
          description: A short summary of the problem.
          example: Forbidden
        detail:
          type: string
          description: Information about the error.
          example: This feature isn't available in your region.
        status:
          type: integer
          format: http-status-code
          description: The error's HTTP status code.
          example: 403
    tagGetPut:
      title: Success Response
      type: object
      properties:
        tags:
          type: array
          maxItems: 5
          minItems: 0
          description: A list of associated tags.
          items:
            type: object
            description: Information about the tag.
            properties:
              slug:
                type: string
                pattern: ^[a-z][a-z0-9-]*[a-z0-9]+$
                minLength: 2
                maxLength: 64
                description: The tag's ID within a team or individual (non-team) user scope.
                example: needs-review
    tag403Error:
      title: Forbidden
      type: object
      properties:
        type:
          type: string
          format: uri-reference
          description: The [URI reference](https://www.rfc-editor.org/rfc/rfc3986) that identifies the type of problem.
          example: https://api.postman.com/problems/forbidden
        title:
          type: string
          description: A short summary of the problem.
          example: Access Denied
        detail:
          type: string
          description: Information about the error.
          example: The tags feature is only available to enterprise teams
        status:
          type: integer
          format: http-status-code
          description: The error's HTTP status code.
          example: 403
    tag400Error:
      title: Bad Request
      type: object
      properties:
        type:
          type: string
          format: uri-reference
          description: The [URI reference](https://www.rfc-editor.org/rfc/rfc3986) that identifies the type of problem.
          example: https://api.postman.com/problems/badrequest
        title:
          type: string
          description: A short summary of the problem.
          example: Bad Request
        detail:
          type: string
          description: Information about the error.
          example: body/tags/0/slug must NOT have more than 64 characters
        status:
          type: integer
          format: http-status-code
          description: The error's HTTP status code.
          example: 400
    tag404Error:
      title: Not Found
      type: object
      properties:
        type:
          type: string
          format: uri-reference
          description: The [URI reference](https://www.rfc-editor.org/rfc/rfc3986) that identifies the type of problem.
          example: https://api.postman.com/problems/not-found
        title:
          type: string
          description: A short summary of the problem.
          example: Resource Not Found
        detail:
          type: string
          description: Information about the error.
          example: Slug 'needs-review' does not exist.
        status:
          type: integer
          format: http-status-code
          description: The error's HTTP status code.
          example: 404
        instance:
          type: string
          description: The URI reference that identifies the specific occurrence of the problem.
          example: /tags/needs-review/entities
  responses:
    tagGetPut:
      description: Success Response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/tagGetPut'
          example:
            tags:
            - slug: needs-review
            - slug: test-api
    tag500Error:
      description: Unexpected Error
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/tag500Error'
          example:
            type: https://api.postman.com/problems/internal-server-error
            title: Something went wrong
            detail: Something went wrong while fetching entities having the provided slug.
            status: 500
            instance: /tags/needs-review/entities
    tag404Error:
      description: Not Found
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/tag404Error'
          example:
            type: https://api.postman.com/problems/not-found
            title: Resource Not Found
            detail: Slug 'needs-review' does not exist.
            status: 404
            instance: /tags/needs-review/entities
    tag401Error:
      description: Unauthorized
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/tag401Error'
          example:
            type: https://api.postman.com/problems/unauthorized
            title: Unauthorized
            detail: The request lacks valid credentials.
            status: 401
    v10HeaderMissing:
      description: Missing v10 Accept Header
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/v10HeaderMissing'
          examples:
            Missing v10 Accept Header:
              $ref: '#/components/examples/v10HeaderMissing'
  requestBodies:
    tagUpdateTags:
      content:
        application/json:
          schema:
            title: Update Tags
            type: object
            required:
            - tags
            properties:
              tags:
                type: array
                minItems: 0
                maxItems: 5
                description: A list of the associated tags as slugs.
                items:
                  type: object
                  description: Information about the tag.
                  required:
                  - slug
                  properties:
                    slug:
                      type: string
                      pattern: ^[a-z][a-z0-9-]*[a-z0-9]+$
                      minLength: 2
                      maxLength: 64
                      description: The tag's ID within a team or individual (non-team) user scope.
                      example: needs-review
          example:
            tags:
            - slug: needs-review
  examples:
    v10HeaderMissing:
      value:
        name: instanceNotFoundError
        message: API not found. For v10 and later APIs, ensure that your request sends the "application/vnd.api.v10+json" Accept header.
    tag400Error:
      value:
        title: Bad Request
        detail: body/tags/0/slug must NOT have more than 64 characters
        status: 400
    tag403Error:
      value:
        type: https://api.postman.com/problems/forbidden
        title: Access Denied
        detail: The tags feature is only available to enterprise teams
        status: 403
    featureUnavailable403Error:
      value:
        type: https://api.postman.com/problems/forbidden
        title: Forbidden
        detail: This feature isn't available in your region.
        status: 403
  parameters:
    v10Accept:
      name: Accept
      in: header
      required: true
      description: The `application/vnd.api.v10+json` request header required to use the endpoint.
      schema:
        type: string
        enum:
        - application/vnd.api.v10+json
        example: application/vnd.api.v10+json
    apiId:
      name: apiId
      in: path
      required: true
      description: The API's ID.
      schema:
        type: string
        example: 90ca9f5a-c4c4-11ed-afa1-0242ac120002
  securitySchemes:
    PostmanApiKey:
      type: apiKey
      in: header
      name: x-api-key
    scimApiKey:
      type: apiKey
      in: header
      name: Authorization
      description: A valid [SCIM API key](https://learning.postman.com/docs/administration/scim-provisioning/scim-provisioning-overview/#generating-scim-api-key) for calls to SCIM endpoints.
