openapi: 3.2.0
info:
  description: 'To get started using Cloudflare''s products and services via the API, refer to [how to interact with Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/), which covers using tools like [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform) and the [official SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows who is making requests and what permissions you have. Create an API token to grant access to the API to perform actions.


    To create an API token, from the Cloudflare dashboard, go to My Profile > API Tokens and select Create Token. For more information on how to create and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).'
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: APIs.io Engineering Platform Cloudflare IP Address Management Dynamic Advertisement API
  version: 4.0.0
tags:
- name: IP Address Management Dynamic Advertisement
paths:
  /accounts/{account_id}/addressing/prefixes/{prefix_id}/bgp/status:
    get:
      description: List the current advertisement state for a prefix.
      operationId: ip-address-management-dynamic-advertisement-get-advertisement-status
      parameters:
      - in: path
        name: prefix_id
        required: true
        schema:
          $ref: '#/components/schemas/addressing_identifier'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/addressing_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/addressing_advertised_response'
                - $ref: '#/components/schemas/addressing_api-response-common-failure'
          description: Get Advertisement Status response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/addressing_advertised_response'
          description: Get Advertisement Status response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Get Advertisement Status
      tags:
      - IP Address Management Dynamic Advertisement
      x-api-token-group:
      - Magic Transit Prefix Read
      - Magic Transit Prefix Write
      - 'IP Prefixes: Write'
      - 'IP Prefixes: Read'
      - 'IP Prefixes: BGP On Demand Write'
      - 'IP Prefixes: BGP On Demand Read'
    patch:
      description: Advertise or withdraw BGP route for a prefix.
      operationId: ip-address-management-dynamic-advertisement-update-prefix-dynamic-advertisement-status
      parameters:
      - in: path
        name: prefix_id
        required: true
        schema:
          $ref: '#/components/schemas/addressing_identifier'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/addressing_identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                advertised:
                  $ref: '#/components/schemas/addressing_schemas-advertised'
              required:
              - advertised
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/addressing_advertised_response'
                - $ref: '#/components/schemas/addressing_api-response-common-failure'
          description: Update Prefix Dynamic Advertisement Status response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/addressing_advertised_response'
          description: Update Prefix Dynamic Advertisement Status response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Update Prefix Dynamic Advertisement Status
      tags:
      - IP Address Management Dynamic Advertisement
      x-api-token-group:
      - Magic Transit Prefix Write
      - 'IP Prefixes: Write'
      - 'IP Prefixes: BGP On Demand Write'
components:
  schemas:
    addressing_advertised_response:
      allOf:
      - $ref: '#/components/schemas/addressing_api-response-single'
      - properties:
          result:
            properties:
              advertised:
                $ref: '#/components/schemas/addressing_schemas-advertised'
              advertised_modified_at:
                $ref: '#/components/schemas/addressing_modified_at_nullable'
            type: object
    addressing_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/addressing_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/addressing_messages'
          example: []
        result:
          enum:
          - null
          type:
          - object
          - 'null'
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    addressing_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    addressing_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/addressing_messages'
        messages:
          $ref: '#/components/schemas/addressing_messages'
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      type: object
    addressing_api-response-single:
      allOf:
      - $ref: '#/components/schemas/addressing_api-response-common'
      type: object
    addressing_identifier:
      description: Identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      type: string
    addressing_schemas-advertised:
      description: Enablement of prefix advertisement to the Internet.
      example: true
      type: boolean
    addressing_modified_at_nullable:
      description: Last time the advertisement status was changed. This field is only not 'null' if on demand is enabled.
      example: '2014-01-01T05:20:00.12345Z'
      format: date-time
      type:
      - string
      - 'null'
  securitySchemes:
    api_email:
      in: header
      name: X-Auth-Email
      type: apiKey
    api_key:
      in: header
      name: X-Auth-Key
      type: apiKey
    api_token:
      scheme: bearer
      type: http
    user_service_key:
      in: header
      name: X-Auth-User-Service-Key
      type: apiKey
