openapi: 3.0.0
info:
  version: "1.0.0"
  x-release: v4
  title: APIs.io Engineering Platform Amazon API Gateway 2014 11 13 User Billing Profile API
  description: <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: apigateway
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/apigateway-2015-07-09.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: https://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: http://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
- url: https://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: User Billing Profile
paths:
  /user/billing/profile:
    get:
      deprecated: true
      description: Accesses your billing profile object.
      operationId: user-billing-profile-(-deprecated)-billing-profile-details
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/bill-subs-api_billing_response_single'
                - $ref: '#/components/schemas/bill-subs-api_api-response-common-failure'
          description: Billing Profile Details response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bill-subs-api_billing_response_single'
          description: Billing Profile Details response
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Billing Profile Details
      tags:
      - User Billing Profile
      x-api-token-group:
      - Billing Write
      - Billing Read
      x-cfPermissionsRequired:
        enum:
        - '#billing:read'
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
components:
  schemas:
    bill-subs-api_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    bill-subs-api_api-response-single:
      allOf:
      - $ref: '#/components/schemas/bill-subs-api_api-response-common'
      - properties:
          result:
            anyOf:
            - nullable: true
              type: object
            - nullable: true
              type: string
      type: object
    bill-subs-api_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/bill-subs-api_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/bill-subs-api_messages'
          example: []
        result:
          enum:
          - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    bill-subs-api_components-schemas-identifier:
      description: Billing item identifier tag.
      example: b69a9f3492637782896352daae219e7d
      maxLength: 32
      readOnly: true
      type: string
    bill-subs-api_billing_response_single:
      allOf:
      - $ref: '#/components/schemas/bill-subs-api_api-response-single'
      - properties:
          result:
            properties:
              account_type:
                example: type
                type: string
              address:
                example: 123 Main Street
                type: string
              address2:
                example: Apt 1
                type: string
              balance:
                example: 0
                type: string
              card_expiry_month:
                example: 12
                type: integer
              card_expiry_year:
                example: 2099
                type: integer
              card_number:
                example: 4242424242424242.0
                type: string
              city:
                example: Anytown
                type: string
              company:
                example: Company
                type: string
              country:
                example: Anycountry
                type: string
              created_on:
                example: '2014-03-01T12:21:59.3456Z'
                format: date-time
                type: string
              device_data:
                example: sample_data
                type: string
              edited_on:
                example: '2014-03-01T12:21:59.3456Z'
                format: date-time
                type: string
              enterprise_billing_email:
                example: johndoe@gmail.com
                type: string
              enterprise_primary_email:
                example: johndoe@gmail.com
                type: string
              first_name:
                example: John
                type: string
              id:
                $ref: '#/components/schemas/bill-subs-api_components-schemas-identifier'
              is_partner:
                example: false
                type: boolean
              last_name:
                example: Doe
                type: string
              next_bill_date:
                example: '2014-03-01T12:21:59.3456Z'
                format: date-time
                type: string
              payment_address:
                example: 123 Main Street
                type: string
              payment_address2:
                example: Apt 1
                type: string
              payment_city:
                example: Anytown
                type: string
              payment_country:
                example: Anycountry
                type: string
              payment_email:
                example: johndoe@gmail.com
                type: string
              payment_first_name:
                example: John
                type: string
              payment_gateway:
                example: gateway
                type: string
              payment_last_name:
                example: Doe
                type: string
              payment_nonce:
                example: abc123
                type: string
              payment_state:
                example: state
                type: string
              payment_zipcode:
                example: 12345
                type: string
              primary_email:
                example: johndoe@gmail.com
                type: string
              state:
                example: AnyState
                type: string
              tax_id_type:
                example: type
                type: string
              telephone:
                example: 1234567899.0
                type: string
              use_legacy:
                example: false
                type: boolean
              validation_code:
                example: 1111
                type: string
              vat:
                example: GB123456789
                type: string
              zipcode:
                example: 12345
                type: string
            type: object
        type: object
    bill-subs-api_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/bill-subs-api_messages'
        messages:
          $ref: '#/components/schemas/bill-subs-api_messages'
        result:
          anyOf:
          - type: object
          - items: {}
            type: array
          - type: string
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/apigateway/
x-hasEquivalentPaths: true
