openapi: 3.2.0
info:
  description: 'To get started using Cloudflare''s products and services via the API, refer to [how to interact with Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/), which covers using tools like [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform) and the [official SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows who is making requests and what permissions you have. Create an API token to grant access to the API to perform actions.


    To create an API token, from the Cloudflare dashboard, go to My Profile > API Tokens and select Create Token. For more information on how to create and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).'
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: APIs.io Engineering Platform Cloudflare Hyperdrive API
  version: 4.0.0
tags:
- name: Hyperdrive
paths:
  /accounts/{account_id}/hyperdrive/configs:
    get:
      description: Returns a list of Hyperdrives
      operationId: list-hyperdrive
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/hyperdrive_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - allOf:
                  - $ref: '#/components/schemas/hyperdrive_api-response-single'
                  - properties:
                      result:
                        type:
                        - object
                        - 'null'
                    type: object
                - $ref: '#/components/schemas/hyperdrive_api-response-common-failure'
          description: List Hyperdrives Failure Response
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/hyperdrive_api-response-common'
                - properties:
                    result:
                      items:
                        $ref: '#/components/schemas/hyperdrive_hyperdrive-with-identifier'
                      type: array
          description: List Hyperdrives Response
      security:
      - api_token: []
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform List Hyperdrives
      tags:
      - Hyperdrive
      x-api-token-group:
      - Hyperdrive Write
      - Hyperdrive Read
      x-cfPermissionsRequired:
        enum:
        - com.cloudflare.edge.hyperdrive.database.list
    post:
      description: Creates and returns a new Hyperdrive configuration.
      operationId: create-hyperdrive
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/hyperdrive_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/hyperdrive_create-update-hyperdrive-config'
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - allOf:
                  - $ref: '#/components/schemas/hyperdrive_api-response-single'
                  - properties:
                      result:
                        type:
                        - object
                        - 'null'
                    type: object
                - $ref: '#/components/schemas/hyperdrive_api-response-common-failure'
          description: Create Hyperdrive Failure Response
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/hyperdrive_api-response-single'
                - properties:
                    result:
                      $ref: '#/components/schemas/hyperdrive_hyperdrive-with-identifier'
          description: Create Hyperdrive Response
      security:
      - api_token: []
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Create Hyperdrive
      tags:
      - Hyperdrive
      x-api-token-group:
      - Hyperdrive Write
      x-cfPermissionsRequired:
        enum:
        - com.cloudflare.edge.hyperdrive.database.create
  /accounts/{account_id}/hyperdrive/configs/{hyperdrive_id}:
    delete:
      description: Deletes the specified Hyperdrive.
      operationId: delete-hyperdrive
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/hyperdrive_identifier'
      - in: path
        name: hyperdrive_id
        required: true
        schema:
          $ref: '#/components/schemas/hyperdrive_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - allOf:
                  - $ref: '#/components/schemas/hyperdrive_api-response-single'
                  - properties:
                      result:
                        type:
                        - object
                        - 'null'
                    type: object
                - $ref: '#/components/schemas/hyperdrive_api-response-common-failure'
          description: Delete Hyperdrive Failure
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/hyperdrive_api-response-single'
                - properties:
                    result:
                      type:
                      - object
                      - 'null'
          description: Delete Hyperdrive Response
      security:
      - api_token: []
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Delete Hyperdrive
      tags:
      - Hyperdrive
      x-api-token-group:
      - Hyperdrive Write
      x-cfPermissionsRequired:
        enum:
        - com.cloudflare.edge.hyperdrive.database.delete
    get:
      description: Returns the specified Hyperdrive configuration.
      operationId: get-hyperdrive
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/hyperdrive_identifier'
      - in: path
        name: hyperdrive_id
        required: true
        schema:
          $ref: '#/components/schemas/hyperdrive_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - allOf:
                  - $ref: '#/components/schemas/hyperdrive_api-response-single'
                  - properties:
                      result:
                        type:
                        - object
                        - 'null'
                    type: object
                - $ref: '#/components/schemas/hyperdrive_api-response-common-failure'
          description: Get Hyperdrive Failure
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/hyperdrive_api-response-single'
                - properties:
                    result:
                      $ref: '#/components/schemas/hyperdrive_hyperdrive-with-identifier'
          description: Get Hyperdrive Response
      security:
      - api_token: []
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Get Hyperdrive
      tags:
      - Hyperdrive
      x-api-token-group:
      - Hyperdrive Write
      - Hyperdrive Read
      x-cfPermissionsRequired:
        enum:
        - com.cloudflare.edge.hyperdrive.database.read
    patch:
      description: Patches and returns the specified Hyperdrive configuration. Updates to the origin and caching settings are applied with an all-or-nothing approach.
      operationId: patch-hyperdrive
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/hyperdrive_identifier'
      - in: path
        name: hyperdrive_id
        required: true
        schema:
          $ref: '#/components/schemas/hyperdrive_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/hyperdrive_patch-hyperdrive-config'
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - allOf:
                  - $ref: '#/components/schemas/hyperdrive_api-response-single'
                  - properties:
                      result:
                        type:
                        - object
                        - 'null'
                    type: object
                - $ref: '#/components/schemas/hyperdrive_api-response-common-failure'
          description: Patch Hyperdrive Failure Response
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/hyperdrive_api-response-single'
                - properties:
                    result:
                      $ref: '#/components/schemas/hyperdrive_hyperdrive-with-identifier'
          description: Patch Hyperdrive Response
      security:
      - api_token: []
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Patch Hyperdrive
      tags:
      - Hyperdrive
      x-api-token-group:
      - Hyperdrive Write
      x-cfPermissionsRequired:
        enum:
        - com.cloudflare.edge.hyperdrive.database.update
    put:
      description: Updates and returns the specified Hyperdrive configuration.
      operationId: update-hyperdrive
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/hyperdrive_identifier'
      - in: path
        name: hyperdrive_id
        required: true
        schema:
          $ref: '#/components/schemas/hyperdrive_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/hyperdrive_create-update-hyperdrive-config'
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - allOf:
                  - $ref: '#/components/schemas/hyperdrive_api-response-single'
                  - properties:
                      result:
                        type:
                        - object
                        - 'null'
                    type: object
                - $ref: '#/components/schemas/hyperdrive_api-response-common-failure'
          description: Update Hyperdrive Failure Response
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/hyperdrive_api-response-single'
                - properties:
                    result:
                      $ref: '#/components/schemas/hyperdrive_hyperdrive-with-identifier'
          description: Update Hyperdrive Response
      security:
      - api_token: []
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Update Hyperdrive
      tags:
      - Hyperdrive
      x-api-token-group:
      - Hyperdrive Write
      x-cfPermissionsRequired:
        enum:
        - com.cloudflare.edge.hyperdrive.database.update
components:
  schemas:
    hyperdrive_hyperdrive-scheme:
      default: postgres
      description: Specifies the URL scheme used to connect to your origin database.
      enum:
      - postgres
      - postgresql
      - mysql
      type: string
    hyperdrive_identifier:
      description: Identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      readOnly: true
      type: string
    hyperdrive_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/hyperdrive_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/hyperdrive_messages'
          example: []
        result:
          enum:
          - null
          type:
          - object
          - 'null'
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    hyperdrive_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/hyperdrive_messages'
        messages:
          $ref: '#/components/schemas/hyperdrive_messages'
        result:
          anyOf:
          - type: object
          - items: {}
            type: array
          - type: string
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    hyperdrive_hyperdrive-caching:
      properties:
        disabled:
          description: 'When set to true, disables the caching of SQL responses. (Default: false)'
          example: false
          type: boolean
        max_age:
          description: 'When present, specifies max duration for which items should persist in the cache. (Default: 60)'
          example: 60
          type: integer
        stale_while_revalidate:
          description: 'When present, indicates the number of seconds cache may serve the response after it becomes stale. (Default: 15)'
          example: 15
          type: integer
      type: object
    hyperdrive_api-response-single:
      allOf:
      - $ref: '#/components/schemas/hyperdrive_api-response-common'
      - properties:
          result:
            anyOf:
            - type: object
            - type: string
            type:
            - object
            - 'null'
      type: object
    hyperdrive_hyperdrive-origin:
      properties:
        access_client_id:
          description: The Client ID of the Access token to use when connecting to the origin database
          example: 0123456789abcdef0123456789abcdef.access
          type: string
        database:
          description: The name of your origin database.
          example: postgres
          type: string
        host:
          description: The host (hostname or IP) of your origin database.
          example: database.example.com
          type: string
        port:
          description: 'The port (default: 5432 for Postgres) of your origin database.'
          example: '5432'
          type: integer
        scheme:
          $ref: '#/components/schemas/hyperdrive_hyperdrive-scheme'
        user:
          description: The user of your origin database.
          example: postgres
          type: string
      required:
      - host
      - scheme
      - database
      - user
      type: object
    hyperdrive_hyperdrive-origin-with-secrets:
      allOf:
      - $ref: '#/components/schemas/hyperdrive_hyperdrive-origin'
      properties:
        access_client_secret:
          description: The Client Secret of the Access token to use when connecting to the origin database
          example: 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
          type: string
        password:
          description: The password required to access your origin database. This value is write-only and never returned by the API.
          example: password1234!
          type: string
      required:
      - password
      type: object
    hyperdrive_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    hyperdrive_hyperdrive-name:
      example: example-hyperdrive
      type: string
    hyperdrive_patch-hyperdrive-config:
      allOf:
      - $ref: '#/components/schemas/hyperdrive_hyperdrive'
      properties:
        origin:
          $ref: '#/components/schemas/hyperdrive_hyperdrive-origin-with-secrets'
      type: object
    hyperdrive_hyperdrive:
      properties:
        caching:
          $ref: '#/components/schemas/hyperdrive_hyperdrive-caching'
        name:
          $ref: '#/components/schemas/hyperdrive_hyperdrive-name'
        origin:
          $ref: '#/components/schemas/hyperdrive_hyperdrive-origin'
      type: object
    hyperdrive_hyperdrive-with-identifier:
      allOf:
      - $ref: '#/components/schemas/hyperdrive_hyperdrive'
      properties:
        id:
          $ref: '#/components/schemas/hyperdrive_identifier'
      type: object
    hyperdrive_create-update-hyperdrive-config:
      allOf:
      - $ref: '#/components/schemas/hyperdrive_hyperdrive'
      properties:
        origin:
          $ref: '#/components/schemas/hyperdrive_hyperdrive-origin-with-secrets'
      required:
      - name
      - origin
      type: object
  securitySchemes:
    api_email:
      in: header
      name: X-Auth-Email
      type: apiKey
    api_key:
      in: header
      name: X-Auth-Key
      type: apiKey
    api_token:
      scheme: bearer
      type: http
    user_service_key:
      in: header
      name: X-Auth-User-Service-Key
      type: apiKey
