openapi: 3.0.0
info:
  version: "1.0.0"
  x-release: v4
  title: APIs.io Engineering Platform Amazon API Gateway 2014 11 13 Stream Video Clipping API
  description: <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: apigateway
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/apigateway-2015-07-09.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: https://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: http://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
- url: https://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: Stream Video Clipping
paths:
  /accounts/{account_id}/stream/clip:
    post:
      description: Clips a video based on the specified start and end times provided in seconds.
      operationId: stream-video-clipping-clip-videos-given-a-start-and-end-time
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/stream_account_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/stream_videoClipStandard'
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stream_api-response-common-failure'
          description: Clip videos given a start and end time response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stream_clipResponseSingle'
          description: Clip videos given a start and end time response
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Clip videos given a start and end time
      tags:
      - Stream Video Clipping
components:
  schemas:
    stream_playback:
      properties:
        dash:
          description: DASH Media Presentation Description for the video.
          example: https://customer-m033z5x00ks6nunl.cloudflarestream.com/ea95132c15732412d22c1476fa83f27a/manifest/video.mpd
          type: string
        hls:
          description: The HLS manifest for the video.
          example: https://customer-m033z5x00ks6nunl.cloudflarestream.com/ea95132c15732412d22c1476fa83f27a/manifest/video.m3u8
          type: string
      type: object
    stream_clipping:
      properties:
        allowedOrigins:
          $ref: '#/components/schemas/stream_allowedOrigins'
        clippedFromVideoUID:
          $ref: '#/components/schemas/stream_clipped_from_video_uid'
        created:
          $ref: '#/components/schemas/stream_clipping_created'
        creator:
          $ref: '#/components/schemas/stream_creator'
        endTimeSeconds:
          $ref: '#/components/schemas/stream_end_time_seconds'
        maxDurationSeconds:
          $ref: '#/components/schemas/stream_maxDurationSeconds'
        meta:
          $ref: '#/components/schemas/stream_media_metadata'
        modified:
          $ref: '#/components/schemas/stream_live_input_modified'
        playback:
          $ref: '#/components/schemas/stream_playback'
        preview:
          $ref: '#/components/schemas/stream_preview'
        requireSignedURLs:
          $ref: '#/components/schemas/stream_requireSignedURLs'
        startTimeSeconds:
          $ref: '#/components/schemas/stream_start_time_seconds'
        status:
          $ref: '#/components/schemas/stream_media_state'
        thumbnailTimestampPct:
          $ref: '#/components/schemas/stream_thumbnailTimestampPct'
        watermark:
          $ref: '#/components/schemas/stream_watermarkAtUpload'
    stream_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/stream_messages'
        messages:
          $ref: '#/components/schemas/stream_messages'
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      type: object
    stream_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    stream_preview:
      description: The video's preview page URI. This field is omitted until encoding is complete.
      example: https://customer-m033z5x00ks6nunl.cloudflarestream.com/ea95132c15732412d22c1476fa83f27a/watch
      format: uri
      type: string
    stream_allowedOrigins:
      description: Lists the origins allowed to display the video. Enter allowed origin domains in an array and use `*` for wildcard subdomains. Empty arrays allow the video to be viewed on any origin.
      example:
      - example.com
      items:
        type: string
      type: array
    stream_creator:
      description: A user-defined identifier for the media creator.
      example: creator-id_abcde12345
      maxLength: 64
      type: string
    stream_clipping_created:
      description: The date and time the clip was created.
      example: '2014-01-02T02:20:00Z'
      format: date-time
      type: string
    stream_maxDurationSeconds:
      description: The maximum duration in seconds for a video upload. Can be set for a video that is not yet uploaded to limit its duration. Uploads that exceed the specified duration will fail during processing. A value of `-1` means the value is unknown.
      maximum: 21600
      minimum: 1
      type: integer
    stream_watermarkAtUpload:
      properties:
        uid:
          description: The unique identifier for the watermark profile.
          example: ea95132c15732412d22c1476fa83f27a
          maxLength: 32
          type: string
      type: object
    stream_media_metadata:
      description: A user modifiable key-value store used to reference other systems of record for managing videos.
      example:
        name: video12345.mp4
      type: object
    stream_live_input_modified:
      description: The date and time the live input was last modified.
      example: '2014-01-02T02:20:00Z'
      format: date-time
      type: string
    stream_thumbnailTimestampPct:
      default: 0
      description: The timestamp for a thumbnail image calculated as a percentage value of the video's duration. To convert from a second-wise timestamp to a percentage, divide the desired timestamp by the total duration of the video.  If this value is not set, the default thumbnail image is taken from 0s of the video.
      example: 0.529241
      maximum: 1
      minimum: 0
      type: number
    stream_account_identifier:
      description: The account identifier tag.
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      type: string
    stream_clipResponseSingle:
      allOf:
      - $ref: '#/components/schemas/stream_api-response-common'
      - properties:
          result:
            $ref: '#/components/schemas/stream_clipping'
    stream_videoClipStandard:
      properties:
        allowedOrigins:
          $ref: '#/components/schemas/stream_allowedOrigins'
        clippedFromVideoUID:
          $ref: '#/components/schemas/stream_clipped_from_video_uid'
        creator:
          $ref: '#/components/schemas/stream_creator'
        endTimeSeconds:
          $ref: '#/components/schemas/stream_end_time_seconds'
        maxDurationSeconds:
          $ref: '#/components/schemas/stream_maxDurationSeconds'
        requireSignedURLs:
          $ref: '#/components/schemas/stream_requireSignedURLs'
        startTimeSeconds:
          $ref: '#/components/schemas/stream_start_time_seconds'
        thumbnailTimestampPct:
          $ref: '#/components/schemas/stream_thumbnailTimestampPct'
        watermark:
          $ref: '#/components/schemas/stream_watermarkAtUpload'
      required:
      - clippedFromVideoUID
      - startTimeSeconds
      - endTimeSeconds
      type: object
    stream_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/stream_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/stream_messages'
          example: []
        result:
          enum:
          - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    stream_end_time_seconds:
      description: Specifies the end time for the video clip in seconds.
      type: integer
    stream_start_time_seconds:
      description: Specifies the start time for the video clip in seconds.
      type: integer
    stream_requireSignedURLs:
      default: false
      description: Indicates whether the video can be a accessed using the UID. When set to `true`, a signed token must be generated with a signing key to view the video.
      example: true
      type: boolean
    stream_clipped_from_video_uid:
      description: The unique video identifier (UID).
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      type: string
    stream_media_state:
      description: Specifies the processing status for all quality levels for a video.
      enum:
      - pendingupload
      - downloading
      - queued
      - inprogress
      - ready
      - error
      example: inprogress
      type: string
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/apigateway/
x-hasEquivalentPaths: true
