openapi: 3.0.0
info:
  version: 2015-07-09
  x-release: v4
  title: APIs.io Engineering Platform Amazon API Gateway 2014 11 13 Zone Subscription API
  description: <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: apigateway
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/apigateway-2015-07-09.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: https://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: http://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
- url: https://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: Zone Subscription
paths:
  /zones/{identifier}/subscription:
    get:
      description: Lists zone subscription details.
      operationId: zone-subscription-zone-subscription-details
      parameters:
      - in: path
        name: identifier
        required: true
        schema:
          $ref: '#/components/schemas/bill-subs-api_schemas-identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/bill-subs-api_zone_subscription_response_single'
                - $ref: '#/components/schemas/bill-subs-api_api-response-common-failure'
          description: Zone Subscription Details response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bill-subs-api_zone_subscription_response_single'
          description: Zone Subscription Details response
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Zone Subscription Details
      tags:
      - Zone Subscription
      x-api-token-group:
      - Billing Write
      - Billing Read
      x-cfPermissionsRequired:
        enum:
        - '#billing:read'
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
    post:
      description: Create a zone subscription, either plan or add-ons.
      operationId: zone-subscription-create-zone-subscription
      parameters:
      - in: path
        name: identifier
        required: true
        schema:
          $ref: '#/components/schemas/bill-subs-api_schemas-identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/bill-subs-api_subscription-v2'
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/bill-subs-api_zone_subscription_response_single'
                - $ref: '#/components/schemas/bill-subs-api_api-response-common-failure'
          description: Create Zone Subscription response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bill-subs-api_zone_subscription_response_single'
          description: Create Zone Subscription response
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Create Zone Subscription
      tags:
      - Zone Subscription
      x-api-token-group:
      - Billing Write
      x-cfPermissionsRequired:
        enum:
        - '#billing:read'
        - '#billing:edit'
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
    put:
      description: Updates zone subscriptions, either plan or add-ons.
      operationId: zone-subscription-update-zone-subscription
      parameters:
      - in: path
        name: identifier
        required: true
        schema:
          $ref: '#/components/schemas/bill-subs-api_schemas-identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/bill-subs-api_subscription-v2'
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/bill-subs-api_zone_subscription_response_single'
                - $ref: '#/components/schemas/bill-subs-api_api-response-common-failure'
          description: Update Zone Subscription response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bill-subs-api_zone_subscription_response_single'
          description: Update Zone Subscription response
      security:
      - api_email: []
        api_key: []
        api_token: []
      summary: APIs.io Engineering Platform Update Zone Subscription
      tags:
      - Zone Subscription
      x-api-token-group:
      - Billing Write
      x-cfPermissionsRequired:
        enum:
        - '#billing:read'
        - '#billing:edit'
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
components:
  schemas:
    bill-subs-api_zone_subscription_response_single:
      allOf:
      - $ref: '#/components/schemas/bill-subs-api_api-response-single'
      - properties:
          result:
            type: object
        type: object
    bill-subs-api_rate_plan:
      description: The rate plan applied to the subscription.
      properties:
        currency:
          description: The currency applied to the rate plan subscription.
          example: USD
          type: string
        externally_managed:
          description: Whether this rate plan is managed externally from Cloudflare.
          example: false
          type: boolean
        id:
          description: The ID of the rate plan.
          example: free
          type: string
        is_contract:
          description: Whether a rate plan is enterprise-based (or newly adopted term contract).
          example: false
          type: boolean
        public_name:
          description: The full name of the rate plan.
          example: Business Plan
          type: string
        scope:
          description: The scope that this rate plan applies to.
          example: zone
          type: string
        sets:
          description: The list of sets this rate plan applies to.
          items:
            type: string
          type: array
      type: object
    bill-subs-api_zone:
      description: A simple zone object. May have null properties if not a zone subscription.
      properties:
        id:
          $ref: '#/components/schemas/bill-subs-api_identifier'
        name:
          $ref: '#/components/schemas/bill-subs-api_name'
      type: object
    bill-subs-api_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    bill-subs-api_component_values:
      description: The list of add-ons subscribed to.
      items:
        $ref: '#/components/schemas/bill-subs-api_component_value'
      type: array
    bill-subs-api_install_id:
      description: app install id.
      type: string
    bill-subs-api_name:
      description: The domain name
      example: example.com
      maxLength: 253
      pattern: ^([a-zA-Z0-9][\-a-zA-Z0-9]*\.)+[\-a-zA-Z0-9]{2,20}$
      readOnly: true
      type: string
    bill-subs-api_subscription-v2:
      properties:
        app:
          properties:
            install_id:
              $ref: '#/components/schemas/bill-subs-api_install_id'
        component_values:
          $ref: '#/components/schemas/bill-subs-api_component_values'
        currency:
          $ref: '#/components/schemas/bill-subs-api_currency'
        current_period_end:
          $ref: '#/components/schemas/bill-subs-api_current_period_end'
        current_period_start:
          $ref: '#/components/schemas/bill-subs-api_current_period_start'
        frequency:
          $ref: '#/components/schemas/bill-subs-api_frequency'
        id:
          $ref: '#/components/schemas/bill-subs-api_schemas-identifier'
        price:
          $ref: '#/components/schemas/bill-subs-api_price'
        rate_plan:
          $ref: '#/components/schemas/bill-subs-api_rate_plan'
        state:
          $ref: '#/components/schemas/bill-subs-api_state'
        zone:
          $ref: '#/components/schemas/bill-subs-api_zone'
      type: object
    bill-subs-api_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/bill-subs-api_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/bill-subs-api_messages'
          example: []
        result:
          enum:
          - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    bill-subs-api_price:
      description: The price of the subscription that will be billed, in US dollars.
      example: 20
      readOnly: true
      type: number
    bill-subs-api_component_value:
      description: A component value for a subscription.
      properties:
        default:
          description: The default amount assigned.
          example: 5
          type: number
        name:
          description: The name of the component value.
          example: page_rules
          type: string
        price:
          description: The unit price for the component value.
          example: 5
          type: number
        value:
          description: The amount of the component value assigned.
          example: 20
          type: number
      type: object
    bill-subs-api_schemas-identifier:
      description: Subscription identifier tag.
      example: 506e3185e9c882d175a2d0cb0093d9f2
      maxLength: 32
      readOnly: true
      type: string
    bill-subs-api_identifier:
      description: Identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      readOnly: true
      type: string
    bill-subs-api_frequency:
      description: How often the subscription is renewed automatically.
      enum:
      - weekly
      - monthly
      - quarterly
      - yearly
      example: monthly
      type: string
    bill-subs-api_state:
      description: The state that the subscription is in.
      enum:
      - Trial
      - Provisioned
      - Paid
      - AwaitingPayment
      - Cancelled
      - Failed
      - Expired
      example: Paid
      readOnly: true
      type: string
    bill-subs-api_current_period_end:
      description: The end of the current period and also when the next billing is due.
      example: '2014-03-31T12:20:00Z'
      format: date-time
      readOnly: true
      type: string
    bill-subs-api_currency:
      description: The monetary unit in which pricing information is displayed.
      example: USD
      readOnly: true
      type: string
    bill-subs-api_api-response-single:
      allOf:
      - $ref: '#/components/schemas/bill-subs-api_api-response-common'
      - properties:
          result:
            anyOf:
            - nullable: true
              type: object
            - nullable: true
              type: string
      type: object
    bill-subs-api_current_period_start:
      description: When the current billing period started. May match initial_period_start if this is the first period.
      example: '2014-05-11T12:20:00Z'
      format: date-time
      readOnly: true
      type: string
    bill-subs-api_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/bill-subs-api_messages'
        messages:
          $ref: '#/components/schemas/bill-subs-api_messages'
        result:
          anyOf:
          - type: object
          - items: {}
            type: array
          - type: string
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/apigateway/
x-hasEquivalentPaths: true
