openapi: 3.0.0
info:
  version: 2015-07-09
  x-release: v4
  title: APIs.io Engineering Platform Amazon API Gateway 2014 11 13 Zero Trust Certificates API
  description: <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: apigateway
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/apigateway-2015-07-09.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: https://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: http://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
- url: https://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: Zero Trust Certificates
paths:
  /accounts/{account_id}/gateway/certificates:
    get:
      description: Fetches all Zero Trust certificates for an account.
      operationId: zero-trust-certificates-list-zero-trust-certificates
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/zero-trust-gateway_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/zero-trust-gateway_response_collection'
                - $ref: '#/components/schemas/zero-trust-gateway_api-response-common-failure'
          description: List Zero Trust certificates response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/zero-trust-gateway_response_collection'
          description: List Zero Trust certificates response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform List Zero Trust certificates
      tags:
      - Zero Trust Certificates
    post:
      description: Creates a new Zero Trust certificate.
      operationId: zero-trust-certificates-create-zero-trust-certificate
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/zero-trust-gateway_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/zero-trust-gateway_generate-cert-request'
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/zero-trust-gateway_single_response'
                - $ref: '#/components/schemas/zero-trust-gateway_api-response-common-failure'
          description: Create Zero Trust certificate response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/zero-trust-gateway_single_response'
          description: Create Zero Trust certificate response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Create Zero Trust certificate
      tags:
      - Zero Trust Certificates
  /accounts/{account_id}/gateway/certificates/{certificate_id}:
    delete:
      description: Deletes a gateway-managed Zero Trust certificate. A certificate must be deactivated from the edge (inactive) before it is deleted.
      operationId: zero-trust-certificates-delete-zero-trust-certificate
      parameters:
      - in: path
        name: certificate_id
        required: true
        schema:
          $ref: '#/components/schemas/zero-trust-gateway_uuid'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/zero-trust-gateway_identifier'
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/zero-trust-gateway_single_response'
                - $ref: '#/components/schemas/zero-trust-gateway_api-response-common-failure'
          description: Delete Zero Trust certificate response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/zero-trust-gateway_single_response'
          description: Delete Zero Trust certificate response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Delete Zero Trust certificate
      tags:
      - Zero Trust Certificates
    get:
      description: Fetches a single Zero Trust certificate.
      operationId: zero-trust-certificates-zero-trust-certificate-details
      parameters:
      - in: path
        name: certificate_id
        required: true
        schema:
          $ref: '#/components/schemas/zero-trust-gateway_uuid'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/zero-trust-gateway_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/zero-trust-gateway_single_response'
                - $ref: '#/components/schemas/zero-trust-gateway_api-response-common-failure'
          description: Get Zero Trust certificate details response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/zero-trust-gateway_single_response'
          description: Get Zero Trust certificate details response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Get Zero Trust certificate details
      tags:
      - Zero Trust Certificates
  /accounts/{account_id}/gateway/certificates/{certificate_id}/activate:
    post:
      description: Binds a single Zero Trust certificate to the edge.
      operationId: zero-trust-certificates-activate-zero-trust-certificate
      parameters:
      - in: path
        name: certificate_id
        required: true
        schema:
          $ref: '#/components/schemas/zero-trust-gateway_uuid'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/zero-trust-gateway_identifier'
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/zero-trust-gateway_single_response'
                - $ref: '#/components/schemas/zero-trust-gateway_api-response-common-failure'
          description: Activate Zero Trust certificate details response failure
        '202':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/zero-trust-gateway_single_response'
          description: Activate Zero Trust certificate details response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Activate a Zero Trust certificate
      tags:
      - Zero Trust Certificates
  /accounts/{account_id}/gateway/certificates/{certificate_id}/deactivate:
    post:
      description: Unbinds a single Zero Trust certificate from the edge
      operationId: zero-trust-certificates-deactivate-zero-trust-certificate
      parameters:
      - in: path
        name: certificate_id
        required: true
        schema:
          $ref: '#/components/schemas/zero-trust-gateway_uuid'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/zero-trust-gateway_identifier'
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/zero-trust-gateway_single_response'
                - $ref: '#/components/schemas/zero-trust-gateway_api-response-common-failure'
          description: Deactivate Zero Trust certificate details response failure
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/zero-trust-gateway_single_response'
          description: Deactivate Zero Trust certificate details response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Deactivate a Zero Trust certificate
      tags:
      - Zero Trust Certificates
components:
  schemas:
    zero-trust-gateway_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    zero-trust-gateway_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/zero-trust-gateway_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/zero-trust-gateway_messages'
          example: []
        result:
          enum:
          - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    zero-trust-gateway_certificates:
      properties:
        binding_status:
          $ref: '#/components/schemas/zero-trust-gateway_binding_status'
        certificate:
          description: The CA certificate
          example: '-----BEGIN CERTIFICATE-----\nMIIDmDCCAoCgAwIBAgIUKTOAZNjcXVZRj4oQt0SHsl1c1vMwDQYJKoZIhvcNAQELBQAwUTELMAkGA1UEBhMCVVMxFjAUBgNVBAgMDVNhbiBGcmFuY2lzY28xEzARBgNVBAcMCkNhbGlmb3JuaWExFTATBgNVBAoMDEV4YW1wbGUgSW5jLjAgFw0yMjExMjIxNjU5NDdaGA8yMTIyMTAyOTE2NTk0N1owUTELMAkGA1UEBhMCVVMxFjAUBgNVBAgMDVNhbiBGcmFuY2lzY28xEzARBgNVBAcMCkNhbGlmb3JuaWExFTATBgNVBAoMDEV4YW1wbGUgSW5jLjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMRcORwgJFTdcG/2GKI+cFYiOBNDKjCZUXEOvXWY42BkH9wxiMT869CO+enA1w5pIrXow6kCM1sQspHHaVmJUlotEMJxyoLFfA/8Kt1EKFyobOjuZs2SwyVyJ2sStvQuUQEosULZCNGZEqoH5g6zhMPxaxm7ZLrrsDZ9maNGVqo7EWLWHrZ57Q/5MtTrbxQL+eXjUmJ9K3kS+3uEwMdqR6Z3BluU1ivanpPc1CN2GNhdO0/hSY4YkGEnuLsqJyDd3cIiB1MxuCBJ4ZaqOd2viV1WcP3oU3dxVPm4MWyfYIldMWB14FahScxLhWdRnM9YZ/i9IFcLypXsuz7DjrJPtPUCAwEAAaNmMGQwHQYDVR0OBBYEFP5JzLUawNF+c3AXsYTEWHh7z2czMB8GA1UdIwQYMBaAFP5JzLUawNF+c3AXsYTEWHh7z2czMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/AgEBMA0GCSqGSIb3DQEBCwUAA4IBAQBc+Be7NDhpE09y7hLPZGRPl1cSKBw4RI0XIv6rlbSTFs5EebpTGjhx/whNxwEZhB9HZ7111Oa1YlT8xkI9DshB78mjAHCKBAJ76moK8tkG0aqdYpJ4ZcJTVBB7l98Rvgc7zfTii7WemTy72deBbSeiEtXavm4EF0mWjHhQ5Nxpnp00Bqn5g1x8CyTDypgmugnep+xG+iFzNmTdsz7WI9T/7kDMXqB7M/FPWBORyS98OJqNDswCLF8bIZYwUBEe+bRHFomoShMzaC3tvim7WCb16noDkSTMlfKO4pnvKhpcVdSgwcruATV7y+W+Lvmz2OT/Gui4JhqeoTewsxndhDDE\n-----END CERTIFICATE-----\n'
          type: string
        created_at:
          $ref: '#/components/schemas/zero-trust-gateway_timestamp'
        expires_on:
          $ref: '#/components/schemas/zero-trust-gateway_timestamp'
        fingerprint:
          description: The SHA256 fingerprint of the certificate.
          example: E9:19:49:AA:DD:D8:1E:C1:20:2A:D8:22:BF:A5:F8:FC:1A:F7:10:9F:C7:5B:69:AB:0:31:91:8B:61:B4:BF:1C
          type: string
        id:
          $ref: '#/components/schemas/zero-trust-gateway_uuid'
        in_use:
          description: Use this certificate for Gateway TLS interception
          type: boolean
        issuer_org:
          description: The organization that issued the certificate.
          example: Example Inc.
          type: string
        issuer_raw:
          description: The entire issuer field of the certificate.
          example: O=Example Inc.,L=California,ST=San Francisco,C=US
          type: string
        type:
          $ref: '#/components/schemas/zero-trust-gateway_type'
        updated_at:
          $ref: '#/components/schemas/zero-trust-gateway_timestamp'
        uploaded_on:
          $ref: '#/components/schemas/zero-trust-gateway_timestamp'
      type: object
    zero-trust-gateway_generate-cert-request:
      properties:
        validity_period_days:
          description: Number of days the generated certificate will be valid, minimum 1 day and maximum 30 years. Defaults to 5 years.
          example: 1826
          type: integer
      type: object
    zero-trust-gateway_timestamp:
      example: '2014-01-01T05:20:00.12345Z'
      format: date-time
      type: string
    zero-trust-gateway_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/zero-trust-gateway_messages'
        messages:
          $ref: '#/components/schemas/zero-trust-gateway_messages'
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      type: object
    zero-trust-gateway_binding_status:
      description: The deployment status of the certificate on Cloudflare's edge. Certificates in the 'active' state may be used for Gateway TLS interception.
      enum:
      - pending_deployment
      - active
      - pending_deletion
      - inactive
      type: string
    zero-trust-gateway_identifier:
      example: 699d98642c564d2e855e9661899b7252
      type: string
    zero-trust-gateway_response_collection:
      allOf:
      - $ref: '#/components/schemas/zero-trust-gateway_api-response-collection'
      - properties:
          result:
            items:
              $ref: '#/components/schemas/zero-trust-gateway_certificates'
            type: array
    zero-trust-gateway_api-response-single:
      allOf:
      - $ref: '#/components/schemas/zero-trust-gateway_api-response-common'
      type: object
    zero-trust-gateway_result_info:
      properties:
        count:
          description: Total number of results for the requested service
          example: 1
          type: number
        page:
          description: Current page within paginated list of results
          example: 1
          type: number
        per_page:
          description: Number of results per page of results
          example: 20
          type: number
        total_count:
          description: Total results available without any search parameters
          example: 2000
          type: number
      type: object
    zero-trust-gateway_single_response:
      allOf:
      - $ref: '#/components/schemas/zero-trust-gateway_api-response-single'
      - properties:
          result:
            $ref: '#/components/schemas/zero-trust-gateway_certificates'
    zero-trust-gateway_type:
      description: The type of certificate, either BYO-PKI (custom) or Gateway-managed.
      enum:
      - custom
      - gateway_managed
      example: gateway_managed
      type: string
    zero-trust-gateway_uuid:
      description: Certificate UUID tag.
      example: f174e90a-fafe-4643-bbbc-4a0ed4fc8415
      maxLength: 36
      type: string
    zero-trust-gateway_api-response-collection:
      allOf:
      - $ref: '#/components/schemas/zero-trust-gateway_api-response-common'
      - properties:
          result_info:
            $ref: '#/components/schemas/zero-trust-gateway_result_info'
      type: object
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/apigateway/
x-hasEquivalentPaths: true
