openapi: 3.2.0
info:
  description: 'To get started using Cloudflare''s products and services via the API, refer to [how to interact with Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/), which covers using tools like [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform) and the [official SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows who is making requests and what permissions you have. Create an API token to grant access to the API to perform actions.


    To create an API token, from the Cloudflare dashboard, go to My Profile > API Tokens and select Create Token. For more information on how to create and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).'
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: APIs.io Engineering Platform Cloudflare Secondary DNS (TSIG) API
  version: 4.0.0
tags:
- name: Secondary DNS (TSIG)
paths:
  /accounts/{account_id}/secondary_dns/tsigs:
    get:
      description: List TSIGs.
      operationId: secondary-dns-(-tsig)-list-tsi-gs
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/secondary-dns_account_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/secondary-dns_response_collection'
                - $ref: '#/components/schemas/secondary-dns_api-response-common-failure'
          description: List TSIGs response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/secondary-dns_response_collection'
          description: List TSIGs response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform List TSIGs
      tags:
      - Secondary DNS (TSIG)
      x-cfPermissionsRequired:
        enum:
        - '#dns_records:read'
        - '#organization:read'
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    post:
      description: Create TSIG.
      operationId: secondary-dns-(-tsig)-create-tsig
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/secondary-dns_account_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/secondary-dns_tsig'
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/secondary-dns_single_response'
                - $ref: '#/components/schemas/secondary-dns_api-response-common-failure'
          description: Create TSIG response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/secondary-dns_single_response'
          description: Create TSIG response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Create TSIG
      tags:
      - Secondary DNS (TSIG)
      x-cfPermissionsRequired:
        enum:
        - '#dns_records:edit'
        - '#organization:read'
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
  /accounts/{account_id}/secondary_dns/tsigs/{tsig_id}:
    delete:
      description: Delete TSIG.
      operationId: secondary-dns-(-tsig)-delete-tsig
      parameters:
      - in: path
        name: tsig_id
        required: true
        schema:
          $ref: '#/components/schemas/secondary-dns_schemas-identifier'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/secondary-dns_account_identifier'
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/secondary-dns_schemas-id_response'
                - $ref: '#/components/schemas/secondary-dns_api-response-common-failure'
          description: Delete TSIG response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/secondary-dns_schemas-id_response'
          description: Delete TSIG response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Delete TSIG
      tags:
      - Secondary DNS (TSIG)
      x-cfPermissionsRequired:
        enum:
        - '#dns_records:edit'
        - '#organization:read'
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    get:
      description: Get TSIG.
      operationId: secondary-dns-(-tsig)-tsig-details
      parameters:
      - in: path
        name: tsig_id
        required: true
        schema:
          $ref: '#/components/schemas/secondary-dns_schemas-identifier'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/secondary-dns_account_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/secondary-dns_single_response'
                - $ref: '#/components/schemas/secondary-dns_api-response-common-failure'
          description: TSIG Details response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/secondary-dns_single_response'
          description: TSIG Details response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform TSIG Details
      tags:
      - Secondary DNS (TSIG)
      x-cfPermissionsRequired:
        enum:
        - '#dns_records:read'
        - '#organization:read'
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    put:
      description: Modify TSIG.
      operationId: secondary-dns-(-tsig)-update-tsig
      parameters:
      - in: path
        name: tsig_id
        required: true
        schema:
          $ref: '#/components/schemas/secondary-dns_schemas-identifier'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/secondary-dns_account_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/secondary-dns_tsig'
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/secondary-dns_single_response'
                - $ref: '#/components/schemas/secondary-dns_api-response-common-failure'
          description: Update TSIG response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/secondary-dns_single_response'
          description: Update TSIG response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Update TSIG
      tags:
      - Secondary DNS (TSIG)
      x-cfPermissionsRequired:
        enum:
        - '#dns_records:edit'
        - '#organization:read'
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
components:
  schemas:
    secondary-dns_api-response-single:
      allOf:
      - $ref: '#/components/schemas/secondary-dns_api-response-common'
      type: object
    secondary-dns_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    secondary-dns_api-response-collection:
      allOf:
      - $ref: '#/components/schemas/secondary-dns_api-response-common'
      - properties:
          result_info:
            $ref: '#/components/schemas/secondary-dns_result_info'
      type: object
    secondary-dns_secret:
      description: TSIG secret.
      example: caf79a7804b04337c9c66ccd7bef9190a1e1679b5dd03d8aa10f7ad45e1a9dab92b417896c15d4d007c7c14194538d2a5d0feffdecc5a7f0e1c570cfa700837c
      type: string
    secondary-dns_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/secondary-dns_messages'
        messages:
          $ref: '#/components/schemas/secondary-dns_messages'
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      type: object
    secondary-dns_account_identifier:
      example: 01a7362d577a6c3019a474fd6f485823
      readOnly: true
      type: string
    secondary-dns_tsig:
      properties:
        algo:
          $ref: '#/components/schemas/secondary-dns_algo'
        id:
          $ref: '#/components/schemas/secondary-dns_schemas-identifier'
        name:
          $ref: '#/components/schemas/secondary-dns_schemas-name'
        secret:
          $ref: '#/components/schemas/secondary-dns_secret'
      required:
      - id
      - name
      - secret
      - algo
      type: object
    secondary-dns_single_response:
      allOf:
      - $ref: '#/components/schemas/secondary-dns_api-response-single'
      - properties:
          result:
            $ref: '#/components/schemas/secondary-dns_tsig'
    secondary-dns_algo:
      description: TSIG algorithm.
      example: hmac-sha512.
      type: string
    secondary-dns_response_collection:
      allOf:
      - $ref: '#/components/schemas/secondary-dns_api-response-collection'
      - properties:
          result:
            items:
              $ref: '#/components/schemas/secondary-dns_tsig'
            type: array
    secondary-dns_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/secondary-dns_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/secondary-dns_messages'
          example: []
        result:
          enum:
          - null
          type:
          - object
          - 'null'
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    secondary-dns_schemas-id_response:
      allOf:
      - $ref: '#/components/schemas/secondary-dns_api-response-single'
      - properties:
          result:
            properties:
              id:
                $ref: '#/components/schemas/secondary-dns_schemas-identifier'
            type: object
    secondary-dns_schemas-identifier:
      example: 69cd1e104af3e6ed3cb344f263fd0d5a
      readOnly: true
      type: string
    secondary-dns_result_info:
      properties:
        count:
          description: Total number of results for the requested service
          example: 1
          type: number
        page:
          description: Current page within paginated list of results
          example: 1
          type: number
        per_page:
          description: Number of results per page of results
          example: 20
          type: number
        total_count:
          description: Total results available without any search parameters
          example: 2000
          type: number
      type: object
    secondary-dns_schemas-name:
      description: TSIG key name.
      example: tsig.customer.cf.
      type: string
  securitySchemes:
    api_email:
      in: header
      name: X-Auth-Email
      type: apiKey
    api_key:
      in: header
      name: X-Auth-Key
      type: apiKey
    api_token:
      scheme: bearer
      type: http
    user_service_key:
      in: header
      name: X-Auth-User-Service-Key
      type: apiKey
