openapi: 3.0.0
info:
  version: "1.0.0"
  x-release: v4
  title: APIs.io Engineering Platform Amazon API Gateway 2014 11 13 Magic Interconnects API
  description: <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: apigateway
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/apigateway-2015-07-09.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: https://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: http://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
- url: https://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: Magic Interconnects
paths:
  /accounts/{account_id}/magic/cf_interconnects:
    get:
      description: Lists interconnects associated with an account.
      operationId: magic-interconnects-list-interconnects
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/magic_components-schemas-tunnels_collection_response'
                - $ref: '#/components/schemas/magic_api-response-common-failure'
          description: List interconnects response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_components-schemas-tunnels_collection_response'
          description: List interconnects response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform List interconnects
      tags:
      - Magic Interconnects
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    put:
      description: Updates multiple interconnects associated with an account. Use `?validate_only=true` as an optional query parameter to only run validation without persisting changes.
      operationId: magic-interconnects-update-multiple-interconnects
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      requestBody:
        content:
          application/json:
            schema:
              required:
              - id
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/magic_components-schemas-modified_tunnels_collection_response'
                - $ref: '#/components/schemas/magic_api-response-common-failure'
          description: Update multiple interconnects response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_components-schemas-modified_tunnels_collection_response'
          description: Update multiple interconnects response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Update multiple interconnects
      tags:
      - Magic Interconnects
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
  /accounts/{account_id}/magic/cf_interconnects/{cf_interconnect_id}:
    get:
      description: Lists details for a specific interconnect.
      operationId: magic-interconnects-list-interconnect-details
      parameters:
      - in: path
        name: cf_interconnect_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/magic_components-schemas-tunnel_single_response'
                - $ref: '#/components/schemas/magic_api-response-common-failure'
          description: List interconnect Details response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_components-schemas-tunnel_single_response'
          description: List interconnect Details response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform List interconnect Details
      tags:
      - Magic Interconnects
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    put:
      description: Updates a specific interconnect associated with an account. Use `?validate_only=true` as an optional query parameter to only run validation without persisting changes.
      operationId: magic-interconnects-update-interconnect
      parameters:
      - in: path
        name: cf_interconnect_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/magic_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/magic_components-schemas-tunnel_update_request'
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/magic_components-schemas-tunnel_modified_response'
                - $ref: '#/components/schemas/magic_api-response-common-failure'
          description: Update interconnect response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/magic_components-schemas-tunnel_modified_response'
          description: Update interconnect response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Update interconnect
      tags:
      - Magic Interconnects
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
components:
  schemas:
    magic_schemas-created_on:
      description: The date and time the tunnel was created.
      example: '2017-06-14T00:00:00Z'
      format: date-time
      readOnly: true
      type: string
    magic_api-response-single:
      allOf:
      - $ref: '#/components/schemas/magic_api-response-common'
      - properties:
          result:
            anyOf:
            - nullable: true
              type: object
            - nullable: true
              type: string
      type: object
    magic_schemas-identifier:
      description: Tunnel identifier tag.
      example: c4a7362d577a6c3019a474fd6f485821
      maxLength: 32
      readOnly: true
      type: string
    magic_identifier:
      description: Identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      readOnly: true
      type: string
    magic_schemas-health_check:
      properties:
        enabled:
          default: true
          description: Determines whether to run healthchecks for a tunnel.
          example: true
          type: boolean
        rate:
          default: mid
          description: How frequent the health check is run. The default value is `mid`.
          enum:
          - low
          - mid
          - high
          example: low
          type: string
        target:
          description: The destination address in a request type health check. After the healthcheck is decapsulated at the customer end of the tunnel, the ICMP echo will be forwarded to this address. This field defaults to `customer_gre_endpoint address`.
          example: 203.0.113.1
          type: string
        type:
          default: reply
          description: The type of healthcheck to run, reply or request. The default value is `reply`.
          enum:
          - reply
          - request
          example: request
          type: string
      type: object
    magic_interconnect_components-schemas-description:
      description: An optional description of the interconnect.
      example: Tunnel for Interconnect to ORD
      type: string
    magic_components-schemas-modified_tunnels_collection_response:
      allOf:
      - $ref: '#/components/schemas/magic_api-response-single'
      - properties:
          result:
            properties:
              modified:
                example: true
                type: boolean
              modified_interconnects:
                items:
                  $ref: '#/components/schemas/magic_interconnect'
                type: array
    magic_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/magic_messages'
        messages:
          $ref: '#/components/schemas/magic_messages'
        result:
          anyOf:
          - type: object
          - items: {}
            type: array
          - type: string
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    magic_components-schemas-tunnel_update_request:
      properties:
        description:
          $ref: '#/components/schemas/magic_interconnect_components-schemas-description'
        gre:
          $ref: '#/components/schemas/magic_gre'
        health_check:
          $ref: '#/components/schemas/magic_schemas-health_check'
        interface_address:
          $ref: '#/components/schemas/magic_interface_address'
        mtu:
          $ref: '#/components/schemas/magic_schemas-mtu'
      type: object
    magic_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    magic_components-schemas-tunnel_single_response:
      allOf:
      - $ref: '#/components/schemas/magic_api-response-single'
      - properties:
          result:
            properties:
              interconnect:
                $ref: '#/components/schemas/magic_interconnect'
            type: object
    magic_interface_address:
      description: 'A 31-bit prefix (/31 in CIDR notation) supporting two hosts, one for each side of the tunnel. Select the subnet from the following private IP space: 10.0.0.0–10.255.255.255, 172.16.0.0–172.31.255.255, 192.168.0.0–192.168.255.255.'
      example: 192.0.2.0/31
      type: string
    magic_gre:
      description: The configuration specific to GRE interconnects.
      properties:
        cloudflare_endpoint:
          description: The IP address assigned to the Cloudflare side of the GRE tunnel created as part of the Interconnect.
          example: 203.0.113.1
          type: string
      type: object
    magic_schemas-modified_on:
      description: The date and time the tunnel was last modified.
      example: '2017-06-14T05:20:00Z'
      format: date-time
      readOnly: true
      type: string
    magic_components-schemas-tunnels_collection_response:
      allOf:
      - $ref: '#/components/schemas/magic_api-response-single'
      - properties:
          result:
            properties:
              interconnects:
                items:
                  $ref: '#/components/schemas/magic_interconnect'
                type: array
    magic_interconnect:
      properties:
        colo_name:
          $ref: '#/components/schemas/magic_components-schemas-name'
        created_on:
          $ref: '#/components/schemas/magic_schemas-created_on'
        description:
          $ref: '#/components/schemas/magic_interconnect_components-schemas-description'
        gre:
          $ref: '#/components/schemas/magic_gre'
        health_check:
          $ref: '#/components/schemas/magic_schemas-health_check'
        id:
          $ref: '#/components/schemas/magic_schemas-identifier'
        interface_address:
          $ref: '#/components/schemas/magic_interface_address'
        modified_on:
          $ref: '#/components/schemas/magic_schemas-modified_on'
        mtu:
          $ref: '#/components/schemas/magic_schemas-mtu'
        name:
          $ref: '#/components/schemas/magic_components-schemas-name'
      type: object
    magic_components-schemas-tunnel_modified_response:
      allOf:
      - $ref: '#/components/schemas/magic_api-response-single'
      - properties:
          result:
            properties:
              modified:
                example: true
                type: boolean
              modified_interconnect:
                $ref: '#/components/schemas/magic_interconnect'
            type: object
    magic_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/magic_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/magic_messages'
          example: []
        result:
          enum:
          - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    magic_schemas-mtu:
      default: 1476
      description: The Maximum Transmission Unit (MTU) in bytes for the interconnect. The minimum value is 576.
      type: integer
    magic_components-schemas-name:
      description: The name of the interconnect. The name cannot share a name with other tunnels.
      example: pni_ord
      type: string
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/apigateway/
x-hasEquivalentPaths: true
