openapi: 3.0.0
info:
  version: 2015-07-09
  x-release: v4
  title: APIs.io Engineering Platform Amazon API Gateway 2014 11 13 2021 11 15 API
  description: <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: apigateway
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/apigateway-2015-07-09.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: https://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: http://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
- url: https://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: 2021 11 15
paths:
  /2021-11-15/functions/{FunctionName}/response-streaming-invocations:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: InvokeWithResponseStream
      description: <p>Configure your Lambda functions to stream response payloads back to clients. For more information, see <a href="https://docs.aws.amazon.com/lambda/latest/dg/configuration-response-streaming.html">Configuring a Lambda function to stream responses</a>.</p> <p>This operation requires permission for the <a href="https://docs.aws.amazon.com/IAM/latest/UserGuide/list_awslambda.html">lambda:InvokeFunction</a> action. For details on how to set up permissions for cross-account invocations, see <a href="https://docs.aws.amazon.com/lambda/latest/dg/access-control-resource-based.html#permissions-resource-xaccountinvoke">Granting function access to other accounts</a>.</p>
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvokeWithResponseStreamResponse'
        '480':
          description: ServiceException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceException'
        '481':
          description: ResourceNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
        '482':
          description: InvalidRequestContentException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidRequestContentException'
        '483':
          description: RequestTooLargeException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestTooLargeException'
        '484':
          description: UnsupportedMediaTypeException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnsupportedMediaTypeException'
        '485':
          description: TooManyRequestsException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TooManyRequestsException'
        '486':
          description: InvalidParameterValueException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidParameterValueException'
        '487':
          description: EC2UnexpectedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EC2UnexpectedException'
        '488':
          description: SubnetIPAddressLimitReachedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubnetIPAddressLimitReachedException'
        '489':
          description: ENILimitReachedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ENILimitReachedException'
        '490':
          description: EFSMountConnectivityException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EFSMountConnectivityException'
        '491':
          description: EFSMountFailureException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EFSMountFailureException'
        '492':
          description: EFSMountTimeoutException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EFSMountTimeoutException'
        '493':
          description: EFSIOException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EFSIOException'
        '494':
          description: SnapStartException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SnapStartException'
        '495':
          description: SnapStartTimeoutException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SnapStartTimeoutException'
        '496':
          description: SnapStartNotReadyException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SnapStartNotReadyException'
        '497':
          description: EC2ThrottledException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EC2ThrottledException'
        '498':
          description: EC2AccessDeniedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EC2AccessDeniedException'
        '499':
          description: InvalidSubnetIDException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidSubnetIDException'
        '500':
          description: InvalidSecurityGroupIDException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidSecurityGroupIDException'
        '501':
          description: InvalidZipFileException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidZipFileException'
        '502':
          description: KMSDisabledException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KMSDisabledException'
        '503':
          description: KMSInvalidStateException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KMSInvalidStateException'
        '504':
          description: KMSAccessDeniedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KMSAccessDeniedException'
        '505':
          description: KMSNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KMSNotFoundException'
        '506':
          description: InvalidRuntimeException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidRuntimeException'
        '507':
          description: ResourceConflictException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceConflictException'
        '508':
          description: ResourceNotReadyException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotReadyException'
      parameters:
      - name: FunctionName
        in: path
        required: true
        description: <p>The name of the Lambda function.</p> <p class="title"> <b>Name formats</b> </p> <ul> <li> <p> <b>Function name</b> â€“ <code>my-function</code>.</p> </li> <li> <p> <b>Function ARN</b> â€“ <code>arn:aws:lambda:us-west-2:123456789012:function:my-function</code>.</p> </li> <li> <p> <b>Partial ARN</b> â€“ <code>123456789012:function:my-function</code>.</p> </li> </ul> <p>The length constraint applies only to the full ARN. If you specify only the function name, it is limited to 64 characters in length.</p>
        schema:
          type: string
          pattern: (arn:(aws[a-zA-Z-]*)?:lambda:)?([a-z]{2}(-gov)?-[a-z]+-\d{1}:)?(\d{12}:)?(function:)?([a-zA-Z0-9-_\.]+)(:(\$LATEST|[a-zA-Z0-9-_]+))?
          minLength: 1
          maxLength: 170
      - name: X-Amz-Invocation-Type
        in: header
        required: false
        description: <p>Use one of the following options:</p> <ul> <li> <p> <code>RequestResponse</code> (default) â€“ Invoke the function synchronously. Keep the connection open until the function returns a response or times out. The API operation response includes the function response and additional data.</p> </li> <li> <p> <code>DryRun</code> â€“ Validate parameter values and verify that the IAM user or role has permission to invoke the function.</p> </li> </ul>
        schema:
          type: string
          enum:
          - RequestResponse
          - DryRun
      - name: X-Amz-Log-Type
        in: header
        required: false
        description: Set to <code>Tail</code> to include the execution log in the response. Applies to synchronously invoked functions only.
        schema:
          type: string
          enum:
          - None
          - Tail
      - name: X-Amz-Client-Context
        in: header
        required: false
        description: Up to 3,583 bytes of base64-encoded data about the invoking client to pass to the function in the context object.
        schema:
          type: string
      - name: Qualifier
        in: query
        required: false
        description: The alias name.
        schema:
          type: string
          pattern: (|[a-zA-Z0-9$_-]+)
          minLength: 1
          maxLength: 128
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Payload:
                  description: '<p>The JSON that you want to provide to your Lambda function as input.</p> <p>You can enter the JSON directly. For example, <code>--payload ''{ "key": "value" }''</code>. You can also specify a file path. For example, <code>--payload file://payload.json</code>.</p>'
                  type: string
                  format: password
      tags:
      - 2021 11 15
components:
  parameters:
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
  schemas:
    KMSInvalidStateException: {}
    TooManyRequestsException: {}
    EFSMountFailureException: {}
    KMSNotFoundException: {}
    ResourceNotReadyException: {}
    EC2ThrottledException: {}
    InvokeResponseStreamUpdate:
      type: object
      properties:
        Payload:
          allOf:
          - $ref: '#/components/schemas/Blob'
          - description: Data returned by your Lambda function.
      description: A chunk of the streamed response payload.
    Integer:
      type: integer
    SnapStartNotReadyException: {}
    InvokeWithResponseStreamResponseEvent:
      type: object
      properties:
        PayloadChunk:
          allOf:
          - $ref: '#/components/schemas/InvokeResponseStreamUpdate'
          - description: A chunk of the streamed response payload.
        InvokeComplete:
          allOf:
          - $ref: '#/components/schemas/InvokeWithResponseStreamCompleteEvent'
          - description: An object that's returned when the stream has ended and all the payload chunks have been returned.
      description: An object that includes a chunk of the response payload. When the stream has ended, Lambda includes a <code>InvokeComplete</code> object.
    InvalidZipFileException: {}
    KMSDisabledException: {}
    InvalidSubnetIDException: {}
    ResourceConflictException: {}
    InvalidRequestContentException: {}
    InvalidParameterValueException: {}
    ENILimitReachedException: {}
    EFSIOException: {}
    String:
      type: string
    KMSAccessDeniedException: {}
    InvokeWithResponseStreamResponse:
      type: object
      properties:
        StatusCode:
          allOf:
          - $ref: '#/components/schemas/Integer'
          - description: For a successful request, the HTTP status code is in the 200 range. For the <code>RequestResponse</code> invocation type, this status code is 200. For the <code>DryRun</code> invocation type, this status code is 204.
        EventStream:
          allOf:
          - $ref: '#/components/schemas/InvokeWithResponseStreamResponseEvent'
          - description: The stream of response payloads.
    InvokeWithResponseStreamCompleteEvent:
      type: object
      properties:
        ErrorCode:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: An error code.
        ErrorDetails:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The details of any returned error.
        LogResult:
          allOf:
          - $ref: '#/components/schemas/String'
          - description: The last 4 KB of the execution log, which is base64-encoded.
      description: A response confirming that the event stream is complete.
    SnapStartTimeoutException: {}
    EFSMountTimeoutException: {}
    ServiceException: {}
    InvalidRuntimeException: {}
    InvalidSecurityGroupIDException: {}
    ResourceNotFoundException: {}
    EC2AccessDeniedException: {}
    EFSMountConnectivityException: {}
    Blob:
      type: string
      format: password
    SubnetIPAddressLimitReachedException: {}
    UnsupportedMediaTypeException: {}
    RequestTooLargeException: {}
    SnapStartException: {}
    EC2UnexpectedException: {}
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/apigateway/
x-hasEquivalentPaths: true
