openapi: 3.2.0
info:
  description: 'To get started using Cloudflare''s products and services via the API, refer to [how to interact with Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/), which covers using tools like [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform) and the [official SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to maintain your Cloudflare resources.


    Using the Cloudflare API requires authentication so that Cloudflare knows who is making requests and what permissions you have. Create an API token to grant access to the API to perform actions.


    To create an API token, from the Cloudflare dashboard, go to My Profile > API Tokens and select Create Token. For more information on how to create and troubleshoot API tokens, refer to

    our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).


    Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).'
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  title: APIs.io Engineering Platform Cloudflare Secondary DNS (ACL) API
  version: 4.0.0
tags:
- name: Secondary DNS (ACL)
paths:
  /accounts/{account_id}/secondary_dns/acls:
    get:
      description: List ACLs.
      operationId: secondary-dns-(-acl)-list-ac-ls
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/secondary-dns_account_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/secondary-dns_components-schemas-response_collection'
                - $ref: '#/components/schemas/secondary-dns_api-response-common-failure'
          description: List ACLs response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/secondary-dns_components-schemas-response_collection'
          description: List ACLs response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform List ACLs
      tags:
      - Secondary DNS (ACL)
      x-cfPermissionsRequired:
        enum:
        - '#organization:read'
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    post:
      description: Create ACL.
      operationId: secondary-dns-(-acl)-create-acl
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/secondary-dns_account_identifier'
      requestBody:
        content:
          application/json:
            schema:
              properties:
                ip_range:
                  $ref: '#/components/schemas/secondary-dns_ip_range'
                name:
                  $ref: '#/components/schemas/secondary-dns_acl_components-schemas-name'
              required:
              - name
              - ip_range
              type: object
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/secondary-dns_components-schemas-single_response'
                - $ref: '#/components/schemas/secondary-dns_api-response-common-failure'
          description: Create ACL response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/secondary-dns_components-schemas-single_response'
          description: Create ACL response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Create ACL
      tags:
      - Secondary DNS (ACL)
      x-cfPermissionsRequired:
        enum:
        - '#dns_records:edit'
        - '#organization:read'
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
  /accounts/{account_id}/secondary_dns/acls/{acl_id}:
    delete:
      description: Delete ACL.
      operationId: secondary-dns-(-acl)-delete-acl
      parameters:
      - in: path
        name: acl_id
        required: true
        schema:
          $ref: '#/components/schemas/secondary-dns_components-schemas-identifier'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/secondary-dns_account_identifier'
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/secondary-dns_components-schemas-id_response'
                - $ref: '#/components/schemas/secondary-dns_api-response-common-failure'
          description: Delete ACL response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/secondary-dns_components-schemas-id_response'
          description: Delete ACL response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Delete ACL
      tags:
      - Secondary DNS (ACL)
      x-cfPermissionsRequired:
        enum:
        - '#dns_records:edit'
        - '#organization:read'
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    get:
      description: Get ACL.
      operationId: secondary-dns-(-acl)-acl-details
      parameters:
      - in: path
        name: acl_id
        required: true
        schema:
          $ref: '#/components/schemas/secondary-dns_components-schemas-identifier'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/secondary-dns_account_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/secondary-dns_components-schemas-single_response'
                - $ref: '#/components/schemas/secondary-dns_api-response-common-failure'
          description: ACL Details response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/secondary-dns_components-schemas-single_response'
          description: ACL Details response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform ACL Details
      tags:
      - Secondary DNS (ACL)
      x-cfPermissionsRequired:
        enum:
        - '#organization:read'
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
    put:
      description: Modify ACL.
      operationId: secondary-dns-(-acl)-update-acl
      parameters:
      - in: path
        name: acl_id
        required: true
        schema:
          $ref: '#/components/schemas/secondary-dns_components-schemas-identifier'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/secondary-dns_account_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/secondary-dns_acl'
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/secondary-dns_components-schemas-single_response'
                - $ref: '#/components/schemas/secondary-dns_api-response-common-failure'
          description: Update ACL response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/secondary-dns_components-schemas-single_response'
          description: Update ACL response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Update ACL
      tags:
      - Secondary DNS (ACL)
      x-cfPermissionsRequired:
        enum:
        - '#dns_records:edit'
        - '#organization:read'
      x-cfPlanAvailability:
        business: false
        enterprise: true
        free: false
        pro: false
components:
  schemas:
    secondary-dns_api-response-single:
      allOf:
      - $ref: '#/components/schemas/secondary-dns_api-response-common'
      type: object
    secondary-dns_ip_range:
      description: Allowed IPv4/IPv6 address range of primary or secondary nameservers. This will be applied for the entire account. The IP range is used to allow additional NOTIFY IPs for secondary zones and IPs Cloudflare allows AXFR/IXFR requests from for primary zones. CIDRs are limited to a maximum of /24 for IPv4 and /64 for IPv6 respectively.
      example: 192.0.2.53/28
      type: string
    secondary-dns_components-schemas-identifier:
      example: 23ff594956f20c2a721606e94745a8aa
      readOnly: true
      type: string
    secondary-dns_acl_components-schemas-name:
      description: The name of the acl.
      example: my-acl-1
      type: string
    secondary-dns_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    secondary-dns_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/secondary-dns_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/secondary-dns_messages'
          example: []
        result:
          enum:
          - null
          type:
          - object
          - 'null'
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    secondary-dns_api-response-collection:
      allOf:
      - $ref: '#/components/schemas/secondary-dns_api-response-common'
      - properties:
          result_info:
            $ref: '#/components/schemas/secondary-dns_result_info'
      type: object
    secondary-dns_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/secondary-dns_messages'
        messages:
          $ref: '#/components/schemas/secondary-dns_messages'
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      type: object
    secondary-dns_components-schemas-id_response:
      allOf:
      - $ref: '#/components/schemas/secondary-dns_api-response-single'
      - properties:
          result:
            properties:
              id:
                $ref: '#/components/schemas/secondary-dns_components-schemas-identifier'
            type: object
    secondary-dns_account_identifier:
      example: 01a7362d577a6c3019a474fd6f485823
      readOnly: true
      type: string
    secondary-dns_result_info:
      properties:
        count:
          description: Total number of results for the requested service
          example: 1
          type: number
        page:
          description: Current page within paginated list of results
          example: 1
          type: number
        per_page:
          description: Number of results per page of results
          example: 20
          type: number
        total_count:
          description: Total results available without any search parameters
          example: 2000
          type: number
      type: object
    secondary-dns_acl:
      properties:
        id:
          $ref: '#/components/schemas/secondary-dns_components-schemas-identifier'
        ip_range:
          $ref: '#/components/schemas/secondary-dns_ip_range'
        name:
          $ref: '#/components/schemas/secondary-dns_acl_components-schemas-name'
      required:
      - id
      - name
      - ip_range
      type: object
    secondary-dns_components-schemas-response_collection:
      allOf:
      - $ref: '#/components/schemas/secondary-dns_api-response-collection'
      - properties:
          result:
            items:
              $ref: '#/components/schemas/secondary-dns_acl'
            type: array
    secondary-dns_components-schemas-single_response:
      allOf:
      - $ref: '#/components/schemas/secondary-dns_api-response-single'
      - properties:
          result:
            $ref: '#/components/schemas/secondary-dns_acl'
  securitySchemes:
    api_email:
      in: header
      name: X-Auth-Email
      type: apiKey
    api_key:
      in: header
      name: X-Auth-Key
      type: apiKey
    api_token:
      scheme: bearer
      type: http
    user_service_key:
      in: header
      name: X-Auth-User-Service-Key
      type: apiKey
