openapi: 3.0.0
info:
  version: 2015-07-09
  x-release: v4
  title: 'APIs.io Engineering Platform Amazon API Gateway 2014 11 13 #Action=ListServiceSpecificCredentials API'
  description: <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: apigateway
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/apigateway-2015-07-09.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: https://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: http://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
- url: https://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#Action=ListServiceSpecificCredentials'
paths:
  /#Action=ListServiceSpecificCredentials:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    get:
      x-aws-operation-name: ListServiceSpecificCredentials
      operationId: GET_ListServiceSpecificCredentials
      description: Returns information about the service-specific credentials associated with the specified IAM user. If none exists, the operation returns an empty list. The service-specific credentials returned by this operation are used only for authenticating the IAM user to a specific service. For more information about using service-specific credentials to authenticate to an Amazon Web Services service, see <a href="https://docs.aws.amazon.com/codecommit/latest/userguide/setting-up-gc.html">Set up service-specific credentials</a> in the CodeCommit User Guide.
      responses:
        '200':
          description: Success
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/ListServiceSpecificCredentialsResponse'
        '480':
          description: NoSuchEntityException
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/NoSuchEntityException'
        '481':
          description: ServiceNotSupportedException
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/ServiceNotSupportedException'
      parameters:
      - name: UserName
        in: query
        required: false
        description: '<p>The name of the user whose service-specific credentials you want information about. If this value is not specified, then the operation assumes the user whose credentials are used to call the operation.</p> <p>This parameter allows (through its <a href="http://wikipedia.org/wiki/regex">regex pattern</a>) a string of characters consisting of upper and lowercase alphanumeric characters with no spaces. You can also include any of the following characters: _+=,.@-</p>'
        schema:
          type: string
          pattern: '[\w+=,.@-]+'
          minLength: 1
          maxLength: 64
      - name: ServiceName
        in: query
        required: false
        description: Filters the returned results to only those for the specified Amazon Web Services service. If not specified, then Amazon Web Services returns service-specific credentials for all services.
        schema:
          type: string
      - name: Action
        in: query
        required: true
        schema:
          type: string
          enum:
          - ListServiceSpecificCredentials
      - name: Version
        in: query
        required: true
        schema:
          type: string
          enum:
          - 2010-05-08
      tags:
      - '#Action=ListServiceSpecificCredentials'
    post:
      x-aws-operation-name: ListServiceSpecificCredentials
      operationId: POST_ListServiceSpecificCredentials
      description: Returns information about the service-specific credentials associated with the specified IAM user. If none exists, the operation returns an empty list. The service-specific credentials returned by this operation are used only for authenticating the IAM user to a specific service. For more information about using service-specific credentials to authenticate to an Amazon Web Services service, see <a href="https://docs.aws.amazon.com/codecommit/latest/userguide/setting-up-gc.html">Set up service-specific credentials</a> in the CodeCommit User Guide.
      responses:
        '200':
          description: Success
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/ListServiceSpecificCredentialsResponse'
        '480':
          description: NoSuchEntityException
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/NoSuchEntityException'
        '481':
          description: ServiceNotSupportedException
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/ServiceNotSupportedException'
      requestBody:
        content:
          text/xml:
            schema:
              $ref: '#/components/schemas/ListServiceSpecificCredentialsRequest'
      parameters:
      - name: Action
        in: query
        required: true
        schema:
          type: string
          enum:
          - ListServiceSpecificCredentials
      - name: Version
        in: query
        required: true
        schema:
          type: string
          enum:
          - 2010-05-08
      tags:
      - '#Action=ListServiceSpecificCredentials'
components:
  parameters:
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
  schemas:
    statusType:
      type: string
      enum:
      - Active
      - Inactive
    userNameType:
      type: string
      pattern: '[\w+=,.@-]+'
      minLength: 1
      maxLength: 64
    ServiceSpecificCredentialsListType:
      type: array
      items:
        $ref: '#/components/schemas/ServiceSpecificCredentialMetadata'
    serviceName:
      type: string
    NoSuchEntityException: {}
    ListServiceSpecificCredentialsRequest:
      type: object
      title: ListServiceSpecificCredentialsRequest
      properties:
        UserName:
          allOf:
          - $ref: '#/components/schemas/userNameType'
          - description: '<p>The name of the user whose service-specific credentials you want information about. If this value is not specified, then the operation assumes the user whose credentials are used to call the operation.</p> <p>This parameter allows (through its <a href="http://wikipedia.org/wiki/regex">regex pattern</a>) a string of characters consisting of upper and lowercase alphanumeric characters with no spaces. You can also include any of the following characters: _+=,.@-</p>'
        ServiceName:
          allOf:
          - $ref: '#/components/schemas/serviceName'
          - description: Filters the returned results to only those for the specified Amazon Web Services service. If not specified, then Amazon Web Services returns service-specific credentials for all services.
    dateType:
      type: string
      format: date-time
    ServiceSpecificCredentialMetadata:
      type: object
      required:
      - UserName
      - Status
      - ServiceUserName
      - CreateDate
      - ServiceSpecificCredentialId
      - ServiceName
      properties:
        UserName:
          allOf:
          - $ref: '#/components/schemas/userNameType'
          - description: The name of the IAM user associated with the service-specific credential.
        Status:
          allOf:
          - $ref: '#/components/schemas/statusType'
          - description: The status of the service-specific credential. <code>Active</code> means that the key is valid for API calls, while <code>Inactive</code> means it is not.
        ServiceUserName:
          allOf:
          - $ref: '#/components/schemas/serviceUserName'
          - description: The generated user name for the service-specific credential.
        CreateDate:
          allOf:
          - $ref: '#/components/schemas/dateType'
          - description: The date and time, in <a href="http://www.iso.org/iso/iso8601">ISO 8601 date-time format</a>, when the service-specific credential were created.
        ServiceSpecificCredentialId:
          allOf:
          - $ref: '#/components/schemas/serviceSpecificCredentialId'
          - description: The unique identifier for the service-specific credential.
        ServiceName:
          allOf:
          - $ref: '#/components/schemas/serviceName'
          - description: The name of the service associated with the service-specific credential.
      description: Contains additional details about a service-specific credential.
    ServiceNotSupportedException: {}
    ListServiceSpecificCredentialsResponse:
      type: object
      properties:
        ServiceSpecificCredentials:
          allOf:
          - $ref: '#/components/schemas/ServiceSpecificCredentialsListType'
          - description: A list of structures that each contain details about a service-specific credential.
    serviceUserName:
      type: string
      pattern: '[\w+=,.@-]+'
      minLength: 17
      maxLength: 200
    serviceSpecificCredentialId:
      type: string
      pattern: '[\w]+'
      minLength: 20
      maxLength: 128
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/apigateway/
x-hasEquivalentPaths: true
