openapi: 3.0.0
info:
  version: "1.0.0"
  x-release: v4
  title: APIs.io Engineering Platform Amazon API Gateway 2014 11 13 Account Request Tracer API
  description: <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: apigateway
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/apigateway-2015-07-09.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: https://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: http://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
- url: https://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: Account Request Tracer
paths:
  /accounts/{account_id}/request-tracer/trace:
    post:
      operationId: account-request-tracer-request-trace
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/request-tracer_identifier'
      requestBody:
        content:
          application/json:
            example:
              body:
                base64: c29tZV9yZXF1ZXN0X2JvZHk=
              context:
                geoloc:
                  city: London
                skip_challenge: true
              cookies:
                cookie_name_1: cookie_value_1
                cookie_name_2: cookie_value_2
              headers:
                header_name_1: header_value_1
                header_name_2: header_value_2
              method: PUT
              protocol: HTTP/1.1
              url: https://some.zone/some_path
            schema:
              properties:
                body:
                  properties:
                    base64:
                      description: Base64 encoded request body
                      example: c29tZV9yZXF1ZXN0X2JvZHk=
                      type: string
                    json:
                      description: Arbitrary json as request body
                      type: object
                    plain_text:
                      description: Request body as plain text
                      type: string
                  type: object
                context:
                  description: Additional request parameters
                  properties:
                    bot_score:
                      description: Bot score used for evaluating tracing request processing
                      type: integer
                    geoloc:
                      description: Geodata for tracing request
                      properties:
                        city:
                          example: London
                          type: string
                        continent:
                          type: string
                        is_eu_country:
                          type: boolean
                        iso_code:
                          type: string
                        latitude:
                          type: number
                        longitude:
                          type: number
                        postal_code:
                          type: string
                        region_code:
                          type: string
                        subdivision_2_iso_code:
                          type: string
                        timezone:
                          type: string
                      type: object
                    skip_challenge:
                      description: 'Whether to skip any challenges for tracing request (e.g.: captcha)'
                      example: true
                      type: boolean
                    threat_score:
                      description: Threat score used for evaluating tracing request processing
                      type: integer
                  type: object
                cookies:
                  additionalProperties:
                    type: string
                  description: Cookies added to tracing request
                  example:
                    cookie_name_1: cookie_value_1
                    cookie_name_2: cookie_value_2
                  type: object
                headers:
                  additionalProperties:
                    type: string
                  description: Headers added to tracing request
                  example:
                    header_name_1: header_value_1
                    header_name_2: header_value_2
                  type: object
                method:
                  description: HTTP Method of tracing request
                  example: PUT
                  type: string
                protocol:
                  description: HTTP Protocol of tracing request
                  example: HTTP/1.1
                  type: string
                skip_response:
                  description: Skip sending the request to the Origin server after all rules evaluation
                  type: boolean
                url:
                  description: URL to which perform tracing request
                  example: https://some.zone/some_path
                  type: string
              required:
              - url
              - method
              type: object
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/request-tracer_api-response-common-failure'
          description: Request Trace response failure
        '200':
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/request-tracer_api-response-common'
                - properties:
                    result:
                      description: Trace result with an origin status code
                      properties:
                        status_code:
                          description: HTTP Status code of zone response
                          type: integer
                        trace:
                          $ref: '#/components/schemas/request-tracer_trace'
                      type: object
                  type: object
                type: object
          description: Request Trace response
      security:
      - api_email: []
        api_key: []
      summary: APIs.io Engineering Platform Request Trace
      tags:
      - Account Request Tracer
      x-api-token-group:
      - Allow Request Tracer Read
      x-cfPlanAvailability:
        business: true
        enterprise: true
        free: true
        pro: true
components:
  schemas:
    request-tracer_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/request-tracer_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/request-tracer_messages'
          example: []
        result:
          enum:
          - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    request-tracer_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/request-tracer_messages'
        messages:
          $ref: '#/components/schemas/request-tracer_messages'
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      type: object
    request-tracer_trace:
      items:
        description: List of steps acting on request/response
        properties:
          action:
            description: If step type is rule, then action performed by this rule
            example: execute
            pattern: ^[a-z_]+$
            type: string
          action_parameters:
            description: If step type is rule, then action parameters of this rule as JSON
            example:
              id: 4814384a9e5d4991b9815dcfc25d2f1f
            type: object
          description:
            description: If step type is rule or ruleset, the description of this entity
            example: some rule
            type: string
          expression:
            description: If step type is rule, then expression used to match for this rule
            example: ip.src ne 1.1.1.1
            type: string
          kind:
            description: If step type is ruleset, then kind of this ruleset
            example: zone
            type: string
          matched:
            description: Whether tracing step affected tracing request/response
            example: true
            type: boolean
          name:
            description: If step type is ruleset, then name of this ruleset
            example: some ruleset name
            type: string
          step_name:
            description: Tracing step identifying name
            example: rule_id01
            type: string
          trace:
            $ref: '#/components/schemas/request-tracer_trace'
          type:
            description: Tracing step type
            example: rule
            type: string
        type: object
      type: array
    request-tracer_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
    request-tracer_identifier:
      description: Identifier
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      readOnly: true
      type: string
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/apigateway/
x-hasEquivalentPaths: true
