openapi: 3.0.0
info:
  version: 2015-07-09
  x-release: v4
  title: APIs.io Engineering Platform Amazon API Gateway 2014 11 13 Calls Apps API
  description: <fullname>Amazon API Gateway</fullname> <p>Amazon API Gateway helps developers deliver robust, secure, and scalable mobile and web application back ends. API Gateway allows developers to securely connect mobile and web applications to APIs that run on AWS Lambda, Amazon EC2, or other publicly addressable web services that are hosted outside of AWS.</p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: apigateway
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/apigateway-2015-07-09.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: https://apigateway.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon API Gateway multi-region endpoint
- url: http://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
- url: https://apigateway.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon API Gateway endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: Calls Apps
paths:
  /accounts/{account_id}/calls/apps:
    get:
      description: Lists all apps in the Cloudflare account
      operationId: calls-apps-list
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/calls_account_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/calls_api-response-common-failure'
          description: List apps response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/calls_app_response_collection'
          description: List apps response
      security:
      - api_token: []
      summary: APIs.io Engineering Platform List apps
      tags:
      - Calls Apps
      x-api-token-group:
      - Calls Write
      - Calls Read
    post:
      description: Creates a new Cloudflare calls app. An app is an unique enviroment where each Session can access all Tracks within the app.
      operationId: calls-apps-create-a-new-app
      parameters:
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/calls_account_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/calls_app_editable_fields'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/calls_app_response_single_with_secret'
          description: Created a new app
      security:
      - api_token: []
      summary: APIs.io Engineering Platform Create a new app
      tags:
      - Calls Apps
      x-api-token-group:
      - Calls Write
  /accounts/{account_id}/calls/apps/{app_id}:
    delete:
      description: Deletes an app from Cloudflare Calls
      operationId: calls-apps-delete-app
      parameters:
      - in: path
        name: app_id
        required: true
        schema:
          $ref: '#/components/schemas/calls_identifier'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/calls_account_identifier'
      responses:
        4XX:
          content:
            application/json: {}
          description: Delete app response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/calls_app_response_single'
          description: Delete app response
      security:
      - api_token: []
      summary: APIs.io Engineering Platform Delete app
      tags:
      - Calls Apps
      x-api-token-group:
      - Calls Write
    get:
      description: Fetches details for a single Calls app.
      operationId: calls-apps-retrieve-app-details
      parameters:
      - in: path
        name: app_id
        required: true
        schema:
          $ref: '#/components/schemas/calls_identifier'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/calls_account_identifier'
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/calls_api-response-common-failure'
          description: Retrieve app details response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/calls_app_response_single'
          description: Retrieve app details response
      security:
      - api_token: []
      summary: APIs.io Engineering Platform Retrieve app details
      tags:
      - Calls Apps
      x-api-token-group:
      - Calls Write
      - Calls Read
    put:
      description: Edit details for a single app.
      operationId: calls-apps-update-app-details
      parameters:
      - in: path
        name: app_id
        required: true
        schema:
          $ref: '#/components/schemas/calls_identifier'
      - in: path
        name: account_id
        required: true
        schema:
          $ref: '#/components/schemas/calls_account_identifier'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/calls_app_editable_fields'
        required: true
      responses:
        4XX:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/calls_api-response-common-failure'
          description: Edit app details response failure
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/calls_app_response_single'
          description: Edit app details response
      security:
      - api_token: []
      summary: APIs.io Engineering Platform Edit app details
      tags:
      - Calls Apps
      x-api-token-group:
      - Calls Write
components:
  schemas:
    calls_api-response-common-failure:
      properties:
        errors:
          allOf:
          - $ref: '#/components/schemas/calls_messages'
          example:
          - code: 7003
            message: No route for the URI
          minLength: 1
        messages:
          allOf:
          - $ref: '#/components/schemas/calls_messages'
          example: []
        result:
          enum:
          - null
          nullable: true
          type: object
        success:
          description: Whether the API call was successful
          enum:
          - false
          example: false
          type: boolean
      required:
      - success
      - errors
      - messages
      - result
      type: object
    calls_identifier:
      description: A Cloudflare-generated unique identifier for a item.
      example: 2a95132c15732412d22c1476fa83f27a
      maxLength: 32
      minLength: 32
      type: string
    calls_app_with_secret:
      properties:
        created:
          $ref: '#/components/schemas/calls_created'
        modified:
          $ref: '#/components/schemas/calls_modified'
        name:
          $ref: '#/components/schemas/calls_name'
        secret:
          $ref: '#/components/schemas/calls_secret'
        uid:
          $ref: '#/components/schemas/calls_identifier'
      type: object
    calls_api-response-single:
      allOf:
      - $ref: '#/components/schemas/calls_api-response-common'
      type: object
    calls_app_response_collection:
      allOf:
      - $ref: '#/components/schemas/calls_api-response-common'
      - properties:
          result:
            items:
              $ref: '#/components/schemas/calls_turn_key'
            type: array
    calls_app_editable_fields:
      properties:
        name:
          $ref: '#/components/schemas/calls_name'
      type: object
    calls_app_response_single:
      allOf:
      - $ref: '#/components/schemas/calls_api-response-single'
      - properties:
          result:
            $ref: '#/components/schemas/calls_app'
    calls_name:
      default: ''
      description: A short description of Calls app, not shown to end users.
      example: production-realtime-app
      type: string
    calls_secret:
      description: Bearer token
      example: 66bcf64aa8907b9f9d90ac17746a77ce394c393b92b3916633dc02846e608ad4
      maxLength: 64
      minLength: 64
      type: string
    calls_account_identifier:
      description: The account identifier tag.
      example: 023e105f4ecef8ad9ca31a8372d0c353
      maxLength: 32
      type: string
    calls_app:
      properties:
        created:
          $ref: '#/components/schemas/calls_created'
        modified:
          $ref: '#/components/schemas/calls_modified'
        name:
          $ref: '#/components/schemas/calls_name'
        uid:
          $ref: '#/components/schemas/calls_identifier'
      type: object
    calls_modified:
      description: The date and time the item was last modified.
      example: '2014-01-02T02:20:00Z'
      format: date-time
      type: string
    calls_app_response_single_with_secret:
      allOf:
      - $ref: '#/components/schemas/calls_api-response-single'
      - properties:
          result:
            $ref: '#/components/schemas/calls_app_with_secret'
    calls_api-response-common:
      properties:
        errors:
          $ref: '#/components/schemas/calls_messages'
        messages:
          $ref: '#/components/schemas/calls_messages'
        success:
          description: Whether the API call was successful
          enum:
          - true
          example: true
          type: boolean
      required:
      - success
      - errors
      - messages
      type: object
    calls_turn_key:
      description: Bearer token
      example: 66bcf64aa8907b9f9d90ac17746a77ce394c393b92b3916633dc02846e608ad4
      maxLength: 64
      minLength: 64
      type: string
    calls_created:
      description: The date and time the item was created.
      example: '2014-01-02T02:20:00Z'
      format: date-time
      type: string
    calls_messages:
      example: []
      items:
        properties:
          code:
            minimum: 1000
            type: integer
          message:
            type: string
        required:
        - code
        - message
        type: object
        uniqueItems: true
      type: array
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/apigateway/
x-hasEquivalentPaths: true
